const { isOwner, isMainOwner, isAdmin, getTarget, getSender, canonicalJid, sameUser, soloMiembros } = require('../utils/wa');
const { pickFresh, fmt } = require('../utils/helpers');
const { getAura, addAura, getAuraRanking } = require('../utils/auraStore');

const ROLL_COOLDOWN_MS = 3 * 60 * 1000; // 3 minutes per user per group
const lastRoll = new Map(); // `${groupJid}|${canonicalJid}` -> timestamp

// Aura roll. Owner 60/40, admin 55/45, member 50/50.
// Members were previously 30/70 — far too punishing for regular use.
function rollAura(targetIsOwner, targetIsAdmin) {
  const r = Math.random();
  // Escala comprimida: una tirada mueve decenas, no miles. Con el arranque en
  // 100 y un "millonario" del grupo en ~10.000, una tirada grande pesa lo que
  // debe pesar sin descompensar el marcador de un solo golpe.
  const big   = () => (25 + Math.floor(Math.random() * 26)) * 10;  // 250..500
  const small = () => ( 5 + Math.floor(Math.random() * 16)) * 10;  // 50..200

  if (targetIsOwner) {
    // 60% positive, 40% negative.
    if (r < 0.35) return { tier: 'blessed', amount: big() };
    if (r < 0.60) return { tier: 'gain',    amount: small() };
    if (r < 0.85) return { tier: 'loss',    amount: -small() };
    return { tier: 'cursed', amount: -big() };
  }
  if (targetIsAdmin) {
    // 55% positive, 45% negative.
    if (r < 0.25) return { tier: 'blessed', amount: big() };
    if (r < 0.55) return { tier: 'gain',    amount: small() };
    if (r < 0.83) return { tier: 'loss',    amount: -small() };
    return { tier: 'cursed', amount: -big() };
  }
  // member — 45% positive, 55% negative.
  if (r < 0.18) return { tier: 'blessed', amount: big() };
  if (r < 0.45) return { tier: 'gain',    amount: small() };
  if (r < 0.78) return { tier: 'loss',    amount: -small() };
  return { tier: 'cursed', amount: -big() };
}

const AURA = {
  blessed: [
    'Entraste, miraste a la nada, y el grupo entero se cagó de respeto. Aura de depredador alfa.',
    'No dijiste ni una palabra y silenciaste a cuatro bocazas de golpe. Eso es dominio puro.',
    'Hiciste algo tan frío que hasta el que te odia tuvo que tragarse el orgullo. Aura máxima.',
    'Esta movida se va a contar en el grupo durante años. Acabas de ascender a otra liga.',
    'Caminaste sin mirar atrás mientras todo ardía detrás de ti. Aura de villano de película.',
    'Nadie entiende cómo lo hiciste y ese es justo el punto. Aura de leyenda inalcanzable.',
    'Una sola frase y dejaste a tres personas reescribiendo su autoestima. Poder absoluto.',
    'Tu aura ahora mismo da miedo. La gente baja la voz cuando apareces y tú ni te enteras.',
    'Convertiste una situación normal en una escena épica sin despeinarte. Aura de protagonista.',
    'Te quedaste de hielo mientras todos perdían la cabeza. El grupo te miró como a un dios.',
    'Eso fue tan limpio que deberían enseñarlo en la universidad. Aura por las nubes.',
    'Apareciste, dijiste lo justo, te fuiste. Maestría que el resto solo puede envidiar.',
    'La frialdad con la que lo hiciste congeló el chat en seco. Respeto total e involuntario.',
    'Generaste una leyenda urbana en tiempo real. Aura infinita, sin techo, imparable.',
    'Ni pestañeaste. Y por eso mismo ahora todos quieren ser tú. Aura demoledora.',
    'El silencio que dejaste vale más que mil mensajes de los demás juntos. Otro nivel.',
    'Hiciste que el grupo entero pareciera amateur sin mover un dedo. Mog social absoluto.',
    'Esto va directo al hall de la fama. Aura máxima histórica, sin asterisco.',
    'Cerraste la boca a todos sin abrir la tuya. Aura de leyenda viva y caminante.',
    'Lo que hiciste no tiene explicación racional. El grupo solo puede arrodillarse.',
    'Te fuiste antes de que terminaran de procesarlo. Aura de fantasma con clase.',
    'Hasta tu peor enemigo tuvo que escribir "respeto" en el chat. Eso no pasa nunca.',
    'Dejaste a todos en visto y aun así ganaste el round. Frialdad de campeón mundial.',
    'Redefiniste lo que significa tener clase en este grupo. Aura suprema indiscutible.',
    'Una mirada y desactivaste tres egos a la vez. Aura quirúrgica, precisión letal.',
    'El chat tembló y tú ni te inmutaste. Aura de hielo puro, sangre fría total.',
    'Lo hiciste ver tan fácil que ahora todos se sienten inútiles. Y tienen razón.',
    'Te convertiste en el tema del que todos van a hablar mañana. Aura histórica.',
    'Pasaste por encima de la situación como si no existiera. Aura imparable, rodillo.',
    'Sin un mensaje, sin una explicación, solo dominio absoluto. El grupo enmudeció.',
    'Todos guardaron silencio solo para verte actuar. Aura de respeto reverencial.',
    'Hiciste que el resto reconsiderara toda su existencia en directo. Aura aplastante.',
    'Frialdad de manual. Te miraron y entendieron que no juegan en tu liga.',
    'Tan limpio que ni dejaste huellas. Aura de profesional que el grupo no merece.',
    'Subiste de nivel delante de todos y nadie pudo ni seguirte el polvo. Legendario.',
    'Tu calma en pleno caos fue la verdadera ejecución. Aura de otro planeta.',
    'Hiciste algo tan limpio que el grupo entero se quedó con cara de estar viendo otra liga. Aura de otro planeta.',
    'Ni te esforzaste y ya dejaste a tres personas replanteándose su existencia. Dominio absoluto.',
    'Apareciste en el peor momento posible y saliste siendo el mejor de la sala. Aura quirúrgica.',
    'Lo tuyo hoy no fue suerte, fue oficio. El grupo aplaudió por dentro y calló por fuera.',
    'Convertiste una situación de mierda en tu mejor momento del mes. Eso no se enseña en ningún lado.',
    'Te callaste justo cuando había que callarse y ganaste todo. Aura de estratega frío.',
    'El grupo entero cambió de tema porque nadie quería competir contigo hoy. Poder puro.',
    'Hiciste el ridículo imposible: quedar bien sin intentarlo. Aura por las nubes y de gratis.',
    'Alguien intentó humillarte y acabó pidiendo perdón sin saber por qué. Aura de depredador.',
    'Saliste de una encerrona con más respeto del que entraste. Eso es tener oficio, no suerte.',
    'Dijiste una frase y tres conversaciones distintas se pararon a leerla. Aura demoledora.',
    'El grupo te estaba esperando para reírse y acabó tomando apuntes. Vuelco total del guion.',
    'Aura máxima. Hiciste lo correcto en el peor momento y encima quedó elegante.',
    'Te subestimaron por última vez. Hoy quedó claro para todos y nadie va a repetir el error.',
    'Cerraste una discusión sin levantar la voz. El resto grita y tú simplemente ganas.',
    'Aura de leyenda. Lo que hiciste va a citarse mal durante meses, que es la mayor gloria.',
    'Ni te enteraste de que estabas ganando y ya habías ganado. Ese es el nivel real.',
    'Hiciste que el más chulo del grupo se pusiera a la defensiva con una sola línea.',
    'Aura brutal. Te miraron esperando un fallo y les regalaste una clase magistral.',
    'El grupo entero se calló y no fue por educación, fue por respeto. Cosa rarísima aquí.',
    'Lo tuyo hoy fue frialdad de manual. Los demás se acaloraron y tú saliste intacto.',
    'Aura de villano bien escrito: nadie te quiere del todo y todos te siguen mirando.',
    'Hiciste lo que nadie se atrevía y encima quedó bien. Doble mérito, doble aura.',
    'Te tendieron una trampa y la usaste de trampolín. Aura de quien juega otro deporte.',
    'Aura máxima confirmada. El grupo va a recordar esto más de lo que tú vas a recordarlo.',
    'Tiraste sin pestañear y el grupo entero se calló. Por una vez no diste pena.',
    'El aura no se te acercó por cariño, se te acercó porque hoy imponías. Aprovecha antes de que se te pase.',
    'Entraste como un don nadie y saliste con la sala mirándote la nuca. Joder, quién lo diría.',
    'Golpe seco, sin discurso, sin postureo. Así se arranca el respeto, pringado.',
    'Hoy no ganaste aura: la cobraste con intereses.',
    'Ni una palabra de más y te llevaste la mesa entera. Eso sí es dominio.',
    'Rascaste algo de aura del suelo. Poco y sucio, pero tuyo.',
    'Ganancia modesta. Nada de lo que presumir, aunque tampoco es una puta mierda.',
    'Miraste la tirada como quien mira a un empleado y ella obedeció. Impresionante para alguien de tu nivel.',
    'Ganaste sin levantar la voz. Eso vale más que todo lo que has dicho este mes.',
    'Aura sumada. Poca, discreta, del montón. Justo tu tamaño.',
    'Por primera vez el grupo no supo qué responderte. Guarda ese silencio, no lo vas a repetir pronto.',
    'Frío, limpio y sin pedir permiso. Hoy nadie se atreve a llamarte inútil.',
    'Subiste un peldaño. Uno. No montes una fiesta.',
    'Te llevaste el respeto sin negociarlo. Eso no se compra ni se roba, y hoy te salió.',
    'Aura ganada, gloria cero. Ni te van a recordar mañana.',
    'La sala entera te vio ganar y a ninguno le salió la broma. Eso es peso.',
    'Ese tiro fue quirúrgico. Da rabia decirlo, pero fue tuyo.',
    'Sumaste algo. Un cambio suelto de aura, calderilla. Tampoco te sobra.',
    'Dominaste la partida con la cara de quien se la suda ganar. Ahí está la clase.',
    'Hoy pasaste de basura a amenaza. Mañana ya veremos.',
    'Ganancia pequeña, sin ruido, sin mérito. Aun así cuenta.',
    'Te miraron esperando el fracaso de siempre y les arruinaste el espectáculo.',
    'Coño, por fin haces algo que no hay que explicar con excusas.',
    'Aura arrancada de cuajo. Nadie te la regaló y eso se nota.',
    'Un puñado de aura. Del tamaño de tus ambiciones, o sea poco.',
    'No presumiste, no celebraste, no dijiste nada. Por eso te lo respetan.',
    'Ganaste como gana la gente que no necesita ganar. Retén esa sensación.',
    'Migajas de aura para el muerto de hambre. Cómetelas, que están calientes.',
    'Tu tirada partió la conversación en dos. Ahora todos hablan de ti y ninguno con ganas.',
    'Hoy fuiste el que decide. Mañana volverás a ser el que pregunta.',
    'Aura mínima, esfuerzo mínimo. Justo tu ritmo.',
    'Nadie aplaudió porque nadie se atrevió. Eso es mejor que cualquier aplauso.',
    'Ganaste sin suerte, por método. Eso da miedo viniendo de ti.',
    'Un poco de aura al bolsillo. No cambia nada, pero tampoco estorba.',
    'La mesa entera se ajustó a tu tiro. Eso no lo hace un cero a la izquierda.',
    'Hoy dijiste menos que nunca y valiste más que nunca. Aprende de ti mismo.',
    'Ganancia gris, sin historia detrás. Nadie va a contarla.',
    'Ese resultado no fue fortuna. Fue que por una vez sabías lo que hacías.',
    'Te llevaste aura y encima dejaste a dos con la boca abierta. Eficiencia.',
    'Sumas aura y sigues siendo el mismo. Al menos ahora con algo en la cuenta.',
    'Ganaste con la frialdad de quien ya sabía el final. Esa cara sí te queda bien.',
    'Poca aura, cero brillo, cero anécdota. Del tamaño exacto de tu día.',
    'Te respetan hoy y ninguno sabe explicar por qué. Ese es el mejor respeto que hay.',
    'No hubo golpe de suerte, hubo criterio. Joder, hasta yo me sorprendo.',
    'Arrancaste aura a un grupo que llevaba semanas riéndose de ti. Anótalo.',
    'Ganancia discreta. Ni fracaso ni gesta. Simplemente existes un poco más.',
    'Tu tirada impuso silencio antes que resultado. Eso vale doble.',
    'Hoy no fuiste el chiste de la sala. Disfruta la novedad.',
    'Subiste de aura como sube el que no le importa subir. Ahí está el truco.',
    'Una pizca de aura. Sabe a poco, pero es más de lo que tenías.',
    'El grupo te odia un poco más y te teme bastante. Buena tarde.',
    'Ganaste sin mendigar atención. Es lo más digno que has hecho en meses.',
    'Aura sumada, orgullo intacto, expectativas por los suelos. Todo en su sitio.',
    'Ese movimiento fue de alguien serio. Vuelve pronto, ese alguien nos cae mejor.',
    'Te llevaste la ronda con la mirada. Ni hizo falta que abrieras la boca.',
    'Ganancia sin épica. Como tú, funcional y olvidable, pero hoy funciona.',
    'Nadie quiso ser el siguiente después de tu tirada. Eso se llama presencia.',
    'Hoy el azar te trató como socio, no como víctima. Aprovecha la reunión.',
    'Poco aura, mucho silencio. Al menos no diste vergüenza.',
    'Ganaste y ni siquiera lo celebraste. Eso descoloca más que el resultado.',
    'La sala esperaba tropiezo y encontró filo. Bien jugado, pringado.',
    'Aura arriba. No te lo mereces del todo, pero te lo has ganado hoy.',
    'Un incremento pequeño y tacaño. Como tú con las rondas.',
    'Te has puesto por encima de gente que llevaba meses pisándote. Sostenlo.',
    'Ganaste con la calma del que no tiene nada que demostrar. Mentira, pero funcionó.',
    'Aura conseguida sin escándalo. Nadie va a hablar de esto, y está bien así.',
    'Ese tiro dejó a la mesa recalculando quién manda. Y no salió tu nombre por casualidad.',
    'Hoy no sonaste a excusa. Sonaste a resultado.',
    'Sumas un poco de aura y sigues sin dar miedo. Pero ya no das lástima.',
    'La ganaste limpia, sin trampas, sin llorar. Nivel al que casi nunca llegas.',
    'Aura moderada, ego moderado, todo correcto por una vez.',
    'El respeto de hoy no te lo prestaron. Te lo llevaste tú.',
    'Ganaste y encima quedó feo para los demás. Doble mérito.',
    'Migaja de aura para tu colección de casi nadas. Aun así, suma.',
    'Ese fue el tipo de tiro que cambia cómo te nombran en el grupo.',
    'Hoy tu nombre pesó. Mañana volverá a flotar, pero hoy pesó.',
    'Ganancia sin adorno. Ni te van a preguntar cómo lo hiciste.',
    'Dominaste sin alzar la voz. Justo lo contrario de todo lo que sueles hacer.',
    'Aura ganada con la elegancia del que no necesita mirar el resultado.',
    'Un poco más de aura y sigues siendo un secundario. Pero un secundario con crédito.',
    'Te ganaste el silencio incómodo de tres personas. Ese es el premio real.',
    'Ganaste y ni te alteraste. Empiezo a pensar que hay alguien ahí dentro.',
    'Aura discreta. Del montón, sin firma, sin gloria. Encaja contigo.',
    'Tu tirada fue una sentencia y la mesa la acató. Así se hace.',
    'Hoy no hubo fracaso que comentar. Qué aburrido y qué merecido.',
    'Ganancia modesta que nadie va a envidiar. Aun así te la quedas.',
    'Ese resultado impuso jerarquía sin que dijeras una palabra. Eso es raro y es tuyo.',
    'Ganaste con frialdad de mármol. Guarda esa cara para más ocasiones.',
    'Aura mínima, pero limpia. No siempre hace falta destrozar a nadie.',
    'La mesa cambió de tono cuando te tocó a ti. Eso ya es poder.',
    'Ganaste sin pedir turno, sin pedir permiso y sin pedir perdón.',
    'Un poco de aura al saldo. Sigue siendo un saldo patético, pero mejora.',
    'Hoy nadie pudo llamarte inútil sin quedar mal. Anótate el día.',
    'Ese tiro tenía intención. No fue suerte, fue decisión.',
    'Ganancia pequeña, sin público, sin ruido. Ya es más de lo habitual.',
    'Te llevaste el respeto de gente que no reparte respeto. Eso escuece bien.',
    'Ganaste con la seguridad del que ya calculó todo. Fingida o no, coló.',
  ],
  gain: [
    'Movida sólida. Sumaste aura sin hacer ruido, como los que de verdad saben.',
    'Bien jugado. Pequeño pero quirúrgico, el grupo lo registró en silencio.',
    'Te llevas puntos con eso. No épico, pero más de lo que el grupo esperaba de ti.',
    'Detalle con clase. Tu aura sube un escalón y alguien tomó nota.',
    'Correcto y con filo. Aura en alza, aprovéchala antes de cagarla.',
    'Bien medido. Te llevas tu aura merecida sin tener que rogar.',
    'Sin pasarte, sin quedarte corto. Suma justa para alguien de tu nivel.',
    'Buena lectura del momento. El aura lo agradece y el grupo también.',
    'Discreto pero letal. Así se construye reputación, no a base de ruido.',
    'Te ganaste el asentimiento silencioso del grupo. Para ti eso ya es mucho.',
    'Nada espectacular, pero nadie te puede quitar estos puntos. Disfrútalos.',
    'Jugada limpia. El aura sube despacio, que es como sube la de los que aguantan.',
    'Bien ahí. Pequeña victoria, pero victoria, que ya es raro en ti.',
    'Sumaste sin drama. La forma más digna de ganar aura que has tenido en meses.',
    'Aprobado con nota. El aura te sonríe hoy, no te acostumbres.',
    'Movimiento correcto. Nada que presumir, pero por una vez nada que lamentar.',
    'Te llevas el visto bueno del grupo, aunque sea sin entusiasmo. Mejor eso que nada.',
    'Cumpliste. El aura te paga lo justo y ni un punto más, porque más no diste.',
    'Pequeño acierto. Lo justo para no hacer el ridículo hoy. Milagro.',
    'Bien medido. Te llevas tu trocito de aura sin que nadie te lo discuta.',
    'Nada del otro mundo, pero el aura lo cuenta a tu favor por esta vez.',
    'Te ganaste un punto de respeto silencioso. Sujétalo fuerte que dura poco.',
    'Acierto modesto. El aura sube lo justo para que se note que sigues vivo.',
    'Jugada decente. Ni aplausos ni abucheos, solo un raro avance tuyo.',
    'Sumaste sin hacerte notar. Tu estilo natural: pasar desapercibido ganando.',
    'Pequeño paso al frente. El aura lo registra y pasa página rápido.',
    'Correcto sin brillar. Tu marca personal. Aun así, suma es suma.',
    'Te llevas unos puntos honestos. Nadie te los discute porque a nadie le importas tanto.',
    'Buen detalle. El aura te lo reconoce a media voz para no hacerte ilusiones.',
    'Avance discreto. El grupo asiente y olvida tu nombre en cinco minutos.',
    'Pequeña ganancia limpia. Hoy el aura no te castiga. Hoy.',
    'Sólido sin más. El aura te deja seguir en positivo por pura compasión.',
    'Acierto de los que no se celebran pero se agradecen. Justo tu techo.',
    'Bien jugado. Nada épico, pero por una vez no diste vergüenza. El aura lo agradece.',
    'Sumaste sin llamar la atención, que es exactamente tu techo y hoy lo tocaste.',
    'Acierto discreto. El grupo lo notó a medias y te lo cuenta como bueno igual.',
    'Pequeño mérito real. No cambia nada, pero es tuyo y nadie te lo discute.',
    'Hiciste lo mínimo con estilo. El aura premia el estilo aunque el mínimo siga siendo mínimo.',
    'Movimiento correcto. Ni brillante ni ridículo: justo el punto medio que dominas.',
    'Sumaste puntos por sentido común, que en este grupo ya es una habilidad rara.',
    'Bien ahí. El aura sube un peldaño y tú ni te das cuenta, como siempre.',
    'Acierto honesto. No lo vas a poder presumir, pero cuenta igual en el marcador.',
    'Cumpliste sin drama. Es poco, pero comparado con lo tuyo habitual es una fiesta.',
    'Ganancia limpia. El grupo asiente y sigue a lo suyo. Tu momento duró dos segundos.',
    'Pequeña victoria. Guárdala, que a este ritmo la siguiente tarda en llegar.',
    'Sumaste por no cagarla, que técnicamente cuenta como mérito en tu caso.',
    'Buen detalle. El aura lo registra sin entusiasmo pero sin objeciones.',
    'Avance discreto. Nadie va a hablar de esto mañana, pero hoy suma y con eso basta.',
    'Acierto de perfil bajo. Justo tu estilo: ganar sin que nadie se entere ni le importe.',
    'Sumaste algo real por una vez. Anótalo en algún sitio, que no pasa a menudo.',
    'Correcto y sin brillo. El aura te paga lo justo porque diste exactamente lo justo.',
    'Ganancia modesta. Suficiente para no bajar, insuficiente para que alguien lo comente.',
    'Bien medido. El aura sube despacio, como suben las cosas de los que aguantan.',
    'Pequeño paso adelante. En tu caso, cualquier paso adelante ya es noticia.',
    'Acierto tranquilo. Ni ovación ni abucheo: el silencio neutro que tanto te pega.',
    'Sumaste. Poco, pero sumaste, y en este grupo eso ya te pone por encima de la mitad.',
    'Movida decente. El aura lo cuenta a tu favor y pasa página en cinco segundos.',
    'Ganancia justa. Diste lo mínimo aceptable y el marcador te lo reconoce a regañadientes.',
    'Aura sumada y expectativas rotas. Buen negocio para un don nadie.',
    'Hoy tu presencia molestó de la buena manera. Sigue así.',
    'Ganancia simple. Sin frase memorable, sin momento. Solo números.',
    'Ese movimiento reordenó la sala. Ahora hay que contar contigo.',
    'Ganaste callado y eso vale más que veinte mensajes tuyos.',
    'Aura arriba, ruido cero. Estilo, por accidente.',
    'Un poco más de aura. Nada que celebrar, nada que lamentar.',
    'Hoy dominaste el ambiente antes que el resultado. Eso no se aprende.',
    'Nadie te regaló nada y aun así saliste con más. Anótalo, no se repite mucho.',
    'Ganancia gris y sin brillo. Justo lo que sabes conseguir sin romper nada.',
    'Ese tiro fue de alguien con la cabeza fría. Sorprende viniendo de ti.',
    'El grupo te tomó en serio por primera vez en semanas. No lo desperdicies.',
    'Ganaste con desprecio hacia el resultado. Eso es lo que impone.',
    'Aura leve, casi imperceptible. Como tu paso por este grupo, pero positiva.',
    'Hoy fuiste el nombre que nadie quiso mencionar en broma. Eso es una victoria.',
    'Ganaste sin necesitar que nadie lo viera. Y aun así lo vieron todos.',
    'Pequeño avance. Ni gesta ni desastre. Solo un martes decente.',
    'Ese resultado dejó claro quién controlaba la mesa. Y no eran ellos.',
    'Ganaste con la boca cerrada. Sigue con ese método, te queda bien.',
    'Aura escasa pero honesta. Por una vez no hubo excusas de por medio.',
    'Hoy no pareciste un pringado. Ya es más de lo que esperaba nadie.',
    'Ese tiro tenía autoridad. La misma que te falta el resto del tiempo.',
    'Ganaste y el ambiente se enfrió. Eso también es aura.',
    'Ganancia pequeña, ego intacto. Equilibrio raro en ti.',
    'Te llevaste todo sin levantar el tono. Los demás gritaron y perdieron.',
    'Hoy el grupo tuvo que tragarse su propia broma sobre ti.',
    'Aura sumada sin épica. No todo tiene que ser una historia.',
    'Ese golpe se sintió en toda la sala. Y no vino acompañado de tonterías.',
    'Ganaste como gana el que ya no necesita aprobación. Bien.',
    'Ligera subida. Nadie va a recordarla, ni siquiera tú dentro de una hora.',
    'Impusiste ritmo, impusiste calma, impusiste resultado. Tres cosas nuevas en ti.',
    'Hoy no fuiste basura. Fuiste referencia. Sostenlo si puedes.',
    'Ese tiro dejó a los graciosos sin material. Servicio público.',
    'Ganaste con el desdén exacto que exige la mesa. Eso no se improvisa.',
    'Aura hacia arriba, silencio hacia los lados. Combinación perfecta.',
    'Pequeña ganancia, cero mérito visible. Aun así, es tuya.',
    'Hoy el respeto no te lo dieron. Se lo quitaste.',
    'Ganaste sin ruido y sin necesidad de explicarte. Nivel alto.',
    'Aura sumada. Poca, tibia, sin nadie mirando. Perfecta para ti.',
    'Ese resultado te puso por encima de gente que se creía intocable.',
    'Ganaste con cara de que te la sudaba. Y precisamente por eso pesó.',
    'Un empujón mínimo en el marcador. Ni celebres ni te quejes.',
    'Hoy dominaste sin necesidad de humillar a nadie. Qué lujo tan raro en ti.',
    'Ese tiro fue frío como una firma. Y valió lo mismo.',
    'Ganancia sin adjetivos. Simplemente ocurrió y te beneficiaste.',
    'Te ganaste el sitio en la mesa, no te lo prestaron. Ocúpalo bien.',
    'Aura arriba y la sala mirando a otro lado. Eso significa que molestó.',
    'Ganaste con precisión de reloj. Sospechoso, pero legítimo.',
    'Sube un poco tu aura. Sigues siendo poca cosa, pero menos que ayer.',
    'Hoy tu tirada mandó y nadie discutió. Ese es el mejor tipo de victoria.',
  ],
  loss: [
    'Perdiste aura sin que nadie te atacara. Hace falta un don especial para perder un partido en el que eras el único equipo, y tú lo tienes: campeón mundial del autogol.',
    'El aura te restó con la misma ternura con la que un cajero te cierra la caja en la cara: sin mirarte y deseando que te largues. El siguiente, por favor.',
    'Tu aura tiene la solidez de una silla de plástico de gasolinera: te confiaste, te apoyaste, y crac, al suelo delante de todos. Era de esperar, manco.',
    'Bajón de aura por causas exclusivamente tuyas. Como siempre: el problema lo traes de casa, lo montas tú y encima cobras entrada para que el grupo lo vea.',
    'Restaste aura tú solito. Eres el único ser capaz de tropezar con un bordillo que llevabas media hora mirando. Talento puro, lástima que para el desastre.',
    'El aura te pasó la factura y ni la discutiste, porque en el fondo sabías que era justa. Primera cosa lúcida que haces hoy: asumir que la cagaste, fracasado.',
    'Perdiste puntos con una naturalidad que asusta. Para ti fracasar no es un evento, es el estado de fábrica, como el wifi de tu casa: malo, lento y constante.',
    'Tu aura baja y el grupo ni levanta la vista. Ya eres ruido de fondo, el goteo de un grifo que nadie arregla porque total, siempre ha estado ahí jodiendo.',
    'Metiste la pata con precisión quirúrgica, pero al revés: lo tenías todo para que saliera bien y aun así encontraste la única forma posible de arruinarlo.',
    'El aura te resta y suspira. Ya ni se enfada contigo, perdedor; le das la misma pereza que los platos de anoche que sigues sin fregar.',
    'Bajón merecido. No fue mala suerte: la mala suerte al menos es aleatoria. Lo tuyo es un patrón que cualquier analista predeciría con los ojos cerrados.',
    'Perdiste aura por abrir la boca antes de encender el cerebro. Llevas ese orden invertido de fábrica y ya no hay actualización que lo arregle, bocazas.',
    'Tu aura cayó como tus propósitos de año nuevo: rápido, en silencio y sin que nadie te pidiera explicaciones, porque nadie esperaba otra cosa de ti.',
    'Restaste puntos en una jugada que un crío de seis años habría leído. Claro que el crío tiene algo que a ti se te quedó pendiente para siempre: futuro.',
    'El aura te penaliza y lo más triste es la cara de sorpresa que pones. ¿En serio todavía te sorprende? Llevas perdiendo desde antes de tener datos móviles.',
    'Bajón. Tu aura es como una planta regada con refresco: te esfuerzas, parece que haces algo, y aun así se muere por tu culpa con dedicación.',
    'Perdiste lo justo para recordarte que existes, que es tu única función en el grupo: servir de marcador de hasta dónde se puede caer sin tocar fondo.',
    'Tu aura se desinfló sola, sin pinchazo, como un globo de cumpleaños al tercer día. Triste, arrugado y sin nadie con ganas de volver a inflarte.',
    'Restaste puntos y el aura ni dramatiza. Para drama ya tienes tu vida entera; esto es solo el resumen ejecutivo en números rojos, fracasado.',
    'El aura te cobró el peaje del ridículo: caro, en efectivo y sin devolución. Igual que cada decisión que tomas desde que tienes uso de razón, o casi.',
    'Bajón de manual. Lo tuyo ya no es resbalar, es que el suelo te ve venir y se aparta para que te des de lleno. Hasta la física te coge manía.',
    'Perdiste aura intentando parecer listo. Es como verte de puntillas para alcanzar un techo que está en otra planta: el esfuerzo enternece, el resultado da pena.',
    'Tu aura baja otro escalón hacia el sótano donde guardas el resto de tu autoestima. Tranquilo, ahí abajo tienes compañía: el polvo y tus excusas.',
    'Restaste puntos y ni notaste el momento exacto, como no notas nada. Vives en modo espectador de tu propio desastre, con palomitas y todo, idiota.',
    'El aura te resta con la frialdad de un informe médico: sin maldad, solo constatando un deterioro que viene de lejos y no tiene tratamiento, perdedor.',
    'Bajón. Eres de los que se caen solos en una habitación vacía y luego miran alrededor a ver quién los empujó. Spoiler: nadie. Eres tú. Siempre tú.',
    'Perdiste aura como pierdes las conversaciones: hablando mucho, aportando nada y dejando a todos esperando a que te calles de una puta vez.',
    'Tu aura se fue por el desagüe con un gluglú casi cómico. Lo más gracioso que has producido en semanas, y ni siquiera fue a propósito.',
    'Restaste en directo. El grupo ya no se ríe, hace esa mueca de cuando alguien tropieza y te da más vergüenza que pena. Esa eres tú en formato gráfico.',
    'El aura te baja y se acabó el misterio: no es la racha, no es el día, no es Mercurio retrógrado. Eres tú, en estado puro, funcionando como de costumbre.',
    'Bajón de los que ni se discuten. Perdiste con la misma elegancia con la que entras al grupo: sin avisar, sin aportar y dejando peor ambiente del que había.',
    'Perdiste aura y la cifra es pequeña solo porque ya no te quedaba mucho que perder. Hasta para arruinarte eres de bajo presupuesto, fracasado.',
    'Tu aura cae y la de los demás ni se entera, porque al grupo le importas lo que un capítulo de relleno: pasa, no aporta y nadie lo comenta.',
    'La cagaste con una naturalidad preocupante. El aura baja y nadie sale a defenderte.',
    'Pequeño desastre. Ni siquiera fue épico: fue de esos fallos aburridos que solo dan pena.',
    'Perdiste aura por hablar cuando tocaba callarse. Otra vez. Como todas las veces.',
    'Hiciste el ridículo a media potencia. Ni para eso llegas al máximo.',
    'El aura baja y el grupo ni comenta. Hasta tus fallos son irrelevantes, que tiene mérito.',
    'Metiste la pata en algo tan fácil que cuesta explicarlo sin reírse. Baja el marcador.',
    'Pérdida limpia. Te equivocaste solo, sin ayuda y sin presión. Todo mérito tuyo.',
    'El aura te castiga por algo que sabías que estaba mal. Lo hiciste igual, claro.',
    'Bajas puestos por insistir donde nadie te llamaba. Un clásico de tu repertorio.',
    'Fallo tonto y caro. La combinación que mejor te define en este grupo.',
    'Perdiste aura y ni te enteraste. Vas a leer esto y seguir sin entender qué hiciste.',
    'El aura baja. Tranquilo, desde donde estás la caída es corta y ya la conoces.',
    'Error de novato con años de experiencia. Eso ya no es fallar, es una firma personal.',
    'Pérdida merecida. Nadie te empujó: te tiraste tú solo, con impulso y todo.',
    'Bajas un escalón. Buenas noticias: quedan pocos escalones por debajo, así que descansas.',
    'La cagaste en público y encima sin gracia. Al menos las cagadas divertidas se perdonan.',
    'El aura te resta por pesado. Había una salida elegante y elegiste la otra.',
    'Fallo de manual. Si hubiera un manual de cómo no hacer las cosas, saldrías en la portada.',
    'Pérdida sin drama. Ni siquiera diste el espectáculo: fallaste en silencio y bajaste igual.',
    'El aura baja porque hiciste exactamente lo que todos esperaban que hicieras mal.',
    'Retrocediste solo. En un grupo lleno de gente dispuesta a hundirte, te bastaste tú.',
    'Error caro y evitable. El aura te lo cobra sin mirarte a la cara, como se cobra a los pesados.',
    'Bajas puestos por confiado. La confianza sin base se paga, y hoy pagaste al contado.',
    'El aura resta. Y lo peor es que mañana vas a repetirlo exactamente igual.',
    'Fallo previsible. Tan previsible que hasta el bot lo veía venir tres mensajes antes.',
    'Perdiste aura. Y ni siquiera de forma espectacular: la perdiste en silencio, como un pringado.',
    'Tirada de mierda. Lo peor es que no sorprendiste a nadie, ni a ti mismo.',
    'Has perdido aura por un fallo tan tonto que da pereza hasta señalarlo.',
    'Tu tirada acaba de recordarte que eres mediocre incluso cuando el azar te da facilidades.',
    'Otra vez para abajo. Eres el único capaz de convertir una tirada en una rutina de fracaso.',
    'Pierdes poco aura, pero es que tampoco tenías gran cosa que perder, don nadie.',
    'Ni ganas ni pierdes con dignidad. Te quedas siempre en ese punto patético de en medio.',
    'Fallaste en lo más fácil. A esto ya no se le llama mala suerte, se le llama ser tú.',
    'Tiraste con toda la ilusión del mundo y te comiste una mierda. Clásico.',
    'Menos aura y la misma cara de tonto. Coherente, al menos.',
    'Lo tuyo no es tener mala suerte, es tener mala cabeza.',
    'Perdiste aura y el grupo ni levantó la vista. Así de irrelevante es tu derrota.',
    'Un fallo pequeño, evitable y absolutamente tuyo. Firma de autor.',
    'Ni el azar quiere cargar con la responsabilidad de haberte ayudado.',
    'Restas aura con la misma naturalidad con la que restas valor a cualquier conversación.',
    'Tu tirada fue floja. Tú también, pero eso ya lo sabíamos.',
    'Has perdido aura por no pensar dos segundos. Dos. Ni eso das.',
    'Lo intentaste, salió mal y aquí estás, tan patético como siempre.',
    'Perder así requiere un talento especial para la incompetencia. Enhorabuena.',
    'No te ha hundido la tirada. Te ha hundido ser tú quien la hizo.',
    'El resultado era previsible. Tú eres previsible. Todo esto es aburridísimo.',
    'Tu fallo no tiene ni el mérito de ser interesante.',
    'Hasta perder se te da de forma mediocre.',
    'El grupo esperaba algo y tú entregaste lo de siempre: una puta mierda pequeña.',
    'Perdiste aura por descuido. Tu especialidad histórica.',
    'No hace falta ni burlarse. La tirada ya lo dijo todo por mí.',
    'Bajaste en aura sin haber subido nunca de verdad. Movimiento neto: cero, como tú.',
    'Te fallaron los reflejos, la cabeza y las ganas. Combo completo.',
    'Cada tirada tuya es una demostración gratuita de incompetencia.',
    'Perdiste, y ni siquiera en algo que importara. Menudo desperdicio de turno.',
    'Tu aura se desinfla sola cuando la tocas. Debe ser alérgica.',
    'Si perder aura diera puntos, serías el número uno. Es lo único que se te da bien.',
    'La suerte se la suda tu esfuerzo, y con razón: no había esfuerzo.',
    'Ni las cosas fáciles te salen. Coño, es que no fallas ni un fallo.',
    'Ese fallo no fue casualidad. Fue tu media histórica funcionando con precisión.',
    'La tirada te dio una oportunidad y tú la convertiste en otro papelón.',
    'Sales de esta con menos aura y con la reputación intacta: sigues siendo un cero a la izquierda.',
    'No perdiste por difícil. Perdiste por vago mental.',
    'Pierdes aura como quien pierde el tiempo: constantemente y sin darse cuenta.',
    'Otra vez el mismo error. Ni para variar sirves.',
    'Hasta el azar tiene mejor criterio que tú, y el azar no piensa.',
    'Perdiste aura sin pena ni gloria. Sobre todo sin gloria.',
    'Tu tirada fue floja, tu reacción será peor y mañana repetirás. Ciclo completo del inútil.',
    'Te la jugaste sin pensar y ahora lloriqueas por dentro. Patético.',
    'Aura perdida por un descuido de manual. Manual que evidentemente no leíste.',
    'No es un bache. Es tu nivel del mar.',
    'El aura se te va y tú sigues creyendo que el problema es el bot.',
    'Tu error de hoy es idéntico al de ayer. Tienes la constancia de un fracasado profesional.',
    'Pierdes aura y el grupo lo registra como ruido de fondo. Igual que tus mensajes.',
    'Ni siquiera te ha salido mal del todo. Te ha salido tibio, que es peor.',
    'Tu tirada dice mediocre. Tu historial dice mediocre. Se llama consenso.',
    'No aprendes. Solo repites, pierdes y te haces el sorprendido.',
    'Perdiste aura y ni una queja. Al menos sabes cuál es tu sitio.',
    'Ese fallo tenía nombre y apellidos desde antes de tirar.',
    'Te sobraban opciones y elegiste la de pringado. Como cada vez.',
    'Tu tirada es el equivalente numérico de encogerse de hombros.',
    'Perdiste por precipitado. Corriendo hacia el fracaso, como siempre.',
    'No fue el azar. Fue esa manía tuya de hacerlo todo a medias.',
    'Otro fallo previsible. Podría escribir tus resultados con una semana de antelación.',
    'Bajas en la lista y en la consideración de todos. Movimiento coherente.',
    'Perdiste aura por un detalle que cualquiera habría visto. Cualquiera menos tú.',
    'Perdiste poquito, sí. Es que humillarte a lo grande sería regalarte protagonismo.',
    'Fallaste y encima con esa lentitud tuya que da vergüenza ajena.',
    'Tu incompetencia es discreta pero constante. Como una gotera.',
    'Aura menos, ridículo más. La ecuación de tu vida.',
    'Perdiste aura por confiado. Confiado tú, con ese historial. Manda cojones.',
    'Te has quedado corto. Como en todo, muerto de hambre.',
    'La tirada no te odia. Simplemente te ha calado, como todos.',
    'Perdiste aura por no leer, no pensar y no mirar. Trío ganador.',
    'Ese fallo es pequeño, pero tú lo llevas puesto todo el día. Disfrútalo.',
    'Bajas de aura sin drama. Es que ni para el drama das.',
    'La tirada salió mal y tú saliste peor en la foto.',
    'Perdiste como se pierde cuando uno va de listo sin serlo.',
    'Tu error no es grave. Es sistemático, que es mucho peor.',
    'Otro fallo evitable. Podrías coleccionarlos, ya casi tienes museo.',
    'No te ha salido. Y lo raro sería que te saliera, seamos honestos.',
    'Fallaste en lo básico. Otra vez. Ya ni te lo discuto.',
    'Tu tirada fue tan gris que ni da para meme.',
    'Esa pérdida es pequeña. Tu incapacidad, en cambio, es enorme.',
    'Otro paso atrás. Al menos eres constante en la dirección.',
    'La tirada te retrató. Y el retrato es feo de cojones.',
    'No fue difícil. Fuiste tú, que lo complicas todo.',
    'Un fallo tonto de una persona que lleva años entrenándolo.',
    'Fallaste sin épica, sin drama y sin excusa. Solo fallaste.',
    'Perdiste aura por distraído. Ni concentrarte cinco segundos puedes.',
    'Ese resultado es tu media. Y tu media es una puta mierda.',
    'Perdiste aura y ya se te olvidó el motivo. Así vas por la vida.',
    'Ni pena das. Solo un poco de fastidio, como una mosca.',
    'Te sobró confianza y te faltó todo lo demás.',
    'Perdiste aura y encima con esa excusa mental que te estás montando ahora mismo.',
    'Fallo simple, culpa entera. No hay reparto posible.',
    'Menos aura para ti, más aburrimiento para nosotros.',
    'Perdiste por no molestarte. Es tu forma preferida de perder.',
    'Otra tirada al basurero. Como casi todo lo que tocas.',
    'No hay giro dramático. Hay un pringado que falló lo evidente.',
    'Tu aura baja y tu ego sigue igual de inflado. Ahí está el chiste.',
    'Ese fallo lo vio venir hasta el que no estaba mirando.',
    'Un tropiezo más en tu carrera de tropiezos. Trayectoria sólida, hay que decirlo.',
  ],
  spiral: [
    'Aura negativa y cavando hacia abajo con pala propia. Eres el único minero que se excava su tumba y encima se queja de que nadie le tira una cuerda.',
    'En rojo y bajando. Tu aura cotiza como esas criptos que iban a cambiarte la vida: hype, caída libre y un gráfico que solo conoce una dirección.',
    'Sigues perdiendo en negativo, que tiene mérito: es como ahogarte en una piscina que vaciaste tú mismo. Constancia admirable, aplicada al desastre.',
    'Tu aura tocó fondo, pidió un préstamo y siguió bajando. Ya no eres pobre de aura, eres un agujero negro: absorbes puntos y no devuelves nada.',
    'Caída libre documentada. A este ritmo vas a necesitar un sótano debajo del sótano, y cuando lo encuentres, descuida, también lo vas a perder.',
    'En negativo y reincidente. Definición de locura: repetir lo mismo esperando otro resultado. Definición de ti: hacerlo además sonriendo, sin enterarte de nada.',
    'Tu aura está tan abajo que la palabra "fondo" te queda de techo. Sigue, sigue, que ahí abajo siempre hay sitio para uno más como tú, perdedor.',
    'Espiral de la muerte en directo. El grupo ya no apuesta por tu recuperación, apuesta por cuánto tardas en batir tu propio récord de patetismo. Las cuotas son malas.',
    'Sigues en rojo y cada tirada es una carta de amor al fracaso. El aura ya te tiene en su lista de clientes vip de la ruina, con tarjeta dorada y todo.',
    'Negativo sobre negativo. Eres la prueba de que se puede llegar tarde hasta al fondo: cuando crees que tocaste, descubres que era solo un descansillo.',
    'Tu aura va camino del centro de la Tierra y el grupo solo se asoma de vez en cuando para confirmar que sí, sigues bajando. Hipnótico de lo predecible.',
    'En caída y sin paracaídas, porque lo vendiste para cubrir la pérdida anterior. Tu gestión del aura es digna de un curso de qué-no-hacer-jamás.',
    'Espiral confirmada. Lo tuyo ya no es mala suerte ni mal día: es una suscripción mensual al ridículo que renuevas tú solito, sin que nadie te obligue.',
    'Bajas tan rápido que el aura ni alcanza a actualizar el marcador. Eres el único capaz de hacer que un número se rinda antes que tú, fracasado.',
    'Negativo histórico y sumando. Si el patetismo cotizara serías millonario; como cotiza el aura, eres exactamente lo contrario: basura en quiebra técnica.',
    'Sigues hundiéndote y el aura ni se inmuta, como el médico que ve la radiografía y directamente llama a la familia. Ya no hay nada que hacer contigo.',
    'Tu aura en rojo es patrimonio cultural del grupo. Te ponen de ejemplo a los nuevos: "no acabéis como ese", señalándote a ti, en directo y sin anestesia.',
    'Caída libre con estilo propio: el de quien se rinde pero sigue jugando. Lo más absurdo que existe. Ni ganas ni te retiras. Solo molestas, perdedor.',
    'En negativo y profundizando, como tus problemas: nunca se resuelven, solo se acumulan en capas igual que el aura que pierdes. Arqueología del fracaso.',
    'Sigues cayendo y ya ni el grupo mira. Aburres hasta en la desgracia.',
    'Otra bajada. A esto ya no se le llama mala racha, se le llama estado natural.',
    'La caída lleva tanto tiempo que el marcador debería cobrarte alquiler por el sótano.',
    'Vas hacia abajo con una constancia que en otra cosa te habría hecho millonario.',
    'Nueva pérdida. Ya no es que te vaya mal: es que te va exactamente como te tiene que ir.',
    'Sigues bajando y encima con confianza. Esa mezcla es la que te trajo hasta aquí.',
    'Otra vez abajo. El grupo dejó de sorprenderse hace bastantes semanas.',
    'La espiral continúa. Tienes menos aura y la misma cantidad de excusas de siempre.',
    'Bajas otra vez. Nadie te empuja, tú solo aceleras y encima sin frenos.',
    'Caída sostenida. Vas camino de un récord que nadie va a querer batir jamás.',
    'Sigues cavando. En algún momento habrá que decirte que el fondo ya lo pasaste.',
    'Otro escalón hacia abajo. El sótano ya te reconoce y te saluda por el nombre.',
    'La bajada es tan constante que podría usarse para calibrar relojes. Impresionante y triste.',
    'Sigues perdiendo. Y lo peor es la naturalidad con la que ya lo asumes.',
    'Nueva pérdida encadenada. El marcador ya no reacciona, solo actualiza y suspira.',
    'Caes otra vez y ni haces ruido al aterrizar. Ya no queda desde dónde caer fuerte.',
    'La espiral sigue. A este ritmo vas a tener que pedir permiso para seguir bajando.',
    'Otra bajada más. Tu historial parece un tobogán y tú sigues subiendo las escaleras para tirarte.',
    'Sigues en caída libre. Lo único constante en tu vida y encima es esto.',
    'Nueva pérdida. El grupo ya no comenta tus caídas igual que no comenta la gravedad.',
    'Tocaste fondo hace tres derrotas y todavía sigues cavando, pringado.',
    'Tu aura ya está bajo cero y aún así encuentras maneras nuevas de hundirla. Eso es talento, pero del malo.',
    'Nadie apuesta ya contra ti porque no hay emoción en ver caer lo que nunca estuvo arriba.',
    'Llevas tantas derrotas seguidas que ganar te daría un susto de muerte.',
    'Tu racha es tan patética que el bot se aburre de anunciarla.',
    'Cada vez que juegas, el contador negativo se estira un poco más y a todos se la suda.',
    'Ya no pierdes, simplemente confirmas lo que todos dábamos por hecho.',
    'Ni el suelo te aguanta, joder. Lo atravesaste hace rato y sigues bajando.',
    'Tu aura tiene signo menos y personalidad propia. Se llama fracaso y vive contigo.',
    'Perder una vez es mala suerte. Perder así de seguido es una definición de quién eres.',
    'Ya nadie se sorprende contigo. Eres el clima de siempre, gris y sin interés.',
    'Has convertido el ridículo en rutina y encima lo haces mal.',
    'Tu historial parece la cuenta bancaria de un muerto de hambre: solo restas.',
    'Si esto fuera un deporte, ya te habrían retirado por incompetencia manifiesta.',
    'Sigues jugando porque no tienes nada mejor, y aun así lo haces fatal.',
    'El fondo del pozo te vio pasar de largo, inútil.',
    'Tu constancia es admirable. Lástima que sea constancia en ser una puta mierda.',
    'El grupo dejó de leer tus resultados hace semanas. Pierdes en silencio, como un don nadie.',
    'Ni cayendo consigues hacerlo con estilo. Caes torpe, ruidoso y solo.',
    'Cada derrota tuya es un capítulo más de una serie que nadie pidió.',
    'Ya no es una racha. Es tu estado natural, pringado.',
    'Cambiar de estrategia no te salvaría porque el problema eres tú.',
    'Perdiste tanto que la palabra derrota se quedó corta contigo.',
    'Tu nombre en la tabla está tan abajo que hay que hacer scroll para humillarte.',
    'Coño, ni intentándolo a propósito se pierde tantas veces seguidas.',
    'Lo tuyo no es descenso, es vocación.',
    'El único récord que ostentas es el de irrelevante con más intentos.',
    'Tu aura negativa ya pesa más que cualquier logro que hayas tenido en la vida.',
    'Sigues escarbando y lo peor es que crees que estás avanzando.',
    'No te da vergüenza porque hace mucho que agotaste esa reserva.',
    'Cero a la izquierda en el juego y cero a la izquierda fuera de él.',
    'Tus derrotas ya no dan pena, dan pereza.',
    'Cada intento tuyo es una confirmación más de que no aprendes nada.',
    'Ni la suerte quiere asociarse contigo, y la suerte no discrimina a casi nadie.',
    'Otra caída y ni un solo mensaje en el grupo. Ese silencio es tu verdadero marcador.',
    'Estás tan abajo que subir un puesto sería noticia mundial.',
    'Lo intentas otra vez con la misma cara de fracasado y el mismo resultado.',
    'Tu racha de derrotas tiene más solidez que cualquier cosa que hayas construido.',
    'Perdiste el respeto hace tiempo. Ahora solo pierdes números.',
    'Ya no compites, decoras la parte de abajo de la lista.',
    'Tienes el aura de un charco: bajo, sucio y sin profundidad.',
    'Basura acumulada, eso es tu historial. Y sigues añadiendo.',
    'Nadie te sostiene en la caída porque nadie sintió tu peso arriba.',
    'Cada derrota tuya es idéntica a la anterior y aun así te sorprende.',
    'Joder, hasta perder requiere algo de dignidad y tú ni eso conservas.',
    'Tu curva no baja, se despeña.',
    'Al menos si tocaras fondo tendrías una excusa. Tú lo perforaste.',
    'Sigues pidiendo revancha como si alguien te la debiera, pringado.',
    'Tus estadísticas son una carta de renuncia a tener orgullo.',
    'Ya no hay caída libre, hay caída rutinaria.',
    'Convertiste la humillación en suscripción mensual y encima la pagas tú.',
    'Perder te sale tan natural que ganar te descolocaría la identidad.',
    'Tu aura negativa es lo único tuyo que crece con constancia.',
    'El grupo no se ríe de ti por educación, sino por aburrimiento.',
    'Otra derrota. Ni siquiera merece comentario, y aun así aquí estoy gastando letras.',
    'Lo tuyo ya no es una mala racha, es un currículum.',
    'Ni chocando contra el fondo se te apaga esa fe absurda en ti mismo.',
    'Cada vez que reapareces sabemos exactamente cómo termina, inútil.',
    'Tienes la resistencia de un fracasado profesional y ninguna otra virtud.',
    'Bajas de posición con la misma facilidad con la que otros respiran.',
    'Si el ridículo cotizara, serías el único con acciones ilimitadas.',
    'Ya nadie te desafía porque vencerte no aporta nada a nadie.',
    'Tu marcador parece una condena y tú firmaste voluntariamente.',
    'Sigues sumando derrotas como quien colecciona basura por deporte.',
    'Un muerto de hambre con hambre de perder, eso eres.',
    'El fondo te queda lejos, y no porque estés arriba.',
    'Tanto insistir para nada. Eso resume tu presencia aquí.',
    'Tu racha ya tiene edad suficiente para tener opinión propia sobre ti, y no es buena.',
    'Cada caída tuya limpia el ambiente de expectativas. Ya nadie espera nada.',
    'Sigues abajo y lo peor es que ahí es donde encajas.',
    'Perdiste tantas veces que la palabra intento se te da mejor que la palabra logro.',
    'Ni cuando tocas fondo aprendes a quedarte quieto.',
    'Tu aura es tan negativa que arrastra a quien se pone cerca. Por eso nadie se pone.',
    'El único suspense contigo es cuánto vas a bajar esta vez.',
    'Sigues jugando con la determinación de un pringado y los resultados que le corresponden.',
    'Otro fracaso encadenado. Ya podrías cobrar por ofrecer este espectáculo triste.',
    'Bajas tan rápido que el sistema debería cobrarte gastos de mantenimiento.',
    'Tus derrotas se apilan tan alto que casi tapan lo poco que eres.',
    'Ni la mediocridad te acepta. Ella te quedaría grande.',
    'Cada partida tuya termina igual y aun así lo llamas mala suerte.',
    'Te la suda perder, y eso es exactamente por lo que sigues perdiendo.',
    'Tu presencia en la tabla es un ancla, no una posición.',
    'Sigues cayendo con la elegancia de una bolsa de basura por unas escaleras.',
    'El aura no te abandona, huye de ti. Hay diferencia.',
    'Otro golpe y ni te inmutas. Ya no queda nada que romper.',
    'Convertiste tocar fondo en una etapa intermedia. Enhorabuena, supongo.',
    'Tu constancia perdiendo es lo más parecido a una identidad que tienes.',
    'Ni una victoria de casualidad, joder. Ni una. Eso ya es estadísticamente insultante.',
    'El grupo te lee las derrotas como quien mira la pared.',
    'Sigues abajo y lo llamas estrategia. Se llama incompetencia.',
    'Tus intentos son puta mierda repetida con ligeras variaciones.',
    'Ya no hay caída que te sorprenda porque ninguna te enseña nada.',
    'Ni un milagro te levantaría. Volverías abajo por costumbre.',
    'Cada derrota te hunde un poco más y a ti te parece un progreso.',
    'El único terreno que dominas es el que está por debajo de cero.',
    'Un don nadie en descenso libre es lo más aburrido que puede pasar en este grupo.',
    'Sigues perdiendo con la naturalidad de quien no conoce otra cosa.',
    'Tu racha es tan larga que ya forma parte del reglamento no escrito: tú pierdes.',
    'Ni el suelo, ni el fondo, ni el ridículo te detienen. Sigue cavando, fracasado.',
    'Otro escalón hacia abajo y ni la molestia de disimular. Al menos eres coherente.',
  ],
  cursed: [
    'Acabas de perder un pastón de aura en directo. El desastre fue tan limpio que el grupo no supo si abuchear o aplaudir. Un Titanic, pero tú eres a la vez el barco y el iceberg.',
    'Catástrofe de aura con público. Tu marcador se desplomó como un suflé al que abren el horno antes de tiempo: rápido, irreversible y con cara de "lo veía venir" en todos menos en ti.',
    'Perdiste toda tu aura de golpe. El silencio que dejaste no fue de respeto, fue el de cuando alguien rueda por las escaleras y todos esperan a ver si se levanta. No te levantaste.',
    'Hundimiento total. Tu aura no bajó, hizo implosión, como esos edificios que demuelen con dinamita: planificado, espectacular y con gente grabándolo para enseñárselo a sus nietos.',
    'Aura aniquilada. Convertiste una simple tirada en una tragedia griega completa, con coro y todo: el grupo entero murmurando "pero cómo es posible" al unísono.',
    'Pulverizaste tu aura con un método que ni queriendo se replica. Eres el accidente que ponen en las autoescuelas: doloroso de ver, imposible de entender, imprescindible como advertencia.',
    'Desastre nuclear de aura. Hay que evacuar la zona, porque el fracaso que acabas de soltar tiene radiación de la que muta a la gente. Sálvese quien pueda del don nadie.',
    'Tu aura se fue a cero y de paso se llevó tu dignidad como daño colateral. Dos por uno en humillación, y encima invitas tú, que para esto siempre tienes presupuesto.',
    'Colapso histórico. El grupo va a recordar esta tirada más que su propio cumpleaños. Pasaste a la historia, sí: al capítulo de "errores que no se deben cometer jamás", con tu foto.',
    'Perdiste toda tu aura con la solemnidad de un funeral. Y en cierto modo lo fue: el de la última esperanza que alguien guardaba de que algún día no la cagaras.',
    'Catástrofe absoluta. Tu aura tocó un fondo tan profundo que rebotó, te ilusionaste medio segundo, y volvió a bajar. Hasta el rebote te traiciónó, fracasado.',
    'Aura desintegrada a nivel atómico. Ni los físicos saben explicar cómo alguien convierte tan poco en aún menos. Eres una anomalía científica con número de teléfono.',
    'Demolición total en horario de máxima audiencia. El grupo no pestañeó. Fue como ver un documental de naturaleza en el que la gacela tropieza ella sola, sin león ni nada.',
    'Perdiste hasta el último punto y el aura cerró la cuenta, cambió la cerradura y tiró las llaves al río. Te quedaste fuera hasta de tu propia ruina, que ya es difícil.',
    'Hecatombe de aura. Lo tuyo no fue caer, fue una renuncia voluntaria a la dignidad con firma, sello y testigos. Trámite completado, perdedor certificado y registrado.',
    'Tu aura se desplomó tan fuerte que se notó en otros grupos. Eres el terremoto del fracaso: epicentro tú, réplicas en todo tu entorno, víctimas todos menos tú, que ni te enteras.',
    'Aniquilación en directo. El grupo hizo captura no para reírse, sino como prueba para cuando lo cuenten y nadie se lo crea. "Os juro que pasó", dirán, señalando tu nombre.',
    'Catástrofe de manual. Cogiste una situación neutra y la convertiste en tu peor momento del año con una eficiencia que, bien usada, te habría sacado de pobre.',
    'Perdiste todo de una forma tan tuya que el grupo ni preguntó qué pasó. Ya lo sabían: pasó lo de siempre, pero en versión extendida, remasterizada y con escenas inéditas.',
    'Tu aura no murió, se suicidó por la vergüenza de pertenecerte. Primera vez que veo a un marcador preferir el cero antes que seguir un segundo más asociado a alguien.',
    'Desastre total con efectos especiales. Si el ridículo diera premios, esta noche subes al escenario, lloras de emoción y olvidas mencionar al único culpable de todo: tú.',
    'Colapso absoluto. Lo que acabas de hacer va a servir de cuento para asustar a los nuevos del grupo: "pórtate bien o acabarás como ese", y todos mirando tu aura en cero.',
    'Perdiste tanta aura que la gráfica parece un acantilado. Los que hacen senderismo por desgracias ajenas se pararían aquí a hacerse una foto: "mira, el Gran Cañón del fracaso".',
    'Aura ejecutada en plaza pública. Ni venda en los ojos pediste. Te plantaste, la cagaste de frente y caíste mirando al grupo: lo más cerca de valiente que vas a estar en tu vida.',
    'Catástrofe con denominación de origen. Otros fracasan; tú fabricas desastres artesanales, de kilómetro cero, con tu sello inconfundible de inútil orgulloso de serlo.',
    'Tu aura se evaporó y el grupo guardó un minuto de silencio. No por ti, tranquilo, sino por el pobre marcador, que no eligió este trabajo y aun así tiene que contarte a ti.',
    'Hundimiento épico. Conseguiste que perder fuera un espectáculo, lo cual ya es raro, porque normalmente eres aburrido. Hoy al menos fracasaste en HD y con sonido envolvente.',
    'Aura demolida. Lo más impresionante es la naturalidad: ni un titubeo, ni una duda. Te lanzaste al ridículo como quien llega a casa. Porque para ti lo es, perdedor.',
    'Catástrofe de las que dejan cráter. El grupo va a tardar en olvidarlo, sobre todo porque pienso recordárselo cada vez que abras la boca. De nada, basura.',
    'Perdiste todo y batiste tu propio récord de patetismo, que ya estaba altísimo. Eres el único atleta que entrena duro para ser cada día un poco peor, y mira, lo clavas.',
    'Tu aura tocó el cero absoluto, temperatura a la que hasta los átomos se quedan quietos. Apropiado, porque tú llevas parado mucho más tiempo y con mucha menos excusa.',
    'Desastre integral. No salvaste nada: ni los muebles, ni la cara, ni el "bueno, al menos lo intenté". Saliste con lo puesto, y lo puesto era pura vergüenza, fracasado.',
    'Aura pulverizada delante de testigos. La diferencia entre tú y un chiste es que el chiste lo cuenta alguien a propósito para que la gente se ría. A ti te sale solo.',
    'Colapso nivel leyenda. Te ganaste plaza permanente en el muro de la vergüenza del grupo, con foto, fecha y un cartelito que dice: "aquí descansa el que lo tenía fácil".',
    'Perdiste hasta lo que no tenías. Cerraste en un negativo tan absurdo que el aura tuvo que inventar un número nuevo solo para humillarte con precisión. Te lo has currado, puto.',
    'Tu aura se desintegró y el grupo entero soltó a la vez ese "uuuf" de cuando alguien se estrella en la tele. Generaste reacción colectiva. Negativa, pero colectiva. Casi te aplaudo.',
    'Hiciste algo tan malo que el grupo entero tuvo que fingir que no lo vio. Aura destruida.',
    'Catástrofe total. Ni el bot encuentra la forma de contarlo sin que suene peor de lo que fue.',
    'Aura pulverizada. Vas a tardar semanas en que alguien te mire sin recordar esto.',
    'Lo tuyo hoy fue un accidente con testigos. El aura no baja, se desintegra.',
    'Desastre absoluto. Tenías una salida fácil y elegiste prender fuego a todo.',
    'Aura por los suelos. El grupo tiene material para reírse de ti hasta fin de año.',
    'Hiciste el ridículo en grado máximo y encima delante de todos. Aura reducida a cenizas.',
    'Fracaso monumental. Ni queriendo se hace tan mal, y tú ni siquiera lo intentabas.',
    'Aura destruida. La gente va a contar esto en el grupo cuando tú ya no estés.',
    'Catástrofe en directo. El grupo entero calló, pero no por respeto: por vergüenza ajena.',
    'Perdiste todo lo que habías construido en un solo movimiento. Talento para lo peor.',
    'Aura arrasada. Esto no fue un error, fue una demolición planificada de ti mismo.',
    'Desastre histórico. Va a ser el ejemplo de lo que no se hace durante mucho tiempo.',
    'Hiciste lo imposible: quedar peor de lo que ya estabas. Aura en números rojos profundos.',
    'Aura aniquilada. Ni un abogado bueno te saca de la que has liado hoy.',
    'Fracaso de los que dejan marca. El grupo cambió de tema para no seguir viéndolo.',
    'Catástrofe absoluta. Te hundiste solo, sin ayuda, con público y en horario de máxima audiencia.',
    'Aura reventada. La única buena noticia es que desde aquí ya no se puede caer más.',
    'Desastre irreparable. Lo intentaste, salió mal, y encima insististe. Eso ya es vocación.',
    'Hoy tocaste fondo y encima con estilo propio. Aura mínima histórica confirmada.',
    'Aura hecha pedazos. El grupo entero fue testigo y nadie va a olvidarlo por caridad.',
    'Colapso total. Había cien formas de salir bien y encontraste la única que no existía.',
    'Aura demolida. Esto no se arregla hablando: se arregla desapareciendo un par de semanas.',
    'Desastre de manual. Cuando cuenten esta historia, tú vas a ser el ejemplo negativo.',
    'Aura mínima. Lo raro no es que fallaras, es la magnitud con la que lo conseguiste.',
    'Tiraste el dado y hasta el azar decidió humillarte delante de todos. Ni la suerte quiere asociarse contigo.',
    'Catastrófico. Como tu vida entera, pero esta vez con testigos.',
    'Acabas de perder tanta aura que el contador se avergüenza de sumarte.',
    'Hiciste el ridículo tú solo, sin ayuda de nadie. Es lo único que se te da bien.',
    'El grupo entero vio cómo te hundías y nadie movió un dedo. Eso dice más de ti que el resultado.',
    'Puta mierda de tirada. Igual que todo lo que tocas, pringado.',
    'Fuiste a por aura y volviste con vergüenza. Menudo negocio, muerto de hambre.',
    'Esto no fue mala suerte. Fue tu marca personal cumpliéndose otra vez en público.',
    'Perdiste aura, respeto y lo poco que quedaba de tu dignidad. Todo en un solo turno.',
    'El dado te miró, te calibró y decidió que merecías menos. Tiene mejor criterio que tú.',
    'Joder, qué desastre. Y lo peor es que nadie se sorprendió.',
    'Tu aura no cayó, se desplomó. Como todo proyecto que empiezas.',
    'Eres tan inútil que hasta el azar te trata como a un chiste que ya no hace gracia.',
    'Te has quedado en números rojos de aura y de credibilidad. Enhorabuena, fracasado.',
    'El grupo entero se quedó callado. No por respeto, sino por pena.',
    'Tiraste como vives: sin cabeza, sin suerte y sin resultados.',
    'Eso no fue una tirada, fue una confesión pública de lo que eres.',
    'Perdiste aura delante de gente que ya te tenía por un cero a la izquierda. Se lo confirmaste.',
    'Cada vez que abres la boca o tiras el dado, el resultado es el mismo: mierda.',
    'Te hundiste solo, sin corriente, sin viento y sin excusas. Puro talento tuyo.',
    'El dado no te odia. Simplemente no encontró nada en ti que salvar.',
    'Tu tirada fue tan mala que hasta el que estaba último respiró aliviado.',
    'Coge tu aura del suelo. Ah, espera, ya no queda nada que recoger.',
    'Hiciste el ridículo con tal naturalidad que se nota que llevas años practicando.',
    'No perdiste una partida, perdiste el poco crédito que te quedaba aquí.',
    'Un desastre con nombre y apellidos. Los tuyos.',
    'Te la jugaste y el resultado fue una bofetada pública. Bien merecida.',
    'Ni con el azar de tu parte servías. Imagínate con esfuerzo real.',
    'Esa tirada es el resumen perfecto de tu paso por este grupo: ruido y nada más.',
    'Perder así requiere un nivel de incompetencia que no se improvisa.',
    'Tu aura acaba de desaparecer y nadie ha preguntado por ella. Como por ti.',
    'Acabas de demostrar que puedes empeorar. Nadie lo creía posible.',
    'Fracasaste tan fuerte que el resto va a usarte de ejemplo durante meses.',
    'Coge aire. Lo vas a necesitar para soportar lo que acaba de pasar delante de todos.',
    'El dado te dio exactamente lo que vales. Redondeando hacia arriba.',
    'Tu intento salió tan mal que hasta a ti te dio vergüenza. Y eso es difícil.',
    'Te has quedado sin aura, sin argumentos y sin nadie que te defienda.',
    'Basura de resultado para un basura de jugador. Todo cuadra.',
    'Nadie va a recordar tus victorias porque no existen. Esta caída sí la recordarán.',
    'El grupo entero acaba de confirmar lo que ya sospechaba de ti. Gracias por la demostración.',
    'Se te cayó la máscara y detrás no había nada. Ni siquiera un fracasado interesante.',
    'Ese resultado no es azar, es diagnóstico.',
    'Perdiste tanta aura que el sistema debería cobrarte por seguir jugando.',
    'Te la suda todo hasta que te toca perder en público. Ahí sí duele, ¿verdad?',
    'Un cero a la izquierda tirando dados. El resultado era predecible.',
    'Cada intento tuyo termina igual: tú en el suelo y el resto mirando.',
    'No fue una derrota. Fue una demolición con espectadores.',
    'Tu aura estaba baja. Ahora directamente no existe. Como tu relevancia.',
    'Ni siquiera lograste fracasar con estilo. Fue feo, lento y vergonzoso.',
    'Ese golpe te lo diste tú solo. Nadie tuvo que esforzarse para verte caer.',
    'Todo el mundo lo vio. Todo el mundo lo entendió. Nadie lo va a olvidar.',
    'Eres el único capaz de salir peor de lo que entró. Un talento raro y totalmente inútil.',
    'Tu tirada huele a lo mismo que tu historial: mierda acumulada.',
    'Perdiste delante de gente que ni te tiene guardado el nombre. Qué humillación más barata.',
    'Fallaste tan a lo grande que casi resulta impresionante. Casi.',
    'Se acabó la fantasía. El resultado te devolvió a tu sitio: el último.',
    'Ni un milagro te habría salvado, y aun así lo esperabas. Eso es lo verdaderamente patético.',
    'Tu aura acaba de tocar fondo y el fondo se ha quejado.',
    'El grupo pidió espectáculo y les diste un funeral de tu propia reputación.',
    'Joder, ni queriendo se falla así. Lo tuyo es vocacional.',
    'Perdiste, te expusiste y encima no tienes con qué responder. Silencio, pringado.',
    'Acabas de regalar tu aura al vacío. Al menos el vacío le dará mejor uso.',
    'Cada tirada tuya es una nueva forma de recordarnos que no vales para esto.',
    'Un inútil con suerte aún puede ganar. Tú ni eso conseguiste.',
    'Te hundiste tanto que habría que excavar para encontrar tu aura.',
    'La caída fue tuya, la vergüenza es tuya y las risas son del resto.',
    'Nadie te saboteó. No hacía falta. Ya te bastas tú solo.',
    'Esa cifra en negativo es lo más honesto que ha dicho nadie sobre ti.',
    'Se te fue el aura y con ella lo único que te hacía soportable aquí.',
    'Menudo tortazo público. Y lo peor es que te lo buscaste con ganas.',
    'Tu aura se ha desintegrado y el grupo lo ha celebrado en silencio.',
    'Fracasaste tan limpio que no hay ni debate. Solo vergüenza ajena.',
    'Vas a tardar meses en recuperar lo que perdiste en dos segundos de estupidez.',
    'Eres el chiste del grupo y acabas de escribir tú mismo el remate.',
    'Perdiste aura por ser exactamente quien eres. No hay tratamiento para eso.',
    'El resto tira dados. Tú tiras tu reputación por la ventana.',
    'Te vieron intentarlo, te vieron fallar y te vieron quedarte callado. Trilogía completa.',
    'Puta mierda de turno. Y aun así es tu mejor actuación del mes.',
    'Tu caída fue tan estrepitosa que hasta los que no jugaban se enteraron.',
    'No hay forma de maquillar esto. Perdiste y quedaste retratado.',
    'Ese resultado te representa mejor que cualquier cosa que hayas dicho aquí.',
    'Te quedó el ego a la altura del suelo. Justo donde debía estar.',
    'Se te va el aura, se te va el turno y se te va la poca paciencia que te tenían.',
    'Fallaste en público, en directo y sin margen de duda. Aplausos por la claridad.',
    'El dado hizo en un segundo lo que el grupo llevaba meses pensando de ti.',
    'Perdiste tanto que ya ni tiene gracia rematarte. Casi.',
    'Nadie apostaba por ti y aun así superaste las expectativas. Por abajo.',
    'Tu turno acabó en catástrofe y encima con nombre propio en el registro.',
    'Coge la derrota, guárdatela y cállate un rato. Ya has hablado bastante con esa tirada.',
    'Un inútil de manual haciendo una demostración de manual.',
    'Se hundió tu aura y contigo dentro. Bonita imagen para el grupo.',
    'Esa tirada debería venir con disculpa incluida hacia los que la presenciaron.',
    'Ni el más torpe habría conseguido un desastre tan redondo.',
    'Te la jugaste con lo poco que tenías y lo perdiste todo. Gestión brillante, fracasado.',
    'Ya no eres el que va perdiendo. Eres el ejemplo de cómo se pierde.',
    'Tu aura no vale nada y encima acabas de demostrar que tú tampoco.',
    'El grupo no se ríe contigo, se ríe de ti. Hoy más que nunca.',
    'Eso fue un derrumbe, no una tirada. Y lo firmaste tú.',
    'Ni siquiera te dio tiempo a presumir. El dado te calló antes.',
    'Se te cayó el aura encima y ni fuerzas tienes para levantarla.',
    'Fracaso público, gratuito y perfectamente evitable. Tu especialidad.',
    'Todo el grupo acaba de subir de nivel viendo lo bajo que puedes caer.',
    'Tu tirada fue el recordatorio colectivo de que aquí no pintas nada.',
    'Ni con ventaja, ni con suerte, ni con ayuda. Sigues siendo un desastre.',
    'Coge nota de este momento. Es lo más cerca que has estado del protagonismo.',
    'Te expusiste, fallaste y ahora tienes que convivir con las miradas. Disfrútalo.',
    'Qué manera más patética de confirmar que no sirves ni para tener suerte.',
    'Se acabó tu racha. Bueno, no tenías racha. Se acabó la ilusión.',
    'El desastre fue tuyo, el espectáculo fue del grupo. Reparto justo.',
    'Ni un solo argumento te queda después de esto. Solo el ridículo.',
    'Perdiste aura de una forma tan tonta que hasta cuesta insultarte con creatividad.',
    'Tu turno pasó a la historia del grupo. Por lo malo, obviamente.',
    'Se la suda a todos tu explicación. Solo importa que perdiste y cómo lo hiciste.',
    'Nunca has estado tan abajo y aun así nadie duda de que puedes bajar más.',
    'Te hundiste tan rápido que ni te dio tiempo a fingir que lo controlabas.',
    'El azar te ofreció una salida y tú elegiste el precipicio. Muy propio.',
    'Catástrofe total. La única cosa que has hecho a lo grande en tu vida.',
  ],
};


// !aura top — leaderboard of accumulated aura in the group.
async function showRanking(sock, msg, groupMeta) {
  const jid = msg.key.remoteJid;
  if (!jid.endsWith('@g.us')) {
    return sock.sendMessage(jid, { text: 'El ranking de aura solo existe en grupos.' }, { quoted: msg });
  }
  // Dos filtros antes de cortar el top 10:
  //   · quien ya no esta en el grupo no ocupa puesto — el aura se guarda para
  //     siempre y sin esto el ranking seguia coronando a gente que se fue;
  //   · el owner principal es invisible en toda salida automatica.
  const ranking = soloMiembros(await getAuraRanking(jid), groupMeta)
    .filter(r => !isMainOwner(r.jid, false, groupMeta))
    .slice(0, 10);
  if (ranking.length === 0) {
    return sock.sendMessage(jid, { text: 'Nadie ha medido su aura todavía. Usa *!aura*.' }, { quoted: msg });
  }
  let text = '*RANKING DE AURA*\n\n';
  const mentions = [];
  ranking.forEach((r, i) => {
    text += `*${i + 1}.* @${r.jid.split('@')[0]} — ${fmt(r.aura)}\n`;
    mentions.push(r.jid);
  });
  await sock.sendMessage(jid, { text: text.trimEnd(), mentions }, { quoted: msg });
}

const AURA_INFO =
`*¿QUÉ ES EL AURA?*

El aura es tu puntuación social en el grupo. Empieza en *100* y sube o baja según lo que hagas.

*CÓMO GANAR O PERDER AURA*
· *!aura* — tiras el dado (3min cooldown). Puede subir o bajar dependiendo de tu rol: el owner tiene ventaja, los admins algo menos, los miembros la peor odds. La tirada no mira cuánta aura llevas: cada tirada empieza de cero.
· *Bonos automáticos* — solo por escribir en el grupo recibes bonos al llegar a 200, 500 y 1000 mensajes diarios. El contador se reinicia cada 24h, así que la carrera empieza de nuevo cada día. Los premios mínimos garantizados: Tier 1 (200 msgs) *1.000*, Tier 2 (500 msgs) *2.500*, Tier 3 (1000 msgs) *5.000*. Con suerte puedes sacar mucho más.
· *Jackpot de redención* — si llevas aura negativa, tienes probabilidad extra de sacar un premio enorme en cualquier tier. El aura del grupo no abandona a los hundidos.
· *!duel @user* — apuesta aura contra otro. El retado acepta con !duel aceptar. Gana el más favorecido por el sistema (owner > admin > miembro), pero nadie está a salvo.
· *!robo @user* — intenta robar aura a alguien. El resultado no es solo ganar o perder: hay golpes maestros, robos a medias y desastres en los que la víctima se queda con lo tuyo. 10min de cooldown.
· *!dar @user <cantidad>* — transfiere aura a otro miembro voluntariamente. Mínimo 5.

*COMANDOS*
· *!aura* — tirar para ti
· *!aura @user* — ver aura de alguien
· *!aura top* — ranking del grupo
· *!aura hoy* — tu progreso de hoy (msgs y próximo bono)`;

// !aura [@user]  — rolls aura for the target and updates their PERSISTENT total.
// !aura top      — shows the group leaderboard.
// !aura info     — explains the full system.
async function cmdAura(sock, msg, args, groupMeta) {
  const jid = msg.key.remoteJid;

  const sub = (args && args[0] ? args[0] : '').toLowerCase();
  if (['top', 'rank', 'ranking', 'leaderboard'].includes(sub)) {
    return showRanking(sock, msg, groupMeta);
  }
  if (['info', 'help', 'ayuda', 'como', 'cómo', '?'].includes(sub)) {
    return sock.sendMessage(jid, { text: AURA_INFO }, { quoted: msg });
  }
  // Progreso diario. Vive en social.js (cmdCasino) y se expone aquí como
  // "!aura hoy" porque es aura, no un casino aparte. !casino sigue valiendo.
  if (['hoy', 'today', 'dia', 'día', 'diario'].includes(sub)) {
    const { cmdCasino } = require('./social');
    return cmdCasino(sock, msg);
  }

  const sender = getSender(msg);

  // El aura es como una moneda: solo el dueño la juega. !aura @alguien es solo
  // una CONSULTA del aura de esa persona — no tira, no gasta cooldown y no
  // modifica nada. Tirar (subir/bajar) siempre es sobre uno mismo.
  const mentioned = getTarget(msg);
  if (mentioned && !sameUser(mentioned, sender)) {
    const aura = await getAura(jid, mentioned);
    return sock.sendMessage(jid, {
      text: `*@${mentioned.split('@')[0]}* tiene *${fmt(aura)}* de aura.`,
      mentions: [mentioned],
    }, { quoted: msg });
  }

  const coolKey = `${jid}|${canonicalJid(sender)}`;
  const last = lastRoll.get(coolKey) || 0;
  const remaining = ROLL_COOLDOWN_MS - (Date.now() - last);
  if (remaining > 0) {
    const mins = Math.ceil(remaining / 60_000);
    return sock.sendMessage(jid, {
      text: `Espera *${mins}min* para volver a tirar.`,
    }, { quoted: msg });
  }
  if (lastRoll.size >= 2000) lastRoll.delete(lastRoll.keys().next().value);
  lastRoll.set(coolKey, Date.now());

  // The roll is rigged by the SENDER's own role — you only ever play your own aura.
  const selfIsOwner = isOwner(sender, msg.key.fromMe, groupMeta);
  const selfIsAdmin = isAdmin(groupMeta?.participants, sender);

  const { tier, amount } = rollAura(selfIsOwner, selfIsAdmin);
  const sign = amount >= 0 ? '+' : '-';

  const { previous, current } = await addAura(jid, sender, amount);

  // Already in the red and going deeper: use spiral phrases
  const effectiveTier = (previous < 0 && amount < 0) ? 'spiral' : tier;

  const text =
    `*@${sender.split('@')[0]} ${sign}${fmt(Math.abs(amount))} de aura*\n` +
    `${pickFresh(AURA[effectiveTier], `${jid}|aura|${effectiveTier}`)}\n\n` +
    `Aura total: *${fmt(current)}*`;

  await sock.sendMessage(jid, { text, mentions: [sender] }, { quoted: msg });
}

module.exports = { cmdAura };
