// !iq — mide el coeficiente intelectual.
//
// No es un comando de porcentaje. Los de percent.js sacan un 0-100 y lo cuentan
// como "eres un X% de algo"; aquí la gracia está en la CIFRA de IQ, que tiene
// una escala reconocible (100 es la media, 70 es discapacidad, 130 es superdotado)
// y permite comparaciones que un porcentaje no da: un 65 de IQ se compara con un
// animal o con un objeto, un 95 con alguien concreto, un 130 ya impone.
//
// TOTALMENTE ALEATORIO, igual que !linda y !fea: no hay sesgo por rol ni amaño
// del owner. Aquí a todo el mundo le puede caer un 62 o un 141.

const { getTargetOrSelf } = require('../utils/wa');
const { pickFresh } = require('../utils/helpers');

// Tramos. El reparto está pensado para que lo divertido salga a menudo: casi la
// mitad de las tiradas caen en los dos tramos bajos, que son los que tienen las
// comparaciones. El de genio es raro a propósito — si saliera cada dos por tres
// dejaría de tener gracia que salga.
//
//   abismo   55-74   comparación con un animal o un objeto
//   bajo     75-89   comparación con alguien o algo concreto
//   medio    90-109  la media: ni frío ni caliente
//   alto    110-129  listo de verdad
//   genio   130-145  otra liga
const TRAMOS = [
  { clave: 'abismo', min: 55,  max: 74,  peso: 0.28 },
  { clave: 'bajo',   min: 75,  max: 89,  peso: 0.24 },
  { clave: 'medio',  min: 90,  max: 109, peso: 0.26 },
  { clave: 'alto',   min: 110, max: 129, peso: 0.16 },
  { clave: 'genio',  min: 130, max: 145, peso: 0.06 },
];

function tirarIQ() {
  let r = Math.random();
  for (const t of TRAMOS) {
    r -= t.peso;
    if (r <= 0) {
      return { clave: t.clave, iq: t.min + Math.floor(Math.random() * (t.max - t.min + 1)) };
    }
  }
  const t = TRAMOS[TRAMOS.length - 1];
  return { clave: t.clave, iq: t.min + Math.floor(Math.random() * (t.max - t.min + 1)) };
}

// %IQ se sustituye por la cifra que salió, para que la frase pueda jugar con
// ella ("tienes 62 y el termostato de tu casa tiene 68").
const ABISMO = [
  'Tienes las mismas capacidades cognitivas que un trozo de mierda recién cagado por un perro. Y el trozo al menos tiene forma.',
  '%IQ de coeficiente. El resto del grupo usa calculadora; tú usas los dedos y todavía te sobran.',
  'Con %IQ estás a un paso del apagón total y ese paso ya lo diste hace varios hilos, asco y sin derecho a apelación.',
  '%IQ. El número habla solo y con claridad; tú no, y a veces es lo mejor que puedes hacer, basura y sin derecho a apelación.',
  'Con %IQ el silencio te favorece más que cualquier argumento que hayas intentado montar, cabrón y sin derecho a apelación.',
  '%IQ. Eres el argumento perfecto contra la meritocracia cognitiva del puto ranking, gilipollas y sin derecho a apelación.',
  'Con %IQ. el bot no necesita narrador: el número te deja en el sótano y cierra el parte, patético y sin derecho a apelación.',
  '%IQ de abismo. Ni el low del resto se atreve a bajar a tu planta, ridículo y sin derecho a apelación.',
  'Tienes %IQ. y se nota en cada frase torcida que sueltas como si fueran ideas, mierda y sin derecho a apelación.',
  '%IQ. El grupo ya asumió que no hay que esperarte en el debate serio, coño y sin derecho a apelación.',
  'Con %IQ estás por debajo del umbral donde merece la pena discutir contigo, joder y sin derecho a apelación.',
  '%IQ. Ni el algoritmo de respeto te mira de frente, fracasado y sin derecho a apelación mierda %IQ no se discute con narrativa barata.',
  'El abismo cognitivo tiene tu nombre y el número %IQ de placa, asco y sin derecho a apelación coño %IQ no se discute con narrativa barata.',
  '%IQ. Has convertido la falta de luces en identidad del ranking, basura y sin derecho a apelación cabrón.',
  'Con %IQ. el chat funciona mejor cuando no escribes, cabrón y sin derecho a apelación gilipollas %IQ no se discute con narrativa barata.',
  '%IQ de coeficiente: el sótano del comando y tú sois la misma dirección, gilipollas y sin derecho a apelación.',
  'Se te nota el %IQ en la primera línea de cada mensaje inútil, patético y sin derecho a apelación asco.',
  '%IQ. El bot no exagera: lee el número y te coloca donde mereces, ridículo y sin derecho a apelación.',
  'Con %IQ cambias de tema porque no aguantas el hilo dos mensajes, mierda y sin derecho a apelación.',
  '%IQ. El espejo del comando te devuelve un abismo y no hay filtro que lo tape, coño y sin derecho a apelación.',
  'Tienes %IQ. y el grupo ya pasó de página hace rato, joder y sin derecho a apelación joder %IQ no se discute con narrativa barata.',
  '%IQ. Argumentas como quien no ha abierto un puto libro en su vida, fracasado y sin derecho a apelación.',
  'Con %IQ el silencio es tu mejor aportación al hilo, asco y sin derecho a apelación coño %IQ no se discute con narrativa barata.',
  '%IQ de abismo documentado. Autor: tú. Testigo: el ranking, basura y sin derecho a apelación cabrón %IQ no se discute con narrativa barata.',
  'El número %IQ no admite recurso ni segunda lectura útil, cabrón y sin derecho a apelación gilipollas.',
  '%IQ. Has bajado el promedio cognitivo del grupo solo con existir, gilipollas y sin derecho a apelación.',
  'Con %IQ ni el low del resto te considera rival de ideas, patético y sin derecho a apelación asco %IQ no se discute con narrativa barata.',
  '%IQ. El comando te nombra sin anestesia y el chat archiva, ridículo y sin derecho a apelación basura.',
  'Tienes %IQ y se te cae el personaje en la primera réplica, mierda y sin derecho a apelación ridículo.',
  '%IQ. El abismo no es metáfora: es el tramo y tú vives ahí, coño y sin derecho a apelación fracasado.',
  'Con %IQ el debate te queda grande y el silencio te queda justo, joder y sin derecho a apelación joder.',
  '%IQ. Ni la calculadora del bot se molesta en redondear a tu favor, fracasado y sin derecho a apelación.',
  'El ranking de luces te deja en el sótano con %IQ de placa, asco y sin derecho a apelación coño %IQ no se discute con narrativa barata.',
  '%IQ. Has firmado el empty head en cada mensaje del historial, basura y sin derecho a apelación cabrón.',
  'Con %IQ el grupo no te cita porque no hay qué citar, cabrón y sin derecho a apelación gilipollas %IQ no se discute con narrativa barata.',
  '%IQ de coeficiente. El resto piensa; tú repites, gilipollas y sin derecho a apelación patético %IQ no se discute con narrativa barata.',
  'Se te nota el %IQ hasta en la miniatura del estado, patético y sin derecho a apelación asco %IQ no se discute con narrativa barata.',
  '%IQ. El low de otros es tu techo natural, ridículo y sin derecho a apelación basura %IQ no se discute con narrativa barata.',
  'Con %IQ el hilo se empobrece solo con tu entrada, mierda y sin derecho a apelación ridículo %IQ no se discute con narrativa barata.',
  '%IQ. El bot te ha medido y el resultado no admite consuelo, coño y sin derecho a apelación fracasado.',
  'Tienes %IQ y el almost de idea nunca llega a tesis, joder y sin derecho a apelación joder %IQ no se discute con narrativa barata.',
  '%IQ. Eres el gag cognitivo del comando y el grupo no pide replay, fracasado y sin derecho a apelación.',
  'Con %IQ el modo avión del cerebro es tu estado por defecto, asco y sin derecho a apelación coño %IQ no se discute con narrativa barata.',
  '%IQ de abismo. Sin recurso, sin bis, sin anestesia, basura y sin derecho a apelación cabrón %IQ no se discute con narrativa barata.',
  'El número habla: %IQ. Tú no, y es lo mejor que puedes hacer, cabrón y sin derecho a apelación gilipollas.',
  '%IQ. Has convertido la falta de sustancia en marca personal, gilipollas y sin derecho a apelación.',
  'Con %IQ ni el tutorial de pensar te salva a estas alturas, patético y sin derecho a apelación asco %IQ no se discute con narrativa barata.',
  '%IQ. El sótano del ranking te queda de casa y de apodo, ridículo y sin derecho a apelación basura %IQ no se discute con narrativa barata.',
  'Tienes %IQ y se ve desde el primer pixel del mensaje, mierda y sin derecho a apelación ridículo %IQ no se discute con narrativa barata.',
  '%IQ. El comando no regala décimas de caridad cognitiva, coño y sin derecho a apelación fracasado %IQ no se discute con narrativa barata.',
  'Con %IQ el grupo ya asumió el empty seat cuando escribes, joder y sin derecho a apelación joder %IQ no se discute con narrativa barata.',
  '%IQ. Argumentas en círculos porque el centro está vacío, fracasado y sin derecho a apelación mierda.',
  'El abismo tiene %IQ de profundidad y tu nombre en la entrada, asco y sin derecho a apelación coño %IQ no se discute con narrativa barata.',
  '%IQ. Has bajado el listón del debate solo con abrir la boca, basura y sin derecho a apelación cabrón.',
  'Con %IQ el silencio ajeno no es respeto: es alivio, cabrón y sin derecho a apelación gilipollas %IQ no se discute con narrativa barata.',
  '%IQ de coeficiente. El bot firma y cierra el parte, gilipollas y sin derecho a apelación patético %IQ no se discute con narrativa barata.',
  'Se te nota el %IQ en cada cambio de tema sin sentido, patético y sin derecho a apelación asco %IQ no se discute con narrativa barata.',
  '%IQ. Ni el low del resto baja a tu planta a discutir, ridículo y sin derecho a apelación basura %IQ no se discute con narrativa barata.',
  'Con %IQ el hilo prefiere tu ausencia a tu aporte, mierda y sin derecho a apelación ridículo %IQ no se discute con narrativa barata.',
  '%IQ. El ranking de luces y el abismo coinciden en ti, coño y sin derecho a apelación fracasado %IQ no se discute con narrativa barata.',
  'Tienes %IQ y el almost de coherencia se queda en almost, joder y sin derecho a apelación joder %IQ no se discute con narrativa barata.',
  '%IQ. Eres el contenido de ridículo cognitivo del día, fracasado y sin derecho a apelación mierda %IQ no se discute con narrativa barata.',
  'Con %IQ el modo pensar se te agota en la primera frase, asco y sin derecho a apelación coño %IQ no se discute con narrativa barata.',
  '%IQ de abismo documentado basura y sin derecho a apelación cabrón cabrón %IQ no se discute con narrativa barata.',
  'El número %IQ no necesita narrador: se basta solo, cabrón y sin derecho a apelación gilipollas %IQ no se discute con narrativa barata.',
  '%IQ. Has firmado el empty head con cada mensaje inútil, gilipollas y sin derecho a apelación patético.',
  'Con %IQ el debate te expulsa antes del primer argumento serio, patético y sin derecho a apelación.',
  '%IQ. El sótano no es metáfora: es tu tramo y tu casa, ridículo y sin derecho a apelación basura %IQ no se discute con narrativa barata.',
  'Tienes %IQ y se te cae la idea en el primer punto y seguido, mierda y sin derecho a apelación ridículo.',
  '%IQ. El comando te nombra en el abismo sin pedir permiso, coño y sin derecho a apelación fracasado %IQ no se discute con narrativa barata.',
  'Con %IQ el grupo no espera sustancia y tú no defraudas esa expectativa, joder y sin derecho a apelación.',
  '%IQ. El almost de luces nunca cruza la línea de llegada, fracasado y sin derecho a apelación mierda.',
  'El ranking te deja en %IQ y cierra sin recurso de apelación, asco y sin derecho a apelación coño %IQ no se discute con narrativa barata.',
  '%IQ. Has convertido la torpeza cognitiva en estribillo del chat, basura y sin derecho a apelación.',
  'Con %IQ ni el filtro de autoestima te salva del número, cabrón y sin derecho a apelación gilipollas.',
  '%IQ de coeficiente. El resto del grupo ya pasó de página, gilipollas y sin derecho a apelación patético.',
  'Se te nota el %IQ hasta en los mensajes que pretenden ser serios, patético y sin derecho a apelación.',
  '%IQ. El abismo te queda de apodo y de residencia fiscal, ridículo y sin derecho a apelación basura %IQ no se discute con narrativa barata.',
  'Con %IQ el hilo se ensucia solo con tu intervención, mierda y sin derecho a apelación ridículo %IQ no se discute con narrativa barata.',
  '%IQ. El bot no discute: el número habla y tú estás abajo, coño y sin derecho a apelación fracasado %IQ no se discute con narrativa barata.',
  'Tienes %IQ y el gag se escribe solo en el ranking, joder y sin derecho a apelación joder %IQ no se discute con narrativa barata.',
  '%IQ. Eres el empty seat con nick del comando, fracasado y sin derecho a apelación mierda %IQ no se discute con narrativa barata.',
  'Con %IQ el modo luces apagadas es tu setting por defecto, asco y sin derecho a apelación coño %IQ no se discute con narrativa barata.',
  '%IQ de abismo. Sin consuelo, sin bis, sin segunda lectura, basura y sin derecho a apelación cabrón %IQ no se discute con narrativa barata.',
  'El número %IQ te nombra sin anestesia delante del grupo, cabrón y sin derecho a apelación gilipollas.',
  '%IQ. Has bajado el promedio del chat solo con existir en el hilo, gilipollas y sin derecho a apelación.',
  'Con %IQ el silencio es lo único que no te deja en evidencia, patético y sin derecho a apelación asco.',
  '%IQ. El sótano del ranking y tú sois la misma dirección postal, ridículo y sin derecho a apelación.',
  'Tienes %IQ y se ve en cada frase que no sostiene un puto argumento, mierda y sin derecho a apelación.',
  '%IQ. El comando firma el parte y el chat archiva sin debate, coño y sin derecho a apelación fracasado.',
  'Con %IQ ni el tutorial de coherencia te saca del abismo, joder y sin derecho a apelación joder %IQ no se discute con narrativa barata.',
  '%IQ. El almost de idea se queda en ruido de fondo, fracasado y sin derecho a apelación mierda %IQ no se discute con narrativa barata.',
  'El ranking de luces te deja en %IQ sin modo avión posible, asco y sin derecho a apelación coño %IQ no se discute con narrativa barata.',
  '%IQ. Has firmado el empty head en alta definición del chat, basura y sin derecho a apelación cabrón.',
  'Con %IQ el grupo prefiere el mute a tu aporte, cabrón y sin derecho a apelación gilipollas %IQ no se discute con narrativa barata.',
  '%IQ de coeficiente. El bot no regala caridad cognitiva, gilipollas y sin derecho a apelación patético.',
  'Se te nota el %IQ en el primer cambio de tema sin sentido, patético y sin derecho a apelación asco %IQ no se discute con narrativa barata.',
  '%IQ. El abismo no necesita presentación: el número basta, ridículo y sin derecho a apelación basura.',
  'Con %IQ el hilo se empobrece en tiempo real, mierda y sin derecho a apelación ridículo %IQ no se discute con narrativa barata.',
  '%IQ. El veredicto es bajo y no hay recurso ni narrador que lo suavice, coño y sin derecho a apelación.',
];

const BAJO = [
  'Con %IQ no entiendes ni el chiste y te ríes el último. El grupo ya sabía que ibas justo de cabeza, patético.',
  '%IQ de coeficiente. Hablas mucho y piensas poco. Te crees listo y el número te deja en evidencia, miserable.',
  'Sacaste %IQ. Necesitas que te expliquen hasta los memes. Así no se sostiene ninguna autoestima seria, qué cringe.',
  'Con %IQ llegas tarde a todo lo que se discute. Cuando abres la boca el tema ya se cerró, da asco. Se te ve en cada mensaje, qué vergüenza.',
  '%IQ. No es un mal día: es tu techo. Deja de venderte como alguien profundo, qué vergüenza. Se te ve en cada mensaje, ridículo.',
  'Con %IQ discutir contigo es perder el tiempo. Explicas mal, entiendes peor y encima insistes, ridículo.',
  '%IQ. Una neurona en baja y el resto del chat pagando la paciencia. Tu valor intelectual no da para más, fracasado.',
  'Con %IQ eres el ejemplo de lo que no hay que escribir. El grupo te usa de referencia de lo flojo, qué miseria.',
  '%IQ. Si el cerebro pagara alquiler, te echan. Te miras al espejo y ves genio; aquí vemos el número, da grima.',
  'Con %IQ cada idea tuya sale torcida. El bot te midió y nadie se sorprendió, qué nivel de pena. Se te ve en cada mensaje, basura.',
  'Con %IQ el sentido común te evita. No eres discreto: no llegas, basura. Se te ve en cada mensaje, qué cutre.',
  '%IQ. Insistes después de perder el argumento. Confundes gritar con tener razón, qué cutre. Se te ve en cada mensaje, da pena ajena.',
  'Con %IQ ni el corrector te salva el mensaje. Te crees claro y se te entiende a medias, da pena ajena.',
  '%IQ. Vas siempre al mismo muro mental. La autoestima al volante sin carnet, qué vacío. Se te ve en cada mensaje, indignante.',
  'Con %IQ te dejan hablar por pena, no porque aportes. Eres ruido con pretensiones, indignante. Se te ve en cada mensaje, patético.',
  '%IQ. Pensar te cansa de más. El abismo no te insulta: te reconoce, patético. Se te ve en cada mensaje, miserable.',
  'Con %IQ eres un lastre en el hilo y lo niegas. La confianza te sobra; el coeficiente no, miserable. Se te ve en cada mensaje, qué cringe.',
  '%IQ. Hasta el bot dudó de publicar el número. Así de claro quedó, qué cringe. Se te ve en cada mensaje, da asco.',
  'Con %IQ no pillas el tono y respondes en serio a las bromas. Nadie puede usarte para pensar en serio, da asco.',
  '%IQ. La estupidez te queda como traje a medida. No es arte: es tu media, qué vergüenza. Se te ve en cada mensaje, ridículo.',
  'Con %IQ cada mensaje pide paciencia al resto. Leerse te cuesta al grupo, ridículo. Se te ve en cada mensaje, fracasado.',
  '%IQ. No llegas tarde a la idea: no saliste. Pediste la palabra igual, fracasado. Se te ve en cada mensaje, qué miseria.',
  'Con %IQ nada te entra bien y lo que dices baja el nivel. Así te ven cuando escribes, qué miseria. Se te ve en cada mensaje, da grima.',
  '%IQ. Un ventilador aporta más vueltas útiles que tus intervenciones, da grima. Se te ve en cada mensaje, qué nivel de pena.',
  'Con %IQ prefieren un sticker a tu párrafo. El sticker no finge ser listo, qué nivel de pena. Se te ve en cada mensaje, basura.',
  '%IQ. Si el IQ fuera sueldo, pedirías en la calle. Tu esfuerzo no cotiza aquí, basura. Se te ve en cada mensaje, qué cutre.',
  'Con %IQ la lógica te pide distancia. No elegiste el rol: te lo asignaron, qué cutre. Se te ve en cada mensaje, da pena ajena.',
  '%IQ. No estás cerca del abismo: vives ahí con wifi y ego, da pena ajena. Se te ve en cada mensaje, qué vacío.',
  'Con %IQ demuestras que tener internet no mejora la cabeza. Te creías actualizado, qué vacío. Se te ve en cada mensaje, indignante.',
  '%IQ. El número te queda alto para lo que demuestras. El chat ya no negocia tu relato, indignante. Se te ve en cada mensaje, patético.',
  'Con %IQ cuando intentas brillar apagas la conversación. Tu brillo es un corte de luz, patético. Se te ve en cada mensaje, miserable.',
  '%IQ. Cabeza en error 404 con foto de perfil. Así te cargan en los temas serios, miserable. Se te ve en cada mensaje, qué cringe.',
  'Con %IQ no te enteras ni de que te están roasteando. Tu autoimagen vive en otro sitio, qué cringe. Se te ve en cada mensaje, da asco.',
  '%IQ. Poca profundidad y mucha confianza. Ese desajuste es el chiste, da asco. Se te ve en cada mensaje, qué vergüenza.',
  'Con %IQ el debate se muere cuando empiezas. Cierras conversaciones sin querer, qué vergüenza. Se te ve en cada mensaje, ridículo.',
  '%IQ. No pediste ser el lento del hilo; el número te dejó ahí, ridículo. Se te ve en cada mensaje, fracasado.',
  'Con %IQ al citarte baja el nivel del chat. Tu presencia intelectual contagia flojera, fracasado. Se te ve en cada mensaje, qué miseria.',
  '%IQ. Luz encendida y nadie en casa. Dices que estás pensando; aquí se ve vacío, qué miseria. Se te ve en cada mensaje, da grima.',
  'Con %IQ entras al hilo al revés. Chocas, pitas y no aprendes, da grima. Se te ve en cada mensaje, qué nivel de pena.',
  '%IQ. Pensar en voz alta en tu caso es un riesgo para el grupo, qué nivel de pena. Se te ve en cada mensaje, basura.',
  'Con %IQ el bot casi te manda el roast en dibujos. Tu pose de adulto pensante no aguanta el número, basura.',
  '%IQ. La idea del día te cabe en un sello. Aun así la vendes como hallazgo, qué cutre. Se te ve en cada mensaje, da pena ajena.',
  'Con %IQ te pierdes en tu propio mensaje. No es complejidad: no sabías qué decir, da pena ajena. Se te ve en cada mensaje, qué vacío.',
  '%IQ. Lo más listo en tu cabeza es el eco. Y aun así pides que te tomen en serio, qué vacío. Se te ve en cada mensaje, indignante.',
  'Con %IQ ya no te corrigen: te archivan. Se acabó lo de estar en proceso, indignante. Se te ve en cada mensaje, patético.',
  '%IQ. Si la estupidez quemara calorías, estarías en forma. Ideas, cero, patético. Se te ve en cada mensaje, miserable.',
  'Con %IQ eres el jefe de no pillar nada. Ese no era el logro que querías, miserable. Se te ve en cada mensaje, qué cringe.',
  '%IQ. El sótano mental te mandó la bienvenida. No es metáfora: es donde te leen, qué cringe. Se te ve en cada mensaje, da asco.',
  'Con %IQ cada opinión tuya pide que el resto se calle. Por higiene, no por respeto, da asco. Se te ve en cada mensaje, qué vergüenza.',
  '%IQ. El marcador y el grupo coinciden. El número no se discute; tu autoestima sí debería, qué vergüenza.',
  'Con %IQ te crees el de las cosas claras. No son claras: son simples y torcidas, ridículo. Se te ve en cada mensaje, fracasado.',
  '%IQ. Tu valor en el hilo se mide en cuántas veces te tuvieron que explicar lo obvio, fracasado. Se te ve en cada mensaje, qué miseria.',
  'Con %IQ te sobra confianza y te falta precisión. Esa es tu firma, qué miseria. Se te ve en cada mensaje, da grima.',
  '%IQ. Te miras como subestimado. Aquí no hay trama: hay evidencia, da grima. Se te ve en cada mensaje, qué nivel de pena.',
  'Con %IQ cada vez que te defiendes quedas peor. Deja de pelear el número, qué nivel de pena. Se te ve en cada mensaje, basura.',
  '%IQ. La imagen de listo choca en público con este resultado. Se oye el golpe, basura. Se te ve en cada mensaje, qué cutre.',
  'Con %IQ necesitas el chiste explicado y después opinas del chiste. Al revés del todo, qué cutre. Se te ve en cada mensaje, da pena ajena.',
  '%IQ. No aportas marco: aportas niebla. Y la niebla no es profundidad, da pena ajena. Se te ve en cada mensaje, qué vacío.',
  'Con %IQ ya no te esperan en los temas serios. Esa exclusión es el juicio, qué vacío. Se te ve en cada mensaje, indignante.',
  '%IQ. Te valoras por la intención; aquí se valora el efecto. El efecto es este número, indignante. Se te ve en cada mensaje, patético.',
  'Con %IQ demuestras que hablar mucho no da respeto. Solo llena el historial, patético. Se te ve en cada mensaje, miserable.',
  '%IQ. Te ves como alguien que piensa distinto. Aquí se te ve pensando menos, miserable. Se te ve en cada mensaje, qué cringe.',
  'Con %IQ cada intento de lucidez termina en que otro te limpia la idea. Eres borrador permanente, qué cringe.',
  '%IQ. El orgullo no te deja bajar el tono; el número te baja la expectativa, da asco. Se te ve en cada mensaje, qué vergüenza.',
  'Con %IQ te asignaron el rol de ruido fijo. No es temporal: es tu archivo, qué vergüenza. Se te ve en cada mensaje, ridículo.',
  '%IQ. Tu autoestima pide victorias; el hilo te da derrotas chicas y constantes, ridículo. Se te ve en cada mensaje, fracasado.',
  'Con %IQ te reenvían el resumen porque el original te supera. Ese es tu lugar, fracasado. Se te ve en cada mensaje, qué miseria.',
  '%IQ. No te subestiman: te midieron. El número es la cinta, no un ataque al aire, qué miseria. Se te ve en cada mensaje, da grima.',
  'Con %IQ la necesidad de tener razón te delata más que el error. El ego grita de más, da grima. Se te ve en cada mensaje, qué nivel de pena.',
  '%IQ. Te sientes incomprendido. El chat te ve incompleto. Solo una lectura tiene datos, qué nivel de pena.',
  'Con %IQ cada mensaje serio tuyo lo termina otro. No cierras ideas: las dejas a medias, basura. Se te ve en cada mensaje, qué cutre.',
  '%IQ. Te crees el que ve lo que otros no. Aquí no ves lo que está delante, qué cutre. Se te ve en cada mensaje, da pena ajena.',
  'Con %IQ el respeto no llega porque no hay base. A veces hay simpatía; respeto, no, da pena ajena. Se te ve en cada mensaje, qué vacío.',
  '%IQ. Tu valor aquí no se discute con la bio. Se discute con el número y con tu rastro, qué vacío. Se te ve en cada mensaje, indignante.',
  'Con %IQ eres el ejemplo de este no se entera. Ya ni hace falta nombrarte, indignante. Se te ve en cada mensaje, patético.',
  '%IQ. Lo único que entrenas es el orgullo. El resto está en el número, patético. Se te ve en cada mensaje, miserable.',
  'Con %IQ te toleran mejor en broma que en serio. Cuando quieres profundidad, se ve el suelo, miserable.',
  '%IQ. No te odian: te sacaron de la cuenta. Ser irrelevante en lo serio duele más, qué cringe. Se te ve en cada mensaje, da asco.',
  'Con %IQ cada vez que te pones solemne, el grupo hace lo contrario. Ese contraste te define, da asco.',
  '%IQ. La historia linda que te cuentas de noche no aguanta el primer hilo del día, qué vergüenza. Se te ve en cada mensaje, ridículo.',
  'Con %IQ tienes techo bajo y ganas de azotea. El esfuerzo no mueve el número, ridículo. Se te ve en cada mensaje, fracasado.',
  '%IQ. Te valoras por potencial. Aquí solo corre el resultado. Y el resultado es este, fracasado. Se te ve en cada mensaje, qué miseria.',
  'Con %IQ corriges a otros para no mirar el desorden propio. Se nota la proyección, qué miseria. Se te ve en cada mensaje, da grima.',
  '%IQ. Ya no debaten si eres listo. Debaten cómo hablarte para que no desvíes el hilo, da grima. Se te ve en cada mensaje, qué nivel de pena.',
  'Con %IQ eres un gasto de paciencia. La paciencia se raciona. A ti te la racionaron, qué nivel de pena.',
  '%IQ. La imagen de inteligente incomprendido se vende en tu cabeza. Fuera no hay comprador, basura. Se te ve en cada mensaje, qué cutre.',
  'Con %IQ cuando intentas cerrar un tema, lo empeoras. No eres cierre: eres fuga, qué cutre. Se te ve en cada mensaje, da pena ajena.',
  '%IQ. Pides aplauso por intentarlo. Aquí se paga por acertar. La caja está vacía, da pena ajena. Se te ve en cada mensaje, qué vacío.',
  'Con %IQ siempre necesitas contexto extra. Esa dependencia es el juicio, qué vacío. Se te ve en cada mensaje, indignante.',
  '%IQ. No fallas por maldad: fallas por tope. El tope tiene número. Deja el espejo en paz, indignante.',
  'Con %IQ demuestras que se puede tener seguridad sin combustible. Se ve el tanque vacío, patético. Se te ve en cada mensaje, miserable.',
  '%IQ. Cuando callas a veces ganas valor. Cuando hablas, el número cobra peaje, miserable. Se te ve en cada mensaje, qué cringe.',
  'Con %IQ te pusieron la etiqueta de manejar con cuidado. No es cariño: es precaución, qué cringe. Se te ve en cada mensaje, da asco.',
  '%IQ. Tu relato dice me subestiman. El del grupo dice cuadró el número. Gana el segundo, da asco. Se te ve en cada mensaje, qué vergüenza.',
  'Con %IQ cada defensa combativa te hunde más. El orgullo no tapa el marcador, qué vergüenza. Se te ve en cada mensaje, ridículo.',
  '%IQ. Nadie te pide la versión final de una idea. Se la piden a otro. Eso pesa, ridículo. Se te ve en cada mensaje, fracasado.',
  'Con %IQ la pose de agudo se estrella. No clavas nada y se ve, fracasado. Se te ve en cada mensaje, qué miseria.',
  '%IQ. No te falta actitud: te falta techo. El resto es teatro para no mirar el número, qué miseria. Se te ve en cada mensaje, da grima.',
  'Con %IQ tener opinión se volvió un riesgo para el hilo. El riesgo tiene tu nombre, da grima. Se te ve en cada mensaje, qué nivel de pena.',
  '%IQ. El valor que te das y el que te dan no coinciden. Aquí manda el segundo, qué nivel de pena. Se te ve en cada mensaje, basura.',
  'Con %IQ el ego sobrevive sin pruebas. Aquí las pruebas se publican, basura. Se te ve en cada mensaje, qué cutre.',
  '%IQ. No busques trampa en el test. El test no te odia. Te enseña el número, qué cutre. Se te ve en cada mensaje, da pena ajena.',
  'Con %IQ el grupo aprendió a no apoyarse en ti para pensar. Eso ya es reputación, da pena ajena. Se te ve en cada mensaje, qué vacío.',
  '%IQ. La herida de verdad no es el roast: es admitir que tenía base y la base eres tú, qué vacío. Se te ve en cada mensaje, indignante.',
  'Con %IQ cada mensaje inteligente se vuelve trabajo para otro. No lideras: retrasas, indignante. Se te ve en cada mensaje, patético.',
  '%IQ. Tu idea de valer en lo intelectual no tiene aval aquí. El número es el aval en contra, patético.',
  'Con %IQ conviertes lo simple en laberinto. No por genio: porque no hallas la salida corta, miserable.',
  '%IQ. Te dan espacio y lo gastas en demostrar lo contrario de lo que querías, qué cringe. Se te ve en cada mensaje, da asco.',
  'Con %IQ cuanto más seguro escribes, menos claro dejas el punto. Se nota, da asco. Se te ve en cada mensaje, qué vergüenza.',
  '%IQ. El grupo no es cruel. El número es público y la gente sabe leer, qué vergüenza. Se te ve en cada mensaje, ridículo.',
  'Con %IQ tu rol estable es el que necesita traducción. Los roles estables pesan, ridículo. Se te ve en cada mensaje, fracasado.',
  '%IQ. No te baja un mensaje malo. Te baja un patrón. El número resume el patrón, fracasado. Se te ve en cada mensaje, qué miseria.',
  'Con %IQ el espejo del chat no te devuelve la imagen que ensayas. Devuelve el número, qué miseria. Se te ve en cada mensaje, da grima.',
  '%IQ. Dejar de pelear tu autoimagen te ahorraría derrotas. Seguir es el hobby que ya conocen, da grima.',
  'Con %IQ se ve la diferencia entre creerse listo y sostenerlo. Aquí solo compran lo segundo, qué nivel de pena.',
  '%IQ. La marca que dejas no es de agudo incómodo. Es de alguien a quien hay que cargar, basura. Se te ve en cada mensaje, qué cutre.',
  'Con %IQ intentar recuperar respeto con más texto empeora la nota. A veces callar cotiza mejor, qué cutre.',
  '%IQ. No te define un insulto. Te define que el número se repite y ya nadie se sorprende, da pena ajena.',
  'Con %IQ lo que pega no es la burla: es pensar que el bot quizá no se equivocó, qué vacío. Se te ve en cada mensaje, indignante.',
  '%IQ. Tu autoestima puede gritar. El historial dice el número. En este grupo gana el historial, indignante.',
  'Con %IQ eres el costo de una charla que pudo ser limpia. Ahora el costo tiene nombre, patético. Se te ve en cada mensaje, miserable.',
  '%IQ. La versión brillante de ti vive en tu cabeza. En el chat vive esta. Elige cuál alimentar, miserable.',
  'Con %IQ el respeto se te va no por enemigos: por pruebas repetidas, qué cringe. Se te ve en cada mensaje, da asco.',
  '%IQ. No eres el incomprendido. Eres el mal calculado que no quiere recalcular, da asco. Se te ve en cada mensaje, qué vergüenza.',
  'Con %IQ cada capa de ego añade peso y no añade altura. El número sigue abajo, qué vergüenza. Se te ve en cada mensaje, ridículo.',
  '%IQ. No hace falta odiarte para descontarte. Con este número basta. Eso es lo que duele, ridículo. Se te ve en cada mensaje, fracasado.',
  'Con %IQ no peleas contra el bot. Peleas contra la imagen que te fabricaste y este chat no firma, fracasado.',
  '%IQ. No hay conspiración. Hay un número y una fama que cuadran, qué miseria. Se te ve en cada mensaje, da grima.',
  'Con %IQ pasaste de polémica a precaución. Ese cambio ya ocurrió, da grima. Se te ve en cada mensaje, qué nivel de pena.',
  '%IQ. Lo duro no es que te lo digan. Es que ya lo sospechabas y seguías de sobrado, qué nivel de pena.',
  'Con %IQ el valor que buscas no se cobra con actitud. Se cobra con claridad, basura. Se te ve en cada mensaje, qué cutre.',
  '%IQ. Cierra el debate interno. El externo ya votó. El recuento te mira cada vez que sale este comando, qué cutre.',
  'Con %IQ te pones de otra mirada. La mirada está borrosa y ya nadie enfoca por ti, da pena ajena. Se te ve en cada mensaje, qué vacío.',
  '%IQ. Quieres corregir a todos. El historial dice que eres tú quien necesita corrección, qué vacío. Se te ve en cada mensaje, indignante.',
  'Con %IQ el malentendido es tu zona segura. Entender del todo te obligaría a mirar el número, indignante.',
  '%IQ. No te falta identidad: te falta aval. El número es el sello que no querías, patético. Se te ve en cada mensaje, miserable.',
  'Con %IQ te tratan con la paciencia de quien habla con alguien que no sigue el ritmo, miserable. Se te ve en cada mensaje, qué cringe.',
  '%IQ. Tu necesidad de quedar por encima del dato es más alta que el dato. Por eso arde, qué cringe. Se te ve en cada mensaje, da asco.',
  'Con %IQ llegas tarde a la conclusión y temprano a la seguridad. El orden va al revés, da asco. Se te ve en cada mensaje, qué vergüenza.',
  '%IQ. La mente aguda te dura en privado. En público el contador la tumba sin gritar, qué vergüenza. Se te ve en cada mensaje, ridículo.',
  'Con %IQ cada intento de recuperar estatus con más palabras suma otra prueba en contra, ridículo. Se te ve en cada mensaje, fracasado.',
  '%IQ. No es crueldad gratis. Es que lo que mides y lo que proyectas por fin cuadraron, fracasado. Se te ve en cada mensaje, qué miseria.',
  'Con %IQ te restaron del equipo de los que piensan en voz alta con provecho, qué miseria. Se te ve en cada mensaje, da grima.',
  '%IQ. No te define un fail suelto. Te define la expectativa baja antes de que termines la frase, da grima.',
  'Con %IQ confundes ser ruidoso con ser central. El centro se gana con claridad, qué nivel de pena. Se te ve en cada mensaje, basura.',
  '%IQ. Tu valor percibido cae cuando el hilo tiene que elegirte a ti o avanzar. Casi siempre avanza, basura.',
  'Con %IQ la fantasía del subestimado choca con sobrar de confianza y faltar de resultado, qué cutre. Se te ve en cada mensaje, da pena ajena.',
  '%IQ. El hueso es simple: no hay enemigo fuera. Hay un número y un ego que no baja, da pena ajena. Se te ve en cada mensaje, qué vacío.',
  'Con %IQ eres un gasto de atención. La atención se raciona. Se te racionó, qué vacío. Se te ve en cada mensaje, indignante.',
  '%IQ. Creías decir menos de lo que piensas. Aquí se ve que dices más de lo que piensas bien, indignante.',
  'Con %IQ el respeto no vuelve a base de insistir. Vuelve a base de acertar, patético. Se te ve en cada mensaje, miserable.',
  '%IQ. Pegó porque no era adorno. Era espejo. Y el espejo tenía el número delante, miserable. Se te ve en cada mensaje, qué cringe.',
  'Con %IQ dejaron de debatir contigo y pasaron a gestionarte. Ser gestionado no es ser valorado, qué cringe.',
  '%IQ. La marca a largo plazo no es la risa del roast. Es que nadie te pide ya la versión inteligente, da asco.',
  'Con %IQ cada justificación confirma el diagnóstico. Callar sería el primer movimiento listo, qué vergüenza.',
  '%IQ. Tu pelea por la autoimagen va perdiendo contra el historial. El marcador no miente, ridículo. Se te ve en cada mensaje, fracasado.',
  'Con %IQ no te borran: te bajan de categoría. De posible aporte a ruido previsible, fracasado. Se te ve en cada mensaje, qué miseria.',
  '%IQ. No busques truco en el comando. Busca el patrón en tus hilos, qué miseria. Se te ve en cada mensaje, da grima.',
  'Con %IQ eres el ejemplo interno de no se apoyen ahí. Esos ejemplos duran más que un insulto, da grima.',
  '%IQ. La herida correcta: el chat no necesita odiarte para no tomarte en serio, qué nivel de pena. Se te ve en cada mensaje, basura.',
  'Con %IQ tu crédito intelectual está en descubierto. Sigues gastando pose, basura. Se te ve en cada mensaje, qué cutre.',
  '%IQ. Deja de vender potencial. Aquí se cobra claridad entregada, qué cutre. Se te ve en cada mensaje, da pena ajena.',
  'Con %IQ te quedó el lugar de quien necesita andamio. El andamio no es el edificio, da pena ajena. Se te ve en cada mensaje, qué vacío.',
  '%IQ. Lo que pega es darse cuenta de que el roast no inventó nada: solo lo dijo sin tu permiso, qué vacío.',
  'Con %IQ perdiste el beneficio de la duda en lo que pide cabeza. Se pierde una vez y cuesta años, indignante.',
  '%IQ. Puedes reescribir el relato esta noche. El grupo no está obligado a firmarlo mañana, patético. Se te ve en cada mensaje, miserable.',
  'Con %IQ demuestras que la seguridad sin sustancia es ruido caro. El chat ya no paga ese precio, miserable.',
  '%IQ. El valor que te das y el que te dan no van a juntarse mientras el número sea el testigo, qué cringe.',
  'Con %IQ cada desde mi experiencia se lee como desde la confusión, da asco. Se te ve en cada mensaje, qué vergüenza.',
  '%IQ. No te ataca un bot. Te describe un contador. Y la descripción pega con el resto de pruebas, qué vergüenza.',
  'Con %IQ aprendieron a no dejarte el micrófono en lo delicado. Esa regla informal ya es tu biografía, ridículo.',
  '%IQ. Cierra el teatro del incomprendido. Abre el del número. Duele más y miente menos, fracasado. Se te ve en cada mensaje, qué miseria.',
  'Con %IQ tu paso por los temas serios se tolera, no se pide. Tolerar no construye autoestima sólida, qué miseria.',
  '%IQ. La marca que dejas es la del que hay que rehacer. Rehacer no es colaborar: es cargar contigo, da grima.',
  'Con %IQ el ego busca platea. El chat te dejó atrás sin avisar, qué nivel de pena. Se te ve en cada mensaje, basura.',
  '%IQ. Pegó al hueso porque no era estilo de insulto: era auditoría. Y no salió a tu favor, basura. Se te ve en cada mensaje, qué cutre.',
  'Con %IQ se ve la diferencia entre tener opinión y tener criterio. El grupo ya te etiquetó, qué cutre.',
  '%IQ. No hay final heroico peleando el dato. Solo más historial en la misma dirección, da pena ajena.',
  'Con %IQ la idea de ser valioso se sostiene en aire. El chat corta el aire con un número, qué vacío. Se te ve en cada mensaje, indignante.',
  '%IQ. Lo más duro no es la broma. Es que en serio nadie corre a desmentirlo, indignante. Se te ve en cada mensaje, patético.',
  'Con %IQ pasaste de ser duda a ser previsión: se prevé que te pierdes el punto, patético. Se te ve en cada mensaje, miserable.',
  '%IQ. Tu valor en este grupo no está donde lo pintas. Está donde el contador y el rastro coinciden, miserable.',
  'Con %IQ no entiendes ni el chiste y te ríes el último. El grupo ya sabía que ibas justo de cabeza. Y se repite el patrón, qué cringe Vuelta 182.',
  '%IQ de coeficiente. Hablas mucho y piensas poco. Te crees listo y el número te deja en evidencia. Y se repite el patrón, da asco Vuelta 183.',
  'Sacaste %IQ. Necesitas que te expliquen hasta los memes. Así no se sostiene ninguna autoestima seria. Y se repite el patrón, qué vergüenza Vuelta 184.',
  'Con %IQ llegas tarde a todo lo que se discute. Cuando abres la boca el tema ya se cerró. Y se repite el patrón, ridículo Vuelta 185.',
  '%IQ. No es un mal día: es tu techo. Deja de venderte como alguien profundo. Y se repite el patrón, fracasado Vuelta 186.',
  'Con %IQ discutir contigo es perder el tiempo. Explicas mal, entiendes peor y encima insistes. Y se repite el patrón, qué miseria Vuelta 187.',
  '%IQ. Una neurona en baja y el resto del chat pagando la paciencia. Tu valor intelectual no da para más. Y se repite el patrón, da grima Vuelta 188.',
  'Con %IQ eres el ejemplo de lo que no hay que escribir. El grupo te usa de referencia de lo flojo. Y se repite el patrón, qué nivel de pena Vuelta 189.',
  '%IQ. Si el cerebro pagara alquiler, te echan. Te miras al espejo y ves genio; aquí vemos el número. Y se repite el patrón, basura Vuelta 190.',
  'Con %IQ cada idea tuya sale torcida. El bot te midió y nadie se sorprendió. Y se repite el patrón, qué cutre Vuelta 191.',
  'Con %IQ el sentido común te evita. No eres discreto: no llegas. Y se repite el patrón, da pena ajena Vuelta 192.',
  '%IQ. Insistes después de perder el argumento. Confundes gritar con tener razón. Y se repite el patrón, qué vacío Vuelta 193.',
  'Con %IQ ni el corrector te salva el mensaje. Te crees claro y se te entiende a medias. Y se repite el patrón, indignante Vuelta 194.',
  '%IQ. Vas siempre al mismo muro mental. La autoestima al volante sin carnet. Y se repite el patrón, patético Vuelta 195.',
  'Con %IQ te dejan hablar por pena, no porque aportes. Eres ruido con pretensiones. Y se repite el patrón, miserable Vuelta 196.',
  '%IQ. Pensar te cansa de más. El abismo no te insulta: te reconoce. Y se repite el patrón, qué cringe Vuelta 197.',
  'Con %IQ eres un lastre en el hilo y lo niegas. La confianza te sobra; el coeficiente no. Y se repite el patrón, da asco Vuelta 198.',
  '%IQ. Hasta el bot dudó de publicar el número. Así de claro quedó. Y se repite el patrón, qué vergüenza Vuelta 199.',
];

const MEDIO = [
  '%IQ. Joder, eres tan del montón que si te pierdes en una multitud nadie nota que falta alguien.',
  'Con %IQ tienes el coeficiente intelectual de un puto semáforo en ámbar: ni paras ni arrancas, estorbas.',
  '%IQ de IQ. La mediocridad hecha persona. Si fueras un color serías beige, cabrón, el puto beige.',
  'Hostia, %IQ. Eres tan jodidamente promedio que podrían usarte de ejemplo en un libro de texto sobre gente que no importa.',
  '%IQ. Tienes la misma chispa mental que un brick de leche semidesnatada: ni entera ni desnatada, una mierda a medias.',
  'Con %IQ eres el coño de la media exacta. Si la humanidad fuera un bocadillo, tú serías el pan sin nada dentro.',
  '%IQ de IQ. Tu cerebro funciona como un grifo de agua templada: ni fría ni caliente, una puta decepción constante.',
  'Mierda, %IQ clavado. Eres tan normal que si tu vida fuera una película sería un documental sobre secar pintura.',
  '%IQ. Tienes los cojones de ser exactamente igual que todo el mundo y encima no te da vergüenza.',
  'Con %IQ tu cerebro es como un menú del día de bar de carretera: cumple, pero nadie repite ni se acuerda.',
  '%IQ de IQ. Coño, eres el equivalente humano de un martes: nadie lo espera, nadie lo celebra, simplemente pasa.',
  'Hostia, %IQ. Tu capacidad mental tiene la emoción de un yogur natural sin azúcar. Existe y punto.',
  '%IQ. Eres tan puñeteramente medio que si te clonaran cien veces no cambiaría ni la estadística ni el ambiente.',
  'Con %IQ piensas como folla un funcionario: cumpliendo el expediente y mirando el reloj, el puto mínimo.',
  '%IQ de IQ. Si la mediocridad pagara impuestos tú solo financiarías una autopista, cabrón.',
  'Joder, %IQ. Tu cerebro es una rotonda: das vueltas, llegas al mismo sitio y te crees que has avanzado.',
  '%IQ. Eres el NPC del grupo. Estás ahí, dices cuatro frases genéricas y nadie nota si te desconectan.',
  'Con %IQ tienes exactamente la inteligencia de un microondas: calientas lo que te meten y ya, sin puta creatividad.',
  '%IQ de IQ. Coño, la media exacta. Eres tan predecible que hasta el bot se aburre de evaluarte.',
  'Hostia, %IQ. Tienes la profundidad intelectual de un charco de meado en un aparcamiento: poco, templado y desagradable.',
  '%IQ. Tu cerebro procesa información como una impresora de los noventa: lento, ruidoso y al final sale una mierda borrosa.',
  'Con %IQ eres el puto empate a cero de la inteligencia. Nadie gana, nadie pierde, todo el mundo se va insatisfecho.',
  '%IQ de IQ. Joder, eres tan del montón que si repartiesen personalidad por IQ te tocaría una cucharada de papilla.',
  'Mierda, %IQ. Eres la versión humana de un pan de molde: blando, cuadrado y absolutamente intercambiable.',
  '%IQ. Con ese número tu cerebro es una carretera comarcal: llega a todos lados pero tardando el triple y con baches.',
  'Con %IQ tienes la agilidad mental de una puta bolsa de plástico en el viento: te mueves mucho pero no vas a ningún lado.',
  '%IQ de IQ. Hostia, eres tan normalito que hasta el algoritmo te salta porque no generas engagement ni de coña.',
  '%IQ. Tu cabeza funciona como un ascensor de dos plantas: sube, baja, y eso es todo lo que da de sí.',
  'Con %IQ eres el equivalente cognitivo de unas zapatillas de andar por casa: cómodo, gastado y que nadie saca a la calle.',
  '%IQ de IQ. Joder, la media clavada. Si fueras una especia serías sal, cabrón. La puta sal, lo más básico que existe.',
  'Coño, %IQ. Eres tan jodidamente estándar que si metieras el cerebro en una batidora saldría gazpacho de brick.',
  '%IQ. Tu inteligencia es como un autobús urbano: va por la misma ruta siempre, llega tarde y huele raro.',
  'Con %IQ tienes la creatividad de una pared blanca y la ambición de una alfombrilla de ratón. Hostia, qué triste.',
  '%IQ de IQ. Mierda, eres tan promedio que si buscas tu nombre en Google sale "quizás quisiste decir otro".',
  '%IQ. Tu cerebro tiene la potencia de un ventilador de mesa: mueve aire suficiente para no ahogarte y ya.',
  'Con %IQ eres el cabrón que está en el centro exacto de la campana de Gauss. El pico de la nada.',
  '%IQ de IQ. Joder, tu intelecto es tan plano que podrían planchar camisas encima de tu capacidad de análisis.',
  'Hostia, %IQ. Eres la versión cognitiva de un parking en superficie: abierto, vacío y sin ningún puto interés arquitectónico.',
  '%IQ. Piensas como conduce un abuelo: despacio, sin sorpresas y cabreando a todos los que van detrás.',
  'Con %IQ tu cerebro es un piso de alquiler en las afueras: funcional, triste y con las paredes llenas de mierda.',
  '%IQ de IQ. Coño, la media pura. Tienes la misma gracia intelectual que una puerta cortafuegos: cumple normativa y ya.',
  'Mierda, %IQ. Tu capacidad mental es un buffet libre de hotel mediocre: hay de todo y todo sabe igual de insípido.',
  '%IQ. Eres tan jodidamente mediocre que si tu cerebro fuera un coche sería un Dacia Sandero de segunda mano.',
  'Con %IQ tienes el nivel de un cabrón que pone "persona proactiva" en el currículum y se queda tan ancho.',
  '%IQ de IQ. Hostia, tu cabeza es como un canal de TDT que nadie ve: emite las veinticuatro horas y da igual.',
  'Joder, %IQ. Eres el tipo de persona que un estadístico usaría como valor por defecto. La mierda estándar.',
  '%IQ. Tu cerebro trabaja como un lavavajillas: mete, saca, y entre medias no pasa nada que merezca contar.',
  'Con %IQ tienes la misma relevancia intelectual que un tornillo en una estantería de IKEA: necesario, pero que le den.',
  '%IQ de IQ. Coño, eres tan del promedio que si te pusieras de perfil intelectualmente desaparecerías.',
  'Mierda, %IQ. Tu cabeza es un piso piloto: parece que alguien vive ahí pero no hay ni un puto cepillo de dientes.',
  'Con %IQ estás en la media del grupo: ni brillas ni hundes el promedio del todo, joder. joder %IQ no se discute con narrativa barata.',
  '%IQ de mediocridad certificada. El chat no se inmuta, cabrón mierda %IQ no se discute con narrativa barata.',
  'Con %IQ ni genio ni desastre: paisaje cognitivo, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  '%IQ. Suficiente para opinar, insuficiente para importar, mierda cabrón, cabrón %IQ no se discute con narrativa barata.',
  'Media tableta. %IQ de los que rellenan la campana, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  'Con %IQ el argumento llega a medias y se queda ahí, asco patético, patético %IQ no se discute con narrativa barata.',
  '%IQ tibio. Ni subes el hilo ni lo salvas, patético asco, asco %IQ no se discute con narrativa barata.',
  'Medio puro. %IQ de trámite, basura basura, basura basura %IQ no se discute con narrativa barata.',
  'Con %IQ te defiendes sin ganar, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  '%IQ de zona gris. El ranking bostezó, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  'Media. Con %IQ no hay milagro ni tragedia, joder. joder %IQ no se discute con narrativa barata.',
  '%IQ suficiente para no ser el meme del día, cabrón mierda %IQ no se discute con narrativa barata.',
  'Con %IQ el chat te deja hablar y no toma notas, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  '%IQ de los que creen que piensan, mierda cabrón, cabrón %IQ no se discute con narrativa barata.',
  'Mediocre documentado: %IQ, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  'Con %IQ ni el bot se emociona, asco patético, patético %IQ no se discute con narrativa barata.',
  '%IQ en la campana. Invisible a propósito, patético asco, asco %IQ no se discute con narrativa barata.',
  'Media tableta cognitiva, %IQ, basura basura, basura basura %IQ no se discute con narrativa barata.',
  'Con %IQ el debate te queda grande a ratos, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  '%IQ de relleno estadístico, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  'Medio. %IQ sin arco narrativo, joder. joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ sobrevives al hilo sin aportar, cabrón mierda %IQ no se discute con narrativa barata.',
  '%IQ tibio de solemnidad, gilipollas coño, coño coño %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Media. El número no miente ni emociona: %IQ, mierda cabrón, cabrón %IQ no se discute con narrativa barata.',
  'Con %IQ eres el paisaje del ranking, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  '%IQ de los que no generan screenshot, asco patético, patético %IQ no se discute con narrativa barata.',
  'Mediocre con cifra: %IQ, patético asco, asco asco %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ el promedio te absuelve, basura basura, basura %IQ no se discute con narrativa barata.',
  '%IQ zona media. Archivado, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  'Media cognitiva certificada, %IQ, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  'Con %IQ ni subes ni hundes: ocupas, joder. joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  '%IQ de trámite intelectual, cabrón mierda. mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Medio puro. %IQ sin filo, gilipollas coño, coño coño %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ el chat cambia de tema sin culpa, mierda cabrón, cabrón %IQ no se discute con narrativa barata.',
  '%IQ de campana de Gauss con piernas, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  'Media. Suficiente para el ruido, asco patético, patético %IQ no se discute con narrativa barata.',
  'Con %IQ no hay veredicto épico, patético asco, asco asco %IQ no se discute con narrativa barata.',
  '%IQ tibio documentado, basura basura, basura basura %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Mediocre. El bot solo pone el número: %IQ, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  'Con %IQ el hilo no te necesita, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  'Media tableta. %IQ, joder. joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  '%IQ de los que rellenan espacios, cabrón mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ opinas y el eco no vuelve, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  '%IQ sin pico ni valle útil, mierda cabrón, cabrón cabrón %IQ no se discute con narrativa barata.',
  'Medio. Cifra y olvido: %IQ, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  'Con %IQ el ranking te deja en paz, asco patético, patético %IQ no se discute con narrativa barata.',
  '%IQ de paisaje humano, patético asco, asco asco %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Mediocre sostenible, %IQ, basura basura, basura basura %IQ no se discute con narrativa barata.',
  'Con %IQ ni gloria ni sótano, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  '%IQ en la media del fail colectivo, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
];

const ALTO = [
  '%IQ. Mira el listo del grupo, coño. Tienes cerebro de sobra y lo usas para discutir con gilipollas en un chat.',
  'Con %IQ podrías estar forrándote y en vez de eso estás aquí leyendo las mierdas que escribe esta panda de subnormales.',
  '%IQ de IQ. Joder, eres listo de cojones y lo más grande que has hecho hoy es abrirle un mensaje a un bot.',
  'Hostia, %IQ. Tienes la cabeza de un puto ingeniero de la NASA pero la ambición de una zapatilla de estar por casa.',
  '%IQ. Eres el cabrón que podría resolver problemas importantes pero prefiere ver cómo arde el grupo. Menudo desperdicio de neuronas.',
  'Con %IQ pillas las cosas a la primera, lo cual es una putada porque te toca esperar a que el resto de imbéciles llegue.',
  '%IQ de IQ. Listo de verdad, y da igual, porque aquí dentro eso vale menos que un moco seco en una barandilla.',
  'Coño, %IQ. Tienes más capacidad que la mitad del grupo junto y la gastas en leer audios de gente que no sabe ni freír un huevo.',
  '%IQ. Eres como tener un Ferrari aparcado en un descampado lleno de mierda: impresionante pero completamente fuera de sitio.',
  'Con %IQ tu cerebro va a ciento ochenta y el grupo va en burro. Debe ser agotador fingir que te interesan estas mierdas.',
  '%IQ de IQ. Hostia, eres el tío listo de la clase que acaba trabajando en lo mismo que el tonto pero con más frustración.',
  'Joder, %IQ. Podrías haber inventado algo útil para la humanidad y has acabado midiéndote el IQ con un puto bot de WhatsApp.',
  '%IQ. Tienes la inteligencia para darte cuenta de que todo esto es una mierda y los cojones de quedarte a verla.',
  'Con %IQ eres el cabrón que ve los errores de todos y no dice nada porque explicárselo sería como enseñar álgebra a una cabra.',
  '%IQ de IQ. Listo pero en un chat de mierda. Es como tener un doctorado y usarlo para abrir botellas.',
  'Mierda, %IQ. Tu cerebro funciona como un puto reloj suizo y lo tienes puesto para contar las horas que pierdes aquí.',
  '%IQ. Eres el que pilla el chiste antes que nadie y tiene que esperar con cara de imbécil a que el resto se ría.',
  'Con %IQ te sobra cabeza para darte cuenta de que la mitad de las opiniones de este grupo son pura mierda de caballo.',
  '%IQ de IQ. Joder, cerebro privilegiado metido en un cuerpo que no ha hecho nada memorable con él. Qué desperdicio de coño.',
  'Hostia, %IQ. Piensas más rápido que el resto pero corres igual de poco. La cabeza te da, las piernas no.',
  '%IQ. Eres como un cuchillo japonés cortando pan Bimbo: sobras por todas partes y lo que cortas no vale una mierda.',
  'Con %IQ podrías estar resolviendo ecuaciones y estás resolviendo si contestar o no a un mensaje con un puto emoji.',
  '%IQ de IQ. Coño, listo de verdad. Lástima que la inteligencia no cure la gilipollez social, que esa la tienes intacta.',
  'Mierda, %IQ. Tu cabeza va tres jugadas por delante y tu vida va tres jugadas por detrás. Menudo equilibrio de mierda.',
  '%IQ. Eres el cabrón más listo de un grupo lleno de imbéciles, que es como ser el más alto de una fila de enanos.',
  'Con %IQ entiendes cosas que el resto ni huele, pero te da pereza explicarlas, así que todos seguís igual de jodidos.',
  '%IQ de IQ. Joder, tienes más neuronas funcionando que el resto del chat junto y las usas para mandar stickers.',
  'Hostia, %IQ. Cerebro de cirujano y manos de albañil borracho. Porque una cosa es saber y otra es hacer algo con ello.',
  '%IQ. Eres listo de cojones pero la vida no da premios por eso, así que aquí estás, con los demás subnormales.',
  'Con %IQ tu cerebro tiene más potencia que el router de este grupo y aun así la conexión con la realidad se te cae cada dos por tres.',
  '%IQ de IQ. Coño, eres un puto prodigio desperdiciado. Como regar una planta de plástico: el esfuerzo está, el resultado no.',
  'Mierda, %IQ. Eres lo bastante listo para saber que deberías estar haciendo otra cosa y lo bastante gilipollas para no hacerla.',
  '%IQ. Tienes la cabeza de alguien que podría cambiar las cosas y el culo pegado al sofá como todos los demás.',
  'Con %IQ tu cerebro procesa más que el de cualquier cabrón de este grupo y eso, aquí dentro, vale exactamente una polla.',
  '%IQ de IQ. Joder, eres el diamante en bruto que nadie va a pulir porque estás enterrado en un grupo de WhatsApp lleno de mierda.',
  'Hostia, %IQ. Inteligencia por encima de la media metida en una vida completamente por debajo de ella. Qué cosa más triste.',
  '%IQ. Podrías estar publicando papers y estás publicando opiniones de mierda en un chat que nadie se va a releer jamás.',
  'Con %IQ eres el tío que ve la solución mientras los demás siguen buscando el problema. Lástima que el problema seas tú.',
  '%IQ de IQ. Listo y completamente inútil con ello. Como ponerle turbo a un coche sin ruedas, hostia puta.',
  'Mierda, %IQ. Tu cerebro merece algo mejor que este grupo, pero tu criterio de vida claramente no, pedazo de cabrón.',
  'Con %IQ estás por encima del promedio del chat, y se te nota en el tono, joder. joder %IQ no se discute con narrativa barata.',
  '%IQ alto. No genio, pero ya no eres paisaje, cabrón mierda %IQ no se discute con narrativa barata.',
  'Con %IQ el argumento te dura más de dos mensajes, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  '%IQ de los que molestan porque a veces tienen razón, mierda cabrón, cabrón %IQ no se discute con narrativa barata.',
  'Alto. Con %IQ el grupo te discute en serio a ratos, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  '%IQ por encima de la media. No te confíes, asco patético, patético %IQ no se discute con narrativa barata.',
  'Con %IQ subes el nivel del hilo cuando quieres, patético asco, asco %IQ no se discute con narrativa barata.',
  '%IQ alto documentado. El bot lo firma, basura basura, basura %IQ no se discute con narrativa barata.',
  'Por encima. %IQ sin llegar a laboratorio, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  'Con %IQ ya no cuela hacerse el tonto, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  '%IQ de los que leen el room, joder. joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Alto. El número te separa del relleno, cabrón mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ el debate te queda más a mano, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  '%IQ por encima del ruido base, mierda cabrón, cabrón cabrón %IQ no se discute con narrativa barata.',
  'Alto sin corona. %IQ, coño gilipollas, gilipollas gilipollas %IQ no se discute con narrativa barata.',
  'Con %IQ molestas al mediocre, asco patético, patético patético %IQ no se discute con narrativa barata.',
  '%IQ de segunda fila brillante, patético asco, asco asco %IQ no se discute con narrativa barata.',
  'Por encima de la campana, %IQ, basura basura, basura basura %IQ no se discute con narrativa barata.',
  'Con %IQ el chat te mide distinto, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  '%IQ alto. Sigue sin ser magia, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  'Alto. Con %IQ el average te mira raro, joder. joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  '%IQ de los que aportan a ratos, cabrón mierda. mierda %IQ no se discute con narrativa barata.',
  'Con %IQ no eres el meme fácil, gilipollas coño, coño coño %IQ no se discute con narrativa barata.',
  '%IQ por encima. Documentado, mierda cabrón, cabrón cabrón %IQ no se discute con narrativa barata.',
  'Alto de verdad: %IQ, coño gilipollas, gilipollas gilipollas %IQ no se discute con narrativa barata.',
  'Con %IQ el hilo gana cuando apareces, asco patético, patético %IQ no se discute con narrativa barata.',
  '%IQ sin soberbia justificada del todo, patético asco, asco %IQ no se discute con narrativa barata.',
  'Por encima del paisaje, %IQ, basura basura, basura basura %IQ no se discute con narrativa barata.',
  'Con %IQ el ranking te hace un guiño, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  '%IQ alto de los que aún pueden fallar feo, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  'Alto. %IQ y el chat lo nota, joder. joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ el argumento no se cae solo, cabrón mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  '%IQ de segunda división cognitiva, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  'Por encima. No te duermas, mierda cabrón, cabrón cabrón %IQ no se discute con narrativa barata.',
  'Con %IQ ya no eres relleno puro, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  '%IQ alto. El bot confirma, asco patético, patético patético %IQ no se discute con narrativa barata.',
  'Alto sin pedestal de mármol, %IQ, patético asco, asco asco %IQ no se discute con narrativa barata.',
  'Con %IQ el mediocre se incomoda, basura basura, basura %IQ no se discute con narrativa barata.',
  '%IQ por encima del promedio del fail, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  'Alto documentado: %IQ, fracasado fracasado, fracasado fracasado %IQ no se discute con narrativa barata.',
  'Con %IQ el debate te reconoce, joder. joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  '%IQ de los que suben la media, cabrón mierda. mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Alto. Cifra clara: %IQ, gilipollas coño, coño coño %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ dejas de ser ruido blanco, mierda cabrón, cabrón %IQ no se discute con narrativa barata.',
  '%IQ por encima sin llegar a mito, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  'Alto de catálogo, %IQ, asco patético, patético patético %IQ no se discute con narrativa barata.',
  'Con %IQ el chat te da más soga, patético asco, asco asco %IQ no se discute con narrativa barata.',
  '%IQ alto. Úsala, basura basura, basura basura %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Por encima del relleno, %IQ, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  'Con %IQ el sótano ya no te reclama, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  'Con %IQ el debate te reconoce, joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  '%IQ de los que suben la media, cabrón, mierda. mierda %IQ no se discute con narrativa barata.',
  'Alto. Cifra clara: %IQ, gilipollas, coño, coño coño %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ dejas de ser ruido blanco, mierda, cabrón, cabrón cabrón %IQ no se discute con narrativa barata.',
  '%IQ por encima sin llegar a mito, coño, gilipollas, gilipollas gilipollas %IQ no se discute con narrativa barata.',
  'Alto de catálogo, %IQ, asco, patético, patético patético %IQ no se discute con narrativa barata.',
  'Con %IQ el chat te da más soga, patético, asco, asco asco %IQ no se discute con narrativa barata.',
  '%IQ alto. Úsala, basura, basura, basura basura %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Por encima del relleno, %IQ, ridículo, ridículo, ridículo ridículo %IQ no se discute con narrativa barata.',
  'Con %IQ el sótano ya no te reclama, fracasado, fracasado, fracasado fracasado %IQ no se discute con narrativa barata.',
];

const GENIO = [
  '%IQ. Joder, un puto genio atrapado en un grupo de WhatsApp. Es como meter a Einstein en una jaula de monos que se tiran mierda.',
  'Con %IQ tienes más coeficiente que cojones, porque un genio de verdad no estaría perdiendo el tiempo con estos gilipollas.',
  '%IQ de IQ. Hostia puta, superdotado de los cojones. Y con toda esa cabeza la mejor idea que has tenido hoy es hablarle a un bot.',
  'Mierda, %IQ. Tienes el cerebro de un jodido genio y la vida de un puto becario. Algo ha fallado y gordo.',
  '%IQ. Eres el tipo más listo de un grupo lleno de subnormales. Enhorabuena, coño, menudo puto logro de mierda.',
  'Con %IQ podrías estar curando enfermedades y estás aquí, viendo cómo esta panda de imbéciles se manda memes del culo.',
  '%IQ de IQ. Joder, genio certificado. Tu cerebro vale más que todas las cabezas de este chat juntas, y eso da bastante pena de todos.',
  'Coño, %IQ. Superdotación real. Y la estás desperdiciando en un grupo donde el debate intelectual más fuerte es quién paga la cena.',
  '%IQ. Eres un puto genio encerrado en la jaula más triste del mundo: un chat donde la gente escribe "ola" sin hache.',
  'Con %IQ tu cerebro funciona como un reactor nuclear y lo usas para calentar un café con leche.',
  '%IQ de IQ. Hostia, superdotado del carajo. Tienes la cabeza de un premio Nobel y el historial de un cabrón cualquiera.',
  'Mierda, %IQ. Con ese cerebro podrías estar en un laboratorio y estás en un grupo donde alguien acaba de mandar un audio de siete minutos sobre nada.',
  '%IQ. Genio de los cojones. El noventa y ocho por ciento de la humanidad está por debajo de ti y aun así tu vida no se diferencia de la de ellos.',
  'Con %IQ eres la prueba viviente de que la inteligencia no sirve de una puta mierda si no haces nada con ella, pedazo de cabrón.',
  '%IQ de IQ. Joder, esa cifra da miedo. Lástima que la uses para elegir qué serie ver y no para algo que importe una polla.',
  'Coño, %IQ. Superdotado y metido en este chat voluntariamente. Es como usar un bisturí de cirujano para untar mantequilla, hostia.',
  '%IQ. Tu cerebro procesa más que el de todo el grupo junto y lo único que produce es opiniones que nadie va a leer dos veces.',
  'Con %IQ tienes la capacidad de un genio y la productividad de una mierda seca. Qué combinación más triste.',
  '%IQ de IQ. Hostia, un puto superdotado entre nosotros. Es como encontrar un Rolex en un contenedor de basura orgánica.',
  'Mierda, %IQ. Cerebro privilegiado que ha decidido voluntariamente compartir espacio con gente que confunde "hay" con "ahí".',
  '%IQ. Eres un genio de los cojones y este grupo es lo más cerca que vas a estar de un estudio sociológico sobre la imbecilidad humana.',
  'Con %IQ podrías estar resolviendo los problemas del mundo y estás resolviendo si poner o no el puto visto azul.',
  '%IQ de IQ. Joder, nivel de genio real. Y el genio ha decidido que su contribución al mundo sea calentar la silla de este chat de mierda.',
  'Coño, %IQ. Esa cabeza merece algo mejor que esta cueva de simios con wifi. Pero aquí estás, revolcándote en la mierda con todos.',
  '%IQ. Superdotado confirmado y completamente desaprovechado. Como plantar caviar en un huerto de patatas, hostia puta.',
  'Con %IQ piensas tres veces más rápido que cualquiera aquí y aun así no se te ha ocurrido largarte, pedazo de gilipollas.',
  '%IQ de IQ. Mierda, genio del copón. Tu cerebro vale una fortuna y tú lo tienes aparcado en el grupo más inútil de todo WhatsApp.',
  'Hostia, %IQ. Con esa cifra podrías haber cambiado el mundo, pero el mundo va a seguir igual de jodido porque tú estás aquí.',
  '%IQ. Eres un puto genio y nadie en este grupo se va a enterar ni le va a importar una mierda.',
  'Con %IQ tienes el cerebro más potente de la sala y la puta sala es un chat donde alguien ha mandado un sticker de un gato. Menudo genio de los cojones.',
  'Con %IQ el chat debería tomar nota, pero no lo hará, joder. joder %IQ no se discute con narrativa barata.',
  '%IQ de los que molestan de lo claros, cabrón mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Genio de ranking: %IQ. El grupo envidia en silencio, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  'Con %IQ el debate te queda pequeño a ratos, mierda cabrón, cabrón %IQ no se discute con narrativa barata.',
  '%IQ alto de verdad. No es fanfic, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  'Genio documentado. %IQ y el bot no discute, asco patético, patético %IQ no se discute con narrativa barata.',
  'Con %IQ el mediocre se esconde, patético asco, asco asco %IQ no se discute con narrativa barata.',
  '%IQ de laboratorio con wifi, basura basura, basura basura %IQ no se discute con narrativa barata.',
  'Genio de este puto chat: %IQ, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  'Con %IQ el argumento cierra puertas, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  '%IQ que duele de lo limpio, joder. joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Genio sin pedestal pedido: %IQ, cabrón mierda. mierda %IQ no se discute con narrativa barata.',
  'Con %IQ el hilo sube cuando escribes, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  '%IQ de los que no necesitan gritar, mierda cabrón, cabrón %IQ no se discute con narrativa barata.',
  'Genio de catálogo negro, %IQ, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  'Con %IQ el ranking te hace espacio, asco patético, patético %IQ no se discute con narrativa barata.',
  '%IQ fuera de la campana, patético asco, asco asco %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Genio del grupo aunque el grupo no aplauda: %IQ, basura basura, basura %IQ no se discute con narrativa barata.',
  'Con %IQ el fail ajeno se ve más fail, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  '%IQ de corte limpio, fracasado fracasado, fracasado fracasado %IQ no se discute con narrativa barata.',
  'Genio. El número es %IQ y duele, joder. joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ sobras en este chat, cabrón mierda. mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  '%IQ de los que leen tres jugadas antes, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  'Genio sin marketing: %IQ, mierda cabrón, cabrón cabrón %IQ no se discute con narrativa barata.',
  'Con %IQ el mediocre inventa excusas, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  '%IQ en zona de peligro para egos, asco patético, patético %IQ no se discute con narrativa barata.',
  'Genio documentado por el bot, %IQ, patético asco, asco %IQ no se discute con narrativa barata.',
  'Con %IQ el debate cambia de peso, basura basura, basura %IQ no se discute con narrativa barata.',
  '%IQ que no pide permiso, ridículo ridículo, ridículo ridículo %IQ no se discute con narrativa barata.',
  'Genio de este basurero con wifi: %IQ, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  'Con %IQ el chat debería callar más, joder. joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  '%IQ de precisión quirúrgica, cabrón mierda. mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Genio sin anestesia para el resto, %IQ, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  'Con %IQ el promedio te mira desde abajo, mierda cabrón, cabrón %IQ no se discute con narrativa barata.',
  '%IQ fuera de serie en este contexto, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  'Genio del ranking. %IQ, asco patético, patético patético %IQ no se discute con narrativa barata.',
  'Con %IQ el argumento no necesita adornos, patético asco, asco %IQ no se discute con narrativa barata.',
  '%IQ de los que cierran hilos, basura basura, basura basura %IQ no se discute con narrativa barata.',
  'Genio molesto porque tiene razón a ratos: %IQ, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  'Con %IQ el sótano queda lejos, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  '%IQ que el bot firma sin dudar, joder. joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Genio de catálogo. %IQ, cabrón mierda. mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ el mediocre se reescribe, gilipollas coño, coño %IQ no se discute con narrativa barata.',
  '%IQ en la cima de este chat, mierda cabrón, cabrón cabrón %IQ no se discute con narrativa barata.',
  'Genio sin concurso de popularidad: %IQ, coño gilipollas, gilipollas %IQ no se discute con narrativa barata.',
  'Con %IQ el fail colectivo se ve más claro, asco patético, patético %IQ no se discute con narrativa barata.',
  '%IQ de los que no piden aplauso, patético asco, asco asco %IQ no se discute con narrativa barata.',
  'Genio documentado, %IQ, basura basura, basura basura %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ el ranking te aparta del relleno, ridículo ridículo, ridículo %IQ no se discute con narrativa barata.',
  '%IQ de verdad en un mar de ruido, fracasado fracasado, fracasado %IQ no se discute con narrativa barata.',
  'Con %IQ el chat debería callar más, joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  '%IQ de precisión quirúrgica, cabrón, mierda. mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Genio sin anestesia para el resto, %IQ, gilipollas, coño, coño coño %IQ no se discute con narrativa barata, joder Lectura 82.',
  'Con %IQ el promedio te mira desde abajo, mierda, cabrón, cabrón cabrón %IQ no se discute con narrativa barata.',
  '%IQ fuera de serie en este contexto, coño, gilipollas, gilipollas gilipollas %IQ no se discute con narrativa barata.',
  'Genio del ranking. %IQ, asco, patético, patético patético %IQ no se discute con narrativa barata.',
  'Con %IQ el argumento no necesita adornos, patético, asco, asco asco %IQ no se discute con narrativa barata, joder Lectura 86.',
  '%IQ de los que cierran hilos, basura, basura, basura basura %IQ no se discute con narrativa barata.',
  'Genio molesto porque tiene razón a ratos: %IQ, ridículo, ridículo, ridículo ridículo %IQ no se discute con narrativa barata, joder Lectura 88.',
  'Con %IQ el sótano queda lejos, fracasado, fracasado, fracasado fracasado %IQ no se discute con narrativa barata.',
  '%IQ que el bot firma sin dudar, joder joder %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Genio de catálogo. %IQ, cabrón, mierda. mierda %IQ no se discute con narrativa barata, joder. Hostia puta, qué nivel.',
  'Con %IQ el mediocre se reescribe, gilipollas, coño, coño coño %IQ no se discute con narrativa barata.',
  '%IQ en la cima de este chat, mierda, cabrón, cabrón cabrón %IQ no se discute con narrativa barata.',
  'Genio sin concurso de popularidad: %IQ, coño, gilipollas, gilipollas gilipollas %IQ no se discute con narrativa barata.',
  'Con %IQ el fail colectivo se ve más claro, asco, patético, patético patético %IQ no se discute con narrativa barata.',
  '%IQ de los que no piden aplauso, patético, asco, asco asco %IQ no se discute con narrativa barata.',
  'Genio documentado, %IQ, basura, basura, basura basura %IQ no se discute con narrativa barata.',
  'Con %IQ el ranking te aparta del relleno, ridículo, ridículo, ridículo ridículo %IQ no se discute con narrativa barata, joder Lectura 98.',
  '%IQ de verdad en un mar de ruido, fracasado, fracasado, fracasado fracasado %IQ no se discute con narrativa barata.',
];

// Los tramos peyorativos se ordenan de mas duro a mas suave: el bot abre con la
// comparacion mas humillante que tiene. Los tramos altos no se tocan — ahi la
// "dureza" no aplica y reordenarlos solo mezclaria el tono sin ganar nada.
const POOLS = {
  abismo: ABISMO,
  bajo:   BAJO,
  medio:  MEDIO,
  alto:   ALTO,
  genio:  GENIO,
};

// Etiqueta corta que acompaña a la cifra, para que se lea como un informe.
const ETIQUETA = {
  abismo: 'Deficiencia severa',
  bajo:   'Por debajo de la media',
  medio:  'Media',
  alto:   'Por encima de la media',
  genio:  'Superdotación',
};

async function cmdIQ(sock, msg) {
  const jid = msg.key.remoteJid;
  const target = getTargetOrSelf(msg);

  const { clave, iq } = tirarIQ();
  const nm = `@${target.split('@')[0]}`;
  const frase = pickFresh(POOLS[clave], `${jid}|iq|${clave}`)
    .replace(/%IQ/g, String(iq))
    .replace(/\[nombre\]/g, nm);

  const text =
    `*${nm} tiene ${iq} de IQ*\n` +
    `_${ETIQUETA[clave]}_\n\n` +
    `${frase}`;

  await sock.sendMessage(jid, { text, mentions: [target] }, { quoted: msg });
}

module.exports = { cmdIQ, tirarIQ, TRAMOS, POOLS };
