// !iq — mide el coeficiente intelectual.
//
// No es un comando de porcentaje. Los de percent.js sacan un 0-100 y lo cuentan
// como "eres un X% de algo"; aquí la gracia está en la CIFRA de IQ, que tiene
// una escala reconocible (100 es la media, 70 es discapacidad, 130 es superdotado)
// y permite comparaciones que un porcentaje no da: un 65 de IQ se compara con un
// animal o con un objeto, un 95 con alguien concreto, un 130 ya impone.
//
// TOTALMENTE ALEATORIO, igual que !linda y !fea: no hay sesgo por rol ni amaño
// del owner. Aquí a todo el mundo le puede caer un 62 o un 141.

const { getTargetOrSelf } = require('../utils/wa');
const { pickFresh, ordenarPorDureza } = require('../utils/helpers');

// Tramos. El reparto está pensado para que lo divertido salga a menudo: casi la
// mitad de las tiradas caen en los dos tramos bajos, que son los que tienen las
// comparaciones. El de genio es raro a propósito — si saliera cada dos por tres
// dejaría de tener gracia que salga.
//
//   abismo   55-74   comparación con un animal o un objeto
//   bajo     75-89   comparación con alguien o algo concreto
//   medio    90-109  la media: ni frío ni caliente
//   alto    110-129  listo de verdad
//   genio   130-145  otra liga
const TRAMOS = [
  { clave: 'abismo', min: 55,  max: 74,  peso: 0.28 },
  { clave: 'bajo',   min: 75,  max: 89,  peso: 0.24 },
  { clave: 'medio',  min: 90,  max: 109, peso: 0.26 },
  { clave: 'alto',   min: 110, max: 129, peso: 0.16 },
  { clave: 'genio',  min: 130, max: 145, peso: 0.06 },
];

function tirarIQ() {
  let r = Math.random();
  for (const t of TRAMOS) {
    r -= t.peso;
    if (r <= 0) {
      return { clave: t.clave, iq: t.min + Math.floor(Math.random() * (t.max - t.min + 1)) };
    }
  }
  const t = TRAMOS[TRAMOS.length - 1];
  return { clave: t.clave, iq: t.min + Math.floor(Math.random() * (t.max - t.min + 1)) };
}

// %IQ se sustituye por la cifra que salió, para que la frase pueda jugar con
// ella ("tienes 62 y el termostato de tu casa tiene 68").
const ABISMO = [
  'Tienes las mismas capacidades cognitivas que un trozo de mierda recién cagado por un perro. Y el trozo al menos tiene forma, joder.',
  '%IQ de coeficiente. El resto del grupo usa calculadora; tú usas los dedos y todavía te sobran, fracasado.',
  'Con %IQ estás a un paso del apagón total y ese paso ya lo diste hace varios hilos, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ. El número habla solo y con claridad; tú no, y a veces es lo mejor que puedes hacer, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'Con %IQ el silencio te favorece más que cualquier argumento que hayas intentado montar, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ. Eres el argumento perfecto contra la meritocracia cognitiva del puto ranking, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Con %IQ el bot no necesita narrador: el número te deja en el sótano y cierra el parte, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ de abismo. Ni el low del resto se atreve a bajar a tu planta, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Tienes %IQ y se nota en cada frase torcida que sueltas como si fueran ideas, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El grupo ya asumió que no hay que esperarte en el debate serio, coño delante del puto grupo y sin derecho a apelación, fracasado.',
  'Con %IQ estás por debajo del umbral donde merece la pena discutir contigo, joder delante del puto grupo y sin derecho a apelación, joder.',
  '%IQ. Ni el algoritmo de respeto te mira de frente, fracasado delante del puto grupo y sin derecho a apelación, mierda.',
  'El abismo cognitivo tiene tu nombre y el número %IQ de placa, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ. Has convertido la falta de luces en identidad del ranking, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'Con %IQ el chat funciona mejor cuando no escribes, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ de coeficiente: el sótano del comando y tú sois la misma dirección, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Se te nota el %IQ en la primera línea de cada mensaje inútil, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ. El bot no exagera: lee el número y te coloca donde mereces, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Con %IQ cambias de tema porque no aguantas el hilo dos mensajes, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El espejo del comando te devuelve un abismo y no hay filtro que lo tape, coño delante del puto grupo y sin derecho a apelación, fracasado.',
  'Tienes %IQ y el grupo ya pasó de página hace rato, joder delante del puto grupo y sin derecho a apelación, joder.',
  '%IQ. Argumentas como quien no ha abierto un puto libro en su vida, fracasado delante del puto grupo y sin derecho a apelación, mierda.',
  'Con %IQ el silencio es tu mejor aportación al hilo, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ de abismo documentado. Autor: tú. Testigo: el ranking, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'El número %IQ no admite recurso ni segunda lectura útil, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ. Has bajado el promedio cognitivo del grupo solo con existir, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Con %IQ ni el low del resto te considera rival de ideas, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ. El comando te nombra sin anestesia y el chat archiva, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Tienes %IQ y se te cae el personaje en la primera réplica, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El abismo no es metáfora: es el tramo y tú vives ahí, coño delante del puto grupo y sin derecho a apelación, fracasado.',
  'Con %IQ el debate te queda grande y el silencio te queda justo, joder delante del puto grupo y sin derecho a apelación, joder.',
  '%IQ. Ni la calculadora del bot se molesta en redondear a tu favor, fracasado delante del puto grupo y sin derecho a apelación, mierda.',
  'El ranking de luces te deja en el sótano con %IQ de placa, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ. Has firmado el empty head en cada mensaje del historial, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'Con %IQ el grupo no te cita porque no hay qué citar, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ de coeficiente. El resto piensa; tú repites, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Se te nota el %IQ hasta en la miniatura del estado, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ. El low de otros es tu techo natural, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Con %IQ el hilo se empobrece solo con tu entrada, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El bot te ha medido y el resultado no admite consuelo, coño delante del puto grupo y sin derecho a apelación, fracasado.',
  'Tienes %IQ y el almost de idea nunca llega a tesis, joder delante del puto grupo y sin derecho a apelación, joder.',
  '%IQ. Eres el gag cognitivo del comando y el grupo no pide replay, fracasado delante del puto grupo y sin derecho a apelación, mierda.',
  'Con %IQ el modo avión del cerebro es tu estado por defecto, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ de abismo. Sin recurso, sin bis, sin anestesia, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'El número habla: %IQ. Tú no, y es lo mejor que puedes hacer, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ. Has convertido la falta de sustancia en marca personal, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Con %IQ ni el tutorial de pensar te salva a estas alturas, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ. El sótano del ranking te queda de casa y de apodo, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Tienes %IQ y se ve desde el primer pixel del mensaje, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El comando no regala décimas de caridad cognitiva, coño delante del puto grupo y sin derecho a apelación, fracasado.',
  'Con %IQ el grupo ya asumió el empty seat cuando escribes, joder delante del puto grupo y sin derecho a apelación, joder.',
  '%IQ. Argumentas en círculos porque el centro está vacío, fracasado delante del puto grupo y sin derecho a apelación, mierda.',
  'El abismo tiene %IQ de profundidad y tu nombre en la entrada, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ. Has bajado el listón del debate solo con abrir la boca, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'Con %IQ el silencio ajeno no es respeto: es alivio, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ de coeficiente. El bot firma y cierra el parte, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Se te nota el %IQ en cada cambio de tema sin sentido, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ. Ni el low del resto baja a tu planta a discutir, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Con %IQ el hilo prefiere tu ausencia a tu aporte, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El ranking de luces y el abismo coinciden en ti, coño delante del puto grupo y sin derecho a apelación, fracasado.',
  'Tienes %IQ y el almost de coherencia se queda en almost, joder delante del puto grupo y sin derecho a apelación, joder.',
  '%IQ. Eres el contenido de ridículo cognitivo del día, fracasado delante del puto grupo y sin derecho a apelación, mierda.',
  'Con %IQ el modo pensar se te agota en la primera frase, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ de abismo documentado delante del puto grupo, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'El número %IQ no necesita narrador: se basta solo, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ. Has firmado el empty head con cada mensaje inútil, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Con %IQ el debate te expulsa antes del primer argumento serio, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ. El sótano no es metáfora: es tu tramo y tu casa, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Tienes %IQ y se te cae la idea en el primer punto y seguido, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El comando te nombra en el abismo sin pedir permiso, coño delante del puto grupo y sin derecho a apelación, fracasado.',
  'Con %IQ el grupo no espera sustancia y tú no defraudas esa expectativa, joder delante del puto grupo y sin derecho a apelación, joder.',
  '%IQ. El almost de luces nunca cruza la línea de llegada, fracasado delante del puto grupo y sin derecho a apelación, mierda.',
  'El ranking te deja en %IQ y cierra sin recurso de apelación, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ. Has convertido la torpeza cognitiva en estribillo del chat, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'Con %IQ ni el filtro de autoestima te salva del número, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ de coeficiente. El resto del grupo ya pasó de página, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Se te nota el %IQ hasta en los mensajes que pretenden ser serios, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ. El abismo te queda de apodo y de residencia fiscal, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Con %IQ el hilo se ensucia solo con tu intervención, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El bot no discute: el número habla y tú estás abajo, coño delante del puto grupo y sin derecho a apelación, fracasado.',
  'Tienes %IQ y el gag se escribe solo en el ranking, joder delante del puto grupo y sin derecho a apelación, joder.',
  '%IQ. Eres el empty seat con nick del comando, fracasado delante del puto grupo y sin derecho a apelación, mierda.',
  'Con %IQ el modo luces apagadas es tu setting por defecto, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ de abismo. Sin consuelo, sin bis, sin segunda lectura, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'El número %IQ te nombra sin anestesia delante del grupo, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ. Has bajado el promedio del chat solo con existir en el hilo, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Con %IQ el silencio es lo único que no te deja en evidencia, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ. El sótano del ranking y tú sois la misma dirección postal, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Tienes %IQ y se ve en cada frase que no sostiene un puto argumento, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El comando firma el parte y el chat archiva sin debate, coño delante del puto grupo y sin derecho a apelación, fracasado.',
  'Con %IQ ni el tutorial de coherencia te saca del abismo, joder delante del puto grupo y sin derecho a apelación, joder.',
  '%IQ. El almost de idea se queda en ruido de fondo, fracasado delante del puto grupo y sin derecho a apelación, mierda.',
  'El ranking de luces te deja en %IQ sin modo avión posible, asco delante del puto grupo y sin derecho a apelación, coño.',
  '%IQ. Has firmado el empty head en alta definición del chat, basura delante del puto grupo y sin derecho a apelación, cabrón.',
  'Con %IQ el grupo prefiere el mute a tu aporte, cabrón delante del puto grupo y sin derecho a apelación, gilipollas.',
  '%IQ de coeficiente. El bot no regala caridad cognitiva, gilipollas delante del puto grupo y sin derecho a apelación, patético.',
  'Se te nota el %IQ en el primer cambio de tema sin sentido, patético delante del puto grupo y sin derecho a apelación, asco.',
  '%IQ. El abismo no necesita presentación: el número basta, ridículo delante del puto grupo y sin derecho a apelación, basura.',
  'Con %IQ el hilo se empobrece en tiempo real, mierda delante del puto grupo y sin derecho a apelación, ridículo.',
  '%IQ. El veredicto es bajo y no hay recurso ni narrador que lo suavice, coño delante del puto grupo y sin derecho a apelación, fracasado.'
];

const BAJO = [
  'Con %IQ estás justo por debajo de la media y se te nota en cada intervención torcida del grupo, joder.',
  '%IQ de coeficiente: suficiente para hablar, insuficiente para no hacer el ridículo en cada hilo serio, mierda.',
  'Estás en la franja donde se ve la falta sin llegar al abismo: incómodo, visible y constante con %IQ, coño.',
  'Con %IQ el razonamiento llega tarde y cojo: el grupo ya cerró el tema cuando tú abres la boca, cabrón.',
  '%IQ. No es drama de portada: es mediocridad hacia abajo que cansa más que un fail espectacular, gilipollas.',
  'Tu cerebro con %IQ prioriza la comodidad sobre la precisión: se nota en cada conclusión floja, patético.',
  'Con %IQ aciertas lo obvio y te estrellas en el primer paso extra: siempre el mismo escalón, ridículo.',
  '%IQ de IQ: justo debajo del corte, ni genio ni anécdota, solo falta ligera y permanente. Y se nota en cada puto mensaje del chat, basura.',
  'Se te nota %IQ en las preguntas que no haces y en las respuestas que sí envías sin pensar, desperdicio.',
  'Con %IQ el análisis se corta cuando empieza a costar: coincides siempre con la zona cómoda. Y se nota en cada puto mensaje del chat, asco.',
  '%IQ. Te basta un escalón para fallar el tono: no necesitas el sótano, usas el rellano a diario, cutre.',
  'El grupo ya no se sorprende de tus fallos con %IQ: los espera con el reloj en la mano. Y se nota en cada puto mensaje del chat, pringado.',
  'Con %IQ la lógica va en línea recta corta y se rompe en la primera curva del argumento. Y se nota en cada puto mensaje del chat, fracasado.',
  '%IQ de coeficiente: el margen de error te roza por abajo y se queda a vivir ahí. Y se nota en cada puto mensaje del chat, vergüenza.',
  'Tu idea de profundidad con %IQ es repetir la superficie con palabras un poco más largas. Y se nota en cada puto mensaje del chat, joder.',
  'Con %IQ llegas a las conclusiones dos mensajes después que el resto: siempre tarde. Y se nota en cada puto mensaje del chat, mierda.',
  '%IQ. Suficiente para no ser el abismo: insuficiente para no notarte claramente abajo. Y se nota en cada puto mensaje del chat, coño.',
  'El pensamiento te dura lo que un story: con %IQ el piloto automático es el modo default. Y se nota en cada puto mensaje del chat, cabrón.',
  'Con %IQ sales al debate, tocas el balón y vuelves al banquillo: participación de adorno, gilipollas.',
  '%IQ de IQ: zona de nadie, ni brillar ni hundirte, solo sobrar en el promedio del chat. Y se nota en cada puto mensaje del chat, patético.',
  'Se te ve el esfuerzo por subir un peldaño con %IQ: el esfuerzo se nota y no alcanza. Y se nota en cada puto mensaje del chat, ridículo.',
  'Con %IQ las analogías se te escapan antes de aterrizar en el punto que querías hacer. Y se nota en cada puto mensaje del chat, basura.',
  '%IQ. El número es el espejo: un poco bajo y sin maquillaje que lo salve. Y se nota en cada puto mensaje del chat, desperdicio.',
  'Tu media personal con %IQ está torcida hacia abajo: el grupo ya calibró la expectativa. Y se nota en cada puto mensaje del chat, asco.',
  'Con %IQ entiendes el chiste al día siguiente: cuando ya no hace gracia a nadie. Y se nota en cada puto mensaje del chat, cutre.',
  '%IQ de coeficiente: no es tragedia, es fricción constante en cada hilo que pide rigor. Y se nota en cada puto mensaje del chat, pringado.',
  'Estás en el tramo que no da titulares: con %IQ das bostezos educados y poco más. Y se nota en cada puto mensaje del chat, fracasado.',
  'Con %IQ el rigor te parece opcional: por eso tus conclusiones también lo parecen. Y se nota en cada puto mensaje del chat, vergüenza.',
  '%IQ. Un paso detrás de la media: un paso que se nota en cada discusión larga. Y se nota en cada puto mensaje del chat, joder.',
  'Tu techo con %IQ está cerca del suelo del resto: la escalera intelectual es corta. Y se nota en cada puto mensaje del chat, mierda.',
  'Con %IQ las matizaciones ajenas te suenan a ruido: por eso no las incorporas nunca. Y se nota en cada puto mensaje del chat, coño.',
  '%IQ. No eres el abismo: eres el escalón suelto que hace tropezar el hilo entero. Y se nota en cada puto mensaje del chat, cabrón.',
  'Estás calibrado bajo con %IQ: el grupo ya no ajusta la esperanza al alza. Y se nota en cada puto mensaje del chat, gilipollas.',
  'Con %IQ el argumento se diluye a mitad de mensaje antes de un punto final claro. Y se nota en cada puto mensaje del chat, patético.',
  '%IQ de IQ: opinas con seguridad que el número no respalda en absoluto. Y se nota en cada puto mensaje del chat, ridículo.',
  'El grupo no te espera en los hilos densos: con %IQ tiene todo el sentido del mundo. Y se nota en cada puto mensaje del chat, basura.',
  'Con %IQ el mapa mental tiene calles cortadas: siempre las mismas, siempre en el mismo barrio, desperdicio.',
  '%IQ. Debajo de la media sin sótano: el rellano más incómodo del edificio cognitivo. Y se nota en cada puto mensaje del chat, asco.',
  'Se te nota cuando el tema pide dos pasos y tú te quedas en uno con %IQ. Y se nota en cada puto mensaje del chat, cutre.',
  'Con %IQ la duda razonable se vuelve eterna o se convierte en certeza falsa. Y se nota en cada puto mensaje del chat, pringado.',
  '%IQ de coeficiente: el bot no exagera, lee el número y te coloca en el estante. Y se nota en cada puto mensaje del chat, fracasado.',
  'Con %IQ malentiendes el subtítulo y te anclas al título como si fuera todo el dato. Y se nota en cada puto mensaje del chat, vergüenza.',
  '%IQ. Llenas formularios mal y sales convencido de que están perfectos. Y se nota en cada puto mensaje del chat, joder.',
  'Tu hardware con %IQ calienta de más para rendir de menos en cada debate. Y se nota en cada puto mensaje del chat, mierda.',
  'Con %IQ el matiz es un lujo que no te puedes permitir: operas a brochazos. Y se nota en cada puto mensaje del chat, coño.',
  '%IQ de IQ: el grupo resume tus intervenciones en un encogimiento de hombros. Y se nota en cada puto mensaje del chat, cabrón.',
  'Estás un peldaño abajo y con %IQ ese peldaño se ha vuelto tu zona de confort. Y se nota en cada puto mensaje del chat, gilipollas.',
  'Con %IQ las excepciones se te convierten en reglas y las reglas en niebla. Y se nota en cada puto mensaje del chat, patético.',
  '%IQ. Justo lo que hace falta para no callarte cuando deberías. Y se nota en cada puto mensaje del chat, ridículo.',
  'El pensamiento en cadena con %IQ se corta al segundo eslabón sin falta. Y se nota en cada puto mensaje del chat, basura.',
  'Con %IQ llegas al aula del debate cuando el examen ya se entregó. Y se nota en cada puto mensaje del chat, desperdicio.',
  '%IQ de coeficiente: suficiente para el ruido, insuficiente para la señal. Y se nota en cada puto mensaje del chat, asco.',
  'Tu cerebro con %IQ elige el atajo y el atajo suele ser el error. Y se nota en cada puto mensaje del chat, cutre.',
  'Con %IQ el hilo serio te expone más que el hilo de memes. Y se nota en cada puto mensaje del chat, pringado.',
  '%IQ. La calculadora del grupo ya te tiene de ejemplo de media baja. Y se nota en cada puto mensaje del chat, fracasado.',
  'Se te escapa el dato clave con %IQ y te agarras al dato decorativo. Y se nota en cada puto mensaje del chat, vergüenza.',
  'Con %IQ la conclusión llega antes que la premisa: y se nota el fraude. Y se nota en cada puto mensaje del chat, joder.',
  '%IQ de IQ: el esfuerzo de parecer listo te dura menos que el mensaje. Y se nota en cada puto mensaje del chat, mierda.',
  'Estás en la cola blanda de la campana: %IQ te clava ahí sin anestesia. Y se nota en cada puto mensaje del chat, coño.',
  'Con %IQ el debate te usa de contraste para que brillen los demás. Y se nota en cada puto mensaje del chat, cabrón.',
  '%IQ. No hay potencial escondido: hay un techo bajo y bien visible. Y se nota en cada puto mensaje del chat, gilipollas.',
  'Tu ritmo cognitivo con %IQ es el del que lee el resumen y opina del libro. Y se nota en cada puto mensaje del chat, patético.',
  'Con %IQ las paradojas te parecen fallos del otro y no límites tuyos. Y se nota en cada puto mensaje del chat, ridículo.',
  '%IQ de coeficiente: el margen por debajo se ha convertido en costumbre. Y se nota en cada puto mensaje del chat, basura.',
  'El grupo aprende a no citarte en los hilos que importan: %IQ mediante. Y se nota en cada puto mensaje del chat, desperdicio.',
  'Con %IQ repites con seguridad lo que acabas de entender a medias. Y se nota en cada puto mensaje del chat, asco.',
  '%IQ. El espejo del ranking no te favorece y no es culpa del cristal. Y se nota en cada puto mensaje del chat, cutre.',
  'Tu ventana de atención con %IQ se cierra antes que el argumento ajeno. Y se nota en cada puto mensaje del chat, pringado.',
  'Con %IQ el matiz fino te resbala: operas con guantes de boxeo en cirugía. Y se nota en cada puto mensaje del chat, fracasado.',
  '%IQ de IQ: participas, ocupas sitio y no mueves el marcador del hilo. Y se nota en cada puto mensaje del chat, vergüenza.',
  'Estás calibrado para el trámite: con %IQ lo denso se te atraganta. Y se nota en cada puto mensaje del chat, joder.',
  'Con %IQ la ironía te llega tarde o te llega al revés. Y se nota en cada puto mensaje del chat, mierda.',
  '%IQ. Un poco bajo, muy visible, imposible de maquillar en serio. Y se nota en cada puto mensaje del chat, coño.',
  'El bot te pone %IQ y el chat confirma el número sin necesidad de calculadora. Y se nota en cada puto mensaje del chat, cabrón.',
  'Con %IQ tus preguntas revelan más lagunas que curiosidad real. Y se nota en cada puto mensaje del chat, gilipollas.',
  '%IQ de coeficiente: la duda te dura poco porque la sustituyes por postura. Y se nota en cada puto mensaje del chat, patético.',
  'Se te ve el sudor cuando el tema sube de nivel con %IQ de base. Y se nota en cada puto mensaje del chat, ridículo.',
  'Con %IQ el resumen te salva: el detalle te condena. Y se nota en cada puto mensaje del chat, basura.',
  '%IQ. Estás en el tramo que no emociona: solo confirma la media baja. Y se nota en cada puto mensaje del chat, desperdicio.',
  'Tu techo de cristal cognitivo con %IQ está a la altura de los ojos del resto. Y se nota en cada puto mensaje del chat, asco.',
  'Con %IQ cambias de opinión sin darte cuenta de que no tenías una sólida. Y se nota en cada puto mensaje del chat, cutre.',
  '%IQ de IQ: el grupo ya tiene plantilla mental para tus intervenciones. Y se nota en cada puto mensaje del chat, pringado.',
  'Estás un paso atrás y con %IQ ese paso se alarga en cada hilo largo. Y se nota en cada puto mensaje del chat, fracasado.',
  'Con %IQ la precisión es un accidente: la aproximación es el plan. Y se nota en cada puto mensaje del chat, vergüenza.',
  '%IQ. No fallas por mala suerte: fallas por hardware justo por debajo. Y se nota en cada puto mensaje del chat, joder.',
  'El razonamiento corto se te hace largo: con %IQ el largo ni se intenta. Y se nota en cada puto mensaje del chat, mierda.',
  'Con %IQ citas mal, entiendes regular y concluyes con demasiada firmeza. Y se nota en cada puto mensaje del chat, coño.',
  '%IQ de coeficiente: suficiente para el ego, insuficiente para el expediente. Y se nota en cada puto mensaje del chat, cabrón.',
  'Tu presencia en debates densos con %IQ es la del que asiente sin seguir. Y se nota en cada puto mensaje del chat, gilipollas.',
  'Con %IQ el punto fuerte es la opinión: el punto débil es todo lo demás. Y se nota en cada puto mensaje del chat, patético.',
  '%IQ. El número no miente y tú hablas como si no lo hubieras visto. Y se nota en cada puto mensaje del chat, ridículo.',
  'Se te acumulan los casi: con %IQ casi entiendes, casi argumentas, casi. Y se nota en cada puto mensaje del chat, basura.',
  'Con %IQ el hilo te supera en la tercera intervención ajena. Y se nota en cada puto mensaje del chat, desperdicio.',
  '%IQ de IQ: zona gris donde sobras sin ser el villano del ranking. Y se nota en cada puto mensaje del chat, asco.',
  'Estás por debajo y se te nota en el tempo: %IQ es retraso crónico. Y se nota en cada puto mensaje del chat, cutre.',
  'Con %IQ las metáforas se te van de las manos y aterrizan en otro tema. Y se nota en cada puto mensaje del chat, pringado.',
  '%IQ. El grupo no necesita el comando para intuirtelo: el comando solo confirma. Y se nota en cada puto mensaje del chat, fracasado.',
  'Tu media con %IQ es una fricción constante, no un evento puntual. Y se nota en cada puto mensaje del chat, vergüenza.',
  'Con %IQ defiendes mal las buenas ideas y con pasión las malas. Y se nota en cada puto mensaje del chat, joder.',
  '%IQ de coeficiente: el estante de abajo del armario cognitivo del chat. Y se nota en cada puto mensaje del chat, mierda.',
  'El silencio te favorece más que tus argumentos con %IQ a la vista. Y se nota en cada puto mensaje del chat, coño.',
  'Con %IQ el cierre del hilo te pilla siempre a mitad de la idea. Y se nota en cada puto mensaje del chat, cabrón.',
  '%IQ. No eres tonto de festivo: eres bajo de diario, y se nota más. Y se nota en cada puto mensaje del chat, gilipollas.',
  'Se te ve la plantilla: con %IQ respondes patrón, no contenido. Y se nota en cada puto mensaje del chat, patético.',
  'Con %IQ el dato incómodo se te olvida antes de integrarlo. Y se nota en cada puto mensaje del chat, ridículo.',
  '%IQ de IQ: el ranking te deja donde el hardware manda. Y se nota en cada puto mensaje del chat, basura.',
  'Estás en el rellano: %IQ no es sótano, pero tampoco subes. Y se nota en cada puto mensaje del chat, desperdicio.',
  'Con %IQ la confianza supera al coeficiente por un margen indecente. Y se nota en cada puto mensaje del chat, asco.',
  '%IQ. Cada intervención un poco floja suma un veredicto claro. Y se nota en cada puto mensaje del chat, cutre.',
  'Tu curva de aprendizaje con %IQ se aplana antes de la primera rampa. Y se nota en cada puto mensaje del chat, pringado.',
  'Con %IQ el debate serio es un idioma que hablas con acento fuerte. Y se nota en cada puto mensaje del chat, fracasado.',
  '%IQ de coeficiente: el bot imprime el número y el grupo asiente. Y se nota en cada puto mensaje del chat, vergüenza.',
  'El matiz se muere en el camino entre lo que lees y lo que respondes con %IQ. Y se nota en cada puto mensaje del chat, joder.',
  'Con %IQ prefieres tener razón aparente a tener razón real. Y se nota en cada puto mensaje del chat, mierda.',
  '%IQ. Bajo de forma estable: no hay pico de lucidez que compense la media. Y se nota en cada puto mensaje del chat, coño.',
  'Se te escapa el hilo conductor y te agarras a un hilo lateral con %IQ. Y se nota en cada puto mensaje del chat, cabrón.',
  'Con %IQ la corrección ajena te parece ataque y no información. Y se nota en cada puto mensaje del chat, gilipollas.',
  '%IQ de IQ: suficiente para el trámite del chat, insuficiente para el fondo. Y se nota en cada puto mensaje del chat, patético.',
  'Estás un peldaño abajo y con %IQ has decorado el peldaño como casa. Y se nota en cada puto mensaje del chat, ridículo.',
  'Con %IQ las premisas flojas te parecen sólidas si suenan fuerte. Y se nota en cada puto mensaje del chat, basura.',
  '%IQ. El espejo del comando te devuelve una media que ya intuíamos. Y se nota en cada puto mensaje del chat, desperdicio.',
  'Tu rendimiento cognitivo con %IQ es el del que llega al resumen por suerte. Y se nota en cada puto mensaje del chat, asco.',
  'Con %IQ el argumento se te desmonta si alguien tira suavemente de un hilo. Y se nota en cada puto mensaje del chat, cutre.',
  '%IQ de coeficiente: no hace falta ensañarse, el número ya lo hace. Y se nota en cada puto mensaje del chat, pringado.',
  'El grupo calibra bajo cuando escribes: %IQ es la etiqueta oficial. Y se nota en cada puto mensaje del chat, fracasado.',
  'Con %IQ confundes volumen de mensajes con calidad de pensamiento. Y se nota en cada puto mensaje del chat, vergüenza.',
  '%IQ. La zona donde el esfuerzo se ve y el resultado no. Y se nota en cada puto mensaje del chat, joder.',
  'Se te nota el techo: con %IQ las ideas altas rebotan antes de entrar. Y se nota en cada puto mensaje del chat, mierda.',
  'Con %IQ el casi es tu marca: casi claro, casi lógico, casi útil. Y se nota en cada puto mensaje del chat, coño.',
  '%IQ de IQ: el rellano permanente del edificio del ranking. Y se nota en cada puto mensaje del chat, cabrón.',
  'Estás por debajo de la media de forma que ya no sorprende a nadie con %IQ. Y se nota en cada puto mensaje del chat, gilipollas.',
  'Con %IQ la duda productiva se te convierte en bloqueo o en postureo. Y se nota en cada puto mensaje del chat, patético.',
  '%IQ. No es un mal día de IQ: es el suelo sobre el que construyes. Y se nota en cada puto mensaje del chat, ridículo.',
  'Tu intervención típica con %IQ añade calor y poca luz al hilo. Y se nota en cada puto mensaje del chat, basura.',
  'Con %IQ el dato que no encaja lo descartas en lugar de usarlo. Y se nota en cada puto mensaje del chat, desperdicio.',
  '%IQ de coeficiente: el margen bajo se ha vuelto tu firma en el chat. Y se nota en cada puto mensaje del chat, asco.',
  'El bot dice %IQ y el historial de mensajes firma debajo sin dudar. Y se nota en cada puto mensaje del chat, cutre.',
  'Con %IQ llegas tarde al punto y temprano a la conclusión errónea. Y se nota en cada puto mensaje del chat, pringado.',
  '%IQ. Bajo visible, estable, sin maquillaje posible en el tramo. Y se nota en cada puto mensaje del chat, fracasado.',
  'Se te ve la plantilla cognitiva: con %IQ el patrón es más claro que el contenido. Y se nota en cada puto mensaje del chat, vergüenza.',
  'Con %IQ el rigor ajeno te cansa antes que el error propio. Y se nota en cada puto mensaje del chat, joder.',
  '%IQ de IQ: participas en la media desde abajo, tirando hacia abajo. Y se nota en cada puto mensaje del chat, mierda.',
  'Estás calibrado para no brillar: %IQ es la especificación del producto. Y se nota en cada puto mensaje del chat, coño.',
  'Con %IQ la ironía del grupo te atraviesa sin hacer blanco en tu radar. Y se nota en cada puto mensaje del chat, cabrón.',
  '%IQ. Un escalón bajo que usas tanto que ya es suelo. Y se nota en cada puto mensaje del chat, gilipollas.',
  'Tu techo con %IQ está documentado: el comando solo pone el sello. Y se nota en cada puto mensaje del chat, patético.',
  'Con %IQ las preguntas buenas se te atragantan y salen las fáciles. Y se nota en cada puto mensaje del chat, ridículo.',
  '%IQ de coeficiente: el estante bajo donde el grupo ya no busca sorpresas. Y se nota en cada puto mensaje del chat, basura.',
  'El pensamiento lateral con %IQ se te va a otro edificio. Y se nota en cada puto mensaje del chat, desperdicio.',
  'Con %IQ defiendes la primera idea que se te ocurre como si fuera la mejor. Y se nota en cada puto mensaje del chat, asco.',
  '%IQ. La media baja que no necesita amplificación: se oye sola. Y se nota en cada puto mensaje del chat, cutre.',
  'Se te acumula el retraso: con %IQ cada hilo denso te deja un mensaje atrás. Y se nota en cada puto mensaje del chat, pringado.',
  'Con %IQ el cierre lógico te pilla escribiendo la introducción. Y se nota en cada puto mensaje del chat, fracasado.',
  '%IQ de IQ: zona de confort cognitiva que el ranking se niega a llamar confort. Y se nota en cada puto mensaje del chat, vergüenza.',
  'Estás por debajo y con %IQ has hecho de la debajo tu estilo. Y se nota en cada puto mensaje del chat, joder.',
  'Con %IQ el argumento sólido ajeno te parece complicarse la vida. Y se nota en cada puto mensaje del chat, mierda.',
  '%IQ. El número es bajo; el uso que le das no lo mejora. Y se nota en cada puto mensaje del chat, coño.',
  'Tu presencia en el debate con %IQ es previsible: el grupo adelanta el fallo. Y se nota en cada puto mensaje del chat, cabrón.',
  'Con %IQ cambias de tema cuando el tema te exige subir el nivel. Y se nota en cada puto mensaje del chat, gilipollas.',
  '%IQ de coeficiente: suficiente para el ego del mensaje, no para el expediente. Y se nota en cada puto mensaje del chat, patético.',
  'El matiz fino muere en tu bandeja de entrada con %IQ de filtro. Y se nota en cada puto mensaje del chat, ridículo.',
  'Con %IQ la corrección se siente como insulto y el insulto como debate. Y se nota en cada puto mensaje del chat, basura.',
  '%IQ. Bajo de diario: el abismo sería vacaciones, esto es la oficina. Y se nota en cada puto mensaje del chat, desperdicio.',
  'Se te nota cuando el hilo pide memoria de lo anterior: con %IQ empiezas de cero. Y se nota en cada puto mensaje del chat, asco.',
  'Con %IQ la conclusión viene de fábrica con defecto de fábrica. Y se nota en cada puto mensaje del chat, cutre.',
  '%IQ de IQ: el ranking te asigna el asiento de atrás sin discutir. Y se nota en cada puto mensaje del chat, pringado.',
  'Estás un paso detrás de la media: %IQ mide el largo de ese paso. Y se nota en cada puto mensaje del chat, fracasado.',
  'Con %IQ el dato incómodo no entra en el modelo mental. Y se nota en cada puto mensaje del chat, vergüenza.',
  '%IQ. No hay pico de lucidez que compense la meseta baja. Y se nota en cada puto mensaje del chat, joder.',
  'Tu curva con %IQ es plana y baja: el comando solo la nombra. Y se nota en cada puto mensaje del chat, mierda.',
  'Con %IQ el grupo aprende a no apoyarse en tus resúmenes. Y se nota en cada puto mensaje del chat, coño.',
  '%IQ de coeficiente: el margen inferior convertido en costumbre de chat. Y se nota en cada puto mensaje del chat, cabrón.',
  'El silencio tras tus mensajes con %IQ no es admiración: es recálculo. Y se nota en cada puto mensaje del chat, gilipollas.',
  'Con %IQ la premisa floja te parece una base de hormigón. Y se nota en cada puto mensaje del chat, patético.',
  '%IQ. Bajo, visible, sin derecho a sorpresa en el veredicto. Y se nota en cada puto mensaje del chat, ridículo.',
  'Se te escapa el hilo y con %IQ agarras el primero que brilla. Y se nota en cada puto mensaje del chat, basura.',
  'Con %IQ la profundidad es un lugar del que has oído hablar. Y se nota en cada puto mensaje del chat, desperdicio.',
  '%IQ de IQ: el rellano donde te quedas mientras otros suben el tramo. Y se nota en cada puto mensaje del chat, asco.',
  'Estás por debajo de la media de forma que el comando solo confirma. Y se nota en cada puto mensaje del chat, cutre.',
  'Con %IQ el esfuerzo por parecer ágil se nota más que la agilidad. Y se nota en cada puto mensaje del chat, pringado.',
  '%IQ. El hardware justo por debajo: el software no compensa. Y se nota en cada puto mensaje del chat, fracasado.',
  'Tu marca con %IQ es el casi: casi argumentas, casi cierras, casi. Y se nota en cada puto mensaje del chat, vergüenza.',
  'Con %IQ el debate denso te deja en modo lectura sin modo escritura útil. Y se nota en cada puto mensaje del chat, joder.',
  '%IQ de coeficiente: el estante bajo del armario, etiqueta visible. Y se nota en cada puto mensaje del chat, mierda.',
  'El bot imprime %IQ y el chat no pide segunda opinión. Y se nota en cada puto mensaje del chat, coño.',
  'Con %IQ llegas al punto cuando el punto ya cambió de sitio. Y se nota en cada puto mensaje del chat, cabrón.',
  '%IQ. Media baja estable: el abismo sería otra película, esto es el día a día. Y se nota en cada puto mensaje del chat, gilipollas.',
  'Se te ve el techo cognitivo: con %IQ las ideas altas no tienen puerta. Y se nota en cada puto mensaje del chat, patético.',
  'Con %IQ la plantilla de respuesta sale antes que el pensamiento. Y se nota en cada puto mensaje del chat, ridículo.',
  '%IQ de IQ: zona gris del ranking, tirando a oscura. Y se nota en cada puto mensaje del chat, basura.',
  'Estás calibrado bajo y con %IQ el calibrado se ha vuelto identidad. Y se nota en cada puto mensaje del chat, desperdicio.',
  'Con %IQ el dato que no encaja lo expulsas del relato. Y se nota en cada puto mensaje del chat, asco.',
  '%IQ. No es un insulto gratuito: es la lectura del número y del historial. Y se nota en cada puto mensaje del chat, cutre.',
  'Tu ritmo con %IQ es el del que opina del libro por la contraportada. Y se nota en cada puto mensaje del chat, pringado.',
  'Con %IQ la ironía del comando te resbala y el número se te queda. Y se nota en cada puto mensaje del chat, fracasado.',
  '%IQ de coeficiente: suficiente para llenar el chat, insuficiente para levantarlo. Y se nota en cada puto mensaje del chat, vergüenza.',
  'El grupo no te pone en la lista de quien aclara: %IQ explica por qué. Y se nota en cada puto mensaje del chat, joder.',
  'Con %IQ el argumento se desmonta con un tirón suave de un solo hilo. Y se nota en cada puto mensaje del chat, mierda.',
  '%IQ. Bajo de forma que ya no requiere demostración adicional. Y se nota en cada puto mensaje del chat, coño.',
  'Se te acumulan las aproximaciones: con %IQ nunca llegas al ajuste fino. Y se nota en cada puto mensaje del chat, cabrón.'
];

const MEDIO = [
  '%IQ. Joder, eres tan del montón que si te pierdes en una multitud nadie nota que falta alguien.',
  'Con %IQ tienes el coeficiente intelectual de un puto semáforo en ámbar: ni paras ni arrancas, estorbas.',
  '%IQ de IQ. La mediocridad hecha persona. Si fueras un color serías beige, cabrón, el puto beige.',
  'Hostia, %IQ. Eres tan jodidamente promedio que podrían usarte de ejemplo en un libro de texto sobre gente que no importa.',
  '%IQ. Tienes la misma chispa mental que un brick de leche semidesnatada: ni entera ni desnatada, una mierda a medias.',
  'Con %IQ eres el coño de la media exacta. Si la humanidad fuera un bocadillo, tú serías el pan sin nada dentro.',
  '%IQ de IQ. Tu cerebro funciona como un grifo de agua templada: ni fría ni caliente, una puta decepción constante.',
  'Mierda, %IQ clavado. Eres tan normal que si tu vida fuera una película sería un documental sobre secar pintura.',
  '%IQ. Tienes los cojones de ser exactamente igual que todo el mundo y encima no te da vergüenza, gilipollas.',
  'Con %IQ tu cerebro es como un menú del día de bar de carretera: cumple, pero nadie repite ni se acuerda.',
  '%IQ de IQ. Coño, eres el equivalente humano de un martes: nadie lo espera, nadie lo celebra, simplemente pasa.',
  'Hostia, %IQ. Tu capacidad mental tiene la emoción de un yogur natural sin azúcar. Existe y punto, joder.',
  '%IQ. Eres tan puñeteramente medio que si te clonaran cien veces no cambiaría ni la estadística ni el ambiente.',
  'Con %IQ piensas como folla un funcionario: cumpliendo el expediente y mirando el reloj, el puto mínimo.',
  '%IQ de IQ. Si la mediocridad pagara impuestos tú solo financiarías una autopista, cabrón.',
  'Joder, %IQ. Tu cerebro es una rotonda: das vueltas, llegas al mismo sitio y te crees que has avanzado.',
  '%IQ. Eres el NPC del grupo. Estás ahí, dices cuatro frases genéricas y nadie nota si te desconectan.',
  'Con %IQ tienes exactamente la inteligencia de un microondas: calientas lo que te meten y ya, sin puta creatividad.',
  '%IQ de IQ. Coño, la media exacta. Eres tan predecible que hasta el bot se aburre de evaluarte.',
  'Hostia, %IQ. Tienes la profundidad intelectual de un charco de meado en un aparcamiento: poco, templado y desagradable.',
  '%IQ. Tu cerebro procesa información como una impresora de los noventa: lento, ruidoso y al final sale una mierda borrosa.',
  'Con %IQ eres el puto empate a cero de la inteligencia. Nadie gana, nadie pierde, todo el mundo se va insatisfecho.',
  '%IQ de IQ. Joder, eres tan del montón que si repartiesen personalidad por IQ te tocaría una cucharada de papilla.',
  'Mierda, %IQ. Eres la versión humana de un pan de molde: blando, cuadrado y absolutamente intercambiable.',
  '%IQ. Con ese número tu cerebro es una carretera comarcal: llega a todos lados pero tardando el triple y con baches.',
  'Con %IQ tienes la agilidad mental de una puta bolsa de plástico en el viento: te mueves mucho pero no vas a ningún lado.',
  '%IQ de IQ. Hostia, eres tan normalito que hasta el algoritmo te salta porque no generas engagement ni de coña.',
  '%IQ. Tu cabeza funciona como un ascensor de dos plantas: sube, baja, y eso es todo lo que da de sí, gilipollas.',
  'Con %IQ eres el equivalente cognitivo de unas zapatillas de andar por casa: cómodo, gastado y que nadie saca a la calle.',
  '%IQ de IQ. Joder, la media clavada. Si fueras una especia serías sal, cabrón. La puta sal, lo más básico que existe.',
  'Coño, %IQ. Eres tan jodidamente estándar que si metieras el cerebro en una batidora saldría gazpacho de brick.',
  '%IQ. Tu inteligencia es como un autobús urbano: va por la misma ruta siempre, llega tarde y huele raro.',
  'Con %IQ tienes la creatividad de una pared blanca y la ambición de una alfombrilla de ratón. Hostia, qué triste.',
  '%IQ de IQ. Mierda, eres tan promedio que si buscas tu nombre en Google sale "quizás quisiste decir otro".',
  '%IQ. Tu cerebro tiene la potencia de un ventilador de mesa: mueve aire suficiente para no ahogarte y ya.',
  'Con %IQ eres el cabrón que está en el centro exacto de la campana de Gauss. El pico de la nada, coño.',
  '%IQ de IQ. Joder, tu intelecto es tan plano que podrían planchar camisas encima de tu capacidad de análisis.',
  'Hostia, %IQ. Eres la versión cognitiva de un parking en superficie: abierto, vacío y sin ningún puto interés arquitectónico.',
  '%IQ. Piensas como conduce un abuelo: despacio, sin sorpresas y cabreando a todos los que van detrás, gilipollas.',
  'Con %IQ tu cerebro es un piso de alquiler en las afueras: funcional, triste y con las paredes llenas de mierda.',
  '%IQ de IQ. Coño, la media pura. Tienes la misma gracia intelectual que una puerta cortafuegos: cumple normativa y ya.',
  'Mierda, %IQ. Tu capacidad mental es un buffet libre de hotel mediocre: hay de todo y todo sabe igual de insípido.',
  '%IQ. Eres tan jodidamente mediocre que si tu cerebro fuera un coche sería un Dacia Sandero de segunda mano.',
  'Con %IQ tienes el nivel de un cabrón que pone "persona proactiva" en el currículum y se queda tan ancho.',
  '%IQ de IQ. Hostia, tu cabeza es como un canal de TDT que nadie ve: emite las veinticuatro horas y da igual.',
  'Joder, %IQ. Eres el tipo de persona que un estadístico usaría como valor por defecto. La mierda estándar.',
  '%IQ. Tu cerebro trabaja como un lavavajillas: mete, saca, y entre medias no pasa nada que merezca contar.',
  'Con %IQ tienes la misma relevancia intelectual que un tornillo en una estantería de IKEA: necesario, pero que le den.',
  '%IQ de IQ. Coño, eres tan del promedio que si te pusieras de perfil intelectualmente desaparecerías, gilipollas.',
  'Mierda, %IQ. Tu cabeza es un piso piloto: parece que alguien vive ahí pero no hay ni un puto cepillo de dientes.',
];

const ALTO = [
  '%IQ. Mira el listo del grupo, coño. Tienes cerebro de sobra y lo usas para discutir con gilipollas en un chat.',
  'Con %IQ podrías estar forrándote y en vez de eso estás aquí leyendo las mierdas que escribe esta panda de subnormales.',
  '%IQ de IQ. Joder, eres listo de cojones y lo más grande que has hecho hoy es abrirle un mensaje a un bot.',
  'Hostia, %IQ. Tienes la cabeza de un puto ingeniero de la NASA pero la ambición de una zapatilla de estar por casa.',
  '%IQ. Eres el cabrón que podría resolver problemas importantes pero prefiere ver cómo arde el grupo. Menudo desperdicio de neuronas.',
  'Con %IQ pillas las cosas a la primera, lo cual es una putada porque te toca esperar a que el resto de imbéciles llegue.',
  '%IQ de IQ. Listo de verdad, y da igual, porque aquí dentro eso vale menos que un moco seco en una barandilla.',
  'Coño, %IQ. Tienes más capacidad que la mitad del grupo junto y la gastas en leer audios de gente que no sabe ni freír un huevo.',
  '%IQ. Eres como tener un Ferrari aparcado en un descampado lleno de mierda: impresionante pero completamente fuera de sitio.',
  'Con %IQ tu cerebro va a ciento ochenta y el grupo va en burro. Debe ser agotador fingir que te interesan estas mierdas.',
  '%IQ de IQ. Hostia, eres el tío listo de la clase que acaba trabajando en lo mismo que el tonto pero con más frustración.',
  'Joder, %IQ. Podrías haber inventado algo útil para la humanidad y has acabado midiéndote el IQ con un puto bot de WhatsApp.',
  '%IQ. Tienes la inteligencia para darte cuenta de que todo esto es una mierda y los cojones de quedarte a verla.',
  'Con %IQ eres el cabrón que ve los errores de todos y no dice nada porque explicárselo sería como enseñar álgebra a una cabra.',
  '%IQ de IQ. Listo pero en un chat de mierda. Es como tener un doctorado y usarlo para abrir botellas, gilipollas.',
  'Mierda, %IQ. Tu cerebro funciona como un puto reloj suizo y lo tienes puesto para contar las horas que pierdes aquí.',
  '%IQ. Eres el que pilla el chiste antes que nadie y tiene que esperar con cara de imbécil a que el resto se ría.',
  'Con %IQ te sobra cabeza para darte cuenta de que la mitad de las opiniones de este grupo son pura mierda de caballo.',
  '%IQ de IQ. Joder, cerebro privilegiado metido en un cuerpo que no ha hecho nada memorable con él. Qué desperdicio de coño.',
  'Hostia, %IQ. Piensas más rápido que el resto pero corres igual de poco. La cabeza te da, las piernas no, cabrón.',
  '%IQ. Eres como un cuchillo japonés cortando pan Bimbo: sobras por todas partes y lo que cortas no vale una mierda.',
  'Con %IQ podrías estar resolviendo ecuaciones y estás resolviendo si contestar o no a un mensaje con un puto emoji.',
  '%IQ de IQ. Coño, listo de verdad. Lástima que la inteligencia no cure la gilipollez social, que esa la tienes intacta.',
  'Mierda, %IQ. Tu cabeza va tres jugadas por delante y tu vida va tres jugadas por detrás. Menudo equilibrio de mierda.',
  '%IQ. Eres el cabrón más listo de un grupo lleno de imbéciles, que es como ser el más alto de una fila de enanos.',
  'Con %IQ entiendes cosas que el resto ni huele, pero te da pereza explicarlas, así que todos seguís igual de jodidos.',
  '%IQ de IQ. Joder, tienes más neuronas funcionando que el resto del chat junto y las usas para mandar stickers.',
  'Hostia, %IQ. Cerebro de cirujano y manos de albañil borracho. Porque una cosa es saber y otra es hacer algo con ello, gilipollas.',
  '%IQ. Eres listo de cojones pero la vida no da premios por eso, así que aquí estás, con los demás subnormales.',
  'Con %IQ tu cerebro tiene más potencia que el router de este grupo y aun así la conexión con la realidad se te cae cada dos por tres.',
  '%IQ de IQ. Coño, eres un puto prodigio desperdiciado. Como regar una planta de plástico: el esfuerzo está, el resultado no.',
  'Mierda, %IQ. Eres lo bastante listo para saber que deberías estar haciendo otra cosa y lo bastante gilipollas para no hacerla.',
  '%IQ. Tienes la cabeza de alguien que podría cambiar las cosas y el culo pegado al sofá como todos los demás, cabrón.',
  'Con %IQ tu cerebro procesa más que el de cualquier cabrón de este grupo y eso, aquí dentro, vale exactamente una polla.',
  '%IQ de IQ. Joder, eres el diamante en bruto que nadie va a pulir porque estás enterrado en un grupo de WhatsApp lleno de mierda.',
  'Hostia, %IQ. Inteligencia por encima de la media metida en una vida completamente por debajo de ella. Qué cosa más triste, coño.',
  '%IQ. Podrías estar publicando papers y estás publicando opiniones de mierda en un chat que nadie se va a releer jamás.',
  'Con %IQ eres el tío que ve la solución mientras los demás siguen buscando el problema. Lástima que el problema seas tú, gilipollas.',
  '%IQ de IQ. Listo y completamente inútil con ello. Como ponerle turbo a un coche sin ruedas, hostia puta.',
  'Mierda, %IQ. Tu cerebro merece algo mejor que este grupo, pero tu criterio de vida claramente no, pedazo de cabrón.',
];

const GENIO = [
  '%IQ. Joder, un puto genio atrapado en un grupo de WhatsApp. Es como meter a Einstein en una jaula de monos que se tiran mierda.',
  'Con %IQ tienes más coeficiente que cojones, porque un genio de verdad no estaría perdiendo el tiempo con estos gilipollas.',
  '%IQ de IQ. Hostia puta, superdotado de los cojones. Y con toda esa cabeza la mejor idea que has tenido hoy es hablarle a un bot.',
  'Mierda, %IQ. Tienes el cerebro de un jodido genio y la vida de un puto becario. Algo ha fallado y gordo, cabrón.',
  '%IQ. Eres el tipo más listo de un grupo lleno de subnormales. Enhorabuena, coño, menudo puto logro de mierda.',
  'Con %IQ podrías estar curando enfermedades y estás aquí, viendo cómo esta panda de imbéciles se manda memes del culo.',
  '%IQ de IQ. Joder, genio certificado. Tu cerebro vale más que todas las cabezas de este chat juntas, y eso da bastante pena de todos.',
  'Coño, %IQ. Superdotación real. Y la estás desperdiciando en un grupo donde el debate intelectual más fuerte es quién paga la cena.',
  '%IQ. Eres un puto genio encerrado en la jaula más triste del mundo: un chat donde la gente escribe "ola" sin hache.',
  'Con %IQ tu cerebro funciona como un reactor nuclear y lo usas para calentar un café con leche, gilipollas.',
  '%IQ de IQ. Hostia, superdotado del carajo. Tienes la cabeza de un premio Nobel y el historial de un cabrón cualquiera.',
  'Mierda, %IQ. Con ese cerebro podrías estar en un laboratorio y estás en un grupo donde alguien acaba de mandar un audio de siete minutos sobre nada.',
  '%IQ. Genio de los cojones. El noventa y ocho por ciento de la humanidad está por debajo de ti y aun así tu vida no se diferencia de la de ellos.',
  'Con %IQ eres la prueba viviente de que la inteligencia no sirve de una puta mierda si no haces nada con ella, pedazo de cabrón.',
  '%IQ de IQ. Joder, esa cifra da miedo. Lástima que la uses para elegir qué serie ver y no para algo que importe una polla.',
  'Coño, %IQ. Superdotado y metido en este chat voluntariamente. Es como usar un bisturí de cirujano para untar mantequilla, hostia.',
  '%IQ. Tu cerebro procesa más que el de todo el grupo junto y lo único que produce es opiniones que nadie va a leer dos veces.',
  'Con %IQ tienes la capacidad de un genio y la productividad de una mierda seca. Qué combinación más triste, cabrón.',
  '%IQ de IQ. Hostia, un puto superdotado entre nosotros. Es como encontrar un Rolex en un contenedor de basura orgánica.',
  'Mierda, %IQ. Cerebro privilegiado que ha decidido voluntariamente compartir espacio con gente que confunde "hay" con "ahí", gilipollas.',
  '%IQ. Eres un genio de los cojones y este grupo es lo más cerca que vas a estar de un estudio sociológico sobre la imbecilidad humana.',
  'Con %IQ podrías estar resolviendo los problemas del mundo y estás resolviendo si poner o no el puto visto azul, cabrón.',
  '%IQ de IQ. Joder, nivel de genio real. Y el genio ha decidido que su contribución al mundo sea calentar la silla de este chat de mierda.',
  'Coño, %IQ. Esa cabeza merece algo mejor que esta cueva de simios con wifi. Pero aquí estás, revolcándote en la mierda con todos.',
  '%IQ. Superdotado confirmado y completamente desaprovechado. Como plantar caviar en un huerto de patatas, hostia puta.',
  'Con %IQ piensas tres veces más rápido que cualquiera aquí y aun así no se te ha ocurrido largarte, pedazo de gilipollas.',
  '%IQ de IQ. Mierda, genio del copón. Tu cerebro vale una fortuna y tú lo tienes aparcado en el grupo más inútil de todo WhatsApp.',
  'Hostia, %IQ. Con esa cifra podrías haber cambiado el mundo, pero el mundo va a seguir igual de jodido porque tú estás aquí.',
  '%IQ. Eres un puto genio y nadie en este grupo se va a enterar ni le va a importar una mierda, cabrón.',
  'Con %IQ tienes el cerebro más potente de la sala y la puta sala es un chat donde alguien ha mandado un sticker de un gato. Menudo genio de los cojones.',
];

// Los tramos peyorativos se ordenan de mas duro a mas suave: el bot abre con la
// comparacion mas humillante que tiene. Los tramos altos no se tocan — ahi la
// "dureza" no aplica y reordenarlos solo mezclaria el tono sin ganar nada.
const POOLS = {
  abismo: ordenarPorDureza(ABISMO),
  bajo:   ordenarPorDureza(BAJO),
  medio:  MEDIO,
  alto:   ALTO,
  genio:  GENIO,
};

// Etiqueta corta que acompaña a la cifra, para que se lea como un informe.
const ETIQUETA = {
  abismo: 'Deficiencia severa',
  bajo:   'Por debajo de la media',
  medio:  'Media',
  alto:   'Por encima de la media',
  genio:  'Superdotación',
};

async function cmdIQ(sock, msg) {
  const jid = msg.key.remoteJid;
  const target = getTargetOrSelf(msg);

  const { clave, iq } = tirarIQ();
  const nm = `@${target.split('@')[0]}`;
  const frase = pickFresh(POOLS[clave], `${jid}|iq|${clave}`)
    .replace(/%IQ/g, String(iq))
    .replace(/\[nombre\]/g, nm);

  const text =
    `*${nm} tiene ${iq} de IQ*\n` +
    `_${ETIQUETA[clave]}_\n\n` +
    `${frase}`;

  await sock.sendMessage(jid, { text, mentions: [target] }, { quoted: msg });
}

module.exports = { cmdIQ, tirarIQ, TRAMOS, POOLS };
