const { isOwner, isAdmin, getTargetOrSelf } = require('../utils/wa');
const { pick } = require('../utils/helpers');

// Distribuciones por tier — basadas en el ROL DEL TARGET, no del sender:
//
//                    │ alto ≥70% │ medio 31-69% │ bajo ≤30%
//  ─────────────────┼───────────┼──────────────┼──────────
//  Negativo miembro │   88 %    │    8 %       │    4 %
//  Negativo admin   │   78 %    │    14 %      │    8 %
//  Negativo owner   │    3 %    │    7 %       │   90 %
//  Positivo miembro │   15 %    │    30 %      │   55 %
//  Positivo admin   │   28 %    │    35 %      │   37 %
//  Positivo owner   │   92 %    │    6 %       │    2 %
function rollPercent(goodIsHigh, targetIsAdmin, targetIsOwner) {
  const rand = Math.random();
  const hi = () => 70 + Math.floor(Math.random() * 31);
  const mid = () => 31 + Math.floor(Math.random() * 39);
  const lo = () => Math.floor(Math.random() * 31);

  if (!goodIsHigh) {
    if (targetIsOwner) {
      if (rand < 0.90) return lo();
      if (rand < 0.97) return mid();
      return hi();
    }
    if (targetIsAdmin) {
      if (rand < 0.78) return hi();
      if (rand < 0.92) return mid();
      return lo();
    }
    if (rand < 0.88) return hi();
    if (rand < 0.96) return mid();
    return lo();
  } else {
    if (targetIsOwner) {
      if (rand < 0.92) return hi();
      if (rand < 0.98) return mid();
      return lo();
    }
    if (targetIsAdmin) {
      if (rand < 0.28) return hi();
      if (rand < 0.63) return mid();
      return lo();
    }
    if (rand < 0.15) return hi();
    if (rand < 0.45) return mid();
    return lo();
  }
}

const LABELS = {

  // ===== POSITIVOS =====

  sexy: {
    name: 'sexy',
    goodIsHigh: true,
    high: [
      'Tienes una cara que la gente no puede dejar de mirar aunque no quiera. Eso no es suerte, es biología.',
      'Entras a un sitio y hay personas que pierden el hilo de lo que estaban diciendo. Eso no pasa por accidente.',
      'Tu físico genera reacciones involuntarias en quien te ve. No tienes que hacer nada para conseguirlo.',
      'Tienes el tipo de cara que los artistas copian y la gente recuerda años después sin haber hablado contigo.',
      'Tu atractivo no depende de la luz, de la ropa ni del ángulo. Está ahí siempre, y eso es lo más escaso.',
      'Eres de los que hacen que la gente revise sus estándares cuando los conoce en persona.',
      'La simetría que tienes se estudia y se ve poco. Tú la llevas de serie sin haber hecho nada para merecerla.',
      'Vistes lo que sea y conviertes la ropa en algo distinto sin que sea tu intención.',
      'Tu atractivo funciona igual en persona que en foto, y eso es una rareza real.',
      'La gente te mira y luego mira a sus parejas con una pregunta silenciosa que no van a verbalizar.',
      'Tienes lo que otros buscan en cirugías y tratamientos durante años sin llegar a conseguirlo.',
      'Hay personas que se arreglan una hora para lo que tú tienes al levantarte sin pensarlo.',
      'Tu cara tiene esa estructura que no se puede entrenar ni comprar. O se tiene o no se tiene.',
      'Eres exactamente el tipo de persona que arruina el día de alguien con solo cruzarse en la calle.',
      'Tienes el tipo de físico que hace que la gente recuerde exactamente qué llevabas cuando os conocisteis.',
      'La combinación que tienes no se fabrica ni se paga. O se tiene o no se tiene.',
      'Tu presencia física en cualquier espacio hace que ese espacio funcione diferente.',
      'Hay un motivo por el que la gente te mira dos veces. No es casualidad ni es tu imaginación.',
      'La genética invirtió en ti de forma seria y se nota sin que tengas que hacer absolutamente nada.',
      'Eres exactamente el tipo de persona que arruina relaciones estables con solo aparecer en escena.',
      'Tienes el tipo de atractivo que la gente intenta copiar y que nunca queda igual.',
      'Hay personas que llevan años en el gym intentando conseguir lo que tú tienes de serie.',
    ],
    mid: [
      'Con buena luz y el filtro correcto pasas por interesante. Fuera de eso estás en el montón exacto.',
      'Ni feo ni guapo. Exactamente el perfil que nadie recuerda dos horas después.',
      'Tu físico no es un activo ni un problema. Simplemente está ahí, sin función concreta.',
      'Con un poco de esfuerzo podrías dar mucho más. Pero no lo haces y por eso estás aquí.',
      'Tu fotogenia depende completamente del filtro y del fotógrafo. Eso ya dice bastante.',
      'Del montón. Sin defecto destacable ni virtud que compense.',
      'Hay días buenos y días malos, y nadie sabe cuál va a ser el de hoy.',
      'Potencial que no trabajas, que es casi peor que no tenerlo.',
    ],
    low: [
      'La genética no invirtió en ti y se nota en cada ángulo, con cualquier luz y sin filtros.',
      'Tu mejor ángulo no existe. Lo has buscado durante años y no está.',
      'No eres feo, eres de los que necesitan personalidad fuerte para compensar. Si eso también falla, el panorama es oscuro.',
      'Hay caras que se olvidan al instante de verlas. La tuya tiene exactamente esa cualidad.',
      'Tu físico es un argumento contra la idea de que el universo tiene diseño inteligente.',
      'Si el físico fuera requisito de entrada a algún sitio, necesitarías una dispensa escrita.',
      'La genética tomó decisiones contigo que ya son irreversibles y se ven desde lejos.',
      'Tu cara tiene el tipo de impacto que hace que la gente cambie de tema rápido.',
    ],
    extreme: [
      'Vas a arruinar muchos días sin proponértelo. Eso no todo el mundo puede decirlo.',
      'Quien acabe contigo va a tener que recordarse cada mañana la suerte que tiene.',
      'La gente coquetea contigo por inercia, sin haberlo decidido, y luego no sabe cómo explicarlo.',
      'Tienes el tipo de atractivo del que se habla cuando ya no estás en la habitación.',
      'Eres de los que se quedan en la memoria de personas que solo te vieron una vez.',
    ],
  },

  crack: {
    name: 'crack',
    goodIsHigh: true,
    high: [
      'Cuando entregas algo no hay que revisarlo. Eso en cualquier contexto es el estándar más alto.',
      'Tu nivel intimida sin que lo busques, que es la única versión del nivel que importa de verdad.',
      'La gente cuenta contigo cuando algo de verdad importa. No cuando hay margen de error.',
      'Donde otros improvisan tú ejecutas. La diferencia entre los dos es todo.',
      'Tus errores son anécdota. Tus aciertos son patrón. Eso ya lo dice todo.',
      'Llegas a sitios donde la mayoría ni aspira a llegar, y lo haces sin necesitar que nadie lo note.',
      'Tu nombre en un proyecto cambia las expectativas de lo que puede salir de él.',
      'Tienes esa fiabilidad que en cualquier mercado real tiene precio alto y escasez garantizada.',
      'La gente se fija en cómo lo haces para aprender, aunque nunca te lo digan.',
      'Tu trabajo lo defiende solo. No necesitas explicarlo ni venderlo.',
      'Lo que para otros es techo para ti es donde empieza el problema interesante.',
      'Llevas a cualquier equipo a un nivel distinto sin que te lo pidan ni lo propongas.',
      'Tu nivel en cualquier cosa que decidas hacer sube el listón de lo que los demás consideran bueno.',
      'La fiabilidad que tienes vale más que cualquier título en cualquier mercado real.',
      'Cuando apareces en algo, las expectativas de lo que puede salir cambian automáticamente.',
      'No necesitas que nadie te motive ni te recuerde lo que hay que hacer. Eso ya te separa del montón.',
      'Eres el tipo de persona al que la gente llama cuando importa de verdad, no cuando hay margen de error.',
      'Tu constancia tiene un valor que muy poca gente consigue mantener a lo largo del tiempo.',
      'La excelencia que tienes no es un estado, es un hábito. Y eso es lo más difícil de construir.',
      'Tu trabajo habla por ti antes de que tú abras la boca. Eso es lo más difícil de conseguir.',
    ],
    mid: [
      'Capacidad tienes. Ganas, no siempre. Y esa diferencia se ve en todo lo que produces.',
      'Llegas a correcto. Nunca a sobresaliente. La distancia entre los dos es completamente mental.',
      'Funcionas bien cuando quieres. El problema es que casi nunca quieres de verdad.',
      'Das lo justo para no fallar. Nunca lo que podrías dar. Eso ya es tu límite autoimpuesto.',
      'Suficiente para pasar, insuficiente para que nadie te recuerde por nada concreto.',
      'Tu nivel oscila sin razón aparente y eso ya es suficiente para que la gente no cuente contigo en serio.',
      'Tienes días buenos que hacen que la gente se pregunte dónde estás el resto del tiempo.',
      'Correcto pero no fiable. Y la fiabilidad es lo único que realmente tiene valor a largo plazo.',
    ],
    low: [
      'No tienes nivel y lo tapas con seguridad que no tiene ningún respaldo real.',
      'La brecha entre lo que crees que haces y lo que realmente haces se ve sin ningún esfuerzo.',
      'Eres el freno del equipo y lo saben todos menos tú, que sigues con el autoconcepto intacto.',
      'Cuando alguien cuenta contigo ya está calculando cuánto va a tardar en rehacer tu parte.',
      'Mediocre constante, sin un solo momento de excepción en el historial que alguien recuerde.',
      'Hay gente sin talento que trabaja el doble para compensar. Tú ni eso te has planteado.',
      'Tu curva de aprendizaje es tan plana que podría confundirse con el suelo de la habitación.',
      'Eres del tipo al que se le asignan tareas que no afectan a nada crítico. Por experiencia acumulada.',
    ],
    extreme: [
      'Lo que tú haces con facilidad otros lo persiguen toda su vida sin alcanzarlo.',
      'Eres el ejemplo que se cita cuando alguien pregunta cómo se hace bien algo.',
      'Subes el listón de cualquier cosa en la que aparezcas, sin proponértelo.',
      'Hay gente que lleva diez años intentando llegar donde tú ya estabas hace tres.',
      'Tu nivel real se ve en los días malos. En los buenos cualquiera puede parecer bueno.',
    ],
  },

  inteligencia: {
    name: 'inteligente',
    goodIsHigh: true,
    high: [
      'Tu cabeza procesa más rápido que la mayoría y cuando hablas ya llevas tres pasos de ventaja.',
      'Ves lo que otros tardan horas en ver, y cuando lo señalas ya estás en el siguiente problema.',
      'Llegas a conclusiones antes de que los demás terminen de formular la pregunta.',
      'Eres de los pocos que saben cuándo no saben. Eso es más difícil que saber.',
      'Tu forma de argumentar convence sin aplastar, y eso requiere más inteligencia que simplemente tener razón.',
      'Aprendes de todo, incluyendo lo que sale mal, y eso te pone por delante de forma constante.',
      'Conectas ideas que nadie más conecta y de ahí sale algo útil casi siempre.',
      'No solo piensas rápido, piensas bien. Los dos juntos es una combinación que escasea.',
      'La gente sale de las conversaciones contigo con algo que no traía cuando entró.',
      'Tienes la claridad que la mayoría no va a desarrollar aunque lo intente toda su vida.',
      'Cuando decides entender algo lo entiendes de verdad, no por encima como hace la mayoría.',
      'Tu silencio se interpreta como pasividad. Cuando hablas ya llevas la solución.',
      'Tienes la capacidad de ver el problema real detrás del problema que todo el mundo está mirando.',
      'Tu forma de procesar información es notablemente diferente a la de la mayoría. En positivo.',
      'Eres de los que aprenden algo una vez y lo tienen para siempre. Eso no es común.',
      'La velocidad a la que conectas ideas que nadie más conectaría es difícil de describir sin verla.',
      'Cuando hablas sobre algo que conoces bien, la gente para lo que está haciendo para escuchar.',
      'Tu inteligencia no es ruidosa. Simplemente funciona cuando hace falta.',
      'Eres de los que entienden el porqué antes que el cómo. Esa diferencia separa a los buenos de los excelentes.',
      'La gente que te conoce bien sabe que si tú ya lo pensaste, no hay mucho más que pensar.',
    ],
    mid: [
      'Inteligencia funcional para el día a día. Nada excepcional que comentar.',
      'Llegas a la conclusión correcta pero llegas tarde. Casi siempre.',
      'Tu razonamiento es lineal y la mayoría de problemas reales no lo son.',
      'Piensas bien cuando te lo propones. El problema es la frecuencia con que te lo propones.',
      'Suficiente para no quedar en evidencia. Insuficiente para resolver nada complejo.',
      'No eres lento, eres inconsistente. El resultado práctico es similar.',
      'A veces sorprendes y a veces no. El problema es que nadie sabe cuándo va a ser cuál.',
      'Tu inteligencia existe. Tu voluntad de usarla no siempre acompaña.',
    ],
    low: [
      'Tardas más en entender algo que en hacer el daño que luego hay que arreglar.',
      'Conviertes lo fácil en imposible solo con tocarlo. Eso también es un talento, aunque inverso.',
      'Preguntas lo que acaban de explicar como si llevaras diez minutos llegando, aunque llevaras ahí desde el principio.',
      'La brecha entre lo que crees que entiendes y lo que entiendes de verdad es un problema documentado.',
      'Eres el tipo que necesita que se lo expliquen con ejemplos y aun así quedan dudas.',
      'Denso en cada conversación, sin distinción de tema ni de interlocutor.',
      'Tu proceso mental en tiempo real es un espectáculo que la gente prefiere no ver.',
      'Llegas a conclusiones que nadie más sacaría porque nadie más las sacaría a propósito.',
    ],
    extreme: [
      'Tienes una forma de pensar que la mayoría no va a desarrollar nunca aunque lo intente.',
      'Dentro de diez años la gente va a recordar conversaciones contigo como de las que cambiaron algo.',
      'Tu inteligencia no es ruidosa. Simplemente funciona. Y eso es lo más difícil de conseguir.',
      'No solo piensas rápido. Piensas bien. La combinación es escasísima en cualquier contexto.',
      'Hay gente con títulos que no llega donde tú llegas con curiosidad básica y ganas reales.',
    ],
  },

  feminidad: {
    name: 'femenina',
    goodIsHigh: true,
    high: [
      'Tienes una elegancia que no se aprende en ningún sitio. O se nace con ella o no se tiene.',
      'Tu feminidad no es una construcción ni un esfuerzo. Es quien eres, y la gente lo nota antes de que hables.',
      'La forma en que te mueves y hablas tiene una gracia que muy poca gente consigue aunque lo intente.',
      'Proyectas una calidez genuina que la gente percibe antes de que hayas dicho nada.',
      'Tienes ese equilibrio entre fuerza y suavidad que define lo que es verdaderamente elegante.',
      'Tu presencia tiene una suavidad que hace que todo sea más fácil alrededor tuyo.',
      'Tu feminidad tiene solidez real. No depende del público ni del contexto ni del día.',
      'Hay personas que pasan la vida intentando proyectar lo que tú emites sin ningún esfuerzo.',
      'Tienes la elegancia que no se compra ni se aprende. La que no se va con los años.',
      'La delicadeza con la que manejas las cosas dice más de ti que cualquier cosa que puedas decir.',
      'Tu feminidad funciona igual estés arreglada que no. Eso es lo más difícil de tener.',
      'La forma en que te relacionas con los demás tiene una gracia que hace que todo fluya mejor.',
      'Tienes algo que la gente percibe sin saber nombrarlo. Y es exactamente lo que más vale.',
    ],
    mid: [
      'Tu feminidad va y viene según el día, sin coherencia ni patrón que nadie pueda seguir.',
      'A veces elegante, a veces todo lo contrario. Sin forma de saber cuál va a ser el de hoy.',
      'La elegancia te visita pero no se instala. Solo de paso.',
      'Tu feminidad depende de quién tienes delante. Eso no es feminidad, es adaptación.',
      'Hay base pero falta consistencia. Y la consistencia es lo único que construye algo real.',
      'A ratos tienes una gracia que sorprende. El problema es que no es predecible.',
    ],
    low: [
      'Tan delicada como una hormigonera a máxima potencia en un lunes de invierno.',
      'La elegancia y tú son conceptos que no han coincidido en tiempo ni en espacio documentado.',
      'Si la feminidad fuera un examen, no llegarías al primer ejercicio con los materiales correctos.',
      'Tu feminidad es una leyenda que nadie ha podido confirmar con evidencia concreta.',
      'Proyectas la suavidad de un bloque de cemento recién vertido en condiciones adversas.',
      'La gracia que no tienes no se puede fingir, y lo que intentas fingir tampoco convence a nadie.',
      'Tu elegancia existe solo en los comunicados que haces de ti misma.',
      'La delicadeza te esquiva con una consistencia que ya parece deliberada.',
    ],
    extreme: [
      'Tienes la feminidad real, la que no se menciona pero que todo el mundo nota cuando entras.',
      'Tu forma de ser tiene una elegancia que no se fabrica. La que queda cuando todo lo demás se va.',
      'La presencia que tienes se queda en la memoria de quien te conoce aunque sea brevemente.',
      'Hay personas que llevan años intentando tener lo que tú llevas de serie.',
      'Tu feminidad tiene la solidez de algo construido, no de algo puesto.',
    ],
  },

  masculinidad: {
    name: 'masculino',
    goodIsHigh: true,
    high: [
      'Tu masculinidad no necesita anunciarse porque se ve sin que hagas nada para mostrarlo.',
      'Tienes la solidez que la gente busca cuando algo de verdad importa y hay que apoyarse en alguien.',
      'Proyectas seguridad que no viene de performance ni de cargo. Viene de dentro.',
      'Tu presencia genera tranquilidad en quien te rodea. Eso no se finge ni se aprende en un fin de semana.',
      'Eres de los que actúan cuando hay que actuar, sin esperar aprobación ni momento perfecto.',
      'Tienes la firmeza que no se rompe cuando las cosas se complican. Esa es la versión que importa.',
      'La gente te da lo serio. No lo fácil, lo serio. Eso no se regala, se gana.',
      'Tu masculinidad tiene profundidad. No es decoración ni fachada que desaparece bajo presión.',
      'Eres de los que resuelven sin quejarse. Eso te separa del noventa por ciento.',
      'La templanza que tienes en los momentos difíciles es lo que te define, no los momentos fáciles.',
      'Tu carácter no sube ni baja según el contexto. Eso es lo más difícil de construir y lo más escaso.',
      'Cuando la situación se complica, eres de los que se quedan. Eso ya dice todo lo que hay que decir.',
      'La confianza que genera tu presencia no es actuación. Se construye con años de ser consistente.',
    ],
    mid: [
      'Tu masculinidad aparece cuando conviene y desaparece cuando hace falta. Exactamente al revés.',
      'Sólido en frío, inconsistente en caliente. El único problema es que en caliente es cuando importa.',
      'Tu seguridad depende de quién tienes delante. Eso no es seguridad, es actuación.',
      'A veces transmites firmeza, a veces todo lo contrario. Nadie sabe de cuál contar.',
      'Hay base pero se nota que no está construida del todo. Bajo presión real se ve la diferencia.',
      'Tu masculinidad funciona bien en los momentos fáciles. Los difíciles son otro tema.',
    ],
    low: [
      'Tu masculinidad es una historia que te cuentas a ti mismo y que nadie más se cree.',
      'Proyectas la solidez de algo que ya estaba roto antes de que empezara la prueba.',
      'Tu firmeza dura lo que dura la ausencia de presión, que en tu caso no es mucho tiempo.',
      'Cuando se complica, eres el primero en buscar la salida lateral. Y todo el mundo ya lo sabe.',
      'Tu seguridad se rompe con una pregunta directa en tono normal sin ninguna hostilidad.',
      'La testosterona en tu caso es más leyenda que evidencia documentada.',
      'Tu masculinidad es aspiracional en el peor sentido del término.',
      'Cuando alguien necesita apoyarse en alguien, no piensan en ti. Ya saben por experiencia.',
    ],
    extreme: [
      'Tienes la masculinidad real, la que no se anuncia porque no hace falta.',
      'Tu manera de manejar la presión es lo que te define. Los momentos fáciles no dicen nada de nadie.',
      'Eres de los pocos que tienen el carácter que necesitan y no el que les conviene mostrar.',
      'La solidez que tienes no se finge ni se aprende. O se construye o no está.',
      'Eres de los que la gente recuerda cuando necesita un ejemplo de cómo se hace.',
    ],
  },

  // ===== NEGATIVOS =====

  gay: {
    name: 'gay',
    goodIsHigh: false,
    high: [
      'Puto gay.',
      'Gay de manual, sin matices ni segunda lectura posible.',
      'Sal del armario ya, que llevas tanto tiempo dentro que el armario tiene tu nombre en la puerta.',
      'Eres gay, todo el mundo lo sabe, y tú eres el único que sigue fingiendo que no.',
      'Gay con todas las letras, en negrita, sin footnote posible ni argumento que lo matice.',
      'Tan gay que hasta cuando lo niegas se nota que lo estás negando con demasiado esfuerzo.',
      'Tu heterosexualidad es el chiste más largo que ha producido este grupo y sigue siendo gracioso.',
      'Llevas tanto tiempo fingiendo que ya ni tú te crees la historia que te has montado.',
      'La pluma que cargas no es ambigüedad. Es identidad. Uno de los dos aún no lo ha procesado.',
      'Tu masculinidad existe solo en el relato que haces de ti mismo y en ningún otro sitio observable.',
      'Todos en este grupo llegaron a la misma conclusión hace meses. Tú sigues en el punto de partida.',
      'Sal del armario de una vez, que dentro llevas tanto tiempo que ya le has puesto muebles y cuadros.',
      'El único misterio que sigues siendo es para ti mismo. Para el resto está clarísimo desde hace tiempo.',
      'Tan obvio que cuando entras a un sitio la gente no necesita que te presentes.',
      'Cada mensaje tuyo tiene más información sobre lo que eres que todo lo que has dicho explícitamente.',
      'Tu heterosexualidad es la obra de ficción más sostenida que has producido en toda tu vida.',
      'Llevas construyendo esa fachada tanto tiempo que ya ni recuerdas cómo eras antes de empezar.',
      'Tu masculinidad sobrevive lo justo para que puedas seguir mintiéndote cada mañana al levantarte.',
      'Gay confirmado. No hace falta ni el comunicado oficial, que ya no sorprendería a nadie.',
      'Tan gay que hasta tus propias excusas suenan gay.',
      'La cantidad de energía que inviertes en negar lo que eres podría usarse en algo útil.',
      'Cuanto más lo niegas, más se nota. Esa es la única constante en este tema.',
      'En cualquier otro contexto ya te habrían dado el comunicado de bienvenida. Aquí también.',
      'Ni tú te crees ya lo que dices de ti mismo. Eso es un avance, aunque no lo parezca todavía.',
      'Tus gestos, tu voz, tu manera de reaccionar. Todo cuenta la misma historia que llevas años negando.',
      'El armario en el que sigues metido tiene más años que tú y ya no engaña a nadie de este grupo.',
      'Lo que niegas todos los días tiene fecha de caducidad.',
      'Puto gay de closet y sin excusa a estas alturas de la película.',
    ],
    mid: [
      'No está del todo confirmado pero hay señales suficientes para que haya debate serio en el grupo.',
      'Hay algo en ti que no encaja con la versión que das de ti mismo y no es solo un día malo.',
      'El grupo tiene una teoría sobre ti que no necesitó mucho debate para formarse.',
      'A veces se nota tanto que ya ni hace falta buscarlo activamente.',
      'Bisexual en negación activa, que para efectos prácticos es lo mismo.',
      'Tu historia no cuadra del todo y la gente que te conoce ya lo sabe aunque no lo diga.',
      'Hay momentos en los que te delatas tú solo sin que nadie te haya preguntado nada.',
      'El debate sobre ti en este grupo existe, es concreto, y lleva un tiempo sin necesitar nuevas pruebas.',
      'A veces se escapa algo que no cuadra. Y cuando se escapa, no hay forma de no haberlo visto.',
      'Tu historial tiene inconsistencias que cualquiera con dos dedos de frente ya interpretó.',
    ],
    low: [
      'Hetero sin debate, sin señales, sin nada que comentar desde este ángulo.',
      'Tu masculinidad no tiene fisuras documentadas. Lo que proyectas no da lugar a segunda lectura.',
      'Tan heterosexual que el concepto se queda corto en tu caso.',
      'Las mujeres lo notan en cuanto entras. Eso no se puede fingir ni entrenar.',
      'Cero ambigüedad, cero señales, todo claro.',
      'Tu historial no tiene ningún capítulo que necesite aclaración.',
      'Lo que proyectas no da lugar a segunda lectura ni a debate de ningún tipo.',
    ],
    extreme: [
      'Nadie te lo dice a la cara para ahorrarse el drama, no porque tengan dudas sobre ti.',
      'Cuando pares de fingir vas a entender por qué todo ha sido tan costoso hasta ahora.',
      'La versión que das de ti mismo no va a sobrevivir mucho más tiempo. Y en el fondo ya lo sabes.',
      'Todo el mundo a tu alrededor ya llegó a la misma conclusión. Tú eres el último en llegar.',
      'El día que lo aceptes vas a entender por qué todo ha sido tan difícil sin necesidad de que lo sea.',
    ],
  },

  simp: {
    name: 'simp',
    goodIsHigh: false,
    high: [
      'Patético.',
      'Simp de nivel olímpico sin medalla posible.',
      'Te rebajaste tanto que ya ni tú recuerdas desde qué altura caíste.',
      'La persona más patética en lo que respecta a sus relaciones. Consistentemente.',
      'Muerto de hambre de atención de alguien que ni te considera una opción real.',
      'Le escribes al momento, le defiendes sin que te lo pida, le das sin que te dé nada. Y encima lo llamas querer.',
      'Eres el plan Z de alguien que tiene veinte opciones antes de llegar a ti.',
      'Tu dignidad lleva tanto tiempo en el suelo que ya dejaste de intentar recogerla.',
      'Estás tan metido en la friendzone que ya le has puesto paredes, cuadros y un felpudo en la entrada.',
      'Te tienen de comodín, de apoyo emocional gratuito, de opción de última hora. Tú lo llamas conexión especial.',
      'Le pides migajas de atención y cuando te las dan das las gracias. Por eso solo te tiran migajas.',
      'Tu disponibilidad total es el motivo exacto por el que no te toman en serio.',
      'Le contestas en treinta segundos, ella te contesta cuando le apetece. Y sigues sin entender la dinámica.',
      'Tanto esfuerzo invertido en alguien que te ve como un recurso disponible y no como una persona.',
      'Sigues apostando por alguien que ya te mostró exactamente cómo te valora.',
      'Aceptas el trato que tienes porque la alternativa de no tenerlo te da más miedo que el daño que te hace.',
      'Le haces favores a alguien que ni recuerda tu nombre cuando alguien te menciona en su presencia.',
      'Llevas meses, quizás años, invirtiendo tiempo, dinero y energía en alguien que no te ve ni cuando te tiene delante.',
      'Tu problema no es que nadie te quiera. Es que tú eres el primero que no se quiere lo suficiente para exigirlo.',
      'Eres de los que aguantan cualquier cosa por no perder algo que ya perdieron hace tiempo.',
      'La persona que te trata así no lo hace porque no sabe lo que hace. Lo sabe perfectamente.',
      'Estás tan acostumbrado al mal trato que cuando alguien te trata bien no sabes cómo procesarlo.',
      'Cada vez que pones el límite y no lo mantienes, el siguiente es más difícil de poner.',
      'Llevas tanto tiempo siendo el que da que ya ni recuerdas si alguna vez recibiste algo de vuelta.',
      'Te ven venir desde cien metros y ya saben exactamente qué botones pulsar.',
      'Tu forma de querer es generosa con quien no se lo merece y escasa con quien sí.',
      'Sabes exactamente lo que está pasando. Y lo permites igual. Eso ya no es ingenuidad.',
      'El tiempo que llevas así podría haberse invertido en construir algo que valiera la pena.',
    ],
    mid: [
      'Sabes exactamente lo que estás haciendo y lo haces igual. Eso ya no es inocencia.',
      'Tu dignidad existe pero tiene precio y ese precio lleva bajando un tiempo.',
      'El patrón lleva suficiente tiempo repitiéndose como para que ya no sea casualidad.',
      'A ratos te respetas y a ratos no, y los ratos que no cada vez ocupan más espacio.',
      'Conoces el límite, lo ves, y cada semana decides no moverse de donde estás.',
      'Lo que llamas amor tiene todos los síntomas de otra cosa que no quieres nombrar.',
      'No eres el peor caso, pero el camino desde donde estás es reconocible.',
      'Tu dignidad aparece cuando conviene y desaparece cuando más falta hace.',
      'Hay días en los que te respetas y días en que no. El problema es la tendencia.',
      'Lo que estás permitiendo ya dura demasiado como para que sea un momento puntual.',
    ],
    low: [
      'Sabes lo que vales y no lo regalas. Eso es más raro de lo que parece.',
      'Cuando alguien no te trata como mereces, te vas. Así funciona quien se respeta.',
      'No confundes disponibilidad con cariño ni atención con amor. Eso ya pone en ventaja.',
      'Tu dignidad tiene un precio que nadie consigue bajar con cuentos ni con promesas.',
      'Digno, sin arrastrarte, sin necesitar aprobación de nadie para saber lo que vales.',
      'Pones límites y los mantienes. Eso ya es más de lo que hace la mayoría.',
      'Sabes cuándo algo no funciona y te vas antes de que cueste más de lo que ya costó.',
    ],
    extreme: [
      'El tiempo que llevas perdiendo en esto no vuelve. Y cuando pare, eso va a ser lo primero que notes.',
      'Algún día vas a entender que nadie puede quererte si tú eres el primero que no lo hace.',
      'La persona de la que dependes no te va a salvar porque ella tampoco se ha salvado a sí misma.',
      'Llevas tanto tiempo buscando aprobación fuera que ya no sabes lo que eres cuando nadie te mira.',
      'Cuando pare todo esto, lo primero que vas a sentir es cuánto tiempo pasó mientras no lo veías.',
    ],
  },

  rata: {
    name: 'rata',
    goodIsHigh: false,
    high: [
      'Rata.',
      'Un traidor de manual.',
      'Falso de pies a cabeza.',
      'Desleal hasta en los gestos pequeños.',
      'La persona más falsa que hay en este grupo, y en cualquier grupo en el que hayas estado.',
      'Eres el tipo de persona con quien todos aprenden a ser cuidadosos después de la primera vez.',
      'La información que te dan llega filtrada porque la gente ya sabe lo que haces con ella.',
      'Traicionas cuando te conviene y luego buscas la manera de que parezca culpa del traicionado.',
      'Tu lealtad tiene precio y ese precio lo paga quien más te conviene en cada momento.',
      'Cambias de bando con más facilidad de la que cambias de opinión cuando tienes razón.',
      'Sonríes con la misma cara con la que hablas mal de alguien. Por eso ya nadie sabe cuándo eres real.',
      'Has quemado puentes que costaron años construir por beneficios que duraron semanas.',
      'Nadie te dice lo que piensa porque aprendieron que lo que dices acaba en otro sitio.',
      'Tu historial de relaciones es un patrón, no una coincidencia. Y el patrón siempre eres tú.',
      'Le mandas capturas a quien no debe, hablas mal de quien te sonríe a la cara.',
      'Tienes información de gente que confió en ti que usarías sin dudar si te beneficiara.',
      'La gente del grupo ya decidió qué nivel de información te da. No es paranoia, es experiencia acumulada.',
      'Te acercas a la gente cuando te sirve y desapareces cuando ya no les necesitas.',
      'Todo el mundo que te conoce bien ya decidió qué tipo de persona eres.',
      'Eres exactamente el tipo que hace que la gente revise lo que te cuenta antes de contarlo.',
      'Tu lealtad no es una característica, es un servicio que ofreces mientras te conviene.',
      'La gente que perdiste no fue mala suerte. Fue consecuencia directa de lo que elegiste ser.',
      'Sabes lo que haces cuando lo haces. Eso te diferencia del descuidado. Y no es para bien.',
      'Cuando te conviene ser leal, lo eres. Eso no es lealtad, es conveniencia con mejor presentación.',
      'Ser rata no es un accidente ni una circunstancia. Es una forma de relacionarse que elegiste.',
      'Tarde o temprano todos los que te rodean llegan al mismo sitio. Solo cambia el tiempo que tardan.',
      'Las relaciones que tienes ahora están construidas sobre lo que dejas ver, no sobre lo que eres.',
      'Tu historial habla por ti con más precisión que cualquier cosa que puedas decir sobre ti mismo.',
    ],
    mid: [
      'A veces eres de fiar y a veces no, y nadie sabe cuándo es cuál. Eso ya es ser poco de fiar.',
      'Traicionas cuando conviene lo suficiente como para que la gente cuide lo que te cuenta.',
      'No eres rata de manual pero tienes los reflejos. Y eso preocupa a quien te conoce bien.',
      'Tu instinto de supervivencia social a veces pisa la lealtad. Y a veces la cruza directamente.',
      'Hay gente en el grupo que ya decidió qué te cuenta. No es paranoia, es haber aprendido.',
      'A veces guardas lo que te dicen. Otras no. Y la incertidumbre ya es suficiente daño.',
      'No tienes mala intención siempre, pero los resultados son los mismos. Y eso ya importa.',
      'Hay una reputación formándose sobre ti que tú no ves pero que todos los demás ya tienen.',
      'Tu fidelidad condicional es peor que la traición directa porque nadie sabe cuándo llega.',
      'La gente que te conoce bien no te da todo. Y tú ya sabes por qué, aunque no lo digas.',
    ],
    low: [
      'Leal aunque pierda, fiel aunque no convenga. Hay gente que lo tiene y hay gente que no.',
      'Lo que te cuentan se queda contigo. Por eso te dicen cosas que no le dicen a nadie más.',
      'Tu palabra vale porque la cumples incluso cuando ya no es cómodo cumplirla.',
      'De los que dan la cara aunque haya algo que perder haciéndolo. Eso escasea.',
      'Alguien con lealtad real como la tuya se encuentra muy pocas veces en la vida.',
      'La gente confía en ti con cosas que no le diría a nadie. Eso tiene un valor enorme.',
      'Fiel por convicción, no por conveniencia. Esa diferencia lo cambia todo.',
    ],
    extreme: [
      'La soledad que viene no es mala suerte. Es la factura de lo que fuiste sembrando.',
      'Las personas que perdiste no vuelven. Y las que vengan tampoco se quedan cuando te conozcan.',
      'Cuando ya no quede nadie, vas a recordar exactamente en qué momento tomaste cada decisión que te dejó aquí.',
      'Tu forma de relacionarte tiene una fecha de caducidad. Y se está acercando.',
      'La reputación que te estás construyendo va a llegar antes que tú a cualquier sitio nuevo.',
    ],
  },

  maricon: {
    name: 'maricon',
    goodIsHigh: false,
    high: [
      'Maricón.',
      'Puto maricón de tomo y lomo.',
      'Maricón sin vuelta de hoja.',
      'Tan maricón que ya no necesita presentación en ningún contexto.',
      'La persona más maricona de este grupo, y de varios grupos adyacentes.',
      'Maricón certificado. Sin categoría de reserva posible.',
      'Tu masculinidad es una obra de teatro mal ensayada que el público lleva tiempo sabiendo que es ficción.',
      'Tan maricón que cuando entras a un sitio la gente reajusta sus expectativas en tiempo real.',
      'Tu intento de parecer masculino lleva tiempo siendo más cómico que convincente.',
      'Más pluma de la que puedes gestionar aunque quisieras, y ya dejaste de querer hace tiempo.',
      'La forma en que te mueves, hablas y reaccionas tiene una coherencia que dice más que tú.',
      'Tu masculinidad existe solo en el relato que haces de ti mismo. En ningún otro sitio observable.',
      'Llevas la pluma tan integrada que ya forma parte de tu forma de existir, no de actuar.',
      'Cada gesto tuyo es un comunicado que nadie pidió pero que todos leen exactamente igual.',
      'Cuando finges ser de otra manera se nota el esfuerzo, y ese esfuerzo ya es la respuesta.',
      'Tu manera de andar, sentarte, gesticular. Todo apunta en la misma dirección.',
      'Tienes más pluma que todo el grupo junto y aún no has procesado lo que eso implica.',
      'La fachada que mantienes cuesta más de lo que consigue y cada vez cuesta más mantenerla.',
      'Tan obvio que hasta los más despistados del grupo lo tienen claro desde hace meses.',
      'El grupo lleva tiempo con una lectura de ti que no necesitó votación para ser unánime.',
      'Más maricón que cualquier comparación que se te ocurra ponerle. Sin margen de maniobra.',
      'La cantidad de energía que inviertes en parecer lo que no eres podría servir para algo útil.',
      'Lo que se ve no se puede no ver. Y lo que se ve aquí está muy claro.',
      'Tu masculinidad tiene el nivel de autenticidad de una firma falsa en un papel oficial.',
      'Llevas construyendo esa fachada tanto tiempo que ya no sabes qué hay detrás de ella.',
      'Ser maricón no es el problema. El problema es la cantidad de energía que gastas en negarlo.',
      'Todo el mundo ya llegó al mismo sitio. El único viaje que queda es el tuyo.',
      'Tu masculinidad es aspiracional en el peor sentido del término.',
    ],
    mid: [
      'Hay momentos en que se te escapa algo que no encaja con la versión que das de ti mismo.',
      'Tu macho tiene fisuras que se ven cuando bajas la guardia, y la bajas con frecuencia.',
      'Ni muy macho ni muy maricón, pero con suficientes señales como para que haya debate.',
      'Finges que no existe algo que a ratos se ve sin que lo busques ni lo construyas.',
      'El grupo tiene tus gestos catalogados aunque no te lo hayan dicho todavía.',
      'Hay algo que no cuadra y la gente que te conoce bien ya lo tiene procesado.',
      'Tu masculinidad funciona la mitad del tiempo. El problema es qué mitad.',
      'A veces pareces una cosa, a veces la otra. El promedio ya es una respuesta.',
      'No hay confirmación pero hay suficiente para que la pregunta sea seria.',
      'Los momentos en que se nota son los que la gente recuerda. No los otros.',
    ],
    low: [
      'Tu masculinidad no se anuncia porque no hace falta. Se ve sola sin que hagas nada.',
      'Tienes la solidez que la gente busca cuando algo de verdad importa.',
      'Tan macho que genera incomodidad silenciosa en los que no pueden decir lo mismo de sí mismos.',
      'Proyectas seguridad sin buscarlo, que es la única versión que convence de verdad.',
      'Tu masculinidad no es un esfuerzo ni una actuación. Es lo que eres sin pensarlo.',
      'Cero pluma, cero debate, nada que comentar desde este ángulo.',
      'La lectura del grupo sobre ti es unánime y no da lugar a ninguna segunda lectura.',
    ],
    extreme: [
      'Nadie te lo dice a la cara porque no quieren el drama. No porque no lo vean.',
      'Llevas construyendo esa fachada tanto tiempo que ya no sabes qué hay detrás.',
      'El día que pares de fingir vas a entender por qué todo ha costado tanto hasta ahora.',
      'La distancia entre lo que eres y lo que finges ser tiene un precio que pagas todos los días.',
      'Hay personas en este grupo que te tienen más respeto del que imaginas. Solo esperan que tú llegues primero.',
    ],
  },

  friki: {
    name: 'friki',
    goodIsHigh: false,
    high: [
      'Friki de tomo y lomo.',
      'Puto friki sin redención posible.',
      'La personificación del friki que no salió nunca al mundo real.',
      'Friki de manual, con todos los elementos del catálogo completo.',
      'Tu vida cabe en una pantalla y en una estantería de plástico que nadie más valoraría.',
      'Sabes más de mundos que no existen que de la realidad en la que vives.',
      'La última vez que viviste algo memorable en el mundo real fue hace tanto que ya ni lo recuerdas.',
      'Tu vida social entera ocurre en chats con gente que no conoces y que tampoco te conoce.',
      'Has cambiado experiencias reales por contenido de consumo y ya no ves la diferencia.',
      'Tus referencias son de series y videojuegos. Las de la gente de tu alrededor son de su propia vida.',
      'Coleccionas objetos de universos ficticios mientras tu vida real acumula polvo junto a ellos.',
      'La gente de tu edad tiene relaciones, viajes, anécdotas. Tú tienes horas en Steam y una estantería.',
      'Has construido una identidad entera alrededor del consumo de entretenimiento. No hay nada más allá.',
      'Te sientes incomprendido porque nadie comparte tus intereses. El problema es que reemplazaron tu personalidad.',
      'El sol no te reconoce porque llevas años evitando el encuentro. Él tampoco te echa de menos.',
      'Tu vida es un resumen de contenido consumido, no de cosas vividas. Eso se nota cuando hablas.',
      'A los cuarenta vas a ser exactamente esto pero con más polvo en la estantería y menos excusas.',
      'La persona que podrías ser si salieras al mundo existe. Pero lleva demasiado tiempo encerrada.',
      'Cuanto más tiempo pasa, más difícil es salir y más cómodo es quedarse. Y tú ya lo sabes.',
      'El mundo real tiene fricción, incomodidad, rechazo. Por eso has elegido el que no tiene nada de eso.',
      'Estás construyendo una vida que solo funciona dentro de cuatro paredes y con conexión estable.',
      'La pantalla no te va a acompañar en los momentos que importan. Para eso necesitas personas reales.',
      'El tiempo que llevas consumiendo en lugar de viviendo no vuelve. Eso también es una elección.',
      'Algún día vas a querer algo que ninguna pantalla puede darte. Para entonces ya llevarás mucho retraso.',
      'La vida que consumes en ficción es prácticamente lo que has elegido no vivir en realidad.',
      'Friki no es solo un hobby. Es una forma de evitar la realidad que funciona hasta que no funciona.',
      'Tus amigos de internet desaparecen cuando el servidor se cae. Las personas reales no funcionan así.',
      'Hay una versión de ti que tiene curiosidad por el mundo de verdad. Lleva tiempo esperando.',
    ],
    mid: [
      'Sales lo suficiente para no ser un caso clínico, pero tus referencias dicen de dónde vienes.',
      'Friki con disimulo es lo mismo pero con hipocresía añadida encima.',
      'Tienes vida, pero la mitad la vives en sitios que no existen y con gente que no conoces.',
      'Puedes mantener una conversación normal durante un rato. Luego se nota de dónde vienen tus referencias.',
      'Friki de armario, que es igual de grave pero con más esfuerzo en negarlo.',
      'Sales, sí. Pero vuelves corriendo. Y todo el mundo sabe a qué vuelves.',
      'Tienes un pie en el mundo real y los otros tres en el que te inventaste.',
      'Tu vida tiene los elementos básicos pero los intereses te delatan cada vez que hablas.',
      'No eres el peor caso pero el camino está clarísimo desde donde estás.',
      'Friki funcional, que es como decir alcohólico que llega al trabajo. El problema sigue siendo el problema.',
    ],
    low: [
      'Tienes una vida real, con experiencias que no caben en ninguna pantalla.',
      'Sales, conoces gente, tienes anécdotas concretas que no vienen de ninguna ficción.',
      'Equilibrado, con referencias del mundo real y presencia en él cuando importa.',
      'Tu identidad no depende de ningún universo ficticio ni de lo que consumes.',
      'Vives. No solo consumes. Esa diferencia es más grande de lo que parece.',
      'Tienes vida social real, experiencias concretas y referencias del mundo en que vives.',
      'La pantalla es una herramienta para ti, no un mundo alternativo. Eso ya es mucho.',
    ],
    extreme: [
      'La pantalla te va a decepcionar en el momento más importante. Las personas también, pero al menos eso es real.',
      'Cuando llegue el momento en que no puedas ignorar lo que has dejado de vivir, ya será tarde para lo que tiene fecha.',
      'Llevas años en modo pausa esperando que llegue algo. No va a llegar hasta que salgas a buscarlo.',
      'El tiempo que no viviste no vuelve. Y llega un momento en que eso pesa.',
      'Hay cosas que solo existen fuera de donde llevas el tiempo metido. Y no pueden esperar indefinidamente.',
    ],
  },

  cerdo: {
    name: 'cerdo',
    goodIsHigh: false,
    high: [
      'Cerdo.',
      'Guarro de categoría.',
      'Cochino de manual.',
      'Guarro sin redención a la vista.',
      'La persona más asquerosa de este grupo sin competencia real.',
      'Tu higiene es un problema activo para cualquiera que comparta contigo cualquier espacio cerrado.',
      'La gente que entra a tu casa lo recuerda como una experiencia que preferiría no haber tenido.',
      'Dejas rastro en los sitios que visitas. El tipo de rastro que hace que la gente compruebe lo que tocas.',
      'Tu relación con el agua caliente y el jabón es menos frecuente de lo que cualquier civilización considera aceptable.',
      'Hueles a algo que debería tener nombre propio. La gente lo sabe y no dice nada por educación.',
      'Tu espacio dice todo lo que necesito saber sobre cómo te valoras a ti mismo.',
      'La gente que ha comido en tu casa no ha vuelto. No es coincidencia.',
      'Eres el tipo de persona que baja el nivel de comodidad de cualquier espacio que ocupa.',
      'Tu baño es un sitio al que la gente busca excusas para no entrar.',
      'Tu ropa ha estado en más situaciones de las que debería sin pasar por agua entre medias.',
      'La última vez que limpiaste a fondo fue porque no te quedó otra.',
      'Tu umbral de asco no comparte medidas con nadie más en un radio de diez metros.',
      'Tu cama tiene capas geológicas que podrían datarse si alguien quisiera.',
      'Comes como si nadie te estuviera mirando aunque haya gente mirándote.',
      'La nevera que tienes cuenta una historia de descuido activo que no tiene justificación.',
      'El nivel de higiene que tienes es el nivel de respeto que te tienes a ti mismo. Saca tus conclusiones.',
      'La gente se adapta a ti bajando sus expectativas. Eso no es normalidad, es resignación.',
      'Hay personas que no pasan a recogerte a tu casa. Ya tienes la explicación.',
      'Tu cuarto es el retrato más honesto de quién eres cuando nadie te mira.',
      'Nadie te dice nada porque es incómodo. No porque no lo piensen.',
      'Las personas que se alejan de ti por higiene no vuelven aunque mejores. Ya formaron su opinión.',
      'Tu estándar de limpieza no es bajo porque no puedes. Es bajo porque elegiste que lo sea.',
      'El cuerpo que tienes es el único que tienes. La forma en que lo tratas dice algo importante.',
    ],
    mid: [
      'Tu higiene es situacional. Te cuidas cuando tienes que causar impresión. El resto del tiempo, no.',
      'Hay días buenos y días malos, y los malos son los que la gente recuerda y menciona después.',
      'Tu nivel de limpieza depende de si tienes visita, no de cómo quieres vivir.',
      'No llegas a desastre total pero el camino desde donde estás es clarísimo.',
      'Tu higiene funciona en público. En privado es otro nivel completamente.',
      'Ni inmundo ni limpio. En el rango que hace que la gente prefiera no pensar demasiado.',
      'Hay olores que se notan y hay olores que se recuerdan. Tú produces los segundos.',
      'Tu espacio personal dice más de lo que quisieras si alguien tiene acceso a él sin previo aviso.',
    ],
    low: [
      'Limpio, sin dejar rastro en los sitios que visitas ni problema en los que te rodean.',
      'Tu higiene no es motivo de conversación, y eso significa que funciona.',
      'Presentable, cuidado, sin olor que comentar ni espacio que haya que explicar.',
      'La forma en que te tratas dice algo de cómo te valoras. En tu caso dice algo bueno.',
      'Tu nivel hace que la gente esté cómoda cerca de ti sin tener que pensarlo.',
      'Limpio y sin generar problemas al entorno. En este contexto eso ya es un mérito.',
      'No hay nada que comentar desde este ángulo. Y eso es exactamente lo que hay que conseguir.',
    ],
    extreme: [
      'La forma en que tratas tu cuerpo y tu espacio es la forma en que te tratas a ti mismo. Y eso lo ven todos.',
      'No es que seas descuidado. Es que decidiste que este es tu estándar. Y ese estándar le afecta a todos en tu radio.',
      'Cuando la gente habla de ti en tu ausencia, la higiene es uno de los primeros temas que aparece.',
      'Hay personas que te conocen bien y que aun así evitan ciertas situaciones contigo. Ya sabes por qué.',
      'La primera impresión que dejas en mucha gente no tiene nada que ver con cómo eres. Solo con cómo hueles.',
    ],
  },

  femboy: {
    name: 'femboy',
    goodIsHigh: false,
    high: [
      'Puto femboy.',
      'Femboy de manual y sin margen de interpretación.',
      'Más femboy que todos los personajes de anime juntos. Y en serio.',
      'Femboy certificado. No hay debate posible.',
      'La persona más femboy de este grupo, de la provincia y de varios países limítrofes.',
      'Tu masculinidad no se fue de vacaciones. Se fue y no dejó ni número de contacto.',
      'Llevas la purpurina en el alma y se nota en el andar, en la voz y en cada reacción involuntaria.',
      'El universo te hizo femboy y tú lo llevas con una naturalidad que ya no admite debate.',
      'Tu guardarropa, tus gestos, tu voz, tu risa. Todo cuenta la misma historia sin excepción.',
      'No hay ángulo desde el que esto se reinterprete de otra manera. La lectura es unánime.',
      'Eres el tipo de persona que se cita como ejemplo cuando alguien necesita ilustrar el concepto.',
      'Tan femboy que los personajes de anime te envidian la coherencia estética.',
      'El grupo lleva tiempo con una lectura de ti que no necesitó votación para ser unánime.',
      'Tu masculinidad sobrevive lo justo para que puedas seguir mintiéndote cada mañana.',
      'Tan femboy que hasta cuando intentas ser macho parece un papel secundario mal interpretado.',
      'Tu lado femenino no es un rasgo. Es la característica definitoria que nadie tiene que señalar.',
      'Lo que eres y lo que finges ser tienen una distancia que se ve desde lejos y desde cerca igual.',
      'Femboy de nivel clínico. No hay segunda opinión que cambie el diagnóstico.',
      'Más pluma que un evento de drag queens y menos excusa para negarlo que nadie en este grupo.',
      'Cuanto más lo niegas, más obvio se vuelve. Esa es la paradoja del caso.',
      'Tu masculinidad existe en tus comunicados y en ningún otro lugar verificable.',
      'La distancia entre lo que crees que proyectas y lo que realmente proyectas podría medirse en kilómetros.',
      'La energía que inviertes en parecer lo que no eres podría ir a construir lo que sí eres.',
      'Todo el mundo llega a la misma conclusión. Tú sigues siendo el único que no ha completado el viaje.',
      'Llevas tanto tiempo siendo femboy que ya forma parte de tu identidad aunque no lo admitas.',
      'No hay narrativa alternativa posible. Solo hay velocidades distintas para llegar a la misma conclusión.',
      'Tu existencia en este espacio generó un consenso que no necesitó que nadie lo propusiera.',
      'Hay una versión tuya que ya no tiene que esforzarse en nada. Está esperando que la dejes ser.',
    ],
    mid: [
      'Hay algo en ti que no cuadra con la versión masculina que intentas proyectar.',
      'A veces se nota y a veces no, pero cuando se nota no hay forma de no haberlo visto.',
      'Tienes gestos y reacciones que el grupo ya tiene catalogados aunque no te lo hayan dicho.',
      'Tu lado fem existe, lo sabe todo el que te conoce, y es más grande de lo que admites.',
      'Finges que no existe algo que se ve solo cuando dejas de gestionarlo activamente.',
      'Hay algo que no coincide entre lo que proyectas y lo que a veces se escapa.',
      'No es la mayoría del tiempo. Pero los momentos que se nota ya son suficientes para el grupo.',
      'Tu masculinidad tiene goteras. No es un derrumbe, pero las goteras se ven.',
      'La duda sobre ti lleva tiempo siendo más que una duda. Ya es más bien una certeza provisional.',
      'Ni confirmado ni descartado, pero hay suficientes pistas para que la gente haya elegido bando.',
    ],
    low: [
      'Masculino, sin ambigüedad, sin elementos que generen debate en ningún contexto conocido.',
      'Tu masculinidad funciona sin esfuerzo ni demostración. Eso es lo único que importa.',
      'Tan macho que no hay lectura alternativa posible ni debate que valga la pena.',
      'La lectura que el grupo tiene de ti es clara y no tiene fisuras desde ningún ángulo.',
      'Tu lado femenino no ha dado señales de vida en ningún contexto documentado.',
      'Cero femboy, cero pluma, nada que comentar desde este ángulo.',
      'Lo que proyectas no da lugar a ningún tipo de debate ni segunda interpretación.',
    ],
    extreme: [
      'Eres exactamente el tipo de ejemplo que se usa cuando alguien necesita ilustrar el concepto.',
      'Lo que eres y lo que finges ser tienen una distancia que se mide en cada conversación.',
      'Llevas tanto tiempo siendo femboy que ya ni te resulta raro, y eso es lo que lo hace definitivo.',
      'El grupo lleva tiempo esperando el momento en que pares de luchar contra lo obvio.',
      'Nadie te lo dice a la cara, pero la lectura es unánime y lleva tiempo siéndolo.',
    ],
  },

  inutil: {
    name: 'inutil',
    goodIsHigh: false,
    high: [
      'Inútil.',
      'Un inútil de categoría.',
      'Completamente inútil, sin atenuantes ni circunstancias.',
      'La persona más inútil con la que ha trabajado cualquiera que haya trabajado contigo.',
      'Inútil de manual. Consistente en eso al menos.',
      'Tu único talento demostrable es hacer el trabajo de los demás más complicado de lo que era antes.',
      'La gente que trabaja contigo aprende a rehacer tu parte antes de que tú termines la tuya.',
      'Cuando te asignan algo, todos los que te conocen están calculando el daño potencial.',
      'Eres el tipo que hace que los proyectos tarden más, cuesten más y salgan peor.',
      'Tu contribución oscila entre cero y negativa en cualquier contexto en el que te han puesto a prueba.',
      'No te piden para nada importante. No es casualidad ni injusto. Es experiencia acumulada.',
      'Has confundido estar presente con contribuir y llevas años creyendo que son lo mismo.',
      'Eres del tipo al que se asignan tareas que no afectan a nada crítico. Todos saben por qué menos tú.',
      'Tu aportación sube el tiempo de entrega, baja la calidad y aumenta el trabajo del resto.',
      'La brecha entre lo que crees que aportas y lo que realmente aportas no tiene corrección sin trabajo real.',
      'El día que alguien sea brutalmente honesto contigo sobre tu rendimiento vas a descubrir lo que todos ya saben.',
      'Cuando te vayas de un proyecto el proyecto respira. Eso es lo que construiste tú solo.',
      'Prometes, no cumples, y encima buscas la justificación. El ciclo lleva suficiente tiempo.',
      'Tu autoconcepto y tu rendimiento real son dos cosas que no han coincidido en ningún punto conocido.',
      'Estás donde estás porque la alternativa requiere esfuerzo, y el esfuerzo no es algo que hayas priorizado.',
      'La mediocridad sostenida es una elección tan activa como cualquier otra.',
      'Tu potencial real es irrelevante si no lo usas. Nadie paga por potencial.',
      'La diferencia entre lo que podrías hacer y lo que haces es una decisión que tomas todos los días.',
      'Nadie va a decirte esto a la cara. Por eso llevas tanto tiempo sin saberlo y sin cambiarlo.',
      'El comodín de "podría si quisiera" tiene fecha de caducidad. Y está vencida.',
      'Tus compañeros de trabajo hablan de ti cuando no estás. Lo que dicen no es lo que imaginas.',
      'Llevas tanto tiempo en el nivel más bajo que ya lo confundes con estar bien.',
      'La pregunta no es si puedes. La pregunta es si quieres. Y la respuesta lleva tiempo siendo la misma.',
    ],
    mid: [
      'Haces lo justo para no ser el problema visible sin llegar a ser parte de la solución.',
      'Funcionas en condiciones ideales. El problema es que las condiciones casi nunca son ideales.',
      'Tu rendimiento depende de tu estado de ánimo, y tu estado de ánimo es impredecible.',
      'Das lo mínimo para pasar sin que te echen, sin aportar nada que nadie recuerde.',
      'Tienes capacidad real que usas de forma selectiva y en los momentos equivocados.',
      'Correcto a veces, invisible la mayoría. Y la invisibilidad tiene su propio precio.',
      'No eres el problema activo pero tampoco eres la solución. Eso también es una posición.',
      'Hay días en los que funciona y días en los que no. El problema es que nadie sabe cuáles van a ser.',
      'Tu rendimiento tiene techo bajo y suelo blando. El rango en el que te mueves es pequeño.',
      'Suficiente para no ser señalado directamente. Insuficiente para que alguien te recuerde.',
    ],
    low: [
      'Capaz, confiable, sin necesitar que te lo repitan. Eso tiene valor real en cualquier contexto.',
      'Cuando algo importa, respondes. No todo el mundo puede decir eso.',
      'La gente cuenta contigo para lo que de verdad importa. Esa posición no se regala.',
      'Tu rendimiento es constante y sin sorpresas negativas. Exactamente lo que tiene precio.',
      'Cuando te asignan algo no hay plan B necesario. Eso te pone por delante de la mayoría.',
      'Fiable, competente, sin necesitar supervisión. Eso escasea más de lo que debería.',
      'La gente sabe que si tú lo tienes, está hecho. Ese nivel de confianza tiene valor.',
    ],
    extreme: [
      'La distancia entre lo que podrías ser y lo que eres es una decisión que se repite cada día.',
      'Todo el mundo que trabaja contigo tiene una opinión formada que tú desconoces y que ya no va a cambiar.',
      'Cuando te vayas de un proyecto, el proyecto va a respirar. Eso es lo que construiste.',
      'Hay una versión de ti que podría hacer cosas que valen la pena. Sigue esperando que la dejes funcionar.',
      'El día que alguien te diga la verdad sobre tu rendimiento va a ser incómodo. Y va a tener razón.',
    ],
  },
};

async function runPercent(sock, msg, key, groupMeta) {
  const jid = msg.key.remoteJid;
  const cfg = LABELS[key];
  if (!cfg) return;

  const target = getTargetOrSelf(msg);
  // El % se basa en el ROL DEL TARGET, no del sender
  const targetIsOwner = isOwner(target, false, groupMeta);
  const targetIsAdmin = isAdmin(groupMeta?.participants, target);

  const percent = rollPercent(cfg.goodIsHigh, targetIsAdmin, targetIsOwner);
  const verdict = percent >= 70 ? pick(cfg.high) : percent <= 30 ? pick(cfg.low) : pick(cfg.mid);
  const showExtreme = percent >= 70 && cfg.extreme?.length;

  const text =
    `*@${target.split('@')[0]} es ${percent}% ${cfg.name}*\n\n` +
    `${verdict}` +
    (showExtreme ? `\n\n${pick(cfg.extreme)}` : '');

  await sock.sendMessage(jid, { text, mentions: [target] }, { quoted: msg });
}

const makeCmd = (key) => (sock, msg, groupMeta) => runPercent(sock, msg, key, groupMeta);

module.exports = {
  cmdGay:           makeCmd('gay'),
  cmdSimp:          makeCmd('simp'),
  cmdHot:           makeCmd('sexy'),
  cmdRata:          makeCmd('rata'),
  cmdMaricon:       makeCmd('maricon'),
  cmdFriki:         makeCmd('friki'),
  cmdCrack:         makeCmd('crack'),
  cmdInteligencia:  makeCmd('inteligencia'),
  cmdCerdo:         makeCmd('cerdo'),
  cmdFeminidad:     makeCmd('feminidad'),
  cmdMasculinidad:  makeCmd('masculinidad'),
  cmdInutil:        makeCmd('inutil'),
  cmdFemboy:        makeCmd('femboy'),
};
