// Generic random % about someone — used by !gay, !simp, !sexy, !rata, !maricon, !friki, !crack, !capo, !listo

function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }

const LABELS = {
  gay: {
    name: 'gay',
    high: [
      'Sal del armario de una vez, todo el mundo ya lo sabe menos tu.',
      'Mas gay que un arcoiris en una sauna, y encima sin disimularlo.',
      'Nenaza redomada, hasta tus huesos son rosas.',
      'La pluma se te escapa por todos los lados, ya no hay vuelta atras.',
      'Naciste con purpurina en las venas y se nota a kilometros.',
      'Hay vecinos que aun no se enteran pero les llegara la circular.',
      'En cuanto entras en una habitacion se enciende el modo fiesta.',
      'Te delata todo, desde como caminas hasta como respiras.',
      'Mas mariquita que un campo de margaritas en mayo.',
      'Eres un faro de pluma en mitad de la noche.',
      'Si la heterosexualidad fuera un examen, tu lo suspenderias antes de empezar.',
      'Tu propio reflejo te mira y suspira de alivio porque por fin lo aceptas.',
      'Tu armario ya no existe, lo has quemado tu solo a base de purpurina.',
      'Naciste para llevar tacones aunque te hayan disfrazado de macho.',
      'Hasta tus aplicaciones del movil te delatan, una por una.',
      'Tu cuerpo se mueve antes que tu razon, y tu razon ya lo asume.',
      'Tu masculinidad no se la cree ni tu sombra.',
      'Tu manera de hablar es un comunicado oficial de pluma.',
      'Cada gesto tuyo confirma lo que tu silencio intenta negar.',
      'Eres tan gay que el sol sale a saludarte con purpurina en los rayos.',
      'No es que se te note, es que se anuncia con megafono.',
      'Tu paleta de colores no la compra un macho ni por error.',
      'Hasta tus padres ya lo asumen aunque no se atrevan a decirlo.',
      'Mas gay que un brunch un domingo de orgullo.',
      'Llevas la bandera por dentro y se transparenta cada vez que sonries.',
      'Tiene la sensibilidad estetica de quien lleva anyos viendolo claro.',
      'Tu Spotify es un mapa autobiografico que cualquiera puede descifrar.',
      'Cuando hablas, las mariposas en tu boca tienen mas estilo que tu vida entera.',
      'Tu colonia se nota a tres barrios de distancia y es siempre la misma.',
      'Tu paleta de colores no la compra un macho ni por error.',
    ],
    mid: [
      'Algo se te mueve por dentro cuando pasan tios buenos.',
      'Ni fu ni fa, pero tampoco eres muy macho.',
      'Cuando bebes algo de mas, se te nota cierta curiosidad.',
      'En ciertos angulos y con cierta luz, levantas sospechas.',
      'Hay gestos tuyos que la gente comenta cuando no estas.',
      'Bisexualidad pendiente de confirmacion oficial.',
      'Tu Spotify te delata mas que tu propio comportamiento.',
      'Una de cal y otra de arena, todavia te lo estas pensando.',
      'A veces si, a veces no, dependiendo del dia y de quien aparezca.',
      'Te falta valentia para asumirlo o para descartarlo del todo.',
      'En el grupo hay debate sobre ti, sin ironia.',
      'Tu indecision es mas evidente que cualquier respuesta.',
      'Cualquier dia te decantas y nadie se va a sorprender.',
      'Estas en esa fase donde te miras los abdominales en el espejo demasiado tiempo.',
      'Hay miradas tuyas que se quedan mas tiempo del aceptable.',
    ],
    low: [
      'Mas hetero que un toro en feria.',
      'Cero pluma, cero duda.',
      'Macho alfa de manual antiguo y polvoriento.',
      'Mas heterosexual que una ferreteria en domingo.',
      'No tienes ni la mas minima sospecha en tu curriculum.',
      'Tu masculinidad raya lo aburrido.',
      'Tan hetero que te incomodan hasta los abrazos largos.',
      'Tu mundo se reduce a futbol, cerveza y poco mas.',
      'Heterosexualidad blindada, sin grietas posibles.',
      'No hay duda en tu hoja de servicios, lastimosamente.',
    ],
    extreme: [
      'Vaya maricon, deberias salirte del grupo, nadie te quiere aca.',
      'Eres el tipo de persona del que todos hablan mal cuando sales de la sala.',
      'Nadie te lo dice a la cara pero todos piensan lo mismo de ti.',
      'Date cuenta de que sobras aqui, en serio.',
      'Tu familia ya ni pregunta por ti, algo habra.',
      'En el grupo te aguantan, no te eligen. Hay una diferencia abismal.',
      'Si manyana desaparecieras nadie te buscaria, piensalo bien.',
      'Cada vez que escribes en el grupo alguien suspira y otro silencia el chat.',
      'Eres exactamente la persona que la gente bloquea cuando se cansa de fingir.',
      'Tus mejores momentos los inventas tu mismo porque nadie mas los recuerda.',
      'La gente que dice quererte solo lo hace porque no le queda otra.',
      'Hay un motivo por el que nunca te invitan primero, y lo sabes perfectamente.',
      'Lo unico estable de tu vida es la decepcion que generas en los demas.',
      'Si pudieras verte desde fuera, tu mismo te darias de baja del grupo.',
      'Te miran y no entienden como sigues aqui, ni tu mismo lo entiendes.',
      'Tu propio reflejo te juzga cada manyana y tiene motivos.',
      'Vas perdiendo gente sin darte cuenta y cuando lo notes ya no quedara nadie.',
      'Tus padres mienten cuando les preguntan que tal te va.',
      'Hay un grupo paralelo sin ti donde se respira tranquilidad.',
      'Eres el tipo de presencia que la gente aprende a esquivar con educacion.',
    ],
  },

  simp: {
    name: 'simp',
    high: [
      'Simp de campeonato, te lamerias los zapatos por un emoji.',
      'Te pones de rodillas con solo que te miren, da pena verte.',
      'Vendes tu dignidad por un hola, eso dice mucho de ti.',
      'Caes redondo en cuanto te ponen un poco de atencion.',
      'Tu autoestima depende de un visto en WhatsApp.',
      'Te enamoras tres veces por semana, todas mal.',
      'Le escribes a la misma persona durante meses sin recibir nada a cambio.',
      'Tu telefono solo manda mensajes, nunca recibe.',
      'Eres el tipo que envia regalos a alguien que ni recuerda tu nombre.',
      'Sabes su signo, su perfume y donde estudio, ella no sabe ni que existes.',
      'Tu plan B es seguir esperando al plan A que nunca va a llegar.',
      'Le contestas a los dos segundos aunque ella tarde tres dias.',
      'Tu estrategia de seduccion consiste en estar disponible las 24 horas y eso te hace invisible.',
      'Te tomas las migajas que te tira como si fueran un banquete.',
      'Tu Instagram es un altar publico a alguien que no te quiere.',
      'Le pagas el bizum mensual y le llamas a eso amor.',
      'Le aguantas las salidas con otros mientras ensayas frases para cuando vuelva contigo.',
      'Te conformas con migajas porque no aspiras a una mesa puesta.',
      'Le defiendes incluso cuando ella ni se entera de que existes.',
      'Tu mejor cualidad segun ella es que siempre estas disponible para escucharla quejarse de otro.',
      'Aceptas la friendzone como si fuera un ascenso.',
      'Coleccionas rechazos como si fueran cromos y aun asi sigues jugando.',
      'Cuando te dice que te quiere como amigo te brillan los ojos. Eso ya es preocupante.',
      'Le mandas buenas noches todos los dias y un dia uno de los dos va a romperse.',
      'Tu autoestima cabe en una notificacion de visto.',
      'Te utilizan como bizum andante y aun das las gracias.',
      'Si te dijera salta, preguntarias desde que altura y con que sonrisa.',
      'Te crees su mejor opcion cuando solo eres la opcion de emergencia.',
      'Te has hecho amigo de su gato para tener excusa para verla.',
      'Le mandas memes a las tres de la manyana esperando que algo cambie.',
    ],
    mid: [
      'Simping controlado, pero se te nota la desesperacion.',
      'No llegas a simp total pero vas por el camino.',
      'A ratos te respetas, a ratos no, eres inconsistente.',
      'Sabes que esta mal pero no puedes evitarlo.',
      'Tu cabeza dice no, tu corazon dice si, tu cartera paga.',
      'Conoces el limite y aun asi flirteas con cruzarlo.',
      'Tienes orgullo, pero negociable.',
      'En ocasiones reaccionas y luego recaes.',
      'Vas y vienes, sin terminar de aprender la leccion.',
      'Cada dos por tres recaes en patrones que sabes que te hacen mal.',
    ],
    low: [
      'Digno. No te arrastras por nadie.',
      'Frialdad de iceberg, nadie te dobla.',
      'Sabes lo que vales y no lo regalas.',
      'Tu amor propio esta blindado, dificil tumbarte.',
      'Te respetan porque te respetas a ti mismo primero.',
      'No persigues, atraes. Esa es la clave.',
      'Cuando alguien no te valora, desapareces. Asi se hace.',
      'Tienes claro que estar solo es mejor que estar mal acompanyado.',
    ],
    extreme: [
      'Eres un felpudo con patas. Te utilizan, lo saben, y tu sigues ahi sonriendo.',
      'Date cuenta de que nadie te respeta y es completamente culpa tuya.',
      'La persona por la que babeas ni recuerda tu nombre, eso te deberia decir algo.',
      'Tan desesperado que das pena hasta a los que te odian.',
      'Llevas tanto tiempo arrastrandote que ya ni sabes como estar de pie.',
      'Hay perros con mas dignidad que tu, y los perros lamen sus propias heridas.',
      'Cuando se rian de ti a tu espalda, recuerda que te lo has ganado a pulso.',
      'Tu existencia entera depende de la aprobacion de gente que no te valora.',
      'Te ven venir desde lejos y aprovechan, porque saben que no vas a decir nada.',
      'Hasta tu propia madre se cansa de verte humillarte por personas que no merecen ni tu hora.',
      'La gente cuenta historias sobre lo patetico que eres, y se rien.',
      'No es amor, es enfermedad, y tu has decidido no curarte.',
      'Eres exactamente el ejemplo que los padres ponen a sus hijos para que no acaben asi.',
      'Te conformas con tan poco que has perdido la capacidad de aspirar a mas.',
      'Vas a llegar a viejo solo y vas a culpar a todos menos a la unica persona responsable.',
      'Tu unica relacion estable es la que tienes con el rechazo.',
      'El amor propio que no tienes te lo va a cobrar la vida con intereses.',
      'Llevas tantos rechazos acumulados que ya solo aspiras a no recibir mas, no a recibir amor.',
      'No la quieres, dependes de ella, y eso es mucho mas triste de admitir.',
      'Has confundido obsesion con amor y eso te ha costado todas tus relaciones.',
      'La gente del grupo se rie de tus mensajes y tu sigues mandandolos.',
      'Tu necesidad de aprobacion la huele cualquiera a kilometros y por eso te evitan.',
      'No vas a estar bien hasta que dejes de buscar a alguien que te salve, y no lo vas a hacer.',
      'Cada noche que duermes solo es un recordatorio de lo poco que te valoras.',
      'La persona que te gusta ya ha tomado una decision sobre ti, solo que no te la ha dicho.',
    ],
  },

  sexy: {
    name: 'sexy',
    high: [
      'Estas hecho un cromo, hay que reconocertelo.',
      'Para comerte vivo, sin cubiertos y sin remordimientos.',
      'Cuando pasas, todo el mundo gira la cabeza, lo sepas o no.',
      'Tienes ese algo que no se explica pero todos notan.',
      'Eres de los que paralizan una conversacion con solo aparecer.',
      'La genetica te debe favores, los has recibido todos juntos.',
      'Hay belleza y luego estas tu, en otra categoria.',
      'Tu sola presencia sube la temperatura de cualquier sala.',
      'Eres peligroso por lo guapo que estas, deberian avisarlo en la puerta.',
      'No tienes derecho a estar tan bien hecho, es injusto para el resto.',
      'Cuando sonries deberias cobrar entrada, en serio.',
      'Tu mirada tiene mas curriculum que la mayoria de la gente entera.',
      'Tienes presencia, no solo cara, y eso es lo dificil.',
      'En una foto de grupo, todo el mundo te mira a ti antes que al fotografo.',
      'Eres atractivo de los que dejan marca, no de los que se olvidan al rato.',
      'Tienes ese tipo de magnetismo natural que la gente paga por intentar imitar.',
      'Tu cara es de las que se quedan en la cabeza durante dias.',
      'Tienes el cuerpo que la gente pide en sus oraciones nocturnas.',
      'Pareces salido de una pelicula y de las buenas.',
      'Eres el tipo de persona que pone nervioso al entrar a una sala.',
      'Tu perfil bueno es bueno, y el malo tambien es mejor que el bueno del resto.',
      'Tienes ese aire de quien sabe que sabe, y eso es irresistible.',
      'Estas en el grupo de los privilegiados esteticos, los que con poco esfuerzo se llevan todo.',
      'Vistes cualquier cosa y la haces parecer cara y pensada.',
      'Tienes el tipo de belleza atemporal, no la de moda fugaz.',
      'La gente te recuerda anyos despues de cruzarte cinco minutos.',
      'Hay caras y luego esta la tuya, una categoria propia.',
      'Tu manera de moverte en una sala dice mas de ti que cualquier presentacion.',
      'Tienes esa combinacion de cara y actitud que muy poca gente consigue tener a la vez.',
      'La gente saca el telefono cuando pasas, aunque no te conozca.',
    ],
    mid: [
      'Tienes lo tuyo, no eres ningun cromo pero tampoco pasas desapercibido.',
      'Con buena luz y buena ropa, das bastante el pego.',
      'Vas mejorando con los anyos, hay que tener paciencia.',
      'Hay dias buenos y dias regulares, depende del espejo.',
      'No eres feo, eres del monton, que es mas dificil de digerir.',
      'Te falta un poco de gimnasio y un poco de actitud, pero hay base.',
      'Mejoraras cuando aprendas a sacarte partido.',
      'Tu estilo es discreto, eso ayuda mucho.',
      'En blanco y negro ganas, en color te la juegas.',
      'Suficiente para no pasar desapercibido, insuficiente para destacar.',
    ],
    low: [
      'La genetica no reparte igual para todos. Ese es tu caso.',
      'Hay rasgos peculiares que a alguien muy concreto le pueden gustar.',
      'No naciste con esa ventaja estetica. Hay que saber con lo que se juega.',
      'La belleza esta en el interior, y en tu caso esta muy dentro.',
      'Con la ropa adecuada y la luz correcta, algo se puede hacer.',
      'Tu mejor baza no es el fisico, trabaja lo que tienes.',
      'Compensas con simpatia lo que la naturaleza no te dio, si funciona.',
      'No te ha tocado la mejor mano en lo estetico, pero la partida sigue.',
    ],
    extreme: [
      'Tienes ese magnetismo que la gente paga para fingir, y a ti te sale gratis.',
      'Cuando entras a un sitio cambia la energia, eso no se aprende.',
      'Vas a romper corazones que ni siquiera sabes que existen.',
      'La gente te admira aunque no te lo diga, esas cosas se notan.',
      'Tienes esa belleza dificil que no todos saben apreciar, mejor asi.',
      'Eres el tipo de persona que se queda en la memoria de quien te conoce.',
      'No necesitas hacer nada para llamar la atencion, solo estar.',
      'Tu personalidad acompanya tu fisico y eso es una combinacion letal.',
      'Hay gente nacida para ser vista, y tu naciste con ese don.',
      'Quien acabe contigo va a tener mucha suerte, asegurate de elegir bien.',
      'Cuando te miras al espejo deberias estar satisfecho, hay motivos para ello.',
      'Cualquiera que te eche la vista encima ya esta pensando en ti horas despues.',
      'Tu confianza es la mitad de tu atractivo, no la pierdas nunca.',
      'La gente coquetea contigo sin darse cuenta, por inercia.',
      'Tienes la suerte de ser guapo y la inteligencia de saberlo sin abusar.',
      'Si pudieras embotellar lo que tienes, te harias rico en una semana.',
      'Hay belleza superficial y belleza real, y tu tienes las dos a la vez.',
      'Te miran y se quedan colgados sin saber por que. Eso es talento puro.',
      'Tienes esa combinacion de fisico y presencia que deja huella sin esfuerzo.',
      'La gente que te conoce entiende rapidamente por que te recuerdan tanto.',
    ],
  },

  rata: {
    name: 'rata',
    high: [
      'Rata de alcantarilla, traicionarias a tu madre por cinco euros.',
      'Judas con zapatillas, lo mas rastrero que existe.',
      'Tu deslealtad es arte. Todo el mundo en este grupo ya lo sabe.',
      'Vendes a tus amigos antes de que termine el dia.',
      'Donde hay un cuchillo por la espalda, hay un dedo tuyo apuntando.',
      'La traicion te sale natural, ni siquiera necesitas pensarla.',
      'Eres el tipo que cuenta secretos en cuanto sale de la habitacion.',
      'No tienes amigos, tienes objetivos a corto plazo.',
      'Cambias de bando con la facilidad que otros cambian de calcetines.',
      'Hueles la traicion antes que el cafe por las mananas.',
      'Te jactas de tu astucia pero todos saben que es simple maldad.',
      'No hay favor que no cobres ni confianza que no rompas.',
      'Hablas mal de la gente cinco minutos despues de abrazarla.',
      'Coleccionas secretos ajenos como municion para usar cuando convenga.',
      'Estas en cuatro grupos distintos hablando mal del resto en cada uno.',
      'Le mandas pantallazos a quien no debe, y crees que nadie se va a enterar.',
      'No tienes principios, tienes calculos.',
      'Tus alianzas duran lo que duran los beneficios que te aportan.',
      'Vendes amistades a precio de saldo en cuanto aparece algo mejor.',
      'Tu palabra no vale nada, ni siquiera para ti mismo.',
      'Sonries con la boca mientras la mente ya esta planeando el siguiente movimiento.',
      'Tu padre sabe quien eres y por eso no presume de ti.',
      'Tus amigos del grupo hablan mal de ti en otro grupo paralelo.',
    ],
    mid: [
      'Algo de rata tienes, pero no llegas al nivel de plaga todavia.',
      'Traicionas cuando conviene, que es lo peor que existe.',
      'Eres leal hasta que aparece una oferta mejor.',
      'Tienes principios moviles segun el viento del momento.',
      'A veces eres buen amigo, otras veces aparece el monstruo.',
      'No estas del todo perdido pero el camino es resbaladizo.',
      'Tienes una rata pequena dentro y esta creciendo.',
      'Algunas amistades ya te miran raro, deberias preocuparte.',
      'Hay gente que ya empieza a contarte solo verdades a medias.',
    ],
    low: [
      'Mas leal que un perro, no traicionarias ni a tu peor enemigo.',
      'Limpio como una patena.',
      'De los que dan la cara aunque pierdan.',
      'Tus amigos pueden dormir tranquilos contigo cerca.',
      'Eres de los que mueren con el secreto, raro pero admirable.',
      'Tu palabra es ley para ti, eso es valor en estos tiempos.',
      'Cuando confias en alguien lo haces hasta el fondo, sin reservas.',
    ],
    extreme: [
      'Todo el mundo en este grupo sabe que no eres de fiar, solo que nadie te lo dice.',
      'Eres el tipo de amigo que la gente va descartando con los anyos, y lo mereces.',
      'La gente no te cuenta cosas importantes porque saben que las vas a usar en tu beneficio.',
      'Hay personas que entran en tu vida y la mejoran. Tu eres de las otras.',
      'Cuando te vayas del grupo nadie va a preguntar por ti, y en el fondo ya lo sabes.',
      'Te van a abandonar uno a uno y vas a culpar al mundo cuando solo es culpa tuya.',
      'La soledad que te espera no es mala suerte, es la factura de lo que sembraste.',
      'Algun dia vas a necesitar a alguien y no va a haber nadie, ni siquiera tu propia familia.',
      'Te van a hacer exactamente lo que tu has hecho, y va a doler el doble.',
      'Tus traiciones llevan tu firma aunque tu creas que no, todos las reconocen.',
      'Cuando seas viejo y estes solo, recuerda que cada decision te trajo hasta ese sillon vacio.',
      'Hay personas que envenenan grupos enteros, y tu eres una de ellas.',
      'Te crees listo pero el unico tonto en esta ecuacion eres tu.',
      'Hasta los que te apoyan en publico te critican en privado, eso es lo que has construido.',
      'Tus hijos van a crecer escuchando que clase de persona fuiste con los demas.',
      'La sonrisa que pones cuando enganas, la gente la fotografia mentalmente para no olvidarla.',
      'Tus actos te han etiquetado para siempre, y esa etiqueta no se quita.',
      'Cuando la gente te recuerde dentro de diez anyos sera con una mueca, no con una sonrisa.',
      'No tienes red de apoyo porque tu mismo cortaste cada cable que te conectaba con alguien.',
      'Mira a tu alrededor. La gente que queda contigo es la que aun no te conoce bien.',
      'Tienes pendiente devolver tantas trampas que la vida ya esta calculando el interes.',
      'Eres ejemplo de lo que no hay que ser, y lo usan en familia para que no salgan como tu.',
    ],
  },

  maricon: {
    name: 'maricon',
    high: [
      'Maricon de tomo y lomo, y encima sin talento para disimularlo.',
      'La reina de las reinas, nadie te quita el trono de lo ridiculo.',
      'Mas pluma que un gallinero en hora punta.',
      'Naciste para llevar tacones aunque tu DNI diga otra cosa.',
      'En cuanto abres la boca cae un purpurinazo de dos kilos.',
      'No hay armario en el mundo que aguante tu pluma encerrada.',
      'Cada gesto tuyo es una declaracion involuntaria.',
      'La masculinidad te queda como un disfraz mal cosido.',
      'Tu intento de macho convence a nadie, ni a ti mismo en el espejo.',
      'Tus colegas hablan de ti sin parar cuando no estas.',
      'Tu manera de andar ya es un mensaje en clave para los entendidos.',
      'Llevas la pluma tan adentro que ya forma parte de tu esqueleto.',
      'Cuando entras a un bar, el camarero ya sabe que vas a pedir antes de que abras la boca.',
      'Hay un sticker tuyo en circulacion en otro grupo, y no es elogioso.',
      'Tu masculinidad raya lo comico, en sentido literal.',
      'Te disfrazas de macho y a la primera curva pierdes la mascara.',
      'Eres tan obvio que ya no enganas ni a los muy distraidos.',
      'Tu sola presencia es objeto de chiste en varias conversaciones distintas.',
      'Tu estilo de ropa es un comunicado oficial sin firmar.',
      'Hasta las paredes huyen del color que desprendes al andar.',
    ],
    mid: [
      'Algo de pluma hay, no te voy a mentir.',
      'Ni muy muy ni tan tan, en el limbo de la virilidad.',
      'A veces se te escapa, a veces lo controlas.',
      'En ciertas situaciones te pones nervioso y se nota a kilometros.',
      'Hay gestos que repites sin darte cuenta y todos los catalogan.',
      'Tu lucha interna es publica aunque tu no lo creas.',
      'Vas a tener que aceptarlo antes o despues, mejor antes.',
    ],
    low: [
      'Mas macho que Rambo con resaca.',
      'Testosterona a raudales, ninguna duda.',
      'Tu masculinidad es de manual antiguo, agresiva y sin matices.',
      'Heterosexualidad sin grietas, casi insoportable.',
      'Tu mundo se reduce a tres temas masculinos repetidos en bucle.',
    ],
    extreme: [
      'Vaya maricon, deberias salirte del grupo, nadie te quiere aca.',
      'Eres exactamente el tipo de persona del que la gente habla mal cuando te vas.',
      'Nadie te lo dice a la cara porque no mereces ni ese esfuerzo.',
      'Piensa cuantas personas del grupo te escribirian si desaparecieras. Piensalo bien.',
      'Hay una razon por la que siempre eres el ultimo al que avisan de los planes.',
      'La gente te soporta, no te quiere. Aprende la diferencia.',
      'En tu propia familia hablan de ti como del problema, no como del hijo.',
      'Tus padres mienten cuando les preguntan que tal te va.',
      'Vas a pasar la vida buscando un sitio donde encajar y nunca lo vas a encontrar.',
      'Hay una conversacion en el grupo donde se hablan pestes tuyas, y no eres miembro de ese grupo.',
      'La carga emocional que generas en los demas pesa mas que tu propia existencia.',
      'Te van a olvidar mas rapido de lo que te tardaron en conocer.',
      'Cuando te mueras, la mitad del grupo no se va a enterar y la otra mitad no va a llorar.',
      'Tu telefono no suena nunca y eso ya deberia decirte algo, pero no escuchas.',
      'Las conversaciones del grupo mejoran cuando no estas, y todos lo notan menos tu.',
      'Cuando alguien te elimina de un chat, no le tiembla el pulso ni un segundo.',
      'Hay un motivo por el que las relaciones se te rompen tan rapido, y eres tu.',
      'Tu propia sombra preferiria estar con cualquier otra persona si pudiera elegir.',
      'Eres el tipo de persona del que la gente se libera, no del que se enamora.',
      'Cuando faltes en una reunion, suspirarian de alivio si no fueran tan educados.',
      'Eres ese amigo del que todos prefieren no acordarse.',
      'Tus cumpleanyos los celebras tu solo porque ya nadie se acuerda de organizarte uno.',
      'Has confundido tu cabezoneria con personalidad, pero la gente solo ve la primera.',
    ],
  },

  friki: {
    name: 'friki',
    high: [
      'Friki supremo, tu cueva huele a fracaso social y pizza fria.',
      'Eres el senyor de los frikis, el elegido por nadie.',
      'Tan friki que hasta los demas frikis te miran raro en los foros.',
      'Tu vida social entera cabe en una pantalla de seis pulgadas.',
      'Sabes mas de personajes ficticios que de personas reales.',
      'Tu Steam tiene mas horas que tu trabajo, tu colegio y tu vida juntos.',
      'El sol te quema porque ya no te reconoce.',
      'Tus conversaciones empiezan con jerga que nadie entiende.',
      'Tu camiseta del videojuego favorito ya forma parte de tu piel.',
      'No tienes amigos, tienes guildmates.',
      'La ultima vez que viste el cielo fue por accidente.',
      'Tu cuarto tiene mas poster que paredes a estas alturas.',
      'Coleccionas figuritas que ningun adulto deberia tener en exposicion.',
      'Tu vida amorosa se reduce a un waifu y dos personajes secundarios.',
      'Tu padre ya no sabe en que invertir esperanza, contigo se rinde.',
      'Hablas de lore de un anime a la primera oportunidad que te dan.',
      'La discusion mas importante de tu semana fue sobre un personaje ficticio.',
      'Llevas tantas horas en pantalla que tus ojos ya no enfocan la realidad.',
      'Tus pijamas tienen mas personajes ficticios que tu vida personajes reales.',
      'Tu casa es un templo a marcas que ningun adulto reconoce.',
    ],
    mid: [
      'Friki moderado, sales a la calle de vez en cuando, lo cual ya es algo.',
      'Friki con disimulo, pero se nota en cuanto abres la boca.',
      'Tienes referencias que nadie pilla pero te las guardas, gracias por eso.',
      'A ratos eres friki, a ratos persona, es complicado.',
      'Sales del cuarto los fines de semana, hay esperanza.',
      'Tu carpeta de descargas y tu carpeta de recuerdos pesan parecido.',
    ],
    low: [
      'Cero raro, lo mas normal del grupo.',
      'Social y presentable, que aburrido.',
      'Te mueves bien en cualquier ambiente, eso es un don.',
      'Tu vida es tan equilibrada que casi suena sospechoso.',
      'Pasas por persona promedio y eso ya es un exito en este grupo.',
    ],
    extreme: [
      'Llevas tanto tiempo hablando con pantallas que ya no sabes como hablar con personas.',
      'Hay un mundo fuera de tu habitacion y lleva anyos sin verte.',
      'La ultima vez que alguien te llamo para salir fue porque se habian equivocado de numero.',
      'Tu historial de busqueda dice mas de ti que cualquier cosa que puedas contarme.',
      'Tu vida real es tan pobre que has tenido que construirte otras en pantallas.',
      'Llevas anyos coleccionando trastos en lugar de coleccionar experiencias.',
      'Cuando salgas de casa por ultima vez, va a ser para mudarte a un sitio peor.',
      'Tus padres ya han renunciado a que tengas pareja, hijos o vida.',
      'Si manyana te pasara algo, lo encontrarian tres dias despues por el olor.',
      'Eres el primer fracaso documentado de tu arbol genealogico, y lo llevas con orgullo.',
      'Tu personalidad esta hecha de retales de series, no tienes nada propio.',
      'Sabes los datos de personajes ficticios y no sabes el cumpleanyos de tu madre.',
      'Confundes pasion con obsesion y soledad con concentracion.',
      'No tienes recuerdos propios, tienes referencias.',
      'Tu cuarto es el unico testigo de tu existencia, y eso es lo mas triste de todo.',
      'A los cuarenta vas a seguir igual, en el mismo cuarto, con los mismos posters.',
      'Vas a llegar a viejo sin haber sentido nada real, todo simulado en pantalla.',
      'Tus amigos online no van a venir a tu entierro, eso te lo aseguro.',
      'Cuando te mueras vas a darte cuenta de todo lo que no viviste, pero ya sera tarde.',
      'Eres el tipo de persona cuya ausencia en los planes nadie nota hasta que apareces.',
    ],
  },

  crack: {
    name: 'crack',
    high: [
      'Tienes un nivel que pocos alcanzan aunque lleven anyos intentandolo.',
      'Cuando haces algo, el resultado habla antes de que abras la boca.',
      'Eres de los que no necesitan explicar lo que saben, se ve solo.',
      'La gente te observa cuando trabajas porque intenta aprender algo.',
      'Tienes mas talento natural que la mayoria acumula en toda su vida.',
      'Cada vez que apareces en una sala, el nivel de esa sala sube.',
      'Hay gente que estudia anyos para hacer lo que tu haces por instinto.',
      'Eres el tipo de persona que hace que el resto se esfuerce mas.',
      'Lo que para otros es dificil, para ti es el punto de partida.',
      'Tienes ese dominio que solo dan los anyos, pero sin necesitar los anyos.',
      'La diferencia entre tu y los demas es visible antes de empezar.',
      'No finges que sabes, sabes. Hay una diferencia enorme y se nota.',
      'Donde otros improvisan, tu ejecutas. Esa distancia es la que importa.',
      'Tienes nivel para estar en conversaciones a las que pocos son invitados.',
      'Eres de los que hacen que un equipo funcione sin pedir protagonismo.',
      'Tu habilidad intimida sin que lo busques, y eso es el nivel real.',
      'Tienes una precision en lo que haces que delata anyos de practica o un don claro.',
      'La gente se fija en ti para saber como se hace bien algo.',
      'Tus errores son anecdota, tus aciertos son patron.',
      'Llegas a sitios donde otros ni aspiran, y lo haces sin drama.',
      'Tu talento tiene solidez, no es suerte ni puntual.',
      'Lo que haces bien, lo haces muy bien. La diferencia reside en eso.',
      'No tienes techo visible todavia, y eso ya lo dice todo.',
      'Cuando terminas algo, el resultado habla solo sin que expliques nada.',
      'Eres de los que mejoran el nivel de cualquier sitio en el que estan.',
    ],
    mid: [
      'Tienes capacidad pero no la explotas, y eso duele verlo.',
      'Llegas, no sobresales. Falta el paso siguiente.',
      'Suficiente para no fallar, insuficiente para destacar.',
      'Hay potencial real, pero sigue sin materializarse.',
      'Haces las cosas bien cuando quieres, el problema es que no siempre quieres.',
      'Correcto sin mas, lo cual es lo mas mediocre que puedes ser siendo capaz.',
      'Tienes rachas buenas seguidas de baches sin motivo aparente.',
      'A veces sorprendes, la mayoria de veces no.',
      'Con mas constancia serias diferente, pero la constancia falla.',
      'Das lo justo, nunca lo que podrias dar.',
      'Tu nivel oscila, y eso impide que la gente cuente contigo de verdad.',
      'Apuntas a crack y llegas a correcto. La distancia es mental, no de capacidad.',
    ],
    low: [
      'No tienes nivel y lo intentas esconder, pero se nota siempre.',
      'Mediocre de manual, ni siquiera llega a honroso.',
      'La brecha entre lo que crees que haces y lo que haces es abismal.',
      'Eres el freno del equipo, siempre. Lo saben todos menos tu.',
      'Tu aportacion al grupo es neutra en el mejor de los casos.',
      'Nulas expectativas y aun asi consigues decepcionar.',
      'Hay personas que nacen sin ese talento y trabajan el doble. Tu ni eso.',
      'Cuando alguien cuenta contigo, ya esta asumiendo que va a tener que rehacer el trabajo.',
    ],
    extreme: [
      'Eres de los que no necesitan que nadie los presente, el trabajo lo hace solo.',
      'Hay gente que lleva anyos intentando llegar donde tu ya estas.',
      'Tienes un nivel que la gente comenta cuando no estas presente.',
      'Cada vez que haces algo bien hecho, estableces el estandar para los demas.',
      'Eres el tipo de persona que los equipos recuerdan como referencia.',
      'Tu dominio no intimida, fascina. Y eso es mas valioso.',
      'Hay razones concretas por las que la gente te busca cuando necesita que algo salga bien.',
      'Lo que haces con facilidad, otros lo persiguen toda su vida sin alcanzarlo.',
      'Tienes el nivel que mucha gente simula tener en el curriculum.',
      'Eres el ejemplo que se pone cuando alguien pregunta como se hace bien.',
      'Tu talento no se improvisa ni se compra, y eso ya lo dice todo.',
      'Cuando pones el nombre, la gente ya espera calidad. Eso es una reputacion ganada.',
      'Hay gente que te observa para aprender algo, aunque nunca te lo digan.',
      'Lo que para otros es techo, para ti es el punto donde empiezas a interesarte.',
      'Tienes ese equilibrio entre talento y trabajo que produce cosas reales.',
      'Eres de los que suben el liston solo con aparecer.',
      'La diferencia entre ti y el resto no se ve en los dias buenos, se ve en los malos.',
      'Cuando te propones algo, el resultado llega. Esa fiabilidad tiene un precio alto.',
      'No todo el mundo puede decir que tiene un nivel real. Tu puedes.',
      'Eres de los que dentro de diez anyos la gente va a recordar por lo que hizo.',
    ],
  },

  inteligencia: {
    name: 'inteligente',
    high: [
      'Tu cabeza procesa rapido lo que a otros les cuesta dias entender.',
      'Tienes ese tipo de inteligencia que se nota en como haces las preguntas, no solo en las respuestas.',
      'Llegas a conclusiones antes de que los demas terminen de formular el problema.',
      'Tu analisis no tiene prisa pero llega primero, eso es eficiencia real.',
      'Hay gente lista y hay gente aguda. Tu eres las dos cosas al mismo tiempo.',
      'Ves los patrones donde otros solo ven datos sueltos.',
      'Tu intuicion tiene base, no es suerte, es razonamiento rapido.',
      'Cuando algo se complica, tu cabeza se acelera en lugar de bloquearse.',
      'Tienes la capacidad de simplificar lo complejo sin perder lo importante.',
      'La gente te busca para que les expliques cosas porque lo haces mejor que nadie.',
      'Tu memoria y tu razonamiento trabajan juntos de una manera que no es comun.',
      'Antes de hablar ya sabes donde va a terminar la conversacion.',
      'Resuelves problemas con recursos que otros ni consideran como opcion.',
      'Tienes la clase de mente que aprende de todo, incluido lo que no parece util.',
      'Tu criterio tiene solidez porque lo construyes con logica, no con costumbre.',
      'Cuando entras en un debate, el nivel del debate sube involuntariamente.',
      'Lees entre lineas donde otros no ven ni las lineas.',
      'Aprendes rapido, retienes bien y conectas ideas que parecen no tener relacion.',
      'Eres de los pocos que saben cuando no saben, que es la primera forma de inteligencia real.',
      'Tienes la razon con mas frecuencia de la que te reconocen, y lo aceptas sin drama.',
      'Tu forma de argumentar no aplasta, convence. Eso es inteligencia social aplicada.',
      'Cuando alguien tiene que elegir a quien consultar, terminan buscandote.',
      'Tienes una mente que trabaja en silencio y en profundidad.',
      'Tu capacidad de adaptacion mental es lo que te diferencia de gente igualmente aplicada.',
      'Eres de los que pueden estar equivocados y aprender del error en tiempo real.',
    ],
    mid: [
      'Inteligencia normal, nada que descubrir por ahora.',
      'Piensas bien cuando te lo propones, el problema es que no siempre te lo propones.',
      'Funcional, no brillante. Hay una diferencia y se nota.',
      'Llegas a la conclusion correcta, pero tarde.',
      'Resuelves lo basico sin problemas, lo complejo te cuesta mas de lo normal.',
      'Tu razonamiento es correcto pero lento, eso te pone en desventaja.',
      'Suficiente para no equivocarte en lo obvio, insuficiente para destacar en lo dificil.',
      'Tienes momentos de claridad seguidos de momentos de confusion innecesaria.',
      'Aprendes, pero necesitas mas tiempo y mas repeticiones que la media.',
      'No eres tonto, pero tampoco eres el que resuelve el problema primero.',
      'Tu inteligencia es practica, no estrategica. Util en lo inmediato, limitada en lo largo.',
      'Piensas bien pero en linea recta, y la mayoria de los problemas no son lineales.',
    ],
    low: [
      'Denso como una pared de cemento en cada conversacion.',
      'Tardas en entender lo que ya explicaron dos veces.',
      'La brecha entre lo que crees que entiendes y lo que entiendes de verdad es considerable.',
      'No eres el que resuelve el problema, eres el que lo complica sin querer.',
      'Cuando la conversacion sube de nivel, te quedas en el acceso.',
      'Tu velocidad de razonamiento no es una virtud, es un obstaculo para el grupo.',
      'Preguntas cosas que acaban de explicar como si hubieras estado en otra habitacion.',
      'Tienes la capacidad de convertir algo sencillo en algo imposible de entender.',
    ],
    extreme: [
      'Tienes una forma de pensar que la mayoria de la gente no va a alcanzar aunque lo intente.',
      'Eres de los que ven la solucion antes de que los demas terminen de leer el problema.',
      'Tu cabeza trabaja en un nivel que intimida a quien se fija en ella de verdad.',
      'La gente sale de las conversaciones contigo con algo que no tenia antes. Eso es valor real.',
      'Tienes inteligencia y sabes como no abusar de ella, que es lo mas dificil.',
      'Cuando razonas en voz alta, la gente toma notas aunque no te lo digan.',
      'Hay gente con titulos que no llega a donde llegas tu con curiosidad.',
      'Tu mente conecta cosas que parecen no tener relacion y produce algo util con eso.',
      'Eres de los que la gente cita cuando quiere dar un argumento solido.',
      'No solo piensas rapido, piensas bien. La combinacion es escasa.',
      'Tu capacidad de analisis es una ventaja competitiva que vas a usar toda la vida.',
      'Aprendes de cualquier experiencia, incluidas las malas. Eso te distancia del resto.',
      'Tienes el tipo de mente que los problemas dificiles buscan para resolverse.',
      'La gente confunde tu silencio con pasividad. Cuando hablas, ya llevas ventaja.',
      'Eres de los que llegan a conclusiones correctas por caminos que otros ni consideraron.',
      'Tu inteligencia no es ruidosa ni necesita demostrarse, simplemente funciona y se nota.',
      'Tienes una claridad mental que la mayoria no va a desarrollar en toda su vida.',
      'Cuando decides aprender algo, lo aprendes de verdad, no por encima.',
      'Eres exactamente el tipo de persona inteligente que no necesita que nadie se lo confirme.',
      'Dentro de diez anyos la gente va a recordar conversaciones contigo como de las que les cambiaron algo.',
    ],
  },

  cerdo: {
    name: 'cerdo',
    high: [
      'Cerdo de manual, tu higiene es un insulto a los sentidos.',
      'Comes con las manos y luego te las limpias en el pantalon, y encima lo normalizas.',
      'Tu cuarto es un vertedero con wifi.',
      'Has convertido la mugre en un estilo de vida y lo llevas con orgullo.',
      'Hueles a algo que no deberia tener nombre.',
      'Tu ropa lleva dias encima y tu cuerpo lleva mas sin agua.',
      'La gente se aparta cuando te sientas y tu crees que es porque les caes mal.',
      'Dejas rastro de porqueria en cualquier lugar que tocas.',
      'Eres el tipo de persona que no lava los platos hasta que el moho ya tiene nombre.',
      'No distingues entre suelo y papelera, todo es lo mismo para ti.',
      'Tu bano es una escena de crimen biologico.',
      'Tu cama tiene capas arqueologicas de mugre que podrian datarse.',
      'Comes lo que cae al suelo y encima calculas los cinco segundos.',
      'El olor que dejas en los sitios persiste horas despues de que te hayas ido.',
      'No tienes normas de higiene, tienes ausencia total de ellas.',
      'Tus habitos alimenticios son un insulto a cualquier animal omnivoro.',
      'La basura de tu cuarto ya tiene ecosistema propio.',
      'Te sudas y lo dejas secar sin ducharte, como si fuera un plan.',
      'Eres el tipo de inquilino del que los caseros hablan anos despues con pesadillas.',
      'Tu nevera es una novela de terror biologico con capitulos por fecha de caducidad.',
    ],
    mid: [
      'Algo de cerdo hay, no te voy a mentir.',
      'Tu higiene es negociable segun el dia, y hay dias muy malos.',
      'No llegas a desastre total pero el camino esta trazado.',
      'Hay momentos en los que te cuidas, son la excepcion.',
      'Vives en el limite entre presentable y alarmante.',
      'A veces te duchas, a veces no, y se nota la diferencia.',
      'Tu nivel de orden depende de si tienes visita, no de criterio propio.',
      'No eres un cerdo completo, eres un cerdo con dias buenos.',
      'Tu cocina cuenta una historia que no quieres que nadie lea.',
      'Descuidas lo basico con una frecuencia que empieza a definirte.',
    ],
    low: [
      'Limpio y ordenado, eso ya dice algo en este grupo.',
      'Tu higiene no da problemas a nadie, lo cual es lo minimo pero no todos lo logran.',
      'Te cuidas lo suficiente para no generar quejas a tu alrededor.',
      'Presentable, sin alardes, pero presentable.',
      'Tienes el orden basico que muchos no consiguen mantener.',
      'Nada que objetar en lo higienico, y eso en este grupo ya es merito.',
    ],
    extreme: [
      'Eres un cerdo clinico, el tipo de persona que baja el nivel de cualquier espacio que habita.',
      'La gente que ha estado en tu casa habla de ello como de una experiencia traumatica.',
      'Tu nivel de suciedad es una declaracion de intenciones sobre como te valoras.',
      'No es que seas desorganizado, es que has renunciado activamente a la higiene.',
      'Hay animales con mas decoro que tu en su propio habitat.',
      'El asco que generas no es accidental, es estructural, va contigo a todos lados.',
      'La gente que te quiere te lo dice con carino: eres un cerdo, y no es un insulto, es un diagnostico.',
      'Tu suciedad no afecta solo a ti, afecta a cualquiera que comparta espacio contigo.',
      'Hay un nivel de mugre que ya no es descuido, es agresion pasiva al entorno, y tu lo has alcanzado.',
      'Cuando te vayas de un sitio, el sitio necesita recuperarse.',
      'Eres el tipo de persona con quien nadie quiere compartir piso, y lo saben antes de conocerte bien.',
      'Tu relacion con la higiene es hostil, no es pereza, es enemistad declarada.',
      'La suciedad que normalizas dice mas de ti que cualquier cosa que puedas contarme.',
      'Si pudieras verte desde fuera te darias asco incluso a ti mismo, y eso es mucho decir.',
      'Eres exactamente el tipo de persona cuya presencia baja la calidad de vida de los que te rodean.',
    ],
  },
};

  feminidad: {
    name: 'femenina',
    high: [
      'Tienes una elegancia que no se aprende, o se nace con ella o no se tiene.',
      'Tu feminidad no es performance, es quien eres, y se nota en cada detalle.',
      'Hay personas que intentan proyectar lo que tu transmites sin esfuerzo.',
      'Tienes ese tipo de gracia que la gente nota antes de que abras la boca.',
      'Tu presencia tiene una suavidad que no todo el mundo sabe mantener.',
      'La forma en que te mueves y hablas tiene una elegancia que pocas personas consiguen.',
      'Tienes esa feminidad solida que no necesita demostrarse constantemente.',
      'Irradias una calidez y una delicadeza que la gente agradece sin decirlo.',
      'Hay una sofisticacion en ti que no viene de la ropa sino de adentro.',
      'Tu feminidad no es debilidad, es precision. Y eso intimida a quien sabe verlo.',
      'Tienes una presencia que llena cualquier espacio sin esfuerzo.',
      'La delicadeza que proyectas no es estudiada, es natural, y se nota.',
      'Eres de las pocas personas que tienen elegancia de verdad, no la de aparentar.',
      'Tu manera de tratar a la gente tiene una ternura que muy poca gente conserva.',
      'Tienes ese equilibrio entre fuerza y suavidad que define la feminidad real.',
      'La gente que te conoce nota rapidamente esa gracia que llevas sin intentarlo.',
      'Hay una calidez en ti que hace que la gente quiera estar cerca sin saber exactamente por que.',
      'Tu feminidad es de las que dejan huella, no de las que se olvidan a los cinco minutos.',
      'La suavidad con la que manejas las cosas dice mas de ti que cualquier presentacion.',
      'Tienes esa combinacion de belleza interior y elegancia exterior que es muy dificil de encontrar.',
    ],
    mid: [
      'Tu feminidad es intermitente, aparece y desaparece segun el dia y el humor.',
      'Hay momentos de gracia y momentos de brusquedad que se contradicen entre si.',
      'Ni muy delicada ni muy tosca, en un termino medio que no destaca.',
      'Tienes potencial de elegancia pero no lo trabajas con constancia.',
      'A veces proyectas suavidad, a veces todo lo contrario. Es inconsistente.',
      'Tu feminidad es situacional, depende de quien este delante.',
      'Tienes dias en los que te comportas con elegancia y dias que contradicen todo eso.',
      'Regular, sin mas. Ni defecto ni virtud clara en este aspecto.',
      'La elegancia te visita de vez en cuando pero no se instala.',
      'Hay base, pero sin trabajarla no llega a ninguna parte.',
    ],
    low: [
      'Tan femenina como un bloque de cemento en diciembre.',
      'Tu gracia y tu delicadeza brillan por su ausencia, y no de forma sutil.',
      'La elegancia te esquiva como si supiera que vienes y tomara otro camino.',
      'Tienes los modales de alguien criado en una obra y lo llevas con orgullo.',
      'Tu feminidad es un mito que nadie en este grupo ha podido confirmar.',
      'La suavidad en ti es una leyenda urbana, como el yeti pero menos creible.',
      'Si la delicadeza fuera un examen, tus resultados serian un insulto al examinador.',
      'Proyectas la feminidad de una excavadora a plena velocidad, y no en el buen sentido.',
    ],
    extreme: [
      'Tienes una feminidad genuina que la mayoria de la gente no va a desarrollar aunque lo intente.',
      'Tu forma de ser tiene una elegancia real que no se aprende ni se compra.',
      'La delicadeza que tienes es de las que envejecen bien, no se va con los anos.',
      'Tienes ese tipo de presencia que la gente recuerda sin saber exactamente por que.',
      'Tu elegancia no depende del contexto, funciona siempre y en cualquier sitio.',
      'Eres de las pocas personas que tienen feminidad de verdad, no la de aparentar para la camara.',
      'La calidez que proyectas es real y la gente lo percibe antes de que digas nada.',
      'Tu manera de estar en el mundo tiene una suavidad que hace que todo sea mas facil a tu alrededor.',
      'Tienes la clase de feminidad que no se menciona pero que todo el mundo nota cuando entras.',
      'Hay personas que pasan la vida intentando tener lo que tu tienes de manera natural.',
      'Tu presencia femenina es de las que se quedan en la memoria de quien te conoce.',
      'La gracia con la que manejas las cosas delata una inteligencia emocional que pocas personas tienen.',
      'Tienes esa combinacion de elegancia y caracter que es lo mas dificil de encontrar.',
      'La gente a tu alrededor se comporta mejor cuando estas cerca, aunque no sepan por que.',
      'Eres exactamente el tipo de persona que eleva el nivel de cualquier espacio que habita.',
    ],
  },

  masculinidad: {
    name: 'masculino',
    high: [
      'Tu masculinidad no necesita demostrarse, se siente cuando entras a un sitio.',
      'Tienes esa solidez que la gente busca en alguien en quien apoyarse.',
      'Proyectas una seguridad que no viene del fisico sino de quien eres por dentro.',
      'Tu presencia genera tranquilidad en las personas que te rodean, y eso es poder real.',
      'Tienes el tipo de caracter que la gente respeta sin que nadie le explique por que.',
      'Tu masculinidad es de las que no necesita ruido para hacerse notar.',
      'Eres de los que resuelven sin quejarse, y eso te diferencia de la mayoria.',
      'Tienes esa fortaleza interior que la gente percibe antes de que hagas nada.',
      'La firmeza con la que tomas las cosas dice mucho de lo que hay dentro.',
      'Tu masculinidad no es agresiva ni ruidosa, es solida. Esa es la version real.',
      'Tienes una templanza que muy poca gente mantiene cuando las cosas se complican.',
      'La gente confia en ti para las cosas serias, y eso no se gana facilmente.',
      'Eres de los que actuan cuando hay que actuar, sin esperar que alguien les diga que lo hagan.',
      'Tu presencia en un grupo lo estabiliza, aunque no lo busques conscientemente.',
      'Tienes ese nivel de seguridad en ti mismo que la gente nota aunque no lo nombre.',
      'La madurez con la que manejas las situaciones dificiles no es comun.',
      'Eres de los que no necesitan validacion externa para saber lo que valen.',
      'Tu masculinidad tiene profundidad, no es superficial ni de fachada.',
      'La forma en que tratas a la gente que te importa dice mucho de tu caracter real.',
      'Tienes esa combinacion de fuerza y control que define la masculinidad que no envejece.',
    ],
    mid: [
      'Tu masculinidad es inconsistente, aparece cuando conviene y desaparece cuando se necesita.',
      'Tienes momentos de firmeza seguidos de momentos de debilidad que los contradicen.',
      'Hay potencial, pero sin trabajarlo no pasa de promesa sin cumplir.',
      'Tu seguridad en ti mismo depende demasiado del contexto y de quien este delante.',
      'A veces solido, a veces inestable. La gente no sabe con cual de los dos contar.',
      'Regular, sin mas. Ni defecto notable ni virtud que destacar.',
      'Tu masculinidad es de las que van y vienen segun el estado de animo.',
      'Con mas consistencia podrias ser diferente, pero la consistencia falla cuando importa.',
      'Tienes la base pero no la estructura, y sin estructura no se sostiene nada.',
      'Proyectas mas de lo que eres, y la gente que te conoce bien ya lo sabe.',
    ],
    low: [
      'Tu masculinidad es una historia que te cuentas a ti mismo y que nadie mas se cree.',
      'Proyectas la solidez de un castillo de naipes en dia de viento.',
      'Menos macho que una declaracion de renta, y eso tiene mucho merito.',
      'Tu firmeza dura lo que dura el buen tiempo, que en tu caso no es mucho.',
      'La seguridad que proyectas no engana a nadie que te haya visto bajo presion.',
      'Tienes el caracter de un flan, y el flan al menos se sostiene en el molde.',
      'Tu masculinidad es tan fragil que se rompe con una pregunta directa.',
      'Cuando las cosas se complican, tu eres el primero en desaparecer, y todos lo saben.',
    ],
    extreme: [
      'Tienes una masculinidad real que no necesita anunciarse porque se percibe sin palabras.',
      'La solidez que proyectas es de las que no se fingen ni se aprenden en un fin de semana.',
      'Eres de los que generan confianza con su presencia antes de haber hecho nada.',
      'Tu manera de manejar la presion es lo que te distingue cuando las cosas importan de verdad.',
      'Tienes el tipo de caracter que la gente busca cuando necesita a alguien de verdad.',
      'La firmeza que tienes no es rigidez, es estructura. Eso es lo que marca la diferencia.',
      'Eres de los pocos que tienen masculinidad de verdad sin necesitar que nadie se los confirme.',
      'Tu presencia en cualquier grupo lo ancla, y la gente lo nota aunque no lo diga.',
      'Tienes esa clase de seguridad que no viene del ego sino del conocimiento propio.',
      'La gente que te conoce bien sabe exactamente lo que vale tenerte cerca cuando las cosas se complican.',
      'Tu caracter tiene solidez real, no es actuacion ni depende del publico.',
      'Eres de los que dejan al grupo en mejor estado que cuando llegaste, y eso es lo mas dificil.',
      'La gente que ha contado contigo en momentos importantes sabe lo que eso vale.',
      'Tienes esa combinacion de calma y determinacion que muy pocos consiguen mantener.',
      'No necesitas que nadie te explique lo que hay que hacer cuando las cosas importan. Eso ya lo dice todo.',
    ],
  },

  inutil: {
    name: 'inutil',
    high: [
      'Inutil certificado, tu presencia en cualquier tarea es un obstaculo documentado.',
      'Das menos que lo que prometes, y lo que prometes ya era poco.',
      'Necesitas ayuda hasta para equivocarte de manera eficiente.',
      'Tu contribucion a cualquier proyecto es neutra en el mejor escenario posible.',
      'Tienes el talento especial de complicar lo simple sin anadir nada al resultado.',
      'La gente que trabaja contigo ya asume de entrada que va a tener que rehacer todo.',
      'Eres el tipo de persona que hace que el trabajo aumente con solo aparecer.',
      'Tu nivel de inutilidad no es descuido, es constancia. Eso al menos merece reconocimiento.',
      'Cuando alguien necesita que algo salga bien, tu eres el primero al que no llaman.',
      'Has convertido la incompetencia en un estilo de vida y lo llevas con una dignidad inexplicable.',
      'Tu aportacion al grupo oscila entre cero y negativa dependiendo del dia.',
      'Eres exactamente el tipo de recurso humano que los equipos aprenden a rodear.',
      'No solo no ayudas, consigues que los que si ayudan tengan que trabajar mas por tu culpa.',
      'Tu ineficiencia tiene una consistencia que, si la aplicaras a algo util, podria ser admirable.',
      'La brecha entre lo que crees que aportas y lo que aportas de verdad es un abismo.',
      'Necesitas instrucciones para las cosas que los demas hacen por instinto.',
      'Eres el freno de cualquier cosa en la que participas, y lo peor es que no te das cuenta.',
      'Tu existencia en un proyecto es mas un obstaculo que un recurso.',
      'Si te pagaran por lo que produces, te deberian dinero a ti en la direccion contraria.',
      'Eres el tipo de persona del que los equipos hablan cuando ponen ejemplos de lo que no hay que hacer.',
    ],
    mid: [
      'Util a ratos, inutil a ratos, sin ritmo ni patron claro.',
      'Ni tan capaz como te crees ni tan inutil como te tratan, en el termino medio mas aburrido.',
      'Haces lo minimo para que no te echen sin llegar a aportar nada memorable.',
      'Tu rendimiento es correcto cuando quieres y desastroso cuando no, y no siempre quieres.',
      'Das lo justo para pasar pero nunca lo suficiente para que alguien te recuerde por algo bueno.',
      'Tienes capacidad real pero una desidia que la anula sistematicamente.',
      'Funcional en circunstancias favorables, un problema cuando hay presion.',
      'No eres un desastre, eres un blando. Y los blandos son un problema de otro tipo.',
      'La gente no cuenta contigo para lo importante pero tampoco te descarta del todo. Eso es lo mas mediocre que existe.',
      'Pasas desapercibido en todo, y en este caso eso no es un cumplido.',
    ],
    low: [
      'Util de verdad, de los que hacen que las cosas funcionen sin necesitar reconocimiento.',
      'Tienes un nivel de competencia real que no todo el mundo puede decir que tiene.',
      'La gente cuenta contigo cuando algo importa, y eso no se regala.',
      'Eres de los que resuelven sin quejarse y sin necesitar que nadie les explique dos veces.',
      'Tu aportacion es de las que se nota cuando faltas, no cuando estas. Eso es el nivel real.',
      'Tienes esa capacidad de ejecucion que la mayoria simula tener sin tenerla.',
      'Cuando hay que hacer algo bien, eres de los que la gente busca. Eso ya lo dice todo.',
    ],
    extreme: [
      'Eres exactamente el tipo de persona del que los grupos hablan cuando ponen ejemplos de lo que ralentiza todo.',
      'Tu nivel de inutilidad tiene una consistencia que, si la aplicaras a algo real, podria ser un record.',
      'La brecha entre tu autoconcepto y tu rendimiento real es uno de los grandes misterios de este grupo.',
      'Hay gente inutil y hay gente que ademas no es consciente de serlo. Tu eres las dos cosas.',
      'La gente ha dejado de contar contigo no por crueldad sino por experiencia acumulada.',
      'Tu ineficiencia no es accidental, tiene estructura, patron y trayectoria. Eso ya es otro nivel.',
      'Cada vez que te asignan algo, alguien en el grupo ya esta pensando en como arreglarlo despues.',
      'No es que no puedas, es que no quieres, y lo peor es que ya no sabes distinguir la diferencia.',
      'Llevas tanto tiempo sin aportar nada que ya ni tu mismo recuerdas cuando fue la ultima vez.',
      'Eres el tipo de presencia en un grupo que hace que los demas suban la guardia.',
      'Tu historial habla por ti, y lo que dice no te deja en buen lugar.',
      'La gente que ha trabajado contigo te ha borrado de sus listas de personas con las que contar para algo serio.',
      'No eres mal tipo, pero eres exactamente el tipo de persona que ningun equipo quiere repetir.',
      'Tu inutilidad tiene fama antes de que llegues, y eso es un logro al reves.',
      'Cuando te vayas de un proyecto, el proyecto va a respirar. Eso es lo que has construido.',
    ],
  },

function extractTarget(msg) {
  const mentioned = msg.message?.extendedTextMessage?.contextInfo?.mentionedJid?.[0];
  if (mentioned) return mentioned;
  const quotedParticipant = msg.message?.extendedTextMessage?.contextInfo?.participant;
  if (quotedParticipant) return quotedParticipant;
  return msg.key.participant || msg.key.remoteJid;
}

async function runPercent(sock, msg, key) {
  const jid = msg.key.remoteJid;
  const cfg = LABELS[key];
  if (!cfg) return;

  const target = extractTarget(msg);
  const percent = Math.floor(Math.random() * 101);
  const verdict = percent >= 70 ? pick(cfg.high) : percent <= 30 ? pick(cfg.low) : pick(cfg.mid);
  const finale = pick(cfg.extreme);

  const text =
    `*@${target.split('@')[0]} es ${percent}% ${cfg.name}*\n\n` +
    `_${verdict}_\n\n` +
    `${finale}`;

  await sock.sendMessage(jid, { text, mentions: [target] }, { quoted: msg });
}

function makeCmd(key) {
  return (sock, msg) => runPercent(sock, msg, key);
}

module.exports = {
  cmdGay:           makeCmd('gay'),
  cmdSimp:          makeCmd('simp'),
  cmdHot:           makeCmd('sexy'),
  cmdRata:          makeCmd('rata'),
  cmdMaricon:       makeCmd('maricon'),
  cmdFriki:         makeCmd('friki'),
  cmdCrack:         makeCmd('crack'),
  cmdInteligencia:  makeCmd('inteligencia'),
  cmdCerdo:         makeCmd('cerdo'),
  cmdFeminidad:     makeCmd('feminidad'),
  cmdMasculinidad:  makeCmd('masculinidad'),
  cmdInutil:        makeCmd('inutil'),
};
