// Generic random % about someone — used by !gay, !simp, !sexy, !rata, !maricon, !friki

function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }

const LABELS = {
  gay: {
    name: 'gay',
    high: [
      'Sal del armario de una vez, todo el mundo ya lo sabe menos tu.',
      'Mas gay que un arcoiris en una sauna, y encima sin disimularlo.',
      'Nenaza redomada, hasta tus huesos son rosas.',
      'La pluma se te escapa por todos los lados, ya no hay vuelta atras.',
      'Naciste con purpurina en las venas y se nota a kilometros.',
      'Hay vecinos que aun no se enteran pero les llegara la circular.',
      'En cuanto entras en una habitacion se enciende el modo fiesta.',
      'Te delata todo, desde como caminas hasta como respiras.',
      'Mas mariquita que un campo de margaritas en mayo.',
      'Eres un faro de pluma en mitad de la noche.',
      'Si la heterosexualidad fuera un examen, tu lo suspenderias antes de empezar.',
      'Tu propio reflejo te mira y suspira de alivio porque por fin lo aceptas.',
      'Cuando hablas, las mariposas en tu boca tienen mas estilo que tu vida entera.',
      'Tu armario ya no existe, lo has quemado tu solo a base de purpurina.',
      'Naciste para llevar tacones aunque te hayan disfrazado de macho.',
      'Tu Spotify es un mapa autobiografico que cualquiera puede descifrar.',
      'Hasta tus aplicaciones del movil te delatan, una por una.',
      'Tu cuerpo se mueve antes que tu razon, y tu razon ya lo asume.',
      'Tu masculinidad no se la cree ni tu sombra.',
      'Vas vestido de heterosexual pero el detalle del pin te delata cada vez.',
      'Tu manera de hablar es un comunicado oficial de pluma.',
      'Cada gesto tuyo confirma lo que tu silencio intenta negar.',
      'Eres tan gay que el sol sale a saludarte con purpurina en los rayos.',
      'Tu colonia se nota a tres barrios de distancia y es siempre la misma.',
      'No es que se te note, es que se anuncia con megafono.',
      'Tu paleta de colores no la compra un macho ni por error.',
      'Tienes la sensibilidad estetica de quien lleva anyos viendolo claro.',
      'Hasta tus padres ya lo asumen aunque no se atrevan a decirlo.',
      'Mas gay que un brunch un domingo de orgullo.',
      'Llevas la bandera por dentro y se transparenta cada vez que sonries.',
    ],
    mid:  [
      'Algo se te mueve por dentro cuando pasan tios buenos.',
      'Ni fu ni fa, pero tampoco eres muy macho.',
      'Cuando bebes algo de mas, se te nota cierta curiosidad.',
      'En ciertos angulos y con cierta luz, levantas sospechas.',
      'Hay gestos tuyos que la gente comenta cuando no estas.',
      'Bisexualidad pendiente de confirmacion oficial.',
      'Tu Spotify te delata mas que tu propio comportamiento.',
      'Una de cal y otra de arena, todavia te lo estas pensando.',
      'A veces si, a veces no, dependiendo del dia y de quien aparezca.',
      'Te falta valentia para asumirlo o para descartarlo del todo.',
      'En el grupo hay debate sobre ti, sin ironia.',
      'Tu indecision es mas evidente que cualquier respuesta.',
      'Cualquier dia te decantas y nadie se va a sorprender.',
      'Estas en esa fase donde te miras los abdominales en el espejo demasiado tiempo.',
      'Hay miradas tuyas que se quedan mas tiempo del aceptable.',
    ],
    low:  [
      'Mas hetero que un toro en feria.',
      'Cero pluma, cero duda.',
      'Macho alfa de manual antiguo y polvoriento.',
      'Mas heterosexual que una ferreteria en domingo.',
      'No tienes ni la mas minima sospecha en tu curriculum.',
      'Tu masculinidad raya lo aburrido.',
      'Tan hetero que te incomodan hasta los abrazos largos.',
      'Tu mundo se reduce a futbol, cerveza y poco mas.',
      'Heterosexualidad blindada, sin grietas posibles.',
      'No hay duda en tu hoja de servicios, lastimosamente.',
    ],
    extreme: [
      'Vaya maricon, deberias salirte del grupo, nadie te quiere aca.',
      'Eres el tipo de persona del que todos hablan mal cuando sales de la sala.',
      'Nadie te lo dice a la cara pero todos piensan lo mismo de ti.',
      'Date cuenta de que sobras aqui, en serio.',
      'Tu familia ya ni pregunta por ti, algo habra.',
      'En el grupo te aguantan, no te eligen. Hay una diferencia abismal.',
      'Si manyana desaparecieras nadie te buscaria, piensalo bien.',
      'Cada vez que escribes en el grupo alguien suspira y otro silencia el chat.',
      'Eres exactamente la persona que la gente bloquea cuando se cansa de fingir.',
      'Tus mejores momentos los inventas tu mismo porque nadie mas los recuerda.',
      'La gente que dice quererte solo lo hace porque no le queda otra.',
      'Hay un motivo por el que nunca te invitan primero, y lo sabes perfectamente.',
      'Lo unico estable de tu vida es la decepcion que generas en los demas.',
      'Si pudieras verte desde fuera, tu mismo te darias de baja del grupo.',
      'Te miran y no entienden como sigues aqui, ni tu mismo lo entiendes.',
      'Tu propio reflejo te juzga cada manyana y tiene motivos.',
      'Vas perdiendo gente sin darte cuenta y cuando lo notes ya no quedara nadie.',
      'Tus padres mienten cuando les preguntan que tal te va.',
      'Hay un grupo paralelo sin ti donde se respira tranquilidad.',
      'Eres el tipo de presencia que la gente aprende a esquivar con educacion.',
    ],
  },

  simp: {
    name: 'simp',
    high: [
      'Simp de campeonato, te lamerias los zapatos por un emoji.',
      'Te pones de rodillas con solo que te miren, da pena verte.',
      'Vendes tu dignidad por un hola, eso dice mucho de ti.',
      'Caes redondo en cuanto te ponen un poco de atencion.',
      'Tu autoestima depende de un visto en WhatsApp.',
      'Te enamoras tres veces por semana, todas mal.',
      'Le escribes a la misma persona durante meses sin recibir nada a cambio.',
      'Tu telefono solo manda mensajes, nunca recibe.',
      'Eres el tipo que envia regalos a alguien que ni recuerda tu nombre.',
      'Sabes su signo, su perfume y donde estudio, ella no sabe ni que existes.',
      'Cuando ves su foto se te cae el alma al suelo y aun asi sigues mirando.',
      'Tu plan B es seguir esperando al plan A que nunca va a llegar.',
      'Le contestas a los dos segundos aunque ella tarde tres dias.',
      'Tu estrategia de seduccion consiste en estar disponible las 24 horas y eso te hace invisible.',
      'Te tomas las migajas que te tira como si fueran un banquete.',
      'Tu Instagram es un altar publico a alguien que no te quiere.',
      'Le pagas el bizum mensual y le llamas a eso amor.',
      'Le aguantas las salidas con otros mientras ensayas frases para cuando vuelva contigo.',
      'Te conformas con migajas porque no aspiras a una mesa puesta.',
      'Le defiendes incluso cuando ella ni se entera de que existes.',
      'Tu mejor cualidad segun ella es que siempre estas disponible para escucharla quejarse de otro.',
      'Te has hecho amigo de su gato para tener excusa para verla.',
      'Aceptas la friendzone como si fuera un ascenso.',
      'Coleccionas rechazos como si fueran cromos y aun asi sigues jugando.',
      'Cuando te dice que te quiere como amigo te brillan los ojos. Eso ya es preocupante.',
      'Le mandas buenas noches todos los dias y un dia uno de los dos va a romperse.',
      'Tu autoestima cabe en una notificacion de visto.',
      'Te utilizan como bizum andante y aun das las gracias.',
      'Si te dijera salta, preguntarias desde que altura y con que sonrisa.',
      'Te crees su mejor opcion cuando solo eres la opcion de emergencia.',
    ],
    mid:  [
      'Simping controlado, pero se te nota la desesperacion.',
      'No llegas a simp total pero vas por el camino.',
      'A ratos te respetas, a ratos no, eres inconsistente.',
      'Sabes que esta mal pero no puedes evitarlo.',
      'Tu cabeza dice no, tu corazon dice si, tu cartera paga.',
      'Conoces el limite y aun asi flirteas con cruzarlo.',
      'Tienes orgullo, pero negociable.',
      'En ocasiones reaccionas y luego recaes.',
      'Vas y vienes, sin terminar de aprender la leccion.',
      'Cada dos por tres recaes en patrones que sabes que te hacen mal.',
    ],
    low:  [
      'Digno. No te arrastras por nadie.',
      'Frialdad de iceberg, nadie te dobla.',
      'Sabes lo que vales y no lo regalas.',
      'Tu amor propio esta blindado, dificil tumbarte.',
      'Te respetan porque te respetas a ti mismo primero.',
      'No persigues, atraes. Esa es la clave.',
      'Cuando alguien no te valora, desapareces. Asi se hace.',
      'Tienes claro que estar solo es mejor que estar mal acompanyado.',
    ],
    extreme: [
      'Eres un felpudo con patas. Te utilizan, lo saben, y tu sigues ahi sonriendo.',
      'Date cuenta de que nadie te respeta y es completamente culpa tuya.',
      'La persona por la que babeas ni recuerda tu nombre, eso te deberia decir algo.',
      'Tan desesperado que das pena hasta a los que te odian.',
      'Llevas tanto tiempo arrastrandote que ya ni sabes como estar de pie.',
      'Hay perros con mas dignidad que tu, y los perros lamen sus propias heridas.',
      'Cuando se rian de ti a tu espalda, recuerda que te lo has ganado a pulso.',
      'Tu existencia entera depende de la aprobacion de gente que no te valora.',
      'Te ven venir desde lejos y aprovechan, porque saben que no vas a decir nada.',
      'Hasta tu propia madre se cansa de verte humillarte por personas que no merecen ni tu hora.',
      'La gente cuenta historias sobre lo patetico que eres, y se rien.',
      'Renuncia, no por ella sino por ti mismo, aunque eso ya es pedir demasiado.',
      'No es amor, es enfermedad, y tu has decidido no curarte.',
      'Eres exactamente el ejemplo que los padres ponen a sus hijos para que no acaben asi.',
      'Te conformas con tan poco que has perdido la capacidad de aspirar a mas.',
      'Vas a llegar a viejo solo y vas a culpar a todos menos a la unica persona responsable.',
      'Tu unica relacion estable es la que tienes con el rechazo.',
      'El amor propio que no tienes te lo va a cobrar la vida con intereses.',
      'Llevas tantos rechazos acumulados que ya solo aspiras a no recibir mas, no a recibir amor.',
      'Cada noche que duermes solo es un recordatorio de lo poco que te valoras.',
      'No la quieres, dependes de ella, y eso es mucho mas triste de admitir.',
      'Has confundido obsesion con amor y eso te ha costado todas tus relaciones.',
      'La gente del grupo se rie de tus mensajes y tu sigues mandandolos.',
      'Tu necesidad de aprobacion la huele cualquiera a kilometros y por eso te evitan.',
      'No vas a estar bien hasta que dejes de buscar a alguien que te salve, y no lo vas a hacer.',
    ],
  },

  sexy: {
    name: 'sexy',
    high: [
      'Estas hecho un cromo, hay que reconocertelo.',
      'Para comerte vivo, sin cubiertos y sin remordimientos.',
      'Cuando pasas, todo el mundo gira la cabeza, lo sepas o no.',
      'Tienes ese algo que no se explica pero todos notan.',
      'Eres de los que paralizan una conversacion con solo aparecer.',
      'La genetica te debe favores, los has recibido todos juntos.',
      'Hay belleza y luego estas tu, en otra categoria.',
      'Tu sola presencia sube la temperatura de cualquier sala.',
      'Eres peligroso por lo guapo que estas, deberian avisarlo en la puerta.',
      'No tienes derecho a estar tan bien hecho, es injusto para el resto.',
      'Cuando sonries deberias cobrar entrada, en serio.',
      'Tu mirada tiene mas curriculum que la mayoria de la gente entera.',
      'Tienes presencia, no solo cara, y eso es lo dificil.',
      'En una foto de grupo, todo el mundo te mira a ti antes que al fotografo.',
      'Eres atractivo de los que dejan marca, no de los que se olvidan al rato.',
      'Tienes ese tipo de magnetismo natural que la gente paga por intentar imitar.',
      'Cuando hablas, no se que dices, solo se que quiero seguir escuchandote.',
      'Tu cara es de las que se quedan en la cabeza durante dias.',
      'Tienes el cuerpo que la gente pide en sus oraciones nocturnas.',
      'Pareces salido de una pelicula y de las buenas.',
      'Eres el tipo de persona que pone nervioso al entrar a una sala.',
      'Tu perfil bueno es bueno, y el malo tambien es mejor que el bueno del resto.',
      'La gente saca el telefono cuando pasas, aunque no te conozca.',
      'Tienes ese aire de quien sabe que sabe, y eso es irresistible.',
      'Estas en el grupo de los privilegiados estaticos, los que con poco esfuerzo se llevan todo.',
      'Cuando entras al mar, el mar se considera afortunado.',
      'Vistes cualquier cosa y la haces parecer cara y pensada.',
      'Tienes el tipo de belleza atemporal, no la de moda fugaz.',
      'La gente te recuerda anyos despues de cruzarte cinco minutos.',
      'Hay caras y luego esta la tuya, una categoria propia.',
    ],
    mid:  [
      'Tienes lo tuyo, no eres ningun cromo pero tampoco pasas desapercibido.',
      'Con buena luz y buena ropa, das bastante el pego.',
      'Vas mejorando con los anyos, hay que tener paciencia.',
      'Pasable, sin alardes, lo justo para defenderte en sociedad.',
      'Hay dias buenos y dias regulares, depende del espejo.',
      'No eres feo, eres del monton, que es mas dificil de digerir.',
      'Te falta un poco de gimnasio y un poco de actitud, pero hay base.',
      'Mejoraras cuando aprendas a sacarte partido.',
      'Tu estilo es discreto, eso ayuda mucho.',
      'En blanco y negro ganas, en color te la juegas.',
    ],
    low:  [
      'No es lo tuyo, pero la personalidad cuenta, eso dicen.',
      'Hay rasgos peculiares que pueden gustar a alguien muy especifico.',
      'No naciste para portada de revista, pero tienes otras virtudes.',
      'La belleza esta en el interior, en tu caso muy en el interior.',
      'Eres del tipo que mejora cuando se le conoce, mantente esperanzado.',
      'Lo tuyo no es el fisico, pero hay vida mas alla.',
      'Compensas con simpatia lo que la naturaleza no te dio.',
      'No te has llevado la mejor mano, juega bien las cartas que tienes.',
    ],
    extreme: [
      'Tienes ese magnetismo que la gente paga para fingir, y a ti te sale gratis.',
      'Cuando entras a un sitio cambia la energia, eso no se aprende.',
      'Vas a romper corazones que ni siquiera sabes que existen.',
      'La gente te admira aunque no te lo diga, esas cosas se notan.',
      'Tienes esa belleza dificil que no todos saben apreciar, mejor asi.',
      'Eres el tipo de persona que se queda en la memoria de quien te conoce.',
      'No necesitas hacer nada para llamar la atencion, solo estar.',
      'Tu personalidad acompanya tu fisico y eso es una combinacion letal.',
      'Hay gente nacida para ser vista, y tu naciste con ese don.',
      'Quien acabe contigo va a tener mucha suerte, asegurate de elegir bien.',
      'Estas en esa edad donde todo te favorece, aprovechala.',
      'Cuando te miras al espejo deberias sonreir, te lo has ganado.',
      'Cualquiera que te eche la vista encima ya esta pensando en ti horas despues.',
      'Tu confianza es la mitad de tu atractivo, no la pierdas nunca.',
      'En cualquier ciudad eres el primer recuerdo que se llevan los visitantes.',
      'La gente coquetea contigo sin darse cuenta, por inercia.',
      'Tienes la suerte de ser guapo y la inteligencia de saberlo sin abusar.',
      'Si pudieras embotellar lo que tienes, te harias rico en una semana.',
      'Hay belleza superficial y belleza real, y tu tienes las dos a la vez.',
      'Te miran y se quedan colgados sin saber por que. Eso es talento puro.',
    ],
  },

  rata: {
    name: 'rata',
    high: [
      'Rata de alcantarilla, traicionarias a tu madre por cinco euros.',
      'Judas con zapatillas, lo mas rastrero que existe.',
      'Tu deslealtad es arte. Todo el mundo en este grupo ya lo sabe.',
      'Vendes a tus amigos antes de que termine el dia.',
      'Donde hay un cuchillo por la espalda, hay un dedo tuyo apuntando.',
      'La traicion te sale natural, ni siquiera necesitas pensarla.',
      'Eres el tipo que cuenta secretos en cuanto sale de la habitacion.',
      'No tienes amigos, tienes objetivos a corto plazo.',
      'Cambias de bando con la facilidad que otros cambian de calcetines.',
      'Hueles la traicion antes que el cafe por las mananas.',
      'Te jactas de tu astucia pero todos saben que es simple maldad.',
      'No hay favor que no cobres ni confianza que no rompas.',
      'Hablas mal de la gente cinco minutos despues de abrazarla.',
      'Tus amigos del grupo de chicos hablan mal de ti en otro grupo paralelo.',
      'Coleccionas secretos ajenos como munición para usar cuando convenga.',
      'Estas en cuatro grupos distintos hablando mal del resto en cada uno.',
      'Le mandas pantallazos a quien no debe, y crees que nadie se va a enterar.',
      'No tienes principios, tienes calculos.',
      'Tus alianzas duran lo que duran los beneficios que te aportan.',
      'Vendes amistades a precio de saldo en cuanto aparece algo mejor.',
      'Tu palabra no vale nada, ni siquiera para ti mismo.',
      'Sonries con la boca mientras la mente ya esta planeando el siguiente movimiento.',
      'Tu padre sabe quien eres y por eso no presume de ti.',
    ],
    mid:  [
      'Algo de rata tienes, pero no llegas al nivel de plaga todavia.',
      'Traicionas cuando conviene, que es lo peor que existe.',
      'Eres leal hasta que aparece una oferta mejor.',
      'Tienes principios moviles segun el viento del momento.',
      'A veces eres buen amigo, otras veces aparece el monstruo.',
      'No estas del todo perdido pero el camino es resbaladizo.',
      'Tienes una rata pequenya dentro y esta creciendo.',
      'Algunas amistades ya te miran raro, deberias preocuparte.',
      'Hay gente que ya empieza a contarte solo verdades a medias.',
    ],
    low:  [
      'Mas leal que un perro, no traicionarias ni a tu peor enemigo.',
      'Limpio como una patena.',
      'De los que dan la cara aunque pierdan.',
      'Tus amigos pueden dormir tranquilos contigo cerca.',
      'Eres de los que mueren con el secreto, raro pero admirable.',
      'Tu palabra es ley para ti, eso es valor en estos tiempos.',
      'Cuando confias en alguien lo haces hasta el fondo, sin reservas.',
    ],
    extreme: [
      'Todo el mundo en este grupo sabe que no eres de fiar, solo que nadie te lo dice.',
      'Eres el tipo de amigo que la gente va descartando con los anyos, y lo mereces.',
      'La gente no te cuenta cosas importantes porque saben que las vas a usar en tu beneficio.',
      'Hay personas que entran en tu vida y la mejoran. Tu eres de las otras.',
      'Cuando te vayas del grupo nadie va a preguntar por ti, y en el fondo ya lo sabes.',
      'Te van a abandonar uno a uno y vas a culpar al mundo cuando solo es culpa tuya.',
      'La soledad que te espera no es mala suerte, es la factura de lo que sembraste.',
      'Algun dia vas a necesitar a alguien y no va a haber nadie, ni siquiera tu propia familia.',
      'Te van a hacer exactamente lo que tu has hecho, y va a doler el doble.',
      'Tus traiciones llevan tu firma aunque tu creas que no, todos las reconocen.',
      'Cuando seas viejo y estes solo, recuerda que cada decision te trajo hasta ese sillon vacio.',
      'Hay personas que envenenan grupos enteros, y tu eres una de ellas, manual de manual.',
      'Te crees listo pero el unico tonto en esta ecuacion eres tu.',
      'Hasta los que te apoyan en publico te critican en privado, eso es lo que has construido.',
      'Tus hijos van a crecer escuchando que clase de persona fuiste con los demas.',
      'Vas a ir a un entierro y va a haber mas gente alli por ti que en el tuyo.',
      'Tienes pendiente devolver tantas trampas que la vida ya esta calculando el interes.',
      'La sonrisa que pones cuando engañas, la gente la fotografia mentalmente para no olvidarla.',
      'Tus actos te han etiquetado para siempre, y esa etiqueta no se quita.',
      'Cuando la gente te recuerde dentro de diez anyos sera con una mueca, no con una sonrisa.',
      'Eres ejemplo de lo que no hay que ser, y lo usan en familia para asustar a los ninos.',
      'No tienes red de apoyo porque tu mismo cortaste cada cable que te conectaba con alguien.',
      'Mira a tu alrededor. La gente que queda contigo es la que aun no te conoce bien.',
    ],
  },

  maricon: {
    name: 'maricon',
    high: [
      'Maricon de tomo y lomo, y encima sin talento para disimularlo.',
      'La reina de las reinas, nadie te quita el trono de lo ridiculo.',
      'Mas pluma que un gallinero en hora punta.',
      'Naciste para llevar tacones aunque tu DNI diga otra cosa.',
      'En cuanto abres la boca cae un purpurinazo de dos kilos.',
      'No hay armario en el mundo que aguante tu pluma encerrada.',
      'Hasta las paredes huyen del color que desprendes al andar.',
      'Cada gesto tuyo es una declaracion involuntaria.',
      'La masculinidad te queda como un disfraz mal cosido.',
      'Tu intento de macho convence a nadie, ni a ti mismo en el espejo.',
      'Tus colegas hablan de ti sin parar cuando no estas.',
      'Tu manera de andar ya es un mensaje en clave para los entendidos.',
      'Llevas la pluma tan adentro que ya forma parte de tu esqueleto.',
      'Cuando entras a un bar, el camarero ya sabe que vas a pedir antes de que abras la boca.',
      'Tu estilo de ropa es un comunicado oficial sin firmar.',
      'Hay un sticker tuyo en circulacion en otro grupo, y no es elogioso.',
      'Tu sola presencia es objeto de chiste en cinco conversaciones distintas.',
      'Tu masculinidad raya lo comico, en sentido literal.',
      'Te disfrazas de macho y a la primera curva pierdes la mascara.',
      'Eres tan obvio que ya no engañas ni a los muy distraidos.',
    ],
    mid:  [
      'Algo de pluma hay, no te voy a mentir.',
      'Ni muy muy ni tan tan, en el limbo de la virilidad.',
      'A veces se te escapa, a veces lo controlas.',
      'En ciertas situaciones te pones nervioso y se nota a kilometros.',
      'Hay gestos que repites sin darte cuenta y todos los catalogan.',
      'Tu lucha interna es publica aunque tu no lo creas.',
      'Vas a tener que aceptarlo antes o despues, mejor antes.',
    ],
    low:  [
      'Mas macho que Rambo con resaca.',
      'Testosterona a raudales, ninguna duda.',
      'Tu masculinidad es de manual antiguo, agresiva y sin matices.',
      'Heterosexualidad sin grietas, casi insoportable.',
      'Tu mundo se reduce a tres temas masculinos repetidos en bucle.',
    ],
    extreme: [
      'Vaya maricon, deberias salirte del grupo, nadie te quiere aca.',
      'Eres exactamente el tipo de persona del que la gente habla mal cuando te vas.',
      'Nadie te lo dice a la cara porque no mereces ni ese esfuerzo.',
      'En serio, piensa cuantas personas del grupo te escribirian si desaparecieras. Piensalo bien.',
      'Hay una razon por la que siempre eres el ultimo al que avisan de los planes.',
      'La gente te soporta, no te quiere. Aprende la diferencia.',
      'En tu propia familia hablan de ti como del problema, no como del hijo.',
      'Tus padres mienten cuando les preguntan que tal te va.',
      'Vas a pasar la vida buscando un sitio donde encajar y nunca lo vas a encontrar.',
      'Cuando estes solo en una habitacion oscura, piensa por que la gente se aleja de ti.',
      'Hay una conversacion en el grupo donde se hablan pestes tuyas, y no eres miembro de ese grupo.',
      'Eres invisible para los que te quieren y visible para los que te desprecian.',
      'La carga emocional que generas en los demas pesa mas que tu propia existencia.',
      'Te van a olvidar mas rapido de lo que te tardaron en conocer.',
      'Cuando te mueras, la mitad del grupo no se va a enterar y la otra mitad no va a llorar.',
      'Tu telefono no suena nunca y eso ya deberia decirte algo, pero no escuchas.',
      'Eres ese amigo del que todos prefieren no acordarse.',
      'Las conversaciones del grupo mejoran cuando no estas, y todos lo notan menos tu.',
      'Has confundido tu cabezoneria con personalidad, pero la gente solo ve la primera.',
      'Cuando alguien te elimina de un chat, no le tiembla el pulso ni un segundo.',
      'Tus cumpleanyos los celebras tu solo porque ya nadie se acuerda de organizarte uno.',
      'Hay un motivo por el que las relaciones se te rompen tan rapido, y eres tu.',
      'Tu propia sombra preferiria estar con cualquier otra persona si pudiera elegir.',
      'Eres el tipo de persona del que la gente se libera, no del que se enamora.',
      'Cuando faltes en una reunion, suspirarian de alivio si no fueran tan educados.',
    ],
  },

  friki: {
    name: 'friki',
    high: [
      'Friki supremo, tu cueva huele a fracaso social y pizza fria.',
      'Eres el senyor de los frikis, el elegido por nadie.',
      'Tan friki que hasta los demas frikis te miran raro en los foros.',
      'Tu vida social entera cabe en una pantalla de seis pulgadas.',
      'Sabes mas de personajes ficticios que de personas reales.',
      'Tu Steam tiene mas horas que tu trabajo, tu colegio y tu vida juntos.',
      'El sol te quema porque ya no te reconoce.',
      'Tus conversaciones empiezan con jerga que nadie entiende.',
      'Tu camiseta del videojuego favorito ya forma parte de tu piel.',
      'No tienes amigos, tienes guildmates.',
      'La ultima vez que viste el cielo fue por accidente.',
      'Tu cuarto tiene mas poster que paredes a estas alturas.',
      'Coleccionas figuritas que ningun adulto deberia tener en exposicion.',
      'Tu vida amorosa se reduce a un waifu y dos personajes secundarios.',
      'Tu padre ya no sabe en que invertir esperanza, contigo se rinde.',
      'Hablas de lore de un anime a la primera oportunidad que te dan.',
      'La discusion mas importante de tu semana fue sobre un personaje ficticio.',
      'Llevas tantas horas en pantalla que tus ojos ya no enfocan la realidad.',
      'Tu casa es un templo a marcas que ningun adulto reconoce.',
      'Tus pijamas tienen mas personajes ficticios que tu vida personajes reales.',
    ],
    mid:  [
      'Friki moderado, sales a la calle de vez en cuando, lo cual ya es algo.',
      'Friki con disimulo, pero se nota en cuanto abres la boca.',
      'Tienes referencias que nadie pilla pero te las guardas, gracias por eso.',
      'A ratos eres friki, a ratos persona, es complicado.',
      'Sales del cuarto los fines de semana, hay esperanza.',
      'Tu carpeta de descargas y tu carpeta de recuerdos pesan parecido.',
    ],
    low:  [
      'Cero raro, lo mas normal del grupo.',
      'Social y presentable, que aburrido.',
      'Te mueves bien en cualquier ambiente, eso es un don.',
      'Tu vida es tan equilibrada que casi suena sospechoso.',
      'Pasas por persona promedio y eso ya es un exito en este grupo.',
    ],
    extreme: [
      'Llevas tanto tiempo hablando con pantallas que ya no sabes como hablar con personas.',
      'Hay un mundo fuera de tu habitacion y lleva anyos sin verte.',
      'La ultima vez que alguien te llamo para salir fue porque se habian equivocado de numero.',
      'Tu historial de busqueda dice mas de ti que cualquier cosa que puedas contarme.',
      'Eres el tipo de persona cuya ausencia en los planes nadie nota hasta que apareces.',
      'Tu vida real es tan pobre que has tenido que construirte otras en pantallas.',
      'Llevas anyos coleccionando trastos en lugar de coleccionar experiencias.',
      'Cuando salgas de casa por ultima vez, va a ser para mudarte a un sitio peor.',
      'Tus padres ya han renunciado a que tengas pareja, hijos o vida.',
      'Si manyana te pasara algo, lo encontrarian tres dias despues por el olor.',
      'Eres el primer fracaso documentado de tu arbol genealogico, y lo llevas con orgullo.',
      'Tu personalidad esta hecha de retales de series, no tienes nada propio.',
      'Sabes los datos de personajes ficticios y no sabes el cumpleanyos de tu madre.',
      'Confundes pasion con obsesion y soledad con concentracion.',
      'No tienes recuerdos propios, tienes referencias.',
      'Tu cuarto es el unico testigo de tu existencia, y eso es lo mas triste de todo.',
      'A los cuarenta vas a seguir igual, en el mismo cuarto, con los mismos posters.',
      'Vas a llegar a viejo sin haber sentido nada real, todo simulado en pantalla.',
      'Tus amigos online no van a venir a tu entierro, eso te lo aseguro.',
      'Cuando te muras vas a darte cuenta de todo lo que no viviste, pero ya sera tarde.',
    ],
  },
};

function extractTarget(msg) {
  const mentioned = msg.message?.extendedTextMessage?.contextInfo?.mentionedJid?.[0];
  if (mentioned) return mentioned;
  const quotedParticipant = msg.message?.extendedTextMessage?.contextInfo?.participant;
  if (quotedParticipant) return quotedParticipant;
  return msg.key.participant || msg.key.remoteJid;
}

async function runPercent(sock, msg, key) {
  const jid = msg.key.remoteJid;
  const cfg = LABELS[key];
  if (!cfg) return;

  const target = extractTarget(msg);
  const percent = Math.floor(Math.random() * 101);
  const verdict = percent >= 70 ? pick(cfg.high) : percent <= 30 ? pick(cfg.low) : pick(cfg.mid);
  const finale = pick(cfg.extreme);

  const filled = Math.round(percent / 10);
  const bar = '+'.repeat(filled) + '-'.repeat(10 - filled);

  const text =
    `*@${target.split('@')[0]} es ${percent}% ${cfg.name}*\n\n` +
    `${bar}\n\n` +
    `_${verdict}_\n\n` +
    `${finale}`;

  await sock.sendMessage(jid, { text, mentions: [target] }, { quoted: msg });
}

function makeCmd(key) {
  return (sock, msg) => runPercent(sock, msg, key);
}

module.exports = {
  cmdGay:     makeCmd('gay'),
  cmdSimp:    makeCmd('simp'),
  cmdHot:     makeCmd('sexy'),
  cmdRata:    makeCmd('rata'),
  cmdMaricon: makeCmd('maricon'),
  cmdFriki:   makeCmd('friki'),
};
