'use strict';

const { parsePhoneNumberFromString } = require('libphonenumber-js');
const { getSender, getTarget, isMainOwner, bareJid, sameUser, canonicalJid } = require('../utils/wa');
const { pickFresh, fmt } = require('../utils/helpers');
const { getUserCount } = require('../utils/messageCounter');

const HEADERS = [
  '*ROAST SIN ANESTESIA JODER*',
  '*EJECUCION PUBLICA DE MIERDA*',
  '*AUTOPSIA EN DIRECTO CABRON*',
  '*DESTRUCCION TOTAL DEL EGO*',
  '*ENTIERRO ABIERTO GILIPOLLAS*',
  '*MASACRE DOCUMENTADA COÑO*',
  '*ASADO HASTA EL HUESO ASCO*',
  '*DEMOLICION CONTROLADA PATETICO*.',
  '*VOLADURA PSICOLOGICA BASURA*',
  '*SENTENCIA SIN APELACION RIDICULO*.',
  '*DESMONTAJE EN DIRECTO FRACASADO*.',
  '*VEREDICTO DEL CHAT JODER*',
  '*HUMILLACION TECNICA DE MIERDA*.',
  '*QUEMA CONTROLADA DEL EGO*',
  '*AJUSTE DE CUENTAS CABRON*',
  '*DERROTA SIMBOLICA GILIPOLLAS*.',
  '*EXPOSICION TOTAL COÑO*',
  '*GOLPE DE GRACIA ASCO*',
  '*CIERRE CON LLAVE PATETICO*',
  '*ROAST DE MIERDA EN VIVO*',
  '*EJECUCION SIN PIEDAD BASURA*',
  '*AUTOPSIA DEL EGO RIDICULO*',
  '*ENTIERRO CON PUBLICO FRACASADO*.',
  '*JUICIO DEL GRUPO JODER*',
  '*FUSILAMIENTO DEL ORGULLO*',
  '*RUINA DOCUMENTADA CABRON*',
  '*CAIDA SIN RED GILIPOLLAS*',
  '*DESGUACE PERSONAL DE MIERDA*',
  '*LIQUIDACION DEL PERSONAJE*',
  '*SENTENCIA FIRME COÑO*',
  '*VEREDICTO SIN ANESTESIA*',
  '*HUMILLACION EN DIRECTO ASCO*',
  '*QUEMA DEL EGO PATETICO*',
  '*EXPOSICION SIN FILTRO BASURA*.',
  '*GOLPE LIMPIO RIDICULO*',
  '*CIERRE DEL ACTA FRACASADO*',
  '*ROAST ARCHIVADO JODER*',
  '*EJECUCION DEL PERSONAJE*',
  '*AUTOPSIA PUBLICA CABRON*',
  '*DERRUMBE SIN PIEDAD MIERDA*',
  '*CRATER DE ORGULLO COÑO*',
  '*TUMBA DEL EGO ASCO*',
  '*JUICIO EN VIVO PATETICO*',
  '*APLASTAMIENTO DEL RELATO*',
  '*RUINA SIN MAQUILLAJE BASURA*',
  '*CAIDA DOCUMENTADA RIDICULO*',
  '*DESGUACE TOTAL FRACASADO*',
  '*LIQUIDACION EN CALIENTE JODER*.',
  '*SENTENCIA DEL CHAT CABRON*',
  '*VEREDICTO CRUDO GILIPOLLAS*',
  '*HUMILLACION DE MIERDA PURA*',
  '*QUEMA SIN RETORNO COÑO*',
  '*EXPOSICION DEL FAIL ASCO*',
  '*GOLPE DE GRACIA DOCUMENTADO*',
  '*CIERRE SIN INDULTO PATETICO*',
  '*ROAST FINAL BASURA TOTAL*',
  '*EJECUCION DEL EGO RIDICULO*',
  '*AUTOPSIA SIN CONSUELO*',
  '*ENTIERRO DEL PERSONAJE JODER*.',
  '*JUICIO SUMARIO CABRON*',
  '*FUSILAMIENTO EN EL HILO*',
  '*RUINA TOTAL GILIPOLLAS*',
  '*CAIDA LIBRE DE MIERDA*',
  '*DESGUACE EN PUBLICO COÑO*',
  '*LIQUIDACION SIN BIS ASCO*',
  '*SENTENCIA ARCHIVADA PATETICO*.',
  '*VEREDICTO DEL BOT BASURA*',
  '*HUMILLACION CERTIFICADA*',
  '*QUEMA DEL RELATO RIDICULO*',
  '*EXPOSICION TOTAL DEL FAIL*',
  '*GOLPE SIN NARRADOR FRACASADO*.',
  '*CIERRE DE MIERDA JODER*',
  '*ROAST SIN RETORNO CABRON*',
  '*EJECUCION DOCUMENTADA*',
  '*AUTOPSIA DEL PERSONAJE*',
  '*DERRUMBE DE MIERDA COÑO*',
  '*CRATER PERSONAL ASCO*',
  '*TUMBA ABIERTA AL CHAT*',
  '*JUICIO SIN FILTRO PATETICO*',
  '*APLASTAMIENTO TOTAL BASURA*',
  '*RUINA EN DIRECTO RIDICULO*',
  '*CAIDA DEL EGO FRACASADO*',
  '*DESGUACE SIN PIEDAD JODER*',
  '*LIQUIDACION DEL EGO CABRON*',
  '*SENTENCIA CRUDA GILIPOLLAS*',
  '*VEREDICTO SIN CONSUELO*',
  '*HUMILLACION EN VIVO MIERDA*',
  '*QUEMA DOCUMENTADA COÑO*',
  '*EXPOSICION SIN ANESTESIA*',
  '*GOLPE ARCHIVADO ASCO*',
  '*CIERRE TOTAL PATETICO*',
  '*ROAST DEL SOTANO BASURA*',
  '*EJECUCION EN CALIENTE*',
  '*AUTOPSIA DEL FAIL RIDICULO*',
  '*ENTIERRO SIN FLORES FRACASADO*.',
  '*JUICIO DEL HILO JODER*',
  '*FUSILAMIENTO SIMBOLICO*',
  '*RUINA DEL PERSONAJE CABRON*',
  '*CAIDA PUBLICA GILIPOLLAS*',
  '*DESGUACE DE MIERDA TOTAL*',
];

const CLOSERS = [
  '_Sin piedad. Sin retorno. Sin terapia que te devuelva la autoestima de antes de leer esto, gilipollas._',
  '_Esto no se cura, se asume. Y duele porque pega donde el ego se escondía, cabrón._',
  '_Archivo cerrado. El contador y el chat firmaron el mismo veredicto, mierda._',
  '_No hay modo avión que te salve el frame. Lo visto queda, joder._',
  '_Fin del roast. La autoestima puede recoger los pedazos cuando quiera, asco._',
  '_Y lo peor es que ni una sola línea era exageración barata, patético._',
  '_Cierre. El grupo ya tenía la intuición; el bot solo puso números, basura._',
  '_Sin apelación. El ego pedía descuento y no hay caja de devoluciones, ridículo._',
  '_Acta levantada. Puedes fingir que no te tocó; el hilo sabe que sí, fracasado._',
  '_Se acabó. Menos misterio, más evidencia. Traga, coño._',
  '_El roast terminó. Tu narrativa personal perdió el round, joder._',
  '_Cerrado. No fue un mal día: fue un retrato, cabrón._',
  '_Sin consuelo de narrador amigo. Solo el eco de lo que ya pensaban, gilipollas._',
  '_Fin. La autoestima que dependía del silencio acaba de conocer el volumen, mierda._',
  '_Documentado. Puedes cambiar de nick; el patrón se queda, asco._',
  '_Última línea. El valor no se discute con bio ni con aura inventada, patético._',
  '_Cierre sin azúcar. El chat no te debe reparación emocional, basura._',
  '_Y punto. El contador habló y el ego debería bajar un tono, ridículo._',
  '_Archivo del fail personal, completado. Siguiente, fracasado._',
  '_Sin bis. La vergüenza es parte del servicio, joder._',
  '_El bot firmó. Tú puedes alegar; los números no, cabrón._',
  '_Fin de transmisión. Autoestima en modo avión forzado, gilipollas._',
  '_Cerrado el expediente. No había heroísmo que salvar, mierda._',
  '_Se terminó. El espejo del grupo no pide permiso, coño._',
  '_Última estocada. Si picó, es porque había carne, asco._',
  '_Sin terapia incluida. Solo diagnóstico en voz alta, patético._',
  '_Cierre. El ranking de dignidad no te debió favores, basura._',
  '_Acta listo. El ego puede presentar recurso en el vacío, ridículo._',
  '_Fin. Menos cuento, más contador, fracasado._',
  '_Y así queda el retrato. No es arte: es evidencia, joder._',
  '_Sin retorno elegante. Solo la salida por la puerta del hilo, cabrón._',
  '_Cerrado. La autoestima que vivía de no ser medida acaba de ser pesada, gilipollas._',
  '_El roast hizo su trabajo. El resto es tuyo, mierda._',
  '_Fin del desfile. Baja del escenario aunque nadie aplaudió, coño._',
  '_Documentado sin anestesia. Duele y basta, asco._',
  '_Última palabra del bot. La tuya ya ocupó demasiado espacio, patético._',
  '_Cierre limpio. Daño al relato personal, permanente, basura._',
  '_Se acabó el turno. El ego puede guardarse el discurso, ridículo._',
  '_Archivo sellado. No hay edición posterior que salve el frame, fracasado._',
  '_Sin indulto. El chat no es un tribunal amigo, joder._',
  '_Fin. Lo que queda es el eco y la cuenta de mensajes, cabrón._',
  '_Cerrado con llave. La autoestima no tiene copia, gilipollas._',
  '_El veredicto no pedía tu aprobación, mierda._',
  '_Última línea sin consuelo. Trágala o repítela, coño._',
  '_Se terminó. El grupo ya pasó de largo con la lección, asco._',
  '_Acta completa. Ego en dieta obligatoria, patético._',
  '_Fin del roast. No fue personal: fue estadística con filo, basura._',
  '_Sin maquillaje final. El retrato se queda así, ridículo._',
  '_Cierre. Puedes reírte; el número no, fracasado._',
  '_Y punto final. Menos aura inventada, más realidad, joder._',
  '_Sin piedad. Sin retorno. Sin terapia que te devuelva la autoestima de antes de leer esto, gilipollas_',
  '_Esto no se cura, se asume. Y duele porque pega donde el ego se escondía, cabrón_',
  '_Archivo cerrado. El contador y el chat firmaron el mismo veredicto, mierda_',
  '_No hay modo avión que te salve el frame. Lo visto queda, joder_',
  '_Fin del roast. La autoestima puede recoger los pedazos cuando quiera, asco_',
  '_Y lo peor es que ni una sola línea era exageración barata, patético_',
  '_Cierre. El grupo ya tenía la intuición; el bot solo puso números, basura_',
  '_Sin apelación. El ego pedía descuento y no hay caja de devoluciones, ridículo_',
  '_Acta levantada. Puedes fingir que no te tocó; el hilo sabe que sí, fracasado_',
  '_Se acabó. Menos misterio, más evidencia. Traga, coño_',
  '_El roast terminó. Tu narrativa personal perdió el round, joder_',
  '_Cerrado. No fue un mal día: fue un retrato, cabrón_',
  '_Sin consuelo de narrador amigo. Solo el eco de lo que ya pensaban, gilipollas_',
  '_Fin. La autoestima que dependía del silencio acaba de conocer el volumen, mierda_',
  '_Documentado. Puedes cambiar de nick; el patrón se queda, asco_',
  '_Última línea. El valor no se discute con bio ni con aura inventada, patético_',
  '_Cierre sin azúcar. El chat no te debe reparación emocional, basura_',
  '_Y punto. El contador habló y el ego debería bajar un tono, ridículo_',
  '_Archivo del fail personal, completado. Siguiente, fracasado_',
  '_Sin bis. La vergüenza es parte del servicio, joder_',
  '_El bot firmó. Tú puedes alegar; los números no, cabrón_',
  '_Fin de transmisión. Autoestima en modo avión forzado, gilipollas_',
  '_Cerrado el expediente. No había heroísmo que salvar, mierda_',
  '_Se terminó. El espejo del grupo no pide permiso, coño_',
  '_Última estocada. Si picó, es porque había carne, asco_',
  '_Sin terapia incluida. Solo diagnóstico en voz alta, patético_',
  '_Cierre. El ranking de dignidad no te debió favores, basura_',
  '_Acta listo. El ego puede presentar recurso en el vacío, ridículo_',
  '_Fin. Menos cuento, más contador, fracasado_',
  '_Y así queda el retrato. No es arte: es evidencia, joder_',
  '_Sin retorno elegante. Solo la salida por la puerta del hilo, cabrón_',
  '_Cerrado. La autoestima que vivía de no ser medida acaba de ser pesada, gilipollas_',
  '_El roast hizo su trabajo. El resto es tuyo, mierda_',
  '_Fin del desfile. Baja del escenario aunque nadie aplaudió, coño_',
  '_Documentado sin anestesia. Duele y basta, asco_',
  '_Última palabra del bot. La tuya ya ocupó demasiado espacio, patético_',
  '_Cierre limpio. Daño al relato personal, permanente, basura_',
  '_Se acabó el turno. El ego puede guardarse el discurso, ridículo_',
  '_Archivo sellado. No hay edición posterior que salve el frame, fracasado_',
  '_Sin indulto. El chat no es un tribunal amigo, joder_',
  '_Fin. Lo que queda es el eco y la cuenta de mensajes, cabrón_',
  '_Cerrado con llave. La autoestima no tiene copia, gilipollas_',
  '_El veredicto no pedía tu aprobación, mierda_',
  '_Última línea sin consuelo. Trágala o repítela, coño_',
  '_Se terminó. El grupo ya pasó de largo con la lección, asco_',
  '_Acta completa. Ego en dieta obligatoria, patético_',
  '_Fin del roast. No fue personal: fue estadística con filo, basura_',
  '_Sin maquillaje final. El retrato se queda así, ridículo_',
  '_Cierre. Puedes reírte; el número no, fracasado_',
  '_Y punto final. Menos aura inventada, más realidad, joder_',
];

function getActivityPhrases(count) {
  const c = fmt(count);

  if (count === 0) {
    return [
      'CERO mensajes. Ni uno. Entras, espías, te pirás y no dejas prueba de vida útil. No es timidez, %N: es parasitismo digital de manual. Consumes lo que otros producen y tu autoestima vive de no arriesgarse a quedar en evidencia.',
      'El contador marca cero, %N. Ni una sílaba. Llevas aquí el tiempo suficiente para que eso ya no sea discreción: es no existir. Un fantasma que se cree interesante por callar.',
      'Cero mensajes, %N. El mirón del grupo. Lo lees todo y no aportas una puta mierda. Nadie te echa de menos porque nadie tiene material para recordarte. Ego de misterio, realidad de silla vacía.',
      'Ni un solo mensaje, %N. El grupo no tiene prueba de que existes. Nombre en la lista, espacio ocupado, valor cero. Tu autoestima se esconde detrás del silencio porque el texto te delataría.',
      'Cero textos, %N. Máximo nivel de gorrón: consumir todo y no dar nada. Estás en cuarenta grupos igual de muerto. La pereza de teclear es el disfraz de no tener nada que valga la pena.',
      'Sin un solo mensaje y ahí sigues pegado, %N. Eso ya no es introversión: es no tener una puta cosa útil que decir y no tener los cojones de largarte. Fantasma-lapa. El ego prefiere invisibilidad a juicio.',
      'Cero mensajes confirmados, %N. Tiempo de sobra para haber soltado algo. No lo hiciste. No es humildad: es vacío. La autoestima te dice que callar te hace profundo; el contador dice que sobras.',
      'El historial dice cero y no miente, %N. Eres el miembro que hincha la lista sin hinchar el chat. Bulto. Decoración. Tu valor aquí es el mismo que el de una silla sin nadie.',
      'Ni respuesta, ni pregunta, ni signo de vida, %N. Cero. Un cero a la izquierda con número de teléfono. La definición del que sobra y encima se cree discreto por no aportar.',
      'Cero mensajes, %N. Estar en un grupo de conversación sin conversar nunca. Inutilidad con estética de misterio. El ego lo vende como selectividad; el grupo lo lee como nada.',
      'Sin un mensaje, %N. Presente en la lista, ausente en todo lo demás. La forma más barata de pertenecer. Tu autoestima no resiste el riesgo de escribir y quedar expuesto.',
      'No existe un solo mensaje tuyo, %N. En un grupo de comunicación eso dice una cosa: no tienes nada que comunicar y ni la decencia de irte. Basura digital con orgullo de fantasma.',
      'Cero. %N ocupa plaza que alguien con algo que decir aprovecharía. Asiento vacío que respira. El inútil de catálogo que sobra y no se entera.',
      'El contador en cero es el resumen de tu valor aquí, %N. No hay subtexto profundo: hay ausencia. El ego prefiere inventar profundidad a arriesgar un texto.',
      'Cero mensajes, %N. El grupo tomó nota: prescindible con datos. Si desapareces mañana no hay hueco que tapar. Eso debería bajar un poco el auto-concepto.',
    ];
  }

  if (count < 20) {
    return [
      `${c} mensajes en total, %N. Todo lo que has aportado cabe en una pantalla. Decoración de fantasma de medio pelo. La autoestima te dice que menos es más; aquí menos es nada.`,
      `Con ${c} mensajes ocupas una plaza que alguien con voz aprovecharía, %N. Asiento vacío que respira. Sobras y el ego no procesa el dato.`,
      `${c} mensajes, %N. Cifra del que no le importa el grupo pero tampoco tiene otro sitio donde fingir pertenencia. Prescindible documentado.`,
      `${c} textos en el historial, %N. Lo justo para confirmar que existes, insuficiente para que a alguien le importe si te borras. Fantasma con wifi.`,
      `${c} mensajes, %N. El número le dice al grupo cuánto te importa estar: una mierda. Y se nota desde el primer registro.`,
      `Con ${c} mensajes tienes historial de quien entró por error y se quedó por inercia, %N. Sin motivo para aportar. Sin motivo para que te pidan nada. Sobras.`,
      `${c} textos, %N. Lo que dejas al irte es lo mismo que dejas al estar: nada. El fantasma más inútil del ranking de presencia.`,
      `${c} mensajes, %N. Cifra del que no considera que el grupo merezca su tiempo pero no tiene plan B. Don nadie por descarte.`,
      `Con ${c} mensajes eres estadísticamente de lo más prescindible del grupo, %N. No el más silencioso con estilo: el más inútil sin estética.`,
      `${c} mensajes, %N. Suficiente para no ser cero del todo, insuficiente para importar. Gris puro. La autoestima busca misterio donde solo hay flojera.`,
      `${c} textos, %N. El grupo no te cita porque no hay qué citar. Existir sin dejar marca es tu especialidad.`,
      `Con ${c} mensajes llevas el perfil del que mira de lejos y se cree por encima del ruido. No estás por encima: estás fuera sin gloria.`,
      `${c} mensajes, %N. La autoestima te vende selectividad; el contador vende desinterés. El chat se queda con el contador.`,
      `${c} en el historial. %N, ni para ser un buen fantasma: hasta el silencio te queda a medias.`,
      `${c} mensajes, %N. El ego necesita creer que callar es poder. Aquí callar es evaporarte.`,
    ];
  }

  if (count < 60) {
    return [
      `${c} mensajes, %N. El que lo lee TODO y no aporta NADA. Espectador que consume el trabajo ajeno y se esconde cuando toca poner algo. Parásito con autoestima de crítico.`,
      `Con ${c} mensajes estás en la zona muerta del que está pero no cuenta, %N. Ni fantasma limpio ni parte de nada memorable. Gris prescindible. Sobras a medias y el ego lo niega.`,
      `${c} putos textos, %N. Justo debajo del umbral donde alguien empieza a importar. Sigues siendo número de lista, no persona con peso. Don nadie de manual.`,
      `${c} mensajes y el grupo sigue sin saber qué coño pintas, %N. Suficiente para molestar el contador, insuficiente para justificar el hueco.`,
      `Con ${c} mensajes eres el casi del chat: casi presente, casi útil, casi olvidable. El ego odia el casi; el grupo se acostumbró.`,
      `${c} textos, %N. Actividad de quien quiere figurar sin arriesgar opinión que duela. Cobardía disfrazada de mesura.`,
      `${c} mensajes, %N. El ranking te ve; el hilo no te necesita. Esa brecha debería bajar el auto-concepto.`,
      `Con ${c} mensajes aportas lo justo para no ser borrado y lo poco para ser recordado. Estrategia de mediocre con ego frágil.`,
      `${c} mensajes, %N. Presencia tibia. Ni te extrañan del todo ni te celebran. El limbo del que no se atreve a valer.`,
      `${c} textos y cero citas que importen, %N. Hablar sin dejar eco es tu deporte. La autoestima inventa profundidad, el chat mide silencio posterior.`,
      `Con ${c} mensajes ocupas el hueco del relleno humano, %N. Hace falta gente así para que el resto brille. No es un cumplido.`,
      `${c} mensajes, %N. El ego lee actividad; el grupo lee irrelevancia funcional. Dos lecturas, una verdad.`,
      `${c} en el contador. %N, casi invisible, casi ruidoso, totalmente prescindible en lo que importa.`,
      `${c} mensajes, %N. Suficiente historial para haber dicho una cosa memorable. No llegó. La oportunidad se fue y tu autoestima no se enteró.`,
      `Con ${c} textos eres el ejemplo del que está sin estar, %N. El chat funciona igual contigo o sin ti. Procesa eso.`,
    ];
  }

  if (count >= 150) {
    return [
      `${c} mensajes, %N. Eso no es ruido: es el motor del puto grupo. Sin gente como tú el hilo se muere de pie.`,
      `Con ${c} mensajes %N sostiene el chat de verdad. El contador no regala ese puesto: se farmea escribiendo.`,
      `${c} textos, %N. Actividad de las que mantienen vivo un grupo. El resto mira; tú empujas el hilo.`,
      `${c} mensajes y se nota quién no abandona el barco, %N. Eso vale más que diez perfiles silenciosos.`,
      `Con ${c} mensajes convertiste el chat en un sitio donde pasa algo. Eso se respeta, aunque no se diga cada día.`,
      `${c} mensajes, %N. El ranking de presencia te pone arriba porque te lo curraste. Sigue así, el grupo lo necesita.`,
      `${c} textos. %N es de los que no dejan morir la conversación. Ese hábito vale oro en un grupo.`,
      `Con ${c} mensajes ya no eres un nombre en la lista: eres parte del clima. Y el clima lo hacen los activos.`,
      `${c} mensajes, %N. Relevancia ganada a base de estar. El fantasma envidia ese número en silencio.`,
      `${c} en el historial. %N, el grupo se nota distinto cuando faltas. Eso solo pasa con quien aporta de verdad.`,
      `Con ${c} mensajes eres de los fijos que sostienen el peaje diario del hilo. Gracias por no ser decoración.`,
      `${c} textos, %N. Presencia real. Mientras otros miran, tú escribes. Así se construye un grupo que no aburre.`,
      `${c} mensajes. %N se plantó y no se fue. Constancia de residente útil, no de turista.`,
      `Con ${c} mensajes el ranking te corona por actividad. La corona aquí se gana tecleando, no presumiendo.`,
      `${c} mensajes, %N. El chat te tiene fichado como de los que tiran del carro. Ese fichaje es un cumplido.`,
      `${c} textos y el hilo te debe horas de vida, %N. Sin activos como tú esto sería un cementerio ordenado.`,
      `Con ${c} mensajes cargaste el grupo a hombros más de una vez. Se nota quién está cuando hace falta ruido bueno.`,
      `${c} mensajes, %N. Saturación productiva. El exceso aquí no estorba: mantiene el pulso.`,
      `${c} en el contador. %N, saber quedarse y aportar es una forma de liderazgo silencioso.`,
      `Con ${c} mensajes convertiste cantidad en hábito de presencia. Ese hábito es lo que el grupo debería copiar.`,
      `${c} mensajes, %N. El número te respalda con orgullo legítimo: te lo trabajaste mensaje a mensaje.`,
      `${c} textos. %N es parte del motor, no del relleno. La diferencia se ve en el historial.`,
      `Con ${c} mensajes ya eres estadística gruesa de los buenos. Las columnas altas sostienen la tabla.`,
      `${c} mensajes, %N. Importante porque estás. Estar cuando el resto flaquea es valor real de grupo.`,
      `${c} textos sin freno útil, %N. La insistencia bien puesta construye comunidad.`,
      `Con ${c} mensajes el hilo te reconoce al vuelo. Reconocer al activo es lo mínimo.`,
      `${c} mensajes, %N. El número te respalda. No es muleta: es prueba de que este chat te importa.`,
      `${c} en el pecho del contador. %N, medalla ganada a base de no desaparecer. Se respeta.`,
      `Con ${c} mensajes ocupas el centro porque lo llenaste de actividad. El micrófono te lo ganaste.`,
      `${c} mensajes, %N. Relevancia de quien no deja el hilo en modo fantasma. Ejemplo a seguir.`,
      `${c} mensajes, %N. Si el grupo respira, es porque gente como tú no cierra el teclado.`,
      `Con ${c} textos %N demuestra que el ranking se puede ganar sin drama: solo escribiendo.`,
      `${c} mensajes. Top de presencia merecido. El resto puede quejarse o ponerse a farmear.`,
      `${c} en el marcador, %N. Actividad de la que hace que un grupo no se pudra en silencio.`,
      `Con ${c} mensajes eres el antídoto del cementerio digital. Sigue, hace falta.`,
      `${c} textos, %N. El chat gana cada vez que decides no ser un perfil decorativo.`,
      `${c} mensajes y contando. %N no vino a mirar: vino a empujar el hilo hacia adelante.`,
      `Con ${c} mensajes el contador te da la razón en una cosa: aquí se te ve el compromiso.`,
      `${c} mensajes, %N. Más activo que la media y se nota en la salud del grupo. Eso importa.`,
      `${c} textos. %N, el fantasma promedio no llega ni a la mitad de eso. Hay nivel.`
    ];
  }

  return [
      `${c} mensajes, %N. Estás en la franja donde ya no eres fantasma y todavía no eres peso. El limbo del ego inseguro.`,
      `Con ${c} mensajes aportas lo suficiente para que no te borren y lo poco para que te nombran con entusiasmo.`,
      `${c} textos, %N. Actividad de quien prueba suerte sin jugarse el tipo. La autoestima evita el riesgo del texto memorable.`,
      `${c} mensajes y el grupo aún negocia si importas. Esa negociación debería humillar un poco.`,
      `Con ${c} mensajes eres el relleno intermedio: ni heroína del hilo ni cero. El gris con wifi.`,
      `${c} textos, %N. Historial de quien podría haber dejado marca y prefirió no arriesgar el ego.`,
      `${c} mensajes. %N aparece, comenta, se esfuma del significado. Presente sin consecuencia.`,
      `Con ${c} mensajes tienes material para un perfil y no para una leyenda. El ego elige leyenda igual.`,
      `${c} mensajes, %N. Suficiente para ser visto, insuficiente para ser necesario. La diferencia duele si eres honesto.`,
      `${c} textos y cero momentos que alguien repita, %N. Hablar sin eco es tu zona de confort.`,
      `Con ${c} mensajes el contador te da carnet de miembro y el hilo te da carnet de extra.`,
      `${c} mensajes, %N. El ego quiere más; el contenido no empuja. Fricción visible, miserable.`,
      `${c} en el historial. %N, mitad presencia, mitad relleno. El chat lo nota sin decirlo, qué cringe.`,
      `${c} mensajes, %N. Actividad correcta de quien no quiere quedar en evidencia ni brillar, da asco.`,
      `Con ${c} textos estás a un paso de importar y a un paso de diluirte. El ego no elige: se queda en medio, qué vergüenza.`,
  ];
}

const OWNER_ROAST = [
  '%N, el creído de mierda que se cree por encima de todo el grupo. Y lo que más jode es que las veces que abres la boca sueles tener razón. Ego insoportable. Baja de la nube, prepotente.',
  'Mira el señor perfecto, %N. Ese aire de que nada se te escapa y de que el resto te debe algo. Un arrogante de manual al que no hay por dónde rebatirle una mierda. Insufrible, de verdad.',
  '%N, hijo de puta con suerte, al que todo le sale redondo sin despeinarse mientras los demás sudan. Y encima con esa cara de superioridad. Que te den, listillo.',
  'El típico prepotente, %N: hablas poco para que parezca que lo tuyo vale oro, y el grupo pica y se calla cuando apareces. Manipulador de mierda con complejo de líder. Bájale.',
  '%N, ego del tamaño de un edificio y la desfachatez de respaldarlo casi siempre. Da una rabia tremenda que un creído como tú acierte tanto. Insoportable.',
  'Aquí el que se cree el más vivo del grupo, %N. Siempre un paso por delante y restregándolo con esa sonrisita de listo. Odioso. Ojalá te equivocaras una vez, prepotente.',
  '%N, el clásico sabelotodo que no aguanta nadie: siempre con la respuesta, siempre quedando por encima, siempre con ese aire de superioridad de mierda. Trágate el ego un día.',
  'Qué pesado eres, %N, con tu maldita costumbre de tener razón. El grupo está harto de que un creído como tú quede bien hasta sin intentarlo. Que te calles un rato, listillo.',
  '%N, arrogante de manual, con un ego que te sale por las orejas y que encima está medio justificado, que es lo que más jode. Insoportable verte tan pagado de ti mismo. y acertar. Bájale.',
  'El intocable del grupo, %N. Ese que se cree por encima de todos y al que, para colmo, nadie consigue rebatir. Prepotente insufrible. Un día te caes y lo celebramos, listo de mierda.',
  '%N, el creído que va de sobrado por la vida y que, para desgracia de todos, casi siempre le sale la jugada. Ego insoportable, actitud de rey de mierda. Que alguien te baje los humos ya.',
  'Mírate, %N, con ese complejo de superioridad y esa manía de tener razón que saca de quicio a cualquiera. Un prepotente de libro. Lo peor es que no podemos ni desmentirte. Insufrible, hijo de puta.',
  '%N, el que se cree imprescindible y lo peor es que medio grupo le da la razón. Prepotente de mierda con permiso del público. Alguien debería quitarle el micrófono.',
  'El puto amo del grupo, %N. Ese al que le molesta que el resto no piense tan rápido. La paciencia de un líder la tiene, la humildad ni de lejos. Sobrado.',
  '%N, siempre con la última palabra y siempre acertando. Qué asco da que alguien tan insoportable tenga razón tan a menudo. Ojalá te equivocaras una puta vez, prepotente.',
  'Aquí viene %N a iluminar al grupo con su puta sabiduría. Lo peor no es que se crea mejor que todos: es que nadie puede decirle lo contrario sin quedar como un imbécil.',
  '%N, con esa cara de listo de mierda. y ese historial de aciertos que le da permiso para ser insufrible. Ego descomunal y medio justificado, que es la combinación más odiosa que existe.',
  'El problema de %N es que se cree el más listo del grupo. Y el problema del grupo es que probablemente lo sea. Prepotente, arrogante y con la razón de su parte. Insoportable, hijo de puta.',
  '%N, el que habla cuando le da la gana y siempre parece que dice lo importante. Los demás hablan para rellenar. Tú hablas para dejar claro que estás por encima. Sobrado de mierda.',
  'Mira el señorito %N. Todo controlado, todo calculado, todo con esa superioridad de quien sabe que el resto no llega. Y lo peor es que no llega, cabrón. Insufrible con razón.',
  '%N, esa arrogancia tuya es de las que generan rencor. Pero el rencor no te quita la razón y eso es lo que realmente jode al grupo entero.',
  'El que manda sin mandar, %N. El que opina poco y acierta siempre. El que calla y el grupo se pregunta qué piensa. Prepotente por omisión, que es la peor clase de prepotente.',
  '%N, el cabrón más pagado de sí mismo de todo el grupo. Y lo peor es que tiene con qué pagarse. Ego justificado es ego peligroso.',
  'El owner de turno, %N, con el aura de quien no necesita pedir permiso. Qué asco de privilegio bien usado.',
  '%N se cree el centro del chat y el contador a veces le hace el favor. asco. Y el grupo lo tiene claro.',
  'Ahí va %N, repartiendo juicio como quien reparte pan. El pan es castigo, patético. Y el grupo lo tiene claro.',
  '%N, el intocable de broma que resulta no ser tan broma, basura. Y el grupo lo tiene claro, joder asco.',
  'Cuando %N habla, el grupo mide dos veces. No por respeto: por cálculo, ridículo. Y el grupo lo tiene claro.',
  '%N tiene el privilegio y encima lo disfruta. El resto mira, fracasado. Y el grupo lo tiene claro.',
  'El puto %N otra vez en modo diésel: avanza y no pregunta, joder. Y el grupo lo tiene claro, joder fracasado.',
  '%N, creído con evidencia. Lo peor de las dos cosas, cabrón. Y el grupo lo tiene claro, joder.',
  'Míralo a %N: suerte, ego y el chat de testigo, gilipollas. Y el grupo lo tiene claro, joder mierda.',
  '%N no pide la corona. Actúa como si ya la llevara, mierda. Y el grupo lo tiene claro, joder coño.',
  'El grupo aguanta a %N porque el ranking a veces no deja otra, coño. Y el grupo lo tiene claro.',
  '%N, privilegiado de los que ni disimulan el desprecio suave, asco. Y el grupo lo tiene claro, joder gilipollas.',
  'Cuando cae el roast sobre %N, el universo parpadea y sigue, patético. Y el grupo lo tiene claro.',
  '%N se cree incombustible. El chat tiene fósforos, basura. Y el grupo lo tiene claro, joder asco.',
  'Ahí está %N, invicto por reglamento y por cara, ridículo. Y el grupo lo tiene claro, joder basura.',
  '%N, el jefe oficioso del hilo. Nadie votó, fracasado. Y el grupo lo tiene claro, joder ridículo.',
  'El aura de %N viene con seguro a todo riesgo, joder. Y el grupo lo tiene claro, joder fracasado.',
  '%N habla y el resto traduce a privilegio, cabrón. Y el grupo lo tiene claro, joder.',
  'Mira quién no necesita pedir perdón: %N, gilipollas. Y el grupo lo tiene claro, joder mierda.',
  '%N, sortudo con manual de instrucciones de creído, mierda. Y el grupo lo tiene claro, joder coño.',
  'El chat le hace el caldo a %N y él ni agradece, coño. Y el grupo lo tiene claro, joder cabrón.',
  '%N en modo intocable. El roast es el peaje simbólico, asco. Y el grupo lo tiene claro, joder gilipollas.',
  'Cuando %N pierde, es noticia. Cuando gana, es el clima, patético. Y el grupo lo tiene claro, joder patético.',
  '%N, el favorito del RNG y de su propio espejo, basura. Y el grupo lo tiene claro, joder asco.',
  'Ahí va el puto %N otra vez, sin pedir turno, ridículo. Y el grupo lo tiene claro, joder basura.',
  '%N se cree el final boss. El grupo es el tutorial, fracasado. Y el grupo lo tiene claro, joder ridículo.',
  'Privilegio con nombre de usuario: %N, joder. Y el grupo lo tiene claro, joder fracasado.',
  '%N en modo intocable. El roast es el único peaje simbólico, asco.',
  'Privilegio con nombre de usuario: %N, y se nota en cada mensaje, joder.',
  '%N reparte veredictos como quien regala stickers, cabrón.',
  'El ego de %N tiene más aura que medio ranking junto, gilipollas.',
  '%N no baja del pedestal ni para atarse los cordones, mierda.',
  'Con %N el chat practica la paciencia a la fuerza, coño.',
  '%N, el que nunca pide contexto porque el contexto es él, asco.',
  'Suerte de %N y cara de %N: combo ilegal en tres países, patético.',
  '%N gana y el grupo finge que era obvio, basura.',
  'El roast a %N es el deporte de riesgo del hilo, ridículo.',
  '%N, intocable de facto y creído de derecho, fracasado.',
  'Cuando %N entra, el tono del chat cambia de gravidez, joder.',
  '%N no necesita introducción: el privilegio ya lo presenta, cabrón.',
  'Mira a %N, campeón de las excepciones, gilipollas.',
  '%N tiene el manual del que siempre aterriza de pie, mierda.',
  'El grupo es el público cautivo de %N, coño.',
  '%N, ego con wifi y cobertura total, asco.',
  'Nadie votó a %N. El ranking a veces sí, patético.',
  '%N disfruta el papel y no lo esconde, basura.',
  'El puto aura de %N molesta hasta cuando calla, ridículo.',
  '%N es el DLC pago que el grupo no pidió, fracasado.',
  'Con %N el rest del chat juega en otra liga de respeto forzado, joder.',
  '%N, sortudo con manual de instrucciones de creído, mierda coño.',
  'El chat le hace el caldo a %N y él ni agradece el cubierto, coño cabrón.',
  '%N en modo intocable. El roast es el único peaje simbólico, asco gilipollas.',
  'Cuando %N pierde, es noticia. Cuando gana, es el clima del grupo, patético.',
  '%N, el favorito del RNG y de su propio espejo, basura asco.',
  'Ahí va el puto %N otra vez, sin pedir turno en el hilo, ridículo basura.',
  '%N se cree el final boss. El grupo es el tutorial eterno, fracasado ridículo.',
  'Privilegio con nombre de usuario: %N, y se nota en cada mensaje, joder fracasado.',
  '%N reparte veredictos como quien regala stickers, cabrón joder.',
  'El ego de %N tiene más aura que medio ranking junto, gilipollas mierda.',
  '%N no baja del pedestal ni para atarse los cordones, mierda coño.',
  'Con %N el chat practica la paciencia a la fuerza, coño cabrón.',
  '%N, el que nunca pide contexto porque el contexto es él, asco gilipollas.',
  'Suerte de %N y cara de %N: combo ilegal en tres países, patético.',
  '%N gana y el grupo finge que era obvio, basura asco.',
  'El roast a %N es el deporte de riesgo del hilo, ridículo basura.',
  '%N, intocable de facto y creído de derecho, fracasado ridículo.',
  'Cuando %N entra, el tono del chat cambia de gravidez, joder fracasado.',
  '%N no necesita introducción: el privilegio ya lo presenta, cabrón joder.',
  'Mira a %N, campeón de las excepciones, gilipollas mierda.',
  '%N tiene el manual del que siempre aterriza de pie, mierda coño.',
  'El grupo es el público cautivo de %N, coño cabrón.',
  '%N, ego con wifi y cobertura total, asco gilipollas.',
  'Nadie votó a %N. El ranking a veces sí, patético.',
  '%N disfruta el papel y no lo esconde, basura asco.',
  'El puto aura de %N molesta hasta cuando calla, ridículo basura.',
  '%N es el DLC pago que el grupo no pidió, fracasado ridículo.',
  'Con %N el rest del chat juega en otra liga de respeto forzado, joder fracasado.',
];

const COUNTRY_ROAST = {
  MX: {
    name: 'México',
    lines: [
    '%N, prefijo de %PAIS y el pack completo de vergüenza exportable. Clásico de México en el grupo, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.',
    '%N, pack %PAIS: pose nacional, vergüenza internacional, ridículo.',
    'Código de %PAIS en el número y de relleno en el hilo, %N, fracasado.',
    '%N exporta de %PAIS ofensa rápida y criterio lento, qué miseria.',
    'Clásico combo %PAIS: mucho nosotros, poco yo responsable, %N, basura.',
    '%N, si el chat cobrara arancel por cringe, %PAIS pagaría por ti, qué cutre.',
    '%N de %PAIS: unisex en el ridículo, da pena ajena.',
    'Prefijo %PAIS y software de ser el centro sin material, %N, indignante.',
    'De %PAIS, %N. El bot solo leyó el código y ya sabía el nivel, qué flojo.',
    '%N, misión fallida de %PAIS en este grupo, menudo desastre.',
    'Número de %PAIS: predecible hasta el aburrimiento, %N, qué pena.',
    '%N, %PAIS en el SIM y el vacío en el argumento, da vergüenza.',
    'Embajada del cringe con sello de %PAIS, %N, qué vergüenza ajena.',
    'Clásico %PAIS en modo grupo: ruido, pose y poco más, %N, patético.',
    '%N representa el lote flojo de %PAIS, miserable.',
    'Prefijo %PAIS, resultado de catálogo, %N, qué cringe.',
    'De %PAIS para el hilo: %N, tutorial de cómo no aportar, da asco.',
    '%N, orgullo de %PAIS mal invertido, qué vergüenza.',
    'Código %PAIS y talento para cansar, %N, ridículo.',
    '%N exporta de %PAIS la costumbre de no mirarse al espejo, fracasado.',
    'Producto %PAIS: etiqueta grande, contenido chico, %N, qué miseria.',
    '%N, de %PAIS y del ranking de prescindibles, basura.',
    'El estereotipo de %PAIS te eligió sin concurso, %N, qué cutre.',
    '%N hace equipo con el cliché de %PAIS y pierde, da pena ajena.',
    'Prefijo de %PAIS: el bot no se sorprendió, %N, indignante.',
    'De %PAIS, %N. Soft power del ridículo, qué flojo.',
    '%N, %PAIS no te debe este espacio, menudo desastre.',
    'Número %PAIS y ego de importación paralela, %N, qué pena.',
    '%N, el chat no es tu consulado de %PAIS, da vergüenza.',
    'Clásico final %PAIS: %N confirma el prejuicio del prefijo, qué vergüenza ajena.',
    'Prefijo %PAIS, veredicto cerrado, %N, patético.'
    ],
  },
  BR: {
    name: 'Brasil',
    lines: [
    '%N, prefijo de %PAIS y el pack completo de vergüenza exportable. Clásico de Brasil en el grupo, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.',
    '%N, pack %PAIS: pose nacional, vergüenza internacional, ridículo.',
    'Código de %PAIS en el número y de relleno en el hilo, %N, fracasado.',
    '%N exporta de %PAIS ofensa rápida y criterio lento, qué miseria.',
    'Clásico combo %PAIS: mucho nosotros, poco yo responsable, %N, basura.',
    '%N, si el chat cobrara arancel por cringe, %PAIS pagaría por ti, qué cutre.',
    '%N de %PAIS: unisex en el ridículo, da pena ajena.',
    'Prefijo %PAIS y software de ser el centro sin material, %N, indignante.',
    'De %PAIS, %N. El bot solo leyó el código y ya sabía el nivel, qué flojo.',
    '%N, misión fallida de %PAIS en este grupo, menudo desastre.',
    'Número de %PAIS: predecible hasta el aburrimiento, %N, qué pena.',
    '%N, %PAIS en el SIM y el vacío en el argumento, da vergüenza.',
    'Embajada del cringe con sello de %PAIS, %N, qué vergüenza ajena.',
    'Clásico %PAIS en modo grupo: ruido, pose y poco más, %N, patético.',
    '%N representa el lote flojo de %PAIS, miserable.',
    'Prefijo %PAIS, resultado de catálogo, %N, qué cringe.',
    'De %PAIS para el hilo: %N, tutorial de cómo no aportar, da asco.',
    '%N, orgullo de %PAIS mal invertido, qué vergüenza.',
    'Código %PAIS y talento para cansar, %N, ridículo.',
    '%N exporta de %PAIS la costumbre de no mirarse al espejo, fracasado.',
    'Producto %PAIS: etiqueta grande, contenido chico, %N, qué miseria.',
    '%N, de %PAIS y del ranking de prescindibles, basura.',
    'El estereotipo de %PAIS te eligió sin concurso, %N, qué cutre.',
    '%N hace equipo con el cliché de %PAIS y pierde, da pena ajena.',
    'Prefijo de %PAIS: el bot no se sorprendió, %N, indignante.',
    'De %PAIS, %N. Soft power del ridículo, qué flojo.',
    '%N, %PAIS no te debe este espacio, menudo desastre.',
    'Número %PAIS y ego de importación paralela, %N, qué pena.',
    '%N, el chat no es tu consulado de %PAIS, da vergüenza.',
    'Clásico final %PAIS: %N confirma el prejuicio del prefijo, qué vergüenza ajena.',
    'Prefijo %PAIS, veredicto cerrado, %N, patético.'
    ],
  },
  CO: {
    name: 'Colombia',
    lines: [
    '%N, prefijo de %PAIS y el pack completo de vergüenza exportable. Clásico de Colombia en el grupo, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.',
    '%N, pack %PAIS: pose nacional, vergüenza internacional, ridículo.',
    'Código de %PAIS en el número y de relleno en el hilo, %N, fracasado.',
    '%N exporta de %PAIS ofensa rápida y criterio lento, qué miseria.',
    'Clásico combo %PAIS: mucho nosotros, poco yo responsable, %N, basura.',
    '%N, si el chat cobrara arancel por cringe, %PAIS pagaría por ti, qué cutre.',
    '%N de %PAIS: unisex en el ridículo, da pena ajena.',
    'Prefijo %PAIS y software de ser el centro sin material, %N, indignante.',
    'De %PAIS, %N. El bot solo leyó el código y ya sabía el nivel, qué flojo.',
    '%N, misión fallida de %PAIS en este grupo, menudo desastre.',
    'Número de %PAIS: predecible hasta el aburrimiento, %N, qué pena.',
    '%N, %PAIS en el SIM y el vacío en el argumento, da vergüenza.',
    'Embajada del cringe con sello de %PAIS, %N, qué vergüenza ajena.',
    'Clásico %PAIS en modo grupo: ruido, pose y poco más, %N, patético.',
    '%N representa el lote flojo de %PAIS, miserable.',
    'Prefijo %PAIS, resultado de catálogo, %N, qué cringe.',
    'De %PAIS para el hilo: %N, tutorial de cómo no aportar, da asco.',
    '%N, orgullo de %PAIS mal invertido, qué vergüenza.',
    'Código %PAIS y talento para cansar, %N, ridículo.',
    '%N exporta de %PAIS la costumbre de no mirarse al espejo, fracasado.',
    'Producto %PAIS: etiqueta grande, contenido chico, %N, qué miseria.',
    '%N, de %PAIS y del ranking de prescindibles, basura.',
    'El estereotipo de %PAIS te eligió sin concurso, %N, qué cutre.',
    '%N hace equipo con el cliché de %PAIS y pierde, da pena ajena.',
    'Prefijo de %PAIS: el bot no se sorprendió, %N, indignante.',
    'De %PAIS, %N. Soft power del ridículo, qué flojo.',
    '%N, %PAIS no te debe este espacio, menudo desastre.',
    'Número %PAIS y ego de importación paralela, %N, qué pena.',
    '%N, el chat no es tu consulado de %PAIS, da vergüenza.',
    'Clásico final %PAIS: %N confirma el prejuicio del prefijo, qué vergüenza ajena.',
    'Prefijo %PAIS, veredicto cerrado, %N, patético.'
    ],
  },
  AR: {
    name: 'Argentina',
    lines: [
    '%N, prefijo de %PAIS y el pack completo de vergüenza exportable. Clásico de Argentina en el grupo, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.',
    '%N, pack %PAIS: pose nacional, vergüenza internacional, ridículo.',
    'Código de %PAIS en el número y de relleno en el hilo, %N, fracasado.',
    '%N exporta de %PAIS ofensa rápida y criterio lento, qué miseria.',
    'Clásico combo %PAIS: mucho nosotros, poco yo responsable, %N, basura.',
    '%N, si el chat cobrara arancel por cringe, %PAIS pagaría por ti, qué cutre.',
    '%N de %PAIS: unisex en el ridículo, da pena ajena.',
    'Prefijo %PAIS y software de ser el centro sin material, %N, indignante.',
    'De %PAIS, %N. El bot solo leyó el código y ya sabía el nivel, qué flojo.',
    '%N, misión fallida de %PAIS en este grupo, menudo desastre.',
    'Número de %PAIS: predecible hasta el aburrimiento, %N, qué pena.',
    '%N, %PAIS en el SIM y el vacío en el argumento, da vergüenza.',
    'Embajada del cringe con sello de %PAIS, %N, qué vergüenza ajena.',
    'Clásico %PAIS en modo grupo: ruido, pose y poco más, %N, patético.',
    '%N representa el lote flojo de %PAIS, miserable.',
    'Prefijo %PAIS, resultado de catálogo, %N, qué cringe.',
    'De %PAIS para el hilo: %N, tutorial de cómo no aportar, da asco.',
    '%N, orgullo de %PAIS mal invertido, qué vergüenza.',
    'Código %PAIS y talento para cansar, %N, ridículo.',
    '%N exporta de %PAIS la costumbre de no mirarse al espejo, fracasado.',
    'Producto %PAIS: etiqueta grande, contenido chico, %N, qué miseria.',
    '%N, de %PAIS y del ranking de prescindibles, basura.',
    'El estereotipo de %PAIS te eligió sin concurso, %N, qué cutre.',
    '%N hace equipo con el cliché de %PAIS y pierde, da pena ajena.',
    'Prefijo de %PAIS: el bot no se sorprendió, %N, indignante.',
    'De %PAIS, %N. Soft power del ridículo, qué flojo.',
    '%N, %PAIS no te debe este espacio, menudo desastre.',
    'Número %PAIS y ego de importación paralela, %N, qué pena.',
    '%N, el chat no es tu consulado de %PAIS, da vergüenza.',
    'Clásico final %PAIS: %N confirma el prejuicio del prefijo, qué vergüenza ajena.',
    'Prefijo %PAIS, veredicto cerrado, %N, patético.'
    ],
  },
  PE: {
    name: 'Perú',
    lines: [
    '%N, prefijo de %PAIS y el pack completo de vergüenza exportable. Clásico de Perú en el grupo, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.',
    '%N, pack %PAIS: pose nacional, vergüenza internacional, ridículo.',
    'Código de %PAIS en el número y de relleno en el hilo, %N, fracasado.',
    '%N exporta de %PAIS ofensa rápida y criterio lento, qué miseria.',
    'Clásico combo %PAIS: mucho nosotros, poco yo responsable, %N, basura.',
    '%N, si el chat cobrara arancel por cringe, %PAIS pagaría por ti, qué cutre.',
    '%N de %PAIS: unisex en el ridículo, da pena ajena.',
    'Prefijo %PAIS y software de ser el centro sin material, %N, indignante.',
    'De %PAIS, %N. El bot solo leyó el código y ya sabía el nivel, qué flojo.',
    '%N, misión fallida de %PAIS en este grupo, menudo desastre.',
    'Número de %PAIS: predecible hasta el aburrimiento, %N, qué pena.',
    '%N, %PAIS en el SIM y el vacío en el argumento, da vergüenza.',
    'Embajada del cringe con sello de %PAIS, %N, qué vergüenza ajena.',
    'Clásico %PAIS en modo grupo: ruido, pose y poco más, %N, patético.',
    '%N representa el lote flojo de %PAIS, miserable.',
    'Prefijo %PAIS, resultado de catálogo, %N, qué cringe.',
    'De %PAIS para el hilo: %N, tutorial de cómo no aportar, da asco.',
    '%N, orgullo de %PAIS mal invertido, qué vergüenza.',
    'Código %PAIS y talento para cansar, %N, ridículo.',
    '%N exporta de %PAIS la costumbre de no mirarse al espejo, fracasado.',
    'Producto %PAIS: etiqueta grande, contenido chico, %N, qué miseria.',
    '%N, de %PAIS y del ranking de prescindibles, basura.',
    'El estereotipo de %PAIS te eligió sin concurso, %N, qué cutre.',
    '%N hace equipo con el cliché de %PAIS y pierde, da pena ajena.',
    'Prefijo de %PAIS: el bot no se sorprendió, %N, indignante.',
    'De %PAIS, %N. Soft power del ridículo, qué flojo.',
    '%N, %PAIS no te debe este espacio, menudo desastre.',
    'Número %PAIS y ego de importación paralela, %N, qué pena.',
    '%N, el chat no es tu consulado de %PAIS, da vergüenza.',
    'Clásico final %PAIS: %N confirma el prejuicio del prefijo, qué vergüenza ajena.',
    'Prefijo %PAIS, veredicto cerrado, %N, patético.'
    ],
  },
  VE: {
    name: 'Venezuela',
    lines: [
    '%N, prefijo de %PAIS y el pack completo de vergüenza exportable. Clásico de Venezuela en el grupo, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.',
    '%N, pack %PAIS: pose nacional, vergüenza internacional, ridículo.',
    'Código de %PAIS en el número y de relleno en el hilo, %N, fracasado.',
    '%N exporta de %PAIS ofensa rápida y criterio lento, qué miseria.',
    'Clásico combo %PAIS: mucho nosotros, poco yo responsable, %N, basura.',
    '%N, si el chat cobrara arancel por cringe, %PAIS pagaría por ti, qué cutre.',
    '%N de %PAIS: unisex en el ridículo, da pena ajena.',
    'Prefijo %PAIS y software de ser el centro sin material, %N, indignante.',
    'De %PAIS, %N. El bot solo leyó el código y ya sabía el nivel, qué flojo.',
    '%N, misión fallida de %PAIS en este grupo, menudo desastre.',
    'Número de %PAIS: predecible hasta el aburrimiento, %N, qué pena.',
    '%N, %PAIS en el SIM y el vacío en el argumento, da vergüenza.',
    'Embajada del cringe con sello de %PAIS, %N, qué vergüenza ajena.',
    'Clásico %PAIS en modo grupo: ruido, pose y poco más, %N, patético.',
    '%N representa el lote flojo de %PAIS, miserable.',
    'Prefijo %PAIS, resultado de catálogo, %N, qué cringe.',
    'De %PAIS para el hilo: %N, tutorial de cómo no aportar, da asco.',
    '%N, orgullo de %PAIS mal invertido, qué vergüenza.',
    'Código %PAIS y talento para cansar, %N, ridículo.',
    '%N exporta de %PAIS la costumbre de no mirarse al espejo, fracasado.',
    'Producto %PAIS: etiqueta grande, contenido chico, %N, qué miseria.',
    '%N, de %PAIS y del ranking de prescindibles, basura.',
    'El estereotipo de %PAIS te eligió sin concurso, %N, qué cutre.',
    '%N hace equipo con el cliché de %PAIS y pierde, da pena ajena.',
    'Prefijo de %PAIS: el bot no se sorprendió, %N, indignante.',
    'De %PAIS, %N. Soft power del ridículo, qué flojo.',
    '%N, %PAIS no te debe este espacio, menudo desastre.',
    'Número %PAIS y ego de importación paralela, %N, qué pena.',
    '%N, el chat no es tu consulado de %PAIS, da vergüenza.',
    'Clásico final %PAIS: %N confirma el prejuicio del prefijo, qué vergüenza ajena.',
    'Prefijo %PAIS, veredicto cerrado, %N, patético.'
    ],
  },
  CL: {
    name: 'Chile',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  EC: {
    name: 'Ecuador',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  GT: {
    name: 'Guatemala',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  CU: {
    name: 'Cuba',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  BO: {
    name: 'Bolivia',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  DO: {
    name: 'República Dominicana',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  HN: {
    name: 'Honduras',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  PY: {
    name: 'Paraguay',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  SV: {
    name: 'El Salvador',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  NI: {
    name: 'Nicaragua',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  CR: {
    name: 'Costa Rica',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  PA: {
    name: 'Panamá',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  UY: {
    name: 'Uruguay',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  },
  PR: {
    name: 'Puerto Rico',
    lines: [
    '%N, prefijo de %PAIS y el mismo export de mediocridad con bandera, patético.',
    'De %PAIS, %N. El estereotipo no tuvo que esforzarse contigo, qué cringe.',
    '%N representa a %PAIS en el chat: ruido local, utilidad global cero, miserable.',
    'Número de %PAIS, %N. Exportas cringe con acento, da asco.',
    '%N, de %PAIS y del club de creerse especial por el prefijo, ridículo.',
    'Clásico %PAIS: ego hinchado y aporte en dietas, %N, fracasado.',
    '%N trae de %PAIS la costumbre de ofenderse barato, qué miseria.',
    'Código %PAIS: orgullo fácil, aporte difícil, %N, basura.',
    '%N, embajador no pedido de %PAIS, qué cutre.',
    'De %PAIS, %N. Match de estereotipo, da pena ajena.',
    '%N de %PAIS: confunde identidad con personalidad, indignante.',
    'Otro de %PAIS con teclado de más, %N, qué flojo.',
    '%N, %PAIS no autorizó esta representación, menudo desastre.',
    'Prefijo de %PAIS y vacío de contenido, %N, qué pena.',
    '%N, de %PAIS y de saturar sin sumar, da vergüenza.',
    'Estereotipo %PAIS personificado: %N, qué vergüenza ajena.',
    '%N hace de %PAIS un meme sin gracia, patético.',
    'Número de %PAIS, lógica de drama importado, %N, miserable.',
    '%N, en %PAIS habrá de todo; aquí eres el lado flojo, qué cringe.',
    'De %PAIS para el grupo: %N, el prefijo no te salva, da asco.'
    ],
  }
};

function countryFromTarget(target, participant) {
  const candidates = [];
  if (participant?.phoneNumber) candidates.push(String(participant.phoneNumber));
  try {
    const can = canonicalJid(target);
    if (can) candidates.push(String(can));
  } catch (_) {}
  candidates.push(String(target || ''));

  for (const raw of candidates) {
    const digits = raw.split('@')[0].split(':')[0].replace(/\D/g, '');
    if (!digits || digits.length < 8 || digits.length > 15) continue;
    const phone = parsePhoneNumberFromString('+' + digits);
    if (phone && phone.isValid() && phone.country) {
      return { iso: phone.country, callingCode: phone.countryCallingCode };
    }
  }
  return null;
}

function pickCountryLine(iso, displayName, jid) {
  const entry = COUNTRY_ROAST[iso];
  if (!entry || !entry.lines?.length) return null;
  const line = pickFresh(entry.lines, `${jid}|roast|country|${iso}`);
  return line.replace(/%N/g, displayName).replace(/%PAIS/g, entry.name);
}

async function cmdRoast(sock, msg, groupMeta) {
  const jid = msg.key.remoteJid;
  if (!jid.endsWith('@g.us')) {
    return sock.sendMessage(jid, { text: 'Solo en grupos.' }, { quoted: msg });
  }

  const sender = getSender(msg);
  const target = getTarget(msg);
  if (!target) return;

  if (sameUser(target, sender)) {
    return sock.sendMessage(jid, {
      text: 'Roastearte a ti mismo es un nivel de autodestrucción que ni el bot va a facilitar.',
    }, { quoted: msg });
  }

  if (isMainOwner(target, false, groupMeta)) {
    const num = target.split('@')[0].split(':')[0];
    const text =
      `${pickFresh(HEADERS, `${jid}|roast|hdr`)}\n` +
      `╾━━━━━━━━━━━━━━╼\n\n` +
      `Víctima: @${num}\n\n` +
      `${pickFresh(OWNER_ROAST, `${jid}|roast|owner`).replace(/%N/g, `@${num}`)}\n\n` +
      `╾━━━━━━━━━━━━━━╼\n` +
      `${pickFresh(CLOSERS, `${jid}|roast|end`)}`;
    return sock.sendMessage(jid, { text, mentions: [target] }, { quoted: msg });
  }

  const participants = groupMeta?.participants || [];
  const participant = participants.find(p =>
    bareJid(p.id) === bareJid(target) ||
    bareJid(p.lid) === bareJid(target) ||
    bareJid(p.phoneNumber) === bareJid(target)
  );

  let targetNum = target.split('@')[0].split(':')[0];
  try {
    const can = canonicalJid(target);
    const d = String(can || '').split('@')[0].split(':')[0].replace(/\D/g, '');
    if (d && d.length >= 8 && d.length <= 15) targetNum = d;
  } catch (_) {}
  if (participant?.phoneNumber) {
    const d = String(participant.phoneNumber).split('@')[0].replace(/\D/g, '');
    if (d && d.length >= 8 && d.length <= 15) targetNum = d;
  }

  const displayName =
    participant?.name ||
    participant?.displayName ||
    participant?.verifiedName ||
    participant?.notify ||
    `@${targetNum}`;

  const msgCount = await getUserCount(jid, target);

  const activityPool = getActivityPhrases(msgCount);
  const activityText = pickFresh(activityPool, `${jid}|roast|act`)
    .replace(/%N/g, displayName)
    .replace(/%C/g, fmt(msgCount));

  const geo = countryFromTarget(target, participant);
  let countryText = '';
  if (geo?.iso && COUNTRY_ROAST[geo.iso]) {
    const line = pickCountryLine(geo.iso, displayName, jid);
    if (line) countryText = `\n\n${line}`;
  }

  const text =
    `${pickFresh(HEADERS, `${jid}|roast|hdr`)}\n` +
    `╾━━━━━━━━━━━━━━╼\n\n` +
    `Víctima: @${targetNum}\n\n` +
    `${activityText}${countryText}\\n\\n.` +
    `╾━━━━━━━━━━━━━━╼\n` +
    `${pickFresh(CLOSERS, `${jid}|roast|end`)}`;

  await sock.sendMessage(jid, { text, mentions: [target] }, { quoted: msg });
}

module.exports = { cmdRoast };
