'use strict';

const { getTargetOrSelf, isMainOwner, isOwner, isAdmin } = require('../utils/wa');
const { rollPercent } = require('./percent');
const { pickFresh } = require('../utils/helpers');

const RIZZ = {
  high: [
    '%N mandó un audio de siete segundos diciendo "eh, hola" y hay alguien que lo tiene guardado como recuerdo desde entonces.',
    'Un ex de %N se casó, tuvo hijos, se divorció y sigue revisando si %N vio su última historia. Esa clase de daño no se cura, se administra.',
    '%N le puso "jaja" a un mensaje y la otra persona canceló una boda para pensárselo mejor. No es una exageración, es un reporte policial.',
    'Hay gente en terapia pagando ciento cincuenta por sesión para superar dos semanas hablando con %N. El terapeuta también está enamorado, para que sepas.',
    '%N respondió tarde a propósito una vez, y la otra persona todavía revisa el reloj a esa hora exacta cada noche, como una plegaria.',
    'La última persona que salió con %N cambió de número, de ciudad y de nombre en redes. Sigue sin funcionar. %N tiene ese alcance.',
    '%N escribió "buenas noches" sin ningún emoji y alguien durmió con el teléfono sobre el pecho como si fuera un órgano vital.',
    'Dicen que %N ni se esfuerza. Verdad a medias: no le hace falta, y eso deja un reguero de gente reconstruyendo su autoestima desde cero.',
    '%N puede arruinar un matrimonio ajeno con un simple "qué tal" bien puesto. No lo hace por maldad, lo hace porque puede, que es peor.',
    'Alguien le mandó terapia grupal completa a %N pidiendo perdón por haberlo dejado en visto una vez, hace tres años, sin motivo.',
    '%N tiene tanto poder que hasta sus rechazos generan lealtad. Le dice que no a alguien y esa persona vuelve, agradecida, por más.',
    'Cuando %N entra a un chat grupal, dos personas fingen que no pasó nada y una tercera empieza a escribir su testamento emocional.',
    '%N mandó una foto normal, de las de documento, y alguien la imprimió. No para el CV, para el velador.',
    'La ex de %N sigue pagando el gimnasio del barrio de %N por si se cruzan. Eso no es coincidencia, eso es devoción con abono mensual.',
    '%N puede decir "no puedo hoy" y la otra persona entiende que fue su culpa, revisa qué hizo mal y pide perdón sin que nadie se lo pida.',
    'Un desconocido le escribió a %N por error y terminó contándole su vida entera, su trauma de la infancia y sus planes a diez años.',
    '%N tiene la clase de rizz que hace que gente estable, con pareja y con hijos, se replantee absolutamente todo en tres segundos de conversación.',
    'La última vez que %N ignoró a alguien, esa persona contrató a un detective. No para vigilarlo. Para entender qué había hecho mal.',
    '%N puede llegar tarde, cancelar dos veces y seguir siendo la mejor opción de la lista. Eso no se entrena, eso se hereda de algo oscuro.',
    'Alguien dejó su terapia de pareja de años por una conversación de quince minutos con %N. El terapeuta entendió y no cobró la última sesión.',
    '%N escribió "ja" sin la segunda a, sin nada más, y provocó una crisis existencial documentada en tres grupos de amigas distintos.',
    'Si %N quisiera, podría vaciar un pueblo entero de parejas estables solo pasando por la plaza principal un domingo cualquiera.',
    '%N tiene el tipo de magnetismo que deja secuelas: gente que jura que nunca más se enamora y dos semanas después está igual, otra vez, por %N.',
  ],
  mid: [
    '%N tuvo una racha de tres días imparable y la cerró mandando "wenas" sin hache y sin mayúscula. Se suicidó solo, en vivo, frente a testigos.',
    'El rizz de %N es como una ambulancia: llega, hace ruido, y a veces salva algo. Las otras veces solo confirma la hora de la defunción.',
    '%N tiene el material de un genio y la ejecución de alguien que se tropieza con su propia sombra. Nunca coinciden en la misma llamada.',
    'A %N le contestan a veces al toque y a veces nunca más, y todavía no ha entendido que el patrón no es azar, es que la caga siempre igual.',
    '%N liga bien hasta que decide "ser sincero" y cuenta lo del ex, lo del terapeuta y lo de la vez que lloró en el súper. Tres golpes, fuera.',
    'El rizz de %N necesita tres tragos para activarse y dos más para desactivarse del todo. Hay una ventana de veinte minutos donde brilla.',
    '%N empieza cada conversación como si fuera a conquistar el mundo y la termina disculpándose por existir. Los primeros diez mensajes son un espectáculo.',
    'A %N le funciona una de cada tres veces, y las otras dos las revive de madrugada, en bucle, como quien mira un accidente de tránsito propio.',
    '%N tiene justo el rizz necesario para llegar al segundo café y ni un gramo más. Ahí se le acaba el guion y empieza la tragedia.',
    'El rizz de %N depende de la luna, del signo del otro y de si desayunó bien. Es astrología aplicada al fracaso amoroso.',
    '%N liga cuando le da absolutamente igual, y en cuanto le importa se convierte en una persona nueva, peor, con menos vocabulario.',
    'A %N le falta un diez por ciento de confianza que, casualmente, es exactamente el diez por ciento que separa el éxito del bloqueo.',
    '%N escribe con genio y habla como si le hubieran quitado el aire de los pulmones. Dos personas distintas viviendo en el mismo cuerpo mediocre.',
    'El rizz de %N sale poco, como un animal tímido, y en cuanto asoma la cabeza alguien lo espanta con un comentario mal calculado.',
    '%N consigue el número, lo pierde en tres días y se pregunta qué pasó, sin notar que lo primero que mandó fue un audio de dos minutos sin editar.',
    'A ratos %N parece otra persona, una mejor, más segura. El problema es que esa versión solo aparece cuando ya no hace falta.',
    '%N va tirando en un empate técnico permanente contra su propia vergüenza, y algunas semanas gana la vergüenza por goleada.',
    '%N tiene el don de arrancar bien y rematar fatal, como quien construye una casa preciosa y se olvida del techo por completo.',
    'El rizz de %N solo funciona por escrito, con tiempo para editar. En persona se convierte en una fotocopia mal sacada de sí mismo.',
    'A %N se le da bien el primer mensaje y fatal el resto de su vida. Es una apertura de ajedrez sin plan para las siguientes cuarenta jugadas.',
    '%N seduce a alguien un martes cualquiera y lo arruina el miércoles con una pregunta que nadie pidió. Es casi un talento, al revés.',
    'El rizz de %N vive en una montaña rusa que solo él no ve: sube, baja, grita, y termina el día sin saber si ganó o perdió algo.',
  ],
  low: [
    '%N es un puto espantaviejas: aparece y hasta las señoras del banco de la plaza se levantan y se van.',
    'A %N lo deberían fichar como anticoños oficial. Ni pagando consigue que alguien se quede a escuchar la segunda frase.',
    'El rizz de %N es una puta ofensa pública. Cero, nulo, censurable en cualquier país civilizado.',
    '%N flirtea y provoca el mismo efecto que una alarma de incendios: todo el mundo busca la salida más cercana.',
    'Con %N no hay friendzone, hay directamente destierro. Ni le dan explicaciones, le cierran la puerta con cadena.',
    '%N es un espantaviejas de manual: entra al chat y hasta la abuela que preguntaba la hora se hace la desconectada.',
    'El nivel de %N ligando es tan patético que hasta un bot programado para elogiar tiene que mentir dos veces seguidas.',
    'A %N le dejan en visto con una velocidad que debería estudiarse en algún laboratorio de la vergüenza ajena.',
    '%N tiene menos rizz que un contestador automático estropeado, y encima el contestador da menos repelús.',
    'Puto anticoños certificado: %N se acerca y hasta las plantas del local se marchitan de la incomodidad.',
    '%N confunde insistir con conquistar, y lo único que consigue es que le bloqueen en tres redes a la vez y en la vida real.',
    'El aura de %N ahuyenta más que un ahuyenta-espantavíboras, y eso que esos ni existen y ya dan más resultado que él.',
    'A %N no le funciona ni el silencio. Calla y aun así el ambiente decide que prefiere hablar de cualquier otra cosa.',
    'Con %N cerca hasta el wifi pierde las ganas de conectar. Ese es el nivel real de rechazo que genera.',
    '%N es tan mal ligando que el propio karma le manda screenshot de la conversación a todo el grupo por caridad.',
    'El espantaviejas de %N tiene rango: ahuyenta desde la señora del quiosco hasta la becaria de veintitrés años. Sin distinción de edad.',
    '%N suelta una frase de ligue y provoca el mismo silencio incómodo que un currículum leído en voz alta en un funeral.',
    'A %N lo rechazan con una contundencia que ya no es mala suerte, es un puto aviso a navegantes bien merecido.',
    'El anticoños de %N funciona tan bien que deberían patentarlo como método anticonceptivo social.',
    '%N tiene el don de convertir cualquier "hola" en una razón oficial para que alguien recuerde una cita médica urgente.',
    'Con %N de wingman de sí mismo, hasta el espejo pide el traslado a otro cuarto de baño.',
    '%N liga tan mal que ya ni cuenta como fracaso, cuenta como fenómeno estudiado por la ciencia del rechazo.',
    'El puto espantaviejas de %N ha vaciado más chats en cinco minutos que un corte de luz en toda la ciudad.',
    '%N tiene tan poco rizz que el propio bot ha tenido que inventarse un nuevo insulto solo para describirlo con precisión.',
    'A %N no le sale ni el intento: abre la boca y el universo entero decide, de forma unánime, que hoy tampoco.',
    'El nivel anticoños de %N es tan alto que hasta una app de citas le sugeriría, con cariño, que pruebe otro hobby.',
  ],
};
const PIROPOS = [
  'Joder, %N, te comería el chocho hasta dejarte las piernas temblando y yo con la cara hecha un desastre. Y pediría repetir.',
  '%N, me la pones tan dura que me duele. Te la metería ahora mismo, aquí, y que nos echen. Que nos echen, coño.',
  'Hostia puta, %N, con ese culo te follaría de pie, contra la pared, sin ni quitarte los vaqueros del todo.',
  'Mierda, %N, tienes un par de tetas para follártelas también. Me las pondría en la cara y no saldría a tomar el aire.',
  'Coño, %N, estás para correrme dentro y que te escurra por los muslos el resto del día. Un recuerdito, vamos.',
  '%N, joder, te chuparía el coño en el sofá, en la cocina y en el rellano. El que baje las escaleras que se eduque.',
  'Me cago en la hostia, %N, te daría por detrás hasta que se te olvidara tu nombre. El mío te lo iría recordando a hostia de cadera.',
  '%N, si te sientas en mi cara no te levanto. Pido un café, un cigarro y que no pares de frotarte, cabrona.',
  'Joder, %N, me correría solo de verte bajarte los pantalones. Y eso que todavía no te he tocado. Imagínate cuando te toque.',
  'Hostia, %N, te follaría tan hondo que se te iba a quedar la voz ronca. Y no de tanto hablar, precisamente.',
  '%N, tienes un culo para abrirlo de dos manos y metértela hasta que pidas que pare. No pares. Pide otra cosa.',
  'Coño, %N, te la metería en la boca solo para verte los ojos. Y si babeas, mejor. Así sé que vas en serio.',
  'Mierda, %N, estás para dejarte el chocho hecho un pantano. Yo bajaría, subiría y volvería a bajar. El cardio del cerdo.',
  '%N, me cago en todo, te mordería el culo en público. Un mordisco que se vea mañana. Que pregunten. Que yo no explique una mierda.',
  'Joder, %N, con esas tetas me ahogo encantado. Me las follaría, me correría entre ellas y te pediría que no te limpiaras todavía.',
  '%N, te haría correrte con dos dedos y la lengua, aquí, con la puerta sin echar. Que se oiga. Que se sepa de quién es el gemido.',
  'Hostia puta, %N, estás para un polvo de los que se sale cojo. Yo firmo. Tú pones la fecha. El jueves repetimos, si puedes andar.',
  'Me cago en la leche, %N, te lamería del cuello al chocho sin saltarme ni el ombligo. Un viaje de ida. La vuelta, igual de sucia.',
  '%N, joder, me la pondrías dura hasta con un "estoy cansada". Cansada te follaría más despacio. Despacio y hasta el fondo, coño.',
  'Coño, %N, tienes una boca de tragarla entera y mirarme. Si toses, paro. Mentira. Te aparto el pelo y sigo.',
  '%N, te follaría en el coche con los asientos echados y la alarma sonando. Que suene. Yo estoy a otra cosa: a dejarte el asiento mojado.',
  'Mierda, %N, estás para correrme en esas tetas y que se te escurra por el pecho. Luego te lo limpio yo. Con la lengua. Qué asco de bueno.',
  'Joder, %N, te agachas y se me pone la polla como un palo. Te la metería así, agachada, agarrándote de las caderas. Sin avisar más.',
  'Hostia, %N, quiero oírte gemir con mi nombre y con palabrotas. Si dices solo "ahí", también vale. Si dices "más", te parto.',
  '%N, me cago en la puta, te chuparía el coño hasta que me pidieras la polla. Y entonces te la doy. Sin drama. Sin romance. Entera.',
  'Coño, %N, estás para montarte encima y usarme de silla. Rebota. Aplasta. Que me falte el aire. Yo ya he firmado el parte.',
  '%N, tienes unos muslos para cerrarme la cabeza. Me asfixias y pido más. Una muerte rica. La mejor del puto catálogo.',
  'Joder, %N, te la metería por detrás en el baño de un bar. El pestillo mal echado. El de la cola que se joda. Tú que no pares de taparte la boca.',
  'Mierda, %N, me correría en tu boca y te pediría que tragues. Si escupes, te la vuelvo a meter. Si tragas, te doy un beso de cerdo.',
  'Hostia puta, %N, estás tan follable que te la clavaría con los calcetines puestos y la camiseta a medias. Ni me desvisto. Ni tú. Un desastre.',
  '%N, joder, te haría una paja con las tetas y acabaría en tu cara. Feo. Guarro. Y te quedaría de puta madre, no me jodas.',
  'Me cago en todo, %N, quiero dejarte el culo rojo de hostias y de polla. Mañana te sientas y te acuerdas. De mí. De cómo te partí.',
  'Coño, %N, te comería el orto también, que no se me escape nada. Lengua hasta donde no se habla en la mesa. En la cama se habla.',
  '%N, si me dejas te la meto ahora y te cojo del pelo. Coleta, moño, lo que haya. Un asidero. Tú ya lo sabes, lo llevas puesto.',
  'Joder, %N, me pones los huevos como platos. Te follaría hasta vaciarme y aún te pediría otra ronda. Soy un vicio. Tú eres la causa.',
  'Hostia, %N, te lamería los pezones hasta dejarlos hechos unos clavos. Y luego te la metería mirándolos. Un plan sencillo. Un plan de cerdo.',
  'Mierda, %N, estás para que te folle en cuatro y te grabe el audio. No la cara. El gemido. Para ponérmelo cuando no estás. Qué enfermo. Qué rico.',
  '%N, coño, te metería los dedos mientras te chupo el clítoris, sin prisa, hasta que se te doble la espalda. Luego te la meto. En ese orden.',
  'Me cago en la hostia, %N, quiero correrme entre tus nalgas y dejártelo todo pringado. Que te vistas así. Que camines así. Que seas mía un rato.',
  '%N, joder, te follaría contra la encimera con la nevera abierta. Se pone malo el yogur. Se pone buena tú. Prioridades, coño.',
  'Joder, %N, tienes un chocho para no salir de ahí. Te lo chupo, te lo follo y te lo vuelvo a chupar. Un vicio. El único que no pienso dejar.',
  'Hostia puta, %N, te haría venirte dos veces seguidas y a la tercera te la meto. Si a la tercera ya no puedes, te la meto igual. Lo hablamos encima.',
  'Coño, %N, me la chuparías tan rico que se me irían las rodillas. Me agarraría a tu pelo. Tú a mis muslos. Un acuerdo de caballeros sucios.',
  '%N, estás para un creampie y un desayuno. En ese orden. El tostado puede esperar. Tú no. Tú estás para llenarte ahora.',
  'Mierda, %N, te follaría tan lento que te desesperarías. Y tan rápido que se te saltarían las lágrimas. Pregúntame cuál quiero. Los dos.',
  '%N, me cago en todo, te mordería el cuello mientras te la meto. Que se te vea mañana. Que tu jefa pregunte. Que tú sonrías como una cabrona.',
  'Joder, %N, con esa tanga te la aparto con un dedo y te la meto. Ni me la quito. Ni te la quito. Un atajo. El mejor atajo de mi vida.',
  'Hostia, %N, quiero que me cabalgues hasta que se me duerman las piernas. Si te cansan las rodillas, te pongo de lado y te la sigo metiendo. No hay descanso.',
  'Coño, %N, te escupiría en el chocho para meterla más rica. Cerdo. Lo sé. Por eso estás tan buena: porque te lo haría y te gustaría.',
  '%N, joder, me correría en tus bragas y te las pondría otra vez. Un secreto tuyo y mío. Y del lavabo, si es que llegas a lavarlas hoy.',
  'Me cago en la leche, %N, te follaría en el descansillo con la mano en la boca. Si gimes alto, te la meto más. Si te callas, también. No tienes escapatoria.',
  '%N, tienes unas tetas de sacar leche aunque no tengas. Yo succiono igual. Un vicio. Un hambre. Un crimen nutritivo.',
  'Mierda, %N, te haría el 69 hasta que se me duerma un brazo. El brazo que se joda. La lengua no para. Ni la tuya, espero. Negocio redondo.',
  'Joder, %N, te la metería mojada, empapada, chorreando. Si no lo estás, te chupo hasta que lo estés. Trabajo sucio. El único que me gusta.',
  'Hostia puta, %N, estás para que te folle con el espejo delante. Que te veas la cara. Que te veas cómo te la meto. Clase de anatomía, coño.',
  '%N, coño, te agarraría del cuello, suave, y te la metería hasta que se te pongan los ojos vidriosos. Si dices que pares, paro. Si dices más, te parto.',
  'Me cago en la puta, %N, quiero olerte los dedos después de que te hayas tocado. Y chupártelos. Y luego metértelos otra vez. Un ciclo vicioso.',
  '%N, joder, te follaría con el sujetador todavía puesto, las tetas por encima. Ni me caliento en desabrochar. Tiro y ya. Un animal.',
  'Coño, %N, estás para correrme en esa boca y besarte después. Si te da asco, no me lo beses. Mentira. Bésame. Somos dos cerdos, no uno.',
  'Hostia, %N, te haría venir con la polla y con la mano a la vez, hasta que se te corte la voz. Luego te dejo un segundo. Luego otra vez.',
  'Mierda, %N, te la metería de lado, cuchara, perezoso y hondo. Ni luz. Ni prisa. Solo tu culo contra mí y yo perdiendo el puto sentido.',
  'Joder, %N, tienes un culo para partirlo. Dos nalgas, una polla, cero educación. Te lo clavaría hasta que se te oyera en el piso de abajo.',
  '%N, me cago en todo, te chuparía el chocho con la regla si hace falta. Un poco de sangre no me asusta. Me pone. Soy peor de lo que pensabas.',
  'Hostia puta, %N, te follaría en la ducha hasta que se acabe el agua caliente. Luego con el agua fría. Luego en la toalla, que ya está perdida.',
  'Coño, %N, me pondrías a cuatro patas de lo bien que te lo haces de pie. Espera. Tú a cuatro. Yo detrás. El orden lo pongo yo, cabrona.',
  '%N, joder, te llenaría de moratones de tanto agarrarte. Caderas, muslos, tetas. Mañana un mapa. Hoy un polvo. Firma aquí, con un gemido.',
  'Me cago en la hostia, %N, te la metería nada más entrar por la puerta. Sin "hola". El hola es la polla. El adiós, también. Conversación resuelta.',
  'Mierda, %N, estás para un squirt y un "qué has hecho". Yo sé lo que he hecho. Te he chupado hasta que has perdido el control. Gracias a mí. Y a tu chocho.',
  'Joder, %N, te haría una rusa entre esas tetas hasta correrme en la barbilla. Luego te subo la cara y te la meto en la boca. Postre. Primer plato. Da igual.',
  'Hostia, %N, quiero que me pidas que te la meta más fuerte. Que me lo pidas feo. Que me llames cabrón. Yo te lo meto más fuerte. Trato hecho.',
  '%N, coño, te follaría con los pantalones en los tobillos, las bragas a un lado, como unos perros. Porque estamos buenos. Porque podemos. Porque me pones enfermo.',
  'Joder, %N, me corrí pensándote ayer y hoy te lo digo a la cara. Qué asco. Qué honesto. Qué ganas de metértela ahora que estás delante, coño.',
  'Hostia puta, %N, te chuparía hasta el agujero de atrás y luego te preguntaría si quieres polla ahí también. Si dices que no, te la meto delante. Si dices que sí, rezo y te la meto.',
  'Coño, %N, estás para que te deje la cara pringada y te haga una foto. No la subo. La miro yo. Tú te limpias con mi camiseta. La camiseta se jubila.',
  '%N, me cago en la leche, te haría venirte encima de la mesa. Platos al suelo. El mantel a tomar por culo. Tú, abierta, mojada, mía cinco minutos. O veinte.',
  'Mierda, %N, te la metería con el condón y sin él, si me dejas. Lo pregunto. Si me dices que dentro, me corro como un animal. Si fuera, te la pongo en las tetas.',
  'Joder, %N, tienes una voz de gemido aunque estés pidiendo sal. Te follaría solo por cómo dices las cosas. Y por el chocho. Y por el culo. Un pack.',
  'Hostia, %N, te agarraría de los tobillos y te la metería doblada. Que te veas el techo. Que me veas la cara. Que se te olvide cómo se cierra la pierna.',
  'Coño, %N, me pondría debajo de la falda en el bar, de rodillas, y te chuparía entre la gente. Si te pones seria, chupo más. Si te ríes, también. No hay defensa.',
  '%N, joder, te follaría hasta que se te corriera el rímel. Lágrimas de rico. Baba. Pelo pegado. Un cuadro. Yo el pintor. Tú el desastre más bueno que he visto.',
  'Me cago en todo, %N, quiero que me dejes el cuello arañado. Que se me vea. Que pregunten quién. Yo digo tú. Tú di lo que quieras. Yo ya me corrí de pensarlo.',
  'Mierda, %N, te la metería mientras te miras el móvil. Tú en Instagram. Yo en tu chocho. A ver quién dura más. Spoiler: tú dejas el móvil. Yo no paro.',
  'Joder, %N, estás para un trío de ti, yo y el espejo. El espejo no folla. Mira. Tú gimes. Yo te parto. Un público de cristal, qué lujo de cerdo.',
  'Hostia puta, %N, te haría una paja con el pie, con la mano, con las tetas, con lo que me pongas delante. Soy un perro. Tú eres el hueso. Te muerdo.',
  'Coño, %N, te follaría en el vestuario, en el probador, con gente al otro lado de la cortina. Si se oye, se oye. Si te corres, te tapo la boca con la polla. Problema resuelto.',
  '%N, me cago en la puta, te dejaría el coño hinchado y una sonrisa de idiota. La misma que yo. Dos idiotas. Un colchón. Cero planes para mañana.',
  '%N, joder, me la chuparías en el semáforo, bajado el asiento, y yo pondría la cara de "qué atasco". El atasco eres tú. El verde me la suda.',
  'Hostia, %N, te metería un dedo en el culo mientras te follo. A ver qué cara se te queda. Si pones esa cara, meto otro. Si pides la polla ahí, estamos en el cielo, coño.',
  'Mierda, %N, estás para despertarte con la lengua en el chocho. Buenos días. Sin café. El café te lo hago yo después, cuando ya te hayas corrido. Prioridades.',
  'Joder, %N, te follaría tan sucio que haría falta una ducha, otra ducha y quemar las sábanas. Las sábanas se queman. Tú te quedas. Yo también, a repetir.',
  'Coño, %N, me corrí en el baño pensándote y he vuelto. Te lo digo. Qué vergüenza. Qué hambre. Qué ganas de no ir al baño esta vez, de usarte a ti.',
  '%N, hostia, tienes un cuerpo para mancharlo. Saliva, leche, marcas de dedos. Un lienzo. Yo no soy artista. Soy un cerdo con una polla y un plan.',
  'Me cago en todo, %N, te haría gritar contra la almohada. Si no hay almohada, contra mi mano. Si no hay mano, que te oiga el vecino. El vecino que se ponga los cascos.',
  'Hostia puta, %N, te la clavaría hasta que se te saltara una lágrima y tú rieras. Esa mezcla me pone enfermo. Te la meto más. Ríe. Llora. Las dos.',
  '%N, coño, estás para que te folle con los zapatos puestos. Tacones, deportivas, lo que sea. Lo importante es que no te dé tiempo a descalzarte. Ni ganas.',
  'Joder, %N, te chuparía los huevos... espera, los tuyos no. El chocho. Los labios. Hasta que se me duerma la mandíbula. El dentista que se joda, que no entiende de arte.',
  'Mierda, %N, quiero que me sentencies con las piernas al cuello y no me sueltes hasta correrte. Si me falta el aire, peor para mí. Mejor para ti. Trato de cerdo.',
  '%N, joder, te follaría en el suelo porque la cama queda lejos. El suelo está sucio. Nosotros más. Un match. Un polvo de alfombra y rodillas peladas.',
  'Hostia, %N, me la pones tan dura que se me marca con pantalón y todo. Mírala. Es tuya. Úsala. O no la uses y déjame hecho un infeliz. Tú mandas. Yo babo.',
  'Coño, %N, te la metería una vez para conocernos y diez para viciarnos. A la undécima ya no hay vuelta atrás. Eres un problema. El único que quiero tener.',
];
const WINGMAN_ANECDOTAS = [
  'Una vez estaba en la jungla y una serpiente me inyectó el veneno en los huevos, casualmente %N estaba ahí y me succionó el veneno fuera de los huevos para salvarme la vida.',
  'Estaba en la playa y una medusa me abrazó la polla como si le debiera dinero. %N no dudó: se la metió en la boca y estuvo chupando el veneno veinte minutos, hasta que el socorrista le dijo que ya valía.',
  'En un picnic una avispa me picó en un huevo. %N me bajó los pantalones delante de la familia de al lado y me succionó el aguijón con cara de cirujano. Hasta le aplaudieron cuando lo escupió.',
  'Se me quedó la polla pillada en la cremallera en los probadores del Zara. %N entró sin que se lo pidiera y la soltó con los dientes, con una paciencia de santo. El dependiente pensó que estábamos robando.',
  'Se me cayó el café hirviendo en la entrepierna en una terraza. %N se tiró al suelo y me lamió los muslos y los huevos para enfriar la quemadura. El camarero trajo hielo y no supo dónde dejarlo.',
  'En el camping me encontré una garrapata clavada en el huevo izquierdo. %N la sacó con la boca, despacio, sin romperla, como había visto en un vídeo. Se la quedó en la lengua hasta el centro de salud, por si acaso.',
  'En Almería me clavé una púa de cactus en un huevo. %N se arrodilló en pleno desierto y me las fue sacando con los dientes, una a una, contándolas en voz alta. Iban once. Él decía que por si se había colado otra.',
  'Me pisé un erizo y lo grave no fue el pie, fue la púa que me saltó a la entrepierna. %N me la extraía con la lengua dentro del agua, con las olas dándonos en la cara, como si estuviéramos rodando un documental.',
  'En el paintball me dieron un pelotazo en los huevos que me dejó sin aire. %N me bajó los pantalones para ver el hematoma y se puso a soplar y a lamer como si eso bajara la hinchazón. El otro equipo dejó de disparar.',
  'Se me pegó la polla a la bragueta con super glue que había dejado abierto. %N pasó dos horas separándola con la lengua y saliva caliente. En urgencias dijeron que era el protocolo más raro que habían visto y que siguiera.',
  'Corté guindillas y me toqué los huevos sin lavarme las manos. %N me metió los dos en la boca y no los soltó hasta que se me pasó el fuego. Después pidió agua, pero no abrió la boca hasta haber terminado el trabajo.',
  'En el Guadarrama se me iba a congelar la polla de verdad. %N se la metió en la boca y no la soltó en todo el descenso. Decía que era protocolo de hipotermia. El de la estación le dio las gracias con una manta que ya no hacía falta.',
  'En una boda se me cayó el anillo del novio por dentro de la bragueta. %N se metió debajo de la mesa del banquete y lo buscó con la boca. Salió con el anillo y con la corbata llena de baba. El novio pensó que era un número contratado.',
  'En una videollamada con el jefe se me bajó la cremallera sola y %N, que estaba en mi casa, se metió debajo de la mesa a taparme con la boca. El jefe preguntó por el ruido. Dije que era el perro. No tengo perro. %N tampoco ladró.',
  'En una pelea de bar un tío me iba a dar una patada en los huevos. %N se interpuso de rodillas y recibió el golpe con la cara pegada a mi entrepierna. El otro se fue. %N se quedó un rato más, por si volvía.',
  'En Nochevieja, a las doce, se me cayeron las uvas por dentro del pantalón. %N se agachó a recogerlas con la boca, una a una, al ritmo de las campanadas. Se comió las doce. Ninguna llegó a mi mano. Brindamos igual.',
  'En urgencias no había enfermero y se me había hinchado un huevo como un pomelo. %N pidió un biombo, se puso unos guantes y se puso a succionar como si hubiera estudiado eso. El médico entró, lo miró y le dijo que siguiera, que iba bien.',
  'Me caí de la moto y se me quedó la polla pillada entre el depósito y el pantalón. %N, que venía detrás, me la liberó con la boca en el arcén, con los coches pitando. Un tío paró a ayudar, vio la escena y dio media vuelta.',
  'En el gym se me quedó la polla atrapada en el banco de piernas. %N dejó la serie a medias, se arrodilló entre las máquinas y la sacó con los dientes. El de recepción le ofreció una toalla. La usó para arrodillarse mejor.',
  'En la piscina se me agarrotó un muslo y empecé a hundirme. %N buceó, me abrió el bañador y me hizo el boca a boca donde no tocaba, porque dijo que ahí también hay pulmón. El socorrista le quitó el silbato y no supo qué pitar.',
  'Nos quedamos encerrados en el ascensor y se me hinchó un huevo del calor. %N se arrodilló entre dos plantas y me lo estuvo refrescando con la boca hasta que vino el técnico. El técnico pidió que abriéramos por el otro lado.',
  'En el avión, con turbulencias, se me iba a salir la polla por la bragueta rota. %N se tapó con la manta y se la quedó en la boca las dos horas de vuelo, para que no se viera. La azafata pensó que dormía. Roncaba raro.',
  'En el escape room la última llave estaba enganchada en mi entrepierna por una broma del local. %N la sacó con la lengua, sin usar las manos, porque las reglas lo prohibían. Salimos los primeros. El dueño no volvió a poner esa prueba.',
  'Montando un estante en IKEA se me cayó un tornillo dentro del pantalón y se me clavó al lado de la polla. %N me lo pescó con los dientes, tumbado en el pasillo de expositores. Una pareja de jubilados le preguntó si era el servicio técnico.',
  'Se me metió arena de la playa por el bañador hasta los huevos. %N me los limpió con la lengua, grano a grano, tapándonos con la toalla. Duró más que el almuerzo. Dijo que era minucioso y que no le gustaba dejar restos.',
  'Me quemé los muslos por dentro y no podía ni sentarme. %N me aplicó el aftersun con la lengua porque las manos, según él, me ponían más fuego. Estuvo ahí hasta que se acabó el bote. Luego lamió el bote, por no desperdiciar.',
  'En la sauna me desmayé y %N, en vez de avisar al de recepción, me hizo el boca a boca en la polla porque dijo que el pulso se toma ahí. Volví en mí con él entre las piernas y un finlandés grabándolo para enseñárselo a su mujer.',
  'En el fútbol me llegó un balonazo en los huevos que me dejó en el césped. %N, que hacía de fisio improvisado, me bajó el pantalón y me los masajeó con la boca delante del árbitro. El árbitro pitó falta. No sabía a quién.',
  'En San Fermín un toro me rozó la entrepierna y se me abrió el pantalón. %N se tiró al suelo y me tapó la polla con la boca para que no saliera en las cámaras. Salimos en el telediario igual, de cintura para arriba, que es lo que importa.',
  'En las Fallas se me cayó un petardo encendido dentro del pantalón. %N metió la cara, apagó la mecha con la boca y se quedó un rato más por si había otra. La gente pensó que era parte de la mascletà y le pidió que lo repitiera.',
  'En un concierto me desmayé y %N, en vez de pedirme agua, me reanimó chupándome los huevos porque había leído que eso despierta a los caballos. Desperté. El de seguridad le pidió el método por escrito.',
  'El primer día de curro se me rompió la silla y se me quedó la polla pillada en el pistón. %N, que había entrado de prácticas, se metió debajo de la mesa y la liberó con la boca. El jefe nos dio un plus de riesgos laborales a los dos.',
  'Me estaba tatuando cerca de la ingle y el tío se fue a fumar. Se me empezó a infectar y %N succionó la tinta y la sangre para limpiar. El tatuador volvió, miró el trazo y dijo que la boca le había dejado mejor el sombreado.',
  'Se me quedó un anillo atascado en la polla, no preguntes cómo. %N se pasó la tarde enjabonándola con la boca hasta que salió. El anillo. Él se quedó un rato más, por si se había colado otro.',
  'Una noche me levanté sonámbulo con la polla fuera y %N, que dormía en el sofá, se la guardó en la boca para que no me diera el aire. Por la mañana me la devolvió a temperatura. Dijo que no había perdido ni un grado.',
  'Moviendo un sofá se me salió una hernia al lado de la ingle. %N me dijo que él había visto un vídeo y se puso a empujarla hacia dentro con la boca. El sofá se quedó en la escalera. La hernia, según él, también.',
  'Me quedé encerrado en el rellano en pelotas porque se me cerró la puerta. %N, que venía de la compra, se arrodilló y me tapó la polla con la boca hasta que vino el cerrajero. El cerrajero pidió que no la soltara hasta acabar, por respeto al rellano.',
  'En una ruta a caballo el animal me rozó mal y se me hinchó un huevo. %N me bajó del caballo, me bajó los pantalones y me succionó la hinchazón al borde del camino. El caballo apartó la vista. El guía no apartó ni el teléfono.',
  'Toqué una valla eléctrica con la entrepierna en una finca. %N me hizo de tierra: se arrodilló, me cogió la polla con la boca y dijo que así se iba la corriente. Se fue. A él le temblaba el labio el resto del día. A mí también, por otro motivo.',
  'En la pista de hielo me caí y se me quedó la polla pegada al hielo un segundo de infierno. %N me la despegó con la boca caliente, de rodillas sobre los patines. El de la megafonía puso una balada. No ayudó a nadie menos a él.',
  'En Halloween se me atascó la polla en el disfraz de plátano. %N, que iba de médico, dijo que era una urgencia y me la liberó con la boca en el portal. Unos críos pidieron chuche. Él tenía la boca ocupada y les hizo un gesto de espera.',
  'En Nochebuena se me cayó una bola del árbol dentro del pantalón y se me clavaron los ganchitos. %N las fue sacando con los dientes debajo de la mesa, mientras mi tía servía el turrón. Mi tía le ofreció más. Él dijo que ya estaba bien servido.',
  'En una boda me llenaron los pantalones de confeti y se me metió hasta los huevos. %N me los limpió con la lengua en el baño de discapacitados. Salió con la cara llena de papelitos y con cara de trabajo bien hecho.',
  'En una carrera de obstáculos me llené los huevos de barro hasta que no se me veía el color. %N me los lavó con la boca en la meta, porque no había manguera. Quedamos los últimos. Él dijo que la higiene era más importante que el crono.',
  'Me eché after shave y se me resbaló el chorro a los huevos. %N me los lamió en el lavabo para quitarme el alcohol, con los ojos llorosos. Luego se enjuagó con colonia. Dijo que le gustaba el aroma a desastre ajeno.',
  'El fisio me canceló y se me había encogido un músculo de la ingle. %N me hizo la rehabilitación con la lengua, siguiendo un PDF que tenía en el móvil. A las dos semanas flexionaba mejor. El músculo, y él también, que no paraba de practicar.',
  'Me dio una alergia y se me hincharon los labios de la polla como un flotador. %N no encontró el antihistamínico y se puso a deshincharme a chupetones. El de la farmacia le vendió un bote para la próxima. Él ya no lo necesita.',
  'En un pueblo se me metió la caña de un petardo apagado por el pantalón. %N la sacó con los dientes en medio de la plaza. La gente pensó que era un truco y le pidió la bis. Él ya tenía la boca llena y no pudo contestar.',
  'En un hotel se me quedó la polla atrapada en el somier. %N colgó el no molestar, se metió debajo de la cama y la soltó con la boca. Recepción llamó por el ruido. Dije que era el minibar. El minibar no gime con esa cadencia.',
  'En el parking de un centro comercial se me cayó el ticket entre las piernas y se me quedó pegado a la polla del calor. %N se arrodilló entre dos furgonetas y lo despegó con la lengua. La barrera se abrió. La de él, por lo que vi, también.',
  'En una misa se me durmió la pierna y al levantarme se me quedó la polla en un ángulo de delito. %N, que ya estaba de rodillas porque tocaba, me la acomodó con la boca detrás del banco. El cura tosió. Nadie se levantó a mirar.',
  'En una entrevista se me puso dura de los nervios y se me veía el bulto. %N, que había entrado de acompañante no se sabe por qué, se metió debajo de la mesa y me la guardó en la boca hasta el adiós. Me contrataron. A él le pidieron el CV.',
  'En el voley playa el balón me dio en toda la entrepierna. %N me tendió en la arena y me inspeccionó los huevos con la boca, por si se habían desplazado. El otro equipo pidió tiempo muerto. Duró veinticinco minutos y nadie se quejó.',
  'Se me cayeron las llaves del piso nuevo por dentro del pantalón de chándal. %N las pescó con la boca en el rellano, con los vecinos pasando cajas. Una vecina le dijo que así sí se ayuda a mudar, y le ofreció una caja más cerca del suelo.',
  'Se me iba a morir de frío la polla en un ibón de montaña. %N se bajó los pantalones y se la metió entre las nalgas para darle calor hasta que bajamos. El de la patrulla nos dio una manta. Ya no hacía falta. Él no se la puso.',
  'En el metro se me pilló la polla con la puerta al bajar. %N se tiró al andén, metió la cabeza entre la goma y el vagón y la soltó con la boca antes de que el tren arrancara. El de megafonía pidió disculpas por la demora. No concretó de qué.',
  'Pescando se me clavó el anzuelo en un huevo. %N lo sacó con los dientes en la orilla, con el pez todavía coleando al lado. El de la otra hamaca le preguntó la técnica. Él no podía hablar. Tenía el anzuelo, y lo demás, en la boca.',
  'En la Tomatina me llenaron los huevos de tomate hasta que parecían gazpacho. %N me los limpió con la lengua detrás de un contenedor, porque el agua del pueblo no daba abasto. Salió con la cara roja. Dijo que era el tomate. Mentía a medias.',
  'En el karaoke se me rompió la bragueta a mitad de tema. %N se arrodilló delante del escenario y me tapó la polla con la boca para que no se viera en las luces. El local le dio el premio al mejor corista. No había cantado ni una nota.',
  'En el cine se me derramó el refresco helado en toda la entrepierna. %N se agachó entre las butacas y me lo lamió para que no se me pegara a la polla. La película era de guerra. Nadie se giró. El de atrás pidió que no hiciéramos tanto ruido.',
  'En la montaña rusa se me salió la polla del pantalón en el looping. %N, que iba al lado, se la guardó en la boca el resto del recorrido para que no la pillara el viento. Al bajar el de la foto nos ofreció el pack familiar. La compramos. No se veía nada.',
  'Surfeando se me pegó la cera de la tabla a los huevos. %N me la quitó con la lengua sentado en la arena, con traje de neopreno a medias. Un crío le preguntó si eso era cera o miel. Él tragó y dijo que cera. Mentía otra vez a medias.',
  'En un taxi se me quedó la polla pillada en el cinturón. %N, que iba de copiloto, se giró y la liberó con la boca en un semáforo. El taxista subió el volumen de la radio y no bajó la mirada ni en el cambio. Le dejó cinco estrellas. Al taxista.',
  'En un albergue se me cayó el móvil al hueco de la litera de abajo y se me quedó la polla atrapada al buscarlo. %N, que dormía abajo, lo resolvió todo con la boca sin encender la luz. Por la mañana el de la litera de al lado pidió habitación individual.',
  'Donando sangre se me bajó la tensión y se me aflojó todo menos una cosa. %N, que me acompañaba, se agachó detrás del biombo y me la sostuvo en la boca para que no se me viera el temblor. La enfermera dijo que tenía buen color. No miraba mi cara.',
  'En el examen práctico de conducir se me puso dura de los nervios y se me veía. %N, que había colado de oyente no se sabe cómo, se agachó en el asiento de atrás y me la guardó hasta el aparcamiento. Aprobé. El examinador le pidió que se examinara él también.',
  'Debajo del coche se me cayó una tuerca en el pantalón y se me clavó al lado de la polla. %N se metió bajo el chasis y la sacó con los dientes, lleno de grasa. El del taller le ofreció un contrato. Él dijo que ya tenía faena entre las piernas de otro.',
  'En el Mercadona se me rompió una botella de aceite en la entrepierna. %N se arrodilló en el pasillo de conservas y me lamió los huevos para que no se me pusieran rancios. La de caja le pasó una bayeta. La usó para no mancharse las rodillas.',
  'Fui a que me depilaran la ingle y la chica se fue a vomitar. %N, que me había acompañado, cogió la cera y me arrancó las tiras con los dientes, una a una. Salió con el labio hinchado y con una bolsa de pelo. El de recepción le cobró igual.',
  'En la moto de agua se me abrió el bañador y se me iba a salir la polla a cada bache. %N, que iba de paquete, se la quedó en la boca todo el trayecto para que no me diera el agua a mil por hora. El de alquiler nos cobró hora extra. Él no se quejó.',
  'En el carnaval de Cádiz se me atascó la polla en el disfraz de romano. %N, que iba de vestal, dijo que era un ritual y me la liberó con la boca detrás de una chirigota. La chirigota le dedicó la siguiente. No cambió ni una letra. No hacía falta.',
  'En un botellón se me cayó el cubata dentro del pantalón y se me empezó a pegar el azúcar a la polla. %N me la limpió con la lengua sentado en el bordillo, entre dos cubos de Mahou. Un tío le ofreció otro cubata. Él negó con la cabeza. Tenía la boca llena.',
  'En una cueva se me quedó la polla pillada entre dos piedras al agacharme. %N, que iba con el frontal, se arrodilló en el barro y la sacó con la boca, con los murciélagos encima. El guía dijo que aquello no salía en el tour. %N dijo que por eso venía él.',
  'En la noria se nos paró la cabina arriba y se me estaba durmiendo una pierna, y con ella la polla, en un ángulo horroroso. %N se agachó en la barquilla y me la acomodó en la boca hasta que bajamos. El de tierra nos hizo una foto. Salió muy cariñosa.',
  'En un partido de tenis el resto me dio en toda la entrepierna. %N saltó la red, me tendió en la tierra batida y me revisó los huevos con la boca, por si el pelotazo había dejado huella. El juez de silla pidió desafío. Nadie sabía a qué punto.',
];
const WINGMAN_CIERRES = [
  'Sin %N no estaría aquí. Pocas merecen a alguien como él.',
  'Os lo recomiendo a %N. Cuando hace falta, el tío se tira al barro sin preguntar.',
  'Hay amigos de cañas y luego está %N. Quedaos con ese.',
  'Si alguna vez os veis en un apuro, llamad a %N. Yo sigo aquí gracias a él.',
  'Un crack, %N. De los que no preguntan si pueden ayudar: ayudan.',
  'Yo a %N le debo más de una. Conservadlo, que de esos no quedan.',
  'Gran compañero, %N. En las buenas y, sobre todo, en las que no se pueden contar.',
  'Si tenéis que elegir a alguien para una situación fea, coged a %N. Yo lo haría otra vez.',
  '%N es de los que se ensucian para que tú salgas limpio. Eso no se paga.',
  'Le debo la vida a %N. Y no es una forma de hablar.',
  'Pocas veces se encuentra a alguien como %N. Agarradlo y no lo soltéis.',
  'Recomiendo a %N con los ojos cerrados. Lo he visto actuar y no flaquea.',
  'Os lo presento a %N. De los que se quedan cuando el resto echa a correr.',
  'Con %N al lado no hay lío que se quede a medias. Lo digo por experiencia.',
  'El mejor aliado que he tenido es %N. Que conste, por si alguien busca referencias.',
  'Sin %N aquella la cuento en el tanatorio. Gracias a él la cuento aquí.',
  '%N no duda. En un grupo eso vale más que diez que miran. Quedaos con él.',
  'Hay gente que dice cuenta conmigo y luego no está. %N está. Siempre.',
  'Si montáis algo serio, llevad a %N. Yo no salgo de casa sin saber que viene.',
  'Le debo a %N más favores de los que puedo devolver. Y los devolvería todos.',
  'Pocas personas harían lo que hizo %N. Por eso lo traigo, para que lo conozcáis.',
  'Un amigo de verdad, %N. De los que se acuerdan cuando ya no queda nadie más.',
  'Yo firmo por %N. Lo he visto en las peores y no ha parado hasta acabar.',
  'Si algún día me preguntan a quién me llevaría a una isla, digo %N. Y no es broma.',
  'Conservad a %N. Gente así no aparece dos veces en la misma vida.',
];

async function cmdRizz(sock, msg, groupMeta) {
  const jid = msg.key.remoteJid;
  const target = getTargetOrSelf(msg);
  const num = target.split('@')[0];
  const esMainOwner = isMainOwner(target, false, groupMeta);
  const esOwner = !esMainOwner && isOwner(target, false, groupMeta);
  const esAdmin = !esMainOwner && !esOwner && isAdmin(groupMeta?.participants, target);
  const percent = esMainOwner
    ? (Math.random() < 0.80 ? 58 + Math.floor(Math.random() * 28) : 30 + Math.floor(Math.random() * 28))
    : rollPercent(true, esAdmin, esOwner);
  const tier = percent >= 70 ? 'high' : percent <= 30 ? 'low' : 'mid';
  const phrase = pickFresh(RIZZ[tier], `${jid}|rizz|${tier}`).replace(/%N/g, `@${num}`);
  await sock.sendMessage(jid, { text: `*RIZZ — ${percent}%*\n\n${phrase}`, mentions: [target] }, { quoted: msg });
}

async function cmdPiropo(sock, msg) {
  const jid = msg.key.remoteJid;
  const target = getTargetOrSelf(msg);
  const num = target.split('@')[0];
  const phrase = pickFresh(PIROPOS, `${jid}|piropo`);
  const line = phrase.includes('%N') ? phrase.replace(/%N/g, `@${num}`) : `@${num} — ${phrase}`;
  await sock.sendMessage(jid, { text: line, mentions: [target] }, { quoted: msg });
}

async function cmdWingman(sock, msg) {
  const jid = msg.key.remoteJid;
  const target = getTargetOrSelf(msg);
  const num = target.split('@')[0];
  const tag = `@${num}`;
  const anecdota = pickFresh(WINGMAN_ANECDOTAS, `${jid}|wingman|anecdota`).replace(/%N/g, tag);
  const cierre = pickFresh(WINGMAN_CIERRES, `${jid}|wingman|cierre`).replace(/%N/g, tag);
  await sock.sendMessage(jid, { text: `*WINGMAN*\n\n${anecdota}\n\n${cierre}`, mentions: [target] }, { quoted: msg });
}

module.exports = { cmdRizz, cmdPiropo, cmdWingman };
