'use strict';

const { getTargetOrSelf, isMainOwner, isOwner, isAdmin } = require('../utils/wa');
const { rollPercent } = require('./percent');
const { pickFresh } = require('../utils/helpers');

const RIZZ = {
  high: [
    '%N mandó un audio de siete segundos diciendo "eh, hola" y hay alguien que lo tiene guardado como recuerdo desde entonces.',
    'Un ex de %N se casó, tuvo hijos, se divorció y sigue revisando si %N vio su última historia. Esa clase de daño no se cura, se administra.',
    '%N le puso "jaja" a un mensaje y la otra persona canceló una boda para pensárselo mejor. No es una exageración, es un reporte policial.',
    'Hay gente en terapia pagando ciento cincuenta por sesión para superar dos semanas hablando con %N. El terapeuta también está enamorado, para que sepas.',
    '%N respondió tarde a propósito una vez, y la otra persona todavía revisa el reloj a esa hora exacta cada noche, como una plegaria.',
    'La última persona que salió con %N cambió de número, de ciudad y de nombre en redes. Sigue sin funcionar. %N tiene ese alcance.',
    '%N escribió "buenas noches" sin ningún emoji y alguien durmió con el teléfono sobre el pecho como si fuera un órgano vital.',
    'Dicen que %N ni se esfuerza. Verdad a medias: no le hace falta, y eso deja un reguero de gente reconstruyendo su autoestima desde cero.',
    '%N puede arruinar un matrimonio ajeno con un simple "qué tal" bien puesto. No lo hace por maldad, lo hace porque puede, que es peor.',
    'Alguien le mandó terapia grupal completa a %N pidiendo perdón por haberlo dejado en visto una vez, hace tres años, sin motivo.',
    '%N tiene tanto poder que hasta sus rechazos generan lealtad. Le dice que no a alguien y esa persona vuelve, agradecida, por más.',
    'Cuando %N entra a un chat grupal, dos personas fingen que no pasó nada y una tercera empieza a escribir su testamento emocional.',
    '%N mandó una foto normal, de las de documento, y alguien la imprimió. No para el CV, para el velador.',
    'La ex de %N sigue pagando el gimnasio del barrio de %N por si se cruzan. Eso no es coincidencia, eso es devoción con abono mensual.',
    '%N puede decir "no puedo hoy" y la otra persona entiende que fue su culpa, revisa qué hizo mal y pide perdón sin que nadie se lo pida.',
    'Un desconocido le escribió a %N por error y terminó contándole su vida entera, su trauma de la infancia y sus planes a diez años.',
    '%N tiene la clase de rizz que hace que gente estable, con pareja y con hijos, se replantee absolutamente todo en tres segundos de conversación.',
    'La última vez que %N ignoró a alguien, esa persona contrató a un detective. No para vigilarlo. Para entender qué había hecho mal.',
    '%N puede llegar tarde, cancelar dos veces y seguir siendo la mejor opción de la lista. Eso no se entrena, eso se hereda de algo oscuro.',
    'Alguien dejó su terapia de pareja de años por una conversación de quince minutos con %N. El terapeuta entendió y no cobró la última sesión.',
    '%N escribió "ja" sin la segunda a, sin nada más, y provocó una crisis existencial documentada en tres grupos de amigas distintos.',
    'Si %N quisiera, podría vaciar un pueblo entero de parejas estables solo pasando por la plaza principal un domingo cualquiera.',
    '%N tiene el tipo de magnetismo que deja secuelas: gente que jura que nunca más se enamora y dos semanas después está igual, otra vez, por %N.',
  ],
  mid: [
    '%N tuvo una racha de tres días imparable y la cerró mandando "wenas" sin hache y sin mayúscula. Se suicidó solo, en vivo, frente a testigos.',
    'El rizz de %N es como una ambulancia: llega, hace ruido, y a veces salva algo. Las otras veces solo confirma la hora de la defunción.',
    '%N tiene el material de un genio y la ejecución de alguien que se tropieza con su propia sombra. Nunca coinciden en la misma llamada.',
    'A %N le contestan a veces al toque y a veces nunca más, y todavía no ha entendido que el patrón no es azar, es que la caga siempre igual.',
    '%N liga bien hasta que decide "ser sincero" y cuenta lo del ex, lo del terapeuta y lo de la vez que lloró en el súper. Tres golpes, fuera.',
    'El rizz de %N necesita tres tragos para activarse y dos más para desactivarse del todo. Hay una ventana de veinte minutos donde brilla.',
    '%N empieza cada conversación como si fuera a conquistar el mundo y la termina disculpándose por existir. Los primeros diez mensajes son un espectáculo.',
    'A %N le funciona una de cada tres veces, y las otras dos las revive de madrugada, en bucle, como quien mira un accidente de tránsito propio.',
    '%N tiene justo el rizz necesario para llegar al segundo café y ni un gramo más. Ahí se le acaba el guion y empieza la tragedia.',
    'El rizz de %N depende de la luna, del signo del otro y de si desayunó bien. Es astrología aplicada al fracaso amoroso.',
    '%N liga cuando le da absolutamente igual, y en cuanto le importa se convierte en una persona nueva, peor, con menos vocabulario.',
    'A %N le falta un diez por ciento de confianza que, casualmente, es exactamente el diez por ciento que separa el éxito del bloqueo.',
    '%N escribe con genio y habla como si le hubieran quitado el aire de los pulmones. Dos personas distintas viviendo en el mismo cuerpo mediocre.',
    'El rizz de %N sale poco, como un animal tímido, y en cuanto asoma la cabeza alguien lo espanta con un comentario mal calculado.',
    '%N consigue el número, lo pierde en tres días y se pregunta qué pasó, sin notar que lo primero que mandó fue un audio de dos minutos sin editar.',
    'A ratos %N parece otra persona, una mejor, más segura. El problema es que esa versión solo aparece cuando ya no hace falta.',
    '%N va tirando en un empate técnico permanente contra su propia vergüenza, y algunas semanas gana la vergüenza por goleada.',
    '%N tiene el don de arrancar bien y rematar fatal, como quien construye una casa preciosa y se olvida del techo por completo.',
    'El rizz de %N solo funciona por escrito, con tiempo para editar. En persona se convierte en una fotocopia mal sacada de sí mismo.',
    'A %N se le da bien el primer mensaje y fatal el resto de su vida. Es una apertura de ajedrez sin plan para las siguientes cuarenta jugadas.',
    '%N seduce a alguien un martes cualquiera y lo arruina el miércoles con una pregunta que nadie pidió. Es casi un talento, al revés.',
    'El rizz de %N vive en una montaña rusa que solo él no ve: sube, baja, grita, y termina el día sin saber si ganó o perdió algo.',
  ],
  low: [
    '%N es un puto espantaviejas: aparece y hasta las señoras del banco de la plaza se levantan y se van.',
    'A %N lo deberían fichar como anticoños oficial. Ni pagando consigue que alguien se quede a escuchar la segunda frase.',
    'El rizz de %N es una puta ofensa pública. Cero, nulo, censurable en cualquier país civilizado.',
    '%N flirtea y provoca el mismo efecto que una alarma de incendios: todo el mundo busca la salida más cercana.',
    'Con %N no hay friendzone, hay directamente destierro. Ni le dan explicaciones, le cierran la puerta con cadena.',
    '%N es un espantaviejas de manual: entra al chat y hasta la abuela que preguntaba la hora se hace la desconectada.',
    'El nivel de %N ligando es tan patético que hasta un bot programado para elogiar tiene que mentir dos veces seguidas.',
    'A %N le dejan en visto con una velocidad que debería estudiarse en algún laboratorio de la vergüenza ajena.',
    '%N tiene menos rizz que un contestador automático estropeado, y encima el contestador da menos repelús.',
    'Puto anticoños certificado: %N se acerca y hasta las plantas del local se marchitan de la incomodidad.',
    '%N confunde insistir con conquistar, y lo único que consigue es que le bloqueen en tres redes a la vez y en la vida real.',
    'El aura de %N ahuyenta más que un ahuyenta-espantavíboras, y eso que esos ni existen y ya dan más resultado que él.',
    'A %N no le funciona ni el silencio. Calla y aun así el ambiente decide que prefiere hablar de cualquier otra cosa.',
    'Con %N cerca hasta el wifi pierde las ganas de conectar. Ese es el nivel real de rechazo que genera.',
    '%N es tan mal ligando que el propio karma le manda screenshot de la conversación a todo el grupo por caridad.',
    'El espantaviejas de %N tiene rango: ahuyenta desde la señora del quiosco hasta la becaria de veintitrés años. Sin distinción de edad.',
    '%N suelta una frase de ligue y provoca el mismo silencio incómodo que un currículum leído en voz alta en un funeral.',
    'A %N lo rechazan con una contundencia que ya no es mala suerte, es un puto aviso a navegantes bien merecido.',
    'El anticoños de %N funciona tan bien que deberían patentarlo como método anticonceptivo social.',
    '%N tiene el don de convertir cualquier "hola" en una razón oficial para que alguien recuerde una cita médica urgente.',
    'Con %N de wingman de sí mismo, hasta el espejo pide el traslado a otro cuarto de baño.',
    '%N liga tan mal que ya ni cuenta como fracaso, cuenta como fenómeno estudiado por la ciencia del rechazo.',
    'El puto espantaviejas de %N ha vaciado más chats en cinco minutos que un corte de luz en toda la ciudad.',
    '%N tiene tan poco rizz que el propio bot ha tenido que inventarse un nuevo insulto solo para describirlo con precisión.',
    'A %N no le sale ni el intento: abre la boca y el universo entero decide, de forma unánime, que hoy tampoco.',
    'El nivel anticoños de %N es tan alto que hasta una app de citas le sugeriría, con cariño, que pruebe otro hobby.',
  ],
};
const PIROPOS = [
  '%N, con ese culo no sé si follarte o denunciarte. Es un atentado y yo soy el primer herido, todavía de pie por milagro.',
  '%N, te miré el escote y se me olvidó la frase. Iba a ser una gilipollez. Ahora es una gilipollez con tetas, que ya es subir de categoría.',
  '%N, no eres mona. Mona es la de la ventanilla. Tú estás para comerte el coño y salir del bar sin saber cómo se paga.',
  '%N, te agachas a por el móvil y este chat debería cobrar entrada. Ese culo no recoge el teléfono: recauda.',
  '%N, si tu padre nos pilla le digo la verdad: que su hija es un peligro público y que yo solo estaba encima, cumpliendo.',
  '%N, ese chocho tiene pinta de multa. Me lo comería igual y llamaría yo a la policía, con la boca todavía ocupada.',
  '%N, con esas tetas callas a un juez. Firma lo que le pongas delante y se va al aseo a resolver el otro sumario, el de la bragueta.',
  '%N, andas tú y el culo llega cinco minutos antes. Es decente: así el resto tenemos tiempo de hacernos una paja de bienvenida.',
  '%N, te ríes y se te marcan las tetas como una falta en el área. El árbitro te saca roja y te espera en el vestuario, el cabrón.',
  '%N, esa boca no es para dar los buenos días. Es para dejar a un tío tartamudo y contento. Di algo limpio a ver si te sale. Spoiler: no.',
  '%N, te comería el coño hasta dejar el bar sin servilletas. El camarero ya me mira mal y todavía no he empezado, el muy hijo de puta.',
  '%N, tienes cara de buena y culo de que no lo eres. Menos mal. Las buenas aburren y tú dejas cojos, pobres y dando las gracias.',
  '%N, no sé qué perfume llevas y me da igual: huele a que esta noche alguien va a hacer el ridículo. Ojalá sea yo, y con la cara entre tus piernas.',
  '%N, tus tetas no caben en esta conversación. Ni en ese sujetador. Ni en mi decencia, que ya era poca y ahora es un chiste.',
  '%N, de frente pareces educada. De lado pareces una condena. Yo pido la de lado, para cumplirla entera y con visita íntima.',
  '%N, si te portaras como andas esto era un prostíbulo con wifi. Y yo socio fundador, con llave del almacén y de tus muslos.',
  '%N, te follaría tan fuerte que se te olvidaría la contraseña del wifi. Y la mía. Y cómo se habla. Un milagro educativo, vamos.',
  '%N, ese culo pide una hostia y un beso, en ese orden. Lo de follártelo es el primer plato, no el postre. El postre también es follártelo.',
  '%N, estás más buena que el pecado, pero el pecado por lo menos se confiesa. Tú dejas al cura hecho un vicioso y te vas tan pancha, coño.',
  '%N, no te maquilles tanto que se te tapa el vicio. Y el vicio es lo único decente que tienes, aparte de ese culo que no pide permiso.',
  '%N, con esa tanga marcada no vienes a comprar pan. Vienes a dejar a tres tíos hablando solo y a uno pidiéndote fuego para el cigarro que no fuma.',
  '%N, te pones esa camiseta sin sujetador y esto deja de ser un grupo y pasa a ser una sala de espera. De la polla, concretamente.',
  '%N, sales de la ducha y todavía goteas. No es agua, es un aviso. El que no se entere es que está muerto o es maricón, o las dos cosas.',
  '%N, te comes ese helado como si no supieras lo que estás haciendo. Lo sabes. Lo sabemos todos. Hasta el de la caja se ha hecho el ocupado.',
  '%N, te cruzas de piernas y se oye un silencio de velatorio. Nadie se ha muerto. Se nos ha muerto la decencia, que es peor y más honesto.',
  '%N, hablas bajo y se me pone dura. Da igual de qué hables. Puedes estar pidiendo sal y yo ya estoy pensando en dejártela en otro sitio.',
  '%N, me mandas un jaja y ya estoy mal. Un jaja tuyo no es una risa, es un preliminar. El siguiente mensaje que te escriba va a ser una vergüenza.',
  '%N, te sientas en el taburete y el taburete debería cobrar horas extra. Ese culo no se sienta: se instala, y echa al resto del local.',
  '%N, subes las escaleras y media calle se vuelve devota. No es fe, es culo. La fe no hace que un tío se tropiece con su propia polla.',
  '%N, esos vaqueros de espaldas son una puta denuncia. El denim no se hizo para eso. Se hizo para tapar, y a ti te delata hasta el pespunte.',
  '%N, te pones la sudadera de tu ex y se te sigue viendo todo. El ex es un pringado. La sudadera, un cómplice. Tú, un delito con capucha.',
  '%N, en bañador no hay horizonte que valga. El que diga que mira el mar es un mentiroso o un puto santo, y aquí no hay santos.',
  '%N, te bajas del coche y esas piernas hacen más daño que la puerta. La puerta como mucho te pilla un dedo. Tú pillas el resto de la vida.',
  '%N, de copiloto así no se llega a ningún sitio. Se llega tarde, duro y sin haber mirado un puto semáforo. El GPS puede irse a tomar por culo.',
  '%N, te quedas en toalla y la toalla hace el ridículo. Inventaron esa tela para tapar. Encima de ti es un chivato. Un chivato húmedo, además.',
  '%N, te pones a hacer sentadillas y el gimnasio debería tener zona VIP. Ese culo subiendo y bajando no es deporte: es cine para adultos con mancuernas.',
  '%N, te aplicas crema en las piernas como si esto fuera un tutorial. No es un tutorial. Es una amenaza. El aftersun no tiene tanta maldad.',
  '%N, te recoges el pelo y ese cuello es una invitación a delinquir. Yo ya tengo antecedentes. Uno más no me va a cambiar el DNI.',
  '%N, te pintas los labios y se te ve el crimen. No es maquillaje, es premeditación. El de al lado ya está ensayando la coartada, el muy gilipollas.',
  '%N, ese moño no es un moño. Es un asidero. Lo disimulas muy mal y te queda de puta madre, que es peor para los que tenemos manos.',
  '%N, te pones tacones y cambias de oficio sin cambiar de trabajo. Sigues siendo tú. El suelo, el aire y mi polla han pedido el traslado.',
  '%N, descalza estás peor. Bueno, peor para nosotros. Para ti estás igual de rica. Para el suelo, es acoso. Para mí, una causa perdida.',
  '%N, te moja la lluvia y esa camiseta cuenta tu vida. No hacía falta. Ya la habíamos imaginado. Ahora es que la tenemos en alta definición, joder.',
  '%N, sales de la piscina y el agua se queda a vivir en tus tetas. El agua tiene más criterio que la mitad de este grupo, y eso que es agua.',
  '%N, entras en el Mercadona y el pasillo de congelados se rinde. No por ti. Por el culo. El culo no compra, el culo ocupa.',
  '%N, te agachas a por el yogur del estante de abajo y hay que llamar a seguridad. No por robo. Por lo que le pasa a la gente de detrás, coño.',
  '%N, en la cocina con esa camiseta no se cocina. Se peca. El arroz se pega, el aceite salta y yo me haría una paja con el trapo de secar.',
  '%N, te follaría contra la encimera y la encimera pediría el divorcio. De la envidia, no del golpe. El golpe se lo lleva otro sitio.',
  '%N, en el ascensor contigo se me olvidan los pisos. Se me olvida hasta que hay que salir. El que pulse el botón es un aguafiestas de los cojones.',
  '%N, te pones las gafas y pareces lista. Te las quitas y pareces un problema. Me quedo con el problema. Las listas no se follan así de rico.',
  '%N, te enfadas y se te pone una cara de que habría que follarte para que se te pase. No es terapia. Es el único tratamiento que te veo, joder.',
  '%N, bailas mal y da igual. Con ese culo el ritmo es un detalle. Puedes ir a contratiempo y todavía dejas el local hecho una puta procesión.',
  '%N, fumas y se te ve la boca de otra manera. No es el cigarro. Es que se te imagina uno haciendo otra cosa, y esa otra cosa no es hablar.',
  '%N, bebes de la botella y se te va un hilo por el labio. Lo limpias con el dedo. Ese dedo debería tener antecedentes. Yo ya se los pondría.',
  '%N, te muerdes el labio como si no supieras el daño. Lo sabes. Si no lo supieras no lo harías. Eres una cabrona con permiso de conducir.',
  '%N, te estiras y se te ve la tira de la tanga. Gracias por el parte meteorológico. Hoy: nublado de ropa y 100 % de probabilidad de paja.',
  '%N, bostezas y se te archiva uno la polla sola. No es tu culpa. Bueno, sí es tu culpa. Toda. Hasta la forma de taparte la boca es guarra.',
  '%N, te despiertas con esa cara de sueño y se te seguiría follando igual. El maquillaje era un adorno. El delito eres tú, recién salida de la cama.',
  '%N, te pones a mirar el móvil y se te marca el perfil. El perfil de la cara, y el otro. El otro es el que tiene más likes, no te engañes.',
  '%N, me dejas en visto y se me pone dura igual. Eres insoportable. Insoportablemente buena. El visto es lo más cerca que voy a estar de un no, y ni eso.',
  '%N, me dices tío y se me cae el personaje. Tío es un amigo. Tú no tienes pinta de amiga. Tienes pinta de que el amigo acaba de rodillas.',
  '%N, dices mi nombre y ya he perdido. Podías haberme llamado gilipollas, que es más honesto. El nombre en tu boca es una puta trampa.',
  '%N, te pones mi camiseta y la camiseta se jubila. Ya no es ropa. Es una reliquia. La voy a oler como un enfermo y no me da ni vergüenza.',
  '%N, te pones solo los calcetines y el resto al aire y esto ya no es un piropo, es un parte médico. Tengo fiebre, erección y mal pronóstico.',
  '%N, se te ve la tanga por encima del pantalón y pretendes que hablemos de otra cosa. De acuerdo. Hablemos de cómo te la quitaría con los dientes.',
  '%N, se te marca el chocho en esos leggins y quieres que te mire a los ojos. Te miro a los ojos. Mentira. Te miro abajo y luego miento, como todo el mundo.',
  '%N, se te escapa el lado de la teta por la camiseta y lo arreglas con un dedo. Ese dedo ha hecho más que algunos en toda una noche. Enhorabuena, cabrona.',
  '%N, te inclinas en la nevera y el fiambre espera. Yo también. La diferencia es que el fiambre no se está imaginando comerte el coño entre el yogur y la mantequilla.',
  '%N, vas en bici y el sillín debería pagar impuestos. Ese culo no pedalea: recauda otra vez. El casco no te tapa lo que hay que tapar.',
  '%N, te subes de paquete en la moto y el que conduce es un hijo de puta con suerte. Tú eres el accidente. Él, el único herido que sonríe.',
  '%N, te asomas a la ventana a fumar y media calle fuma contigo. Nadie enciende nada. Están todos haciendo como que buscan las llaves, los muy pringados.',
  '%N, te miras al espejo y el espejo pide un aumento. No por vanidad. Por horas extra. Ver ese culo de frente y de atrás en el mismo turno es abuso laboral.',
  '%N, te pones el choker y ya no hay conversación decente. Ese cuello pide mano. Esa boca pide otra cosa. Yo pido las dos, y no soy de pedir.',
  '%N, te sueltas el pelo y parece que vas a hacer algo ilegal. Hazlo. O deja que lo haga yo. Legal no va a ser de todas formas, con esa cara.',
  '%N, te oigo por el pasillo y ya sé que eres tú. No por los pasos. Por cómo se calla la gente. El silencio ese no es respeto, es bragueta en alerta.',
  '%N, te sientas al lado y se me va la polla hacia ti como una brújula de pobre. El norte eres tú. El sur, mi dignidad. El sur está perdido.',
  '%N, te pones a cantar mal y se te hinchan las tetas con el aire. Sigue cantando mal. El oído sufre. La vista cobra. Sale a cuenta, joder.',
  '%N, te manchas de salsa en el labio y te la quitas con la lengua. Gracias por el trailer. La película no la vamos a poder poner en este chat, por desgracia.',
  '%N, te ríes con la cabeza hacia atrás y se te ve el cuello, las tetas y la falta de vergüenza. Tres cosas ricas. La vergüenza no hace falta, déjala en casa.',
  '%N, te pones a llorar de risa y se te corre el rímel. Hasta el rímel quiere bajar. Yo le entiendo. Yo también iría para abajo, y no a consolarte.',
  '%N, te pones el pijama de ositos y pretendes que no te folle nadie. Los ositos no te van a salvar. A los ositos les haría el mismo favor que a ti.',
  '%N, te tapas con la manta y se te sigue viendo el perfil del culo. La manta es un chiste. Tú eres el chiste. Yo soy el que se ríe con la mano ocupada.',
  '%N, te pones a hacer la cama y te agachas de una forma que no es hacer la cama. Es una oferta. La cama ya está hecha. Lo que falta es destrozarla.',
  '%N, te pones crema en las manos y te las frotas despacio. No sé si te das cuenta. Te das cuenta. Eres una cabrona. Sigue, que esto es mejor que el porno.',
  '%N, te atizas el pintalabios mirándome. Eso no es maquillarse. Eso es un aviso de desahucio. Mi polla ya está haciendo las maletas hacia tu boca.',
  '%N, te pones a bailar sentada y se te mueve el culo en la silla. La silla no firmó para esto. Yo sí. Donde haya que firmar, firmo. Hasta en la entrepierna.',
  '%N, te comes un pincho y se te queda aceite en el dedo y te lo chupas. El pincho era de tortilla. Lo que has hecho no tiene nada que ver con la tortilla, coño.',
  '%N, te pones a buscar algo debajo del sofá y ese culo al aire es el hallazgo. Deja lo que buscaras. Ya hemos encontrado todos. Hasta el que no buscaba.',
  '%N, te pones el pelo en una coleta alta y ya no eres gente. Eres un mango con tetas. Lo digo con cariño. Con cariño guarro, que es el único que tengo.',
  '%N, te pones a estirar en el salón y se te abre la pierna como una amenaza. El yoga es una coartada. Lo tuyo es terrorismo de coño en pantalón elástico.',
  '%N, te pones a reírte de un tío y se te ve el colmillo. Ese colmillo se te vería igual de rico rozando otra cosa. No voy a decir cuál. La sabes.',
  '%N, te pones seria y das más miedo. Miedo rico. Miedo de que te lo tomes en serio y me dejes la espalda hecha un mapa. Firmo el mapa.',
  '%N, te pones a hablar de tu ex y se te pone una boca de que el ex es un pringado. Lo es. Cualquiera que te haya tenido y te haya soltado es un puto amnésico.',
  '%N, te pones a beber de la caña y se te queda espuma en el labio. Te la quitas con el dorso. Ese dorso merece una medalla. O una paja. Las dos, por este orden.',
  '%N, te pones el abrigo y se te ve solo el escote. El abrigo es un cabrón. Te tapa lo justo para que uno imagine el resto y se haga daño solo, el gilipollas.',
  '%N, te pones a correr y se te mueven las tetas de una forma que el running no cubre. Eso no es cardio. Eso es una multa a la vista. Yo la pago, pero mirando.',
  '%N, te pones a secarte el pelo y se te levanta la camiseta. Un segundo de barriga y de tira de tanga. Un segundo. Me llega para la semana, cabrona.',
  '%N, te pones a cantar por lo bajo y se te hincha la teta con cada verso. No entiendo la canción. Entiendo el estribillo. El estribillo es follarte.',
  '%N, te pones a pedir otra ronda y se te inclina el cuerpo sobre la barra. La barra te ha visto el escote más veces que tu médico. La barra es una puta privilegiada.',
  '%N, si te follara ahora mismo y alguien llamara a la puerta, yo abriría con la polla fuera y le diría que vuelva en una hora. Mentira. En tres.',
];
const WINGMAN_ANECDOTAS = [
  'Una vez estaba en la jungla y una serpiente me inyectó el veneno en los huevos, casualmente %N estaba ahí y me succionó el veneno fuera de los huevos para salvarme la vida.',
  'Estaba en la playa y una medusa me abrazó la polla como si le debiera dinero. %N no dudó: se la metió en la boca y estuvo chupando el veneno veinte minutos, hasta que el socorrista le dijo que ya valía.',
  'En un picnic una avispa me picó en un huevo. %N me bajó los pantalones delante de la familia de al lado y me succionó el aguijón con cara de cirujano. Hasta le aplaudieron cuando lo escupió.',
  'Se me quedó la polla pillada en la cremallera en los probadores del Zara. %N entró sin que se lo pidiera y la soltó con los dientes, con una paciencia de santo. El dependiente pensó que estábamos robando.',
  'Se me cayó el café hirviendo en la entrepierna en una terraza. %N se tiró al suelo y me lamió los muslos y los huevos para enfriar la quemadura. El camarero trajo hielo y no supo dónde dejarlo.',
  'En el camping me encontré una garrapata clavada en el huevo izquierdo. %N la sacó con la boca, despacio, sin romperla, como había visto en un vídeo. Se la quedó en la lengua hasta el centro de salud, por si acaso.',
  'En Almería me clavé una púa de cactus en un huevo. %N se arrodilló en pleno desierto y me las fue sacando con los dientes, una a una, contándolas en voz alta. Iban once. Él decía que por si se había colado otra.',
  'Me pisé un erizo y lo grave no fue el pie, fue la púa que me saltó a la entrepierna. %N me la extraía con la lengua dentro del agua, con las olas dándonos en la cara, como si estuviéramos rodando un documental.',
  'En el paintball me dieron un pelotazo en los huevos que me dejó sin aire. %N me bajó los pantalones para ver el hematoma y se puso a soplar y a lamer como si eso bajara la hinchazón. El otro equipo dejó de disparar.',
  'Se me pegó la polla a la bragueta con super glue que había dejado abierto. %N pasó dos horas separándola con la lengua y saliva caliente. En urgencias dijeron que era el protocolo más raro que habían visto y que siguiera.',
  'Corté guindillas y me toqué los huevos sin lavarme las manos. %N me metió los dos en la boca y no los soltó hasta que se me pasó el fuego. Después pidió agua, pero no abrió la boca hasta haber terminado el trabajo.',
  'En el Guadarrama se me iba a congelar la polla de verdad. %N se la metió en la boca y no la soltó en todo el descenso. Decía que era protocolo de hipotermia. El de la estación le dio las gracias con una manta que ya no hacía falta.',
  'En una boda se me cayó el anillo del novio por dentro de la bragueta. %N se metió debajo de la mesa del banquete y lo buscó con la boca. Salió con el anillo y con la corbata llena de baba. El novio pensó que era un número contratado.',
  'En una videollamada con el jefe se me bajó la cremallera sola y %N, que estaba en mi casa, se metió debajo de la mesa a taparme con la boca. El jefe preguntó por el ruido. Dije que era el perro. No tengo perro. %N tampoco ladró.',
  'En una pelea de bar un tío me iba a dar una patada en los huevos. %N se interpuso de rodillas y recibió el golpe con la cara pegada a mi entrepierna. El otro se fue. %N se quedó un rato más, por si volvía.',
  'En Nochevieja, a las doce, se me cayeron las uvas por dentro del pantalón. %N se agachó a recogerlas con la boca, una a una, al ritmo de las campanadas. Se comió las doce. Ninguna llegó a mi mano. Brindamos igual.',
  'En urgencias no había enfermero y se me había hinchado un huevo como un pomelo. %N pidió un biombo, se puso unos guantes y se puso a succionar como si hubiera estudiado eso. El médico entró, lo miró y le dijo que siguiera, que iba bien.',
  'Me caí de la moto y se me quedó la polla pillada entre el depósito y el pantalón. %N, que venía detrás, me la liberó con la boca en el arcén, con los coches pitando. Un tío paró a ayudar, vio la escena y dio media vuelta.',
  'En el gym se me quedó la polla atrapada en el banco de piernas. %N dejó la serie a medias, se arrodilló entre las máquinas y la sacó con los dientes. El de recepción le ofreció una toalla. La usó para arrodillarse mejor.',
  'En la piscina se me agarrotó un muslo y empecé a hundirme. %N buceó, me abrió el bañador y me hizo el boca a boca donde no tocaba, porque dijo que ahí también hay pulmón. El socorrista le quitó el silbato y no supo qué pitar.',
  'Nos quedamos encerrados en el ascensor y se me hinchó un huevo del calor. %N se arrodilló entre dos plantas y me lo estuvo refrescando con la boca hasta que vino el técnico. El técnico pidió que abriéramos por el otro lado.',
  'En el avión, con turbulencias, se me iba a salir la polla por la bragueta rota. %N se tapó con la manta y se la quedó en la boca las dos horas de vuelo, para que no se viera. La azafata pensó que dormía. Roncaba raro.',
  'En el escape room la última llave estaba enganchada en mi entrepierna por una broma del local. %N la sacó con la lengua, sin usar las manos, porque las reglas lo prohibían. Salimos los primeros. El dueño no volvió a poner esa prueba.',
  'Montando un estante en IKEA se me cayó un tornillo dentro del pantalón y se me clavó al lado de la polla. %N me lo pescó con los dientes, tumbado en el pasillo de expositores. Una pareja de jubilados le preguntó si era el servicio técnico.',
  'Se me metió arena de la playa por el bañador hasta los huevos. %N me los limpió con la lengua, grano a grano, tapándonos con la toalla. Duró más que el almuerzo. Dijo que era minucioso y que no le gustaba dejar restos.',
  'Me quemé los muslos por dentro y no podía ni sentarme. %N me aplicó el aftersun con la lengua porque las manos, según él, me ponían más fuego. Estuvo ahí hasta que se acabó el bote. Luego lamió el bote, por no desperdiciar.',
  'En la sauna me desmayé y %N, en vez de avisar al de recepción, me hizo el boca a boca en la polla porque dijo que el pulso se toma ahí. Volví en mí con él entre las piernas y un finlandés grabándolo para enseñárselo a su mujer.',
  'En el fútbol me llegó un balonazo en los huevos que me dejó en el césped. %N, que hacía de fisio improvisado, me bajó el pantalón y me los masajeó con la boca delante del árbitro. El árbitro pitó falta. No sabía a quién.',
  'En San Fermín un toro me rozó la entrepierna y se me abrió el pantalón. %N se tiró al suelo y me tapó la polla con la boca para que no saliera en las cámaras. Salimos en el telediario igual, de cintura para arriba, que es lo que importa.',
  'En las Fallas se me cayó un petardo encendido dentro del pantalón. %N metió la cara, apagó la mecha con la boca y se quedó un rato más por si había otra. La gente pensó que era parte de la mascletà y le pidió que lo repitiera.',
  'En un concierto me desmayé y %N, en vez de pedirme agua, me reanimó chupándome los huevos porque había leído que eso despierta a los caballos. Desperté. El de seguridad le pidió el método por escrito.',
  'El primer día de curro se me rompió la silla y se me quedó la polla pillada en el pistón. %N, que había entrado de prácticas, se metió debajo de la mesa y la liberó con la boca. El jefe nos dio un plus de riesgos laborales a los dos.',
  'Me estaba tatuando cerca de la ingle y el tío se fue a fumar. Se me empezó a infectar y %N succionó la tinta y la sangre para limpiar. El tatuador volvió, miró el trazo y dijo que la boca le había dejado mejor el sombreado.',
  'Se me quedó un anillo atascado en la polla, no preguntes cómo. %N se pasó la tarde enjabonándola con la boca hasta que salió. El anillo. Él se quedó un rato más, por si se había colado otro.',
  'Una noche me levanté sonámbulo con la polla fuera y %N, que dormía en el sofá, se la guardó en la boca para que no me diera el aire. Por la mañana me la devolvió a temperatura. Dijo que no había perdido ni un grado.',
  'Moviendo un sofá se me salió una hernia al lado de la ingle. %N me dijo que él había visto un vídeo y se puso a empujarla hacia dentro con la boca. El sofá se quedó en la escalera. La hernia, según él, también.',
  'Me quedé encerrado en el rellano en pelotas porque se me cerró la puerta. %N, que venía de la compra, se arrodilló y me tapó la polla con la boca hasta que vino el cerrajero. El cerrajero pidió que no la soltara hasta acabar, por respeto al rellano.',
  'En una ruta a caballo el animal me rozó mal y se me hinchó un huevo. %N me bajó del caballo, me bajó los pantalones y me succionó la hinchazón al borde del camino. El caballo apartó la vista. El guía no apartó ni el teléfono.',
  'Toqué una valla eléctrica con la entrepierna en una finca. %N me hizo de tierra: se arrodilló, me cogió la polla con la boca y dijo que así se iba la corriente. Se fue. A él le temblaba el labio el resto del día. A mí también, por otro motivo.',
  'En la pista de hielo me caí y se me quedó la polla pegada al hielo un segundo de infierno. %N me la despegó con la boca caliente, de rodillas sobre los patines. El de la megafonía puso una balada. No ayudó a nadie menos a él.',
  'En Halloween se me atascó la polla en el disfraz de plátano. %N, que iba de médico, dijo que era una urgencia y me la liberó con la boca en el portal. Unos críos pidieron chuche. Él tenía la boca ocupada y les hizo un gesto de espera.',
  'En Nochebuena se me cayó una bola del árbol dentro del pantalón y se me clavaron los ganchitos. %N las fue sacando con los dientes debajo de la mesa, mientras mi tía servía el turrón. Mi tía le ofreció más. Él dijo que ya estaba bien servido.',
  'En una boda me llenaron los pantalones de confeti y se me metió hasta los huevos. %N me los limpió con la lengua en el baño de discapacitados. Salió con la cara llena de papelitos y con cara de trabajo bien hecho.',
  'En una carrera de obstáculos me llené los huevos de barro hasta que no se me veía el color. %N me los lavó con la boca en la meta, porque no había manguera. Quedamos los últimos. Él dijo que la higiene era más importante que el crono.',
  'Me eché after shave y se me resbaló el chorro a los huevos. %N me los lamió en el lavabo para quitarme el alcohol, con los ojos llorosos. Luego se enjuagó con colonia. Dijo que le gustaba el aroma a desastre ajeno.',
  'El fisio me canceló y se me había encogido un músculo de la ingle. %N me hizo la rehabilitación con la lengua, siguiendo un PDF que tenía en el móvil. A las dos semanas flexionaba mejor. El músculo, y él también, que no paraba de practicar.',
  'Me dio una alergia y se me hincharon los labios de la polla como un flotador. %N no encontró el antihistamínico y se puso a deshincharme a chupetones. El de la farmacia le vendió un bote para la próxima. Él ya no lo necesita.',
  'En un pueblo se me metió la caña de un petardo apagado por el pantalón. %N la sacó con los dientes en medio de la plaza. La gente pensó que era un truco y le pidió la bis. Él ya tenía la boca llena y no pudo contestar.',
  'En un hotel se me quedó la polla atrapada en el somier. %N colgó el no molestar, se metió debajo de la cama y la soltó con la boca. Recepción llamó por el ruido. Dije que era el minibar. El minibar no gime con esa cadencia.',
  'En el parking de un centro comercial se me cayó el ticket entre las piernas y se me quedó pegado a la polla del calor. %N se arrodilló entre dos furgonetas y lo despegó con la lengua. La barrera se abrió. La de él, por lo que vi, también.',
  'En una misa se me durmió la pierna y al levantarme se me quedó la polla en un ángulo de delito. %N, que ya estaba de rodillas porque tocaba, me la acomodó con la boca detrás del banco. El cura tosió. Nadie se levantó a mirar.',
  'En una entrevista se me puso dura de los nervios y se me veía el bulto. %N, que había entrado de acompañante no se sabe por qué, se metió debajo de la mesa y me la guardó en la boca hasta el adiós. Me contrataron. A él le pidieron el CV.',
  'En el voley playa el balón me dio en toda la entrepierna. %N me tendió en la arena y me inspeccionó los huevos con la boca, por si se habían desplazado. El otro equipo pidió tiempo muerto. Duró veinticinco minutos y nadie se quejó.',
  'Se me cayeron las llaves del piso nuevo por dentro del pantalón de chándal. %N las pescó con la boca en el rellano, con los vecinos pasando cajas. Una vecina le dijo que así sí se ayuda a mudar, y le ofreció una caja más cerca del suelo.',
  'Se me iba a morir de frío la polla en un ibón de montaña. %N se bajó los pantalones y se la metió entre las nalgas para darle calor hasta que bajamos. El de la patrulla nos dio una manta. Ya no hacía falta. Él no se la puso.',
  'En el metro se me pilló la polla con la puerta al bajar. %N se tiró al andén, metió la cabeza entre la goma y el vagón y la soltó con la boca antes de que el tren arrancara. El de megafonía pidió disculpas por la demora. No concretó de qué.',
  'Pescando se me clavó el anzuelo en un huevo. %N lo sacó con los dientes en la orilla, con el pez todavía coleando al lado. El de la otra hamaca le preguntó la técnica. Él no podía hablar. Tenía el anzuelo, y lo demás, en la boca.',
  'En la Tomatina me llenaron los huevos de tomate hasta que parecían gazpacho. %N me los limpió con la lengua detrás de un contenedor, porque el agua del pueblo no daba abasto. Salió con la cara roja. Dijo que era el tomate. Mentía a medias.',
  'En el karaoke se me rompió la bragueta a mitad de tema. %N se arrodilló delante del escenario y me tapó la polla con la boca para que no se viera en las luces. El local le dio el premio al mejor corista. No había cantado ni una nota.',
  'En el cine se me derramó el refresco helado en toda la entrepierna. %N se agachó entre las butacas y me lo lamió para que no se me pegara a la polla. La película era de guerra. Nadie se giró. El de atrás pidió que no hiciéramos tanto ruido.',
  'En la montaña rusa se me salió la polla del pantalón en el looping. %N, que iba al lado, se la guardó en la boca el resto del recorrido para que no la pillara el viento. Al bajar el de la foto nos ofreció el pack familiar. La compramos. No se veía nada.',
  'Surfeando se me pegó la cera de la tabla a los huevos. %N me la quitó con la lengua sentado en la arena, con traje de neopreno a medias. Un crío le preguntó si eso era cera o miel. Él tragó y dijo que cera. Mentía otra vez a medias.',
  'En un taxi se me quedó la polla pillada en el cinturón. %N, que iba de copiloto, se giró y la liberó con la boca en un semáforo. El taxista subió el volumen de la radio y no bajó la mirada ni en el cambio. Le dejó cinco estrellas. Al taxista.',
  'En un albergue se me cayó el móvil al hueco de la litera de abajo y se me quedó la polla atrapada al buscarlo. %N, que dormía abajo, lo resolvió todo con la boca sin encender la luz. Por la mañana el de la litera de al lado pidió habitación individual.',
  'Donando sangre se me bajó la tensión y se me aflojó todo menos una cosa. %N, que me acompañaba, se agachó detrás del biombo y me la sostuvo en la boca para que no se me viera el temblor. La enfermera dijo que tenía buen color. No miraba mi cara.',
  'En el examen práctico de conducir se me puso dura de los nervios y se me veía. %N, que había colado de oyente no se sabe cómo, se agachó en el asiento de atrás y me la guardó hasta el aparcamiento. Aprobé. El examinador le pidió que se examinara él también.',
  'Debajo del coche se me cayó una tuerca en el pantalón y se me clavó al lado de la polla. %N se metió bajo el chasis y la sacó con los dientes, lleno de grasa. El del taller le ofreció un contrato. Él dijo que ya tenía faena entre las piernas de otro.',
  'En el Mercadona se me rompió una botella de aceite en la entrepierna. %N se arrodilló en el pasillo de conservas y me lamió los huevos para que no se me pusieran rancios. La de caja le pasó una bayeta. La usó para no mancharse las rodillas.',
  'Fui a que me depilaran la ingle y la chica se fue a vomitar. %N, que me había acompañado, cogió la cera y me arrancó las tiras con los dientes, una a una. Salió con el labio hinchado y con una bolsa de pelo. El de recepción le cobró igual.',
  'En la moto de agua se me abrió el bañador y se me iba a salir la polla a cada bache. %N, que iba de paquete, se la quedó en la boca todo el trayecto para que no me diera el agua a mil por hora. El de alquiler nos cobró hora extra. Él no se quejó.',
  'En el carnaval de Cádiz se me atascó la polla en el disfraz de romano. %N, que iba de vestal, dijo que era un ritual y me la liberó con la boca detrás de una chirigota. La chirigota le dedicó la siguiente. No cambió ni una letra. No hacía falta.',
  'En un botellón se me cayó el cubata dentro del pantalón y se me empezó a pegar el azúcar a la polla. %N me la limpió con la lengua sentado en el bordillo, entre dos cubos de Mahou. Un tío le ofreció otro cubata. Él negó con la cabeza. Tenía la boca llena.',
  'En una cueva se me quedó la polla pillada entre dos piedras al agacharme. %N, que iba con el frontal, se arrodilló en el barro y la sacó con la boca, con los murciélagos encima. El guía dijo que aquello no salía en el tour. %N dijo que por eso venía él.',
  'En la noria se nos paró la cabina arriba y se me estaba durmiendo una pierna, y con ella la polla, en un ángulo horroroso. %N se agachó en la barquilla y me la acomodó en la boca hasta que bajamos. El de tierra nos hizo una foto. Salió muy cariñosa.',
  'En un partido de tenis el resto me dio en toda la entrepierna. %N saltó la red, me tendió en la tierra batida y me revisó los huevos con la boca, por si el pelotazo había dejado huella. El juez de silla pidió desafío. Nadie sabía a qué punto.',
];
const WINGMAN_CIERRES = [
  'Sin %N no estaría aquí. Pocas merecen a alguien como él.',
  'Os lo recomiendo a %N. Cuando hace falta, el tío se tira al barro sin preguntar.',
  'Hay amigos de cañas y luego está %N. Quedaos con ese.',
  'Si alguna vez os veis en un apuro, llamad a %N. Yo sigo aquí gracias a él.',
  'Un crack, %N. De los que no preguntan si pueden ayudar: ayudan.',
  'Yo a %N le debo más de una. Conservadlo, que de esos no quedan.',
  'Gran compañero, %N. En las buenas y, sobre todo, en las que no se pueden contar.',
  'Si tenéis que elegir a alguien para una situación fea, coged a %N. Yo lo haría otra vez.',
  '%N es de los que se ensucian para que tú salgas limpio. Eso no se paga.',
  'Le debo la vida a %N. Y no es una forma de hablar.',
  'Pocas veces se encuentra a alguien como %N. Agarradlo y no lo soltéis.',
  'Recomiendo a %N con los ojos cerrados. Lo he visto actuar y no flaquea.',
  'Os lo presento a %N. De los que se quedan cuando el resto echa a correr.',
  'Con %N al lado no hay lío que se quede a medias. Lo digo por experiencia.',
  'El mejor aliado que he tenido es %N. Que conste, por si alguien busca referencias.',
  'Sin %N aquella la cuento en el tanatorio. Gracias a él la cuento aquí.',
  '%N no duda. En un grupo eso vale más que diez que miran. Quedaos con él.',
  'Hay gente que dice cuenta conmigo y luego no está. %N está. Siempre.',
  'Si montáis algo serio, llevad a %N. Yo no salgo de casa sin saber que viene.',
  'Le debo a %N más favores de los que puedo devolver. Y los devolvería todos.',
  'Pocas personas harían lo que hizo %N. Por eso lo traigo, para que lo conozcáis.',
  'Un amigo de verdad, %N. De los que se acuerdan cuando ya no queda nadie más.',
  'Yo firmo por %N. Lo he visto en las peores y no ha parado hasta acabar.',
  'Si algún día me preguntan a quién me llevaría a una isla, digo %N. Y no es broma.',
  'Conservad a %N. Gente así no aparece dos veces en la misma vida.',
];

async function cmdRizz(sock, msg, groupMeta) {
  const jid = msg.key.remoteJid;
  const target = getTargetOrSelf(msg);
  const num = target.split('@')[0];
  const esMainOwner = isMainOwner(target, false, groupMeta);
  const esOwner = !esMainOwner && isOwner(target, false, groupMeta);
  const esAdmin = !esMainOwner && !esOwner && isAdmin(groupMeta?.participants, target);
  const percent = esMainOwner
    ? (Math.random() < 0.80 ? 58 + Math.floor(Math.random() * 28) : 30 + Math.floor(Math.random() * 28))
    : rollPercent(true, esAdmin, esOwner);
  const tier = percent >= 70 ? 'high' : percent <= 30 ? 'low' : 'mid';
  const phrase = pickFresh(RIZZ[tier], `${jid}|rizz|${tier}`).replace(/%N/g, `@${num}`);
  await sock.sendMessage(jid, { text: `*RIZZ — ${percent}%*\n\n${phrase}`, mentions: [target] }, { quoted: msg });
}

async function cmdPiropo(sock, msg) {
  const jid = msg.key.remoteJid;
  const target = getTargetOrSelf(msg);
  const num = target.split('@')[0];
  const phrase = pickFresh(PIROPOS, `${jid}|piropo`);
  const line = phrase.includes('%N') ? phrase.replace(/%N/g, `@${num}`) : `@${num} — ${phrase}`;
  await sock.sendMessage(jid, { text: line, mentions: [target] }, { quoted: msg });
}

async function cmdWingman(sock, msg) {
  const jid = msg.key.remoteJid;
  const target = getTargetOrSelf(msg);
  const num = target.split('@')[0];
  const tag = `@${num}`;
  const anecdota = pickFresh(WINGMAN_ANECDOTAS, `${jid}|wingman|anecdota`).replace(/%N/g, tag);
  const cierre = pickFresh(WINGMAN_CIERRES, `${jid}|wingman|cierre`).replace(/%N/g, tag);
  await sock.sendMessage(jid, { text: `*WINGMAN*\n\n${anecdota}\n\n${cierre}`, mentions: [target] }, { quoted: msg });
}

module.exports = { cmdRizz, cmdPiropo, cmdWingman };
